# -*- coding: utf-8 -*-
"""Emit mvDivCurlQuizzes.js — Divergence & Curl guide banks."""
from _quiz_emit import q, emit_file, OUT


def build():
    banks = {}

    banks["FIELD_CONCEPT_QUIZ"] = [
        q("Evaluate $\\mathbf F(1,-2,3)$ for $\\mathbf F=\\langle x,y,z\\rangle$.",
          ["$\\langle 1,-2,3\\rangle$", "$\\langle 1,2,3\\rangle$", "$\\langle 0,0,0\\rangle$"], 0,
          "Substitute the point into each component."),
        q("The field $\\mathbf F=\\langle -y,x\\rangle$ in the plane is best described as:",
          ["A rotational (circular) field", "A radial source field", "A constant field"], 0,
          "It is tangent to circles centered at the origin."),
        q("For $\\mathbf G=\\langle 2,0,-1\\rangle$, the vector at every point is:",
          ["The same constant vector", "Radial from the origin", "Zero"], 0,
          "No dependence on $(x,y,z)$."),
        q("If $\\mathbf F=\\nabla f$ for $f=x^2y$, then $\\mathbf F$ equals:",
          ["$\\langle 2xy,x^2\\rangle$", "$\\langle x^2,y\\rangle$", "$\\langle 2x,y\\rangle$"], 0,
          "Compute the gradient components."),
        q("Component functions of $\\mathbf F=\\langle P,Q,R\\rangle=\\langle yz,xz,xy\\rangle$ give $P(1,2,3)$:",
          ["$6$", "$3$", "$2$"], 0, "$P=yz=2\\cdot 3=6$."),
        q("A flow line of a constant field $\\mathbf F=\\langle 1,0,0\\rangle$ is:",
          ["A straight line parallel to the $x$-axis", "A circle in the $xy$-plane", "A helix about the $z$-axis"], 0,
          "Velocity is always $\\mathbf i$."),
        q("The radial field $\\mathbf F=\\langle x,y\\rangle$ points:",
          ["Away from the origin (for $(x,y)\\ne\\mathbf 0$)", "Clockwise around the origin", "Always upward"], 0,
          "The vector equals the position vector."),
        q("Evaluate $\\mathbf H(0,1,0)$ for $\\mathbf H=\\langle z,x,y\\rangle$.",
          ["$\\langle 0,0,1\\rangle$", "$\\langle 0,1,0\\rangle$", "$\\langle 1,0,0\\rangle$"], 0,
          "$\\langle 0,0,1\\rangle$."),
        q("A gradient field is also called:",
          ["Conservative (on a suitable domain)", "Solenoidal", "Incompressible only"], 0,
          "Gradient fields are conservative where the domain allows."),
        q("For $\\mathbf F=\\langle e^x,0,0\\rangle$, $\\|\\mathbf F(0,5,-2)\\|$ equals:",
          ["$1$", "$e$", "$0$"], 0, "$\\mathbf F(0,5,-2)=\\langle 1,0,0\\rangle$."),
        q("Sketch cue: arrows of $\\mathbf F=\\langle -x,-y\\rangle$ near the origin point:",
          ["Toward the origin", "Away from the origin", "Tangentially clockwise"], 0,
          "It is the inward radial field."),
        q("If $\\mathbf F=\\langle P,Q\\rangle$ with $P=x$ and $Q=0$, streamlines satisfy:",
          ["Horizontal motion scaling with $x$", "Vertical circles", "Constant speed $1$ everywhere"], 0,
          "Velocity has only an $x$-component equal to $x$."),
        q("The zero field $\\mathbf F=\\mathbf 0$ has flow lines that are:",
          ["Constant (stationary points)", "Unit-speed lines", "Only closed loops"], 0,
          "Velocity zero means particles stay put."),
        q("For $\\mathbf F=\\langle xy,1\\rangle$, the $y$-component at $(2,3)$ is:",
          ["$1$", "$6$", "$2$"], 0, "$Q=1$ constantly."),
        q("A vector field on $\\mathbb{R}^3$ assigns to each point:",
          ["A vector in $\\mathbb{R}^3$", "A scalar only", "A $3\\times 3$ matrix only"], 0,
          "Definition of a 3D vector field."),
    ]

    banks["DIV_FORMULA_QUIZ"] = [
        q("Compute $\\nabla\\cdot\\langle x^2,y^2,z^2\\rangle$.",
          ["$2x+2y+2z$", "$2x$", "$x^2+y^2+z^2$"], 0,
          "$P_x+Q_y+R_z=2x+2y+2z$."),
        q("For $\\mathbf F=\\langle y,-x,0\\rangle$, $\\nabla\\cdot\\mathbf F$ equals:",
          ["$0$", "$2$", "$-2$"], 0, "$0+0+0=0$."),
        q("Evaluate $\\nabla\\cdot\\langle e^x,e^y,e^z\\rangle$ at $(0,0,0)$.",
          ["$3$", "$1$", "$0$"], 0, "Divergence is $e^x+e^y+e^z$; at origin equals $3$."),
        q("If $\\nabla\\cdot\\mathbf F>0$ at a point, the field behaves locally like a:",
          ["Source", "Sink", "Pure rotation with no expansion"], 0,
          "Positive divergence means net outward flux density."),
        q("A field with $\\nabla\\cdot\\mathbf F=0$ everywhere is called:",
          ["Solenoidal (incompressible)", "Conservative", "Irrotational"], 0,
          "Zero divergence is the solenoidal condition."),
        q("Compute $\\nabla\\cdot\\langle 3x,2y,-5z\\rangle$.",
          ["$0$", "$3$", "$-5$"], 0, "$3+2-5=0$."),
        q("Laplacian connection: $\\nabla\\cdot(\\nabla f)$ equals:",
          ["$\\nabla^2 f$", "$\\nabla\\times(\\nabla f)$", "$\\|\\nabla f\\|$"], 0,
          "Divergence of the gradient is the Laplacian."),
        q("For $f=x^2+y^2+z^2$, $\\nabla\\cdot(\\nabla f)$ equals:",
          ["$6$", "$2$", "$0$"], 0, "$\\nabla f=\\langle 2x,2y,2z\\rangle$, divergence $6$."),
        q("Compute $\\nabla\\cdot\\langle xy,yz,zx\\rangle$ at $(1,1,1)$.",
          ["$3$", "$1$", "$0$"], 0, "$y+z+x$ equals $3$ at $(1,1,1)$."),
        q("Divergence of a constant field is:",
          ["$0$", "$1$", "Undefined"], 0, "All partials vanish."),
        q("For $\\mathbf F=\\langle x/r^3,y/r^3,z/r^3\\rangle$ with $r=\\sqrt{x^2+y^2+z^2}$ (off the origin), a classical computation gives $\\nabla\\cdot\\mathbf F$:",
          ["$0$", "$1$", "$3/r^2$"], 0,
          "Away from the origin this Coulomb field is divergence-free."),
        q("If $\\mathbf F=\\langle P,Q,R\\rangle$ and $P_x=1$, $Q_y=2$, $R_z=-4$, then $\\nabla\\cdot\\mathbf F$ equals:",
          ["$-1$", "$3$", "$7$"], 0, "$1+2-4=-1$."),
        q("Sign check: $\\nabla\\cdot\\langle -x,-y,-z\\rangle$ equals:",
          ["$-3$", "$3$", "$0$"], 0, "Each component contributes $-1$."),
        q("Compute $\\nabla\\cdot\\langle \\sin y,\\cos x,z\\rangle$.",
          ["$1$", "$0$", "$\\cos y-\\sin x$"], 0, "$P_x=0$, $Q_y=0$, $R_z=1$."),
        q("At a sink point one expects $\\nabla\\cdot\\mathbf F$ to be:",
          ["Negative", "Positive", "Always exactly $1$"], 0,
          "Negative divergence means net inward flux density."),
    ]

    banks["CURL_CORE_QUIZ"] = [
        q("Compute $\\nabla\\times\\langle -y,x,0\\rangle$.",
          ["$\\langle 0,0,2\\rangle$", "$\\langle 0,0,0\\rangle$", "$\\langle 0,0,1\\rangle$"], 0,
          "$Q_x-P_y=1-(-1)=2$."),
        q("For $\\mathbf F=\\langle yz,xz,xy\\rangle$, $\\nabla\\times\\mathbf F$ equals:",
          ["$\\mathbf 0$", "$\\langle 1,1,1\\rangle$", "$\\langle y,x,0\\rangle$"], 0,
          "Each curl component cancels."),
        q("Curl of a gradient $\\nabla\\times(\\nabla f)$ is:",
          ["$\\mathbf 0$", "$\\nabla^2 f$", "$\\nabla f$"], 0,
          "Classic identity."),
        q("For a 2D field $\\langle P,Q\\rangle$, $\\nabla\\times\\mathbf F$ reduces to:",
          ["$(Q_x-P_y)\\mathbf k$", "$(P_x+Q_y)\\mathbf k$", "$(P_y-Q_x)\\mathbf i$"], 0,
          "Only the $k$-component survives."),
        q("Evaluate $\\nabla\\times\\langle 0,-z,y\\rangle$.",
          ["$\\langle 2,0,0\\rangle$", "$\\langle 0,0,0\\rangle$", "$\\langle 0,1,-1\\rangle$"], 0,
          "$\\mathbf i(1-(-1))=2\\mathbf i$."),
        q("A field with $\\nabla\\times\\mathbf F=\\mathbf 0$ is called:",
          ["Irrotational", "Solenoidal", "Incompressible"], 0,
          "Zero curl means irrotational."),
        q("Rigid rotation $\\mathbf F=\\langle -\\omega y,\\omega x,0\\rangle$ has curl:",
          ["$\\langle 0,0,2\\omega\\rangle$", "$\\langle 0,0,0\\rangle$", "$\\langle \\omega,\\omega,0\\rangle$"], 0,
          "$Q_x-P_y=\\omega-(-\omega)=2\\omega$."),
        q("Compute $\\nabla\\times\\langle z,0,-x\\rangle$ at $(1,2,3)$.",
          ["$\\langle 0,2,0\\rangle$", "$\\langle 0,0,0\\rangle$", "$\\langle 1,0,-1\\rangle$"], 0,
          "Curl is $\\langle 0,2,0\\rangle$ constantly."),
        q("If $\\mathbf F=\\langle x^2,y^2,z^2\\rangle$, then $\\nabla\\times\\mathbf F$ equals:",
          ["$\\mathbf 0$", "$\\langle 2x,2y,2z\\rangle$", "$\\langle 0,0,2\\rangle$"], 0,
          "All curl components vanish."),
        q("Compute the $k$-component of curl for $\\langle x^2y,xy^2\\rangle$:",
          ["$y^2-x^2$", "$x^2-y^2$", "$2xy$"], 0,
          "$Q_x-P_y=y^2-x^2$."),
        q("For $\\mathbf F=\\langle 0,0,x\\rangle$, $\\nabla\\times\\mathbf F$ equals:",
          ["$\\langle 0,-1,0\\rangle$", "$\\langle 1,0,0\\rangle$", "$\\mathbf 0$"], 0,
          "$\\mathbf j$ component is $-(R_x-P_z)=-1$."),
        q("Curl measures local:",
          ["Rotation density", "Expansion density", "Path length"], 0,
          "Interpretation of $\\nabla\\times\\mathbf F$."),
        q("Compute $\\nabla\\times\\langle ye^z,xe^z,xye^z\\rangle$.",
          ["$\\mathbf 0$", "$\\langle e^z,e^z,0\\rangle$", "$\\langle 0,0,e^z\\rangle$"], 0,
          "It is $\\nabla(xye^z)$ up to checking; curl vanishes."),
        q("If curl is $\\langle 0,0,4\\rangle$ everywhere, circulation around a unit circle (via Stokes on the disk) is:",
          ["$4\\pi$", "$4$", "$0$"], 0,
          "Flux of curl through unit disk is $4\\cdot\\pi$."),
        q("For $\\mathbf F=\\langle -z,0,y\\rangle$, $\\nabla\\times\\mathbf F$ equals:",
          ["$\\langle 1,1,0\\rangle$", "$\\langle 0,0,0\\rangle$", "$\\langle 1,0,1\\rangle$"], 0,
          "$\\mathbf i(1-0)-\\mathbf j(0-(-1))+\\mathbf k(0)=\\langle 1,1,0\\rangle$."),
    ]

    banks["VECTOR_CATALOG_QUIZ"] = [
        q("Work of $\\mathbf F$ along $C$ is the line integral:",
          ["$\\int_C\\mathbf F\\cdot d\\mathbf r$", "$\\int_C\\mathbf F\\cdot\\mathbf n\\,ds$", "$\\iint_S\\mathbf F\\cdot\\mathbf n\\,dS$"], 0,
          "Tangent work integral."),
        q("A field is conservative on a simply connected domain if:",
          ["$\\nabla\\times\\mathbf F=\\mathbf 0$", "$\\nabla\\cdot\\mathbf F=0$", "$\\|\\mathbf F\\|=1$"], 0,
          "Irrotational plus topology hypotheses."),
        q("For $\\mathbf F=\\langle 2x,2y\\rangle$, a potential is:",
          ["$f=x^2+y^2$", "$f=2xy$", "$f=x+y$"], 0,
          "$\\nabla f=\\langle 2x,2y\\rangle$."),
        q("Path independence of work integrals is equivalent to:",
          ["Existence of a scalar potential (on the domain)", "Zero divergence", "Closed paths only"], 0,
          "Conservative field characterization."),
        q("Flux of a 2D field across a curve uses:",
          ["$\\int_C\\mathbf F\\cdot\\mathbf n\\,ds$", "$\\int_C\\mathbf F\\cdot d\\mathbf r$", "$\\nabla\\times\\mathbf F$ only"], 0,
          "Normal line integral."),
        q("Test: for $\\langle P,Q\\rangle=\\langle -y,x\\rangle$, $Q_x-P_y$ equals $2\\ne 0$, so on $\\mathbb{R}^2$ the field is:",
          ["Not conservative", "Conservative with potential $xy$", "Divergence-free and conservative"], 0,
          "Nonzero curl obstruction."),
        q("Physical reading: divergence models local:",
          ["Expansion/compression of fluid", "Rotation rate only", "Temperature alone"], 0,
          "Continuity equation intuition."),
        q("Physical reading: curl models local:",
          ["Rotation / vorticity", "Mass creation only", "Pressure"], 0,
          "Vorticity interpretation."),
        q("Find $f$ with $\\nabla f=\\langle y,x\\rangle$:",
          ["$f=xy+C$", "$f=x^2+y^2$", "$f=x+y$"], 0,
          "Integrate $f_x=y$ then match $f_y=x$."),
        q("If $\\mathbf F=\\nabla f$ and $A,B$ are endpoints of any path in a simply connected domain,",
          ["$\\int_A^B\\mathbf F\\cdot d\\mathbf r=f(B)-f(A)$", "The integral depends on the path shape", "The integral is always $0$"], 0,
          "Fundamental theorem for line integrals."),
        q("Mixed partials test for $\\langle P,Q\\rangle$: check:",
          ["$P_y=Q_x$", "$P_x=Q_y$", "$P+Q=0$"], 0,
          "Necessary condition for a potential."),
        q("For $\\mathbf F=\\langle e^y,xe^y\\rangle$, since $P_y=e^y=Q_x$, a potential is:",
          ["$f=xe^y$", "$f=e^y$", "$f=xy$"], 0,
          "Integrate $P$ in $x$."),
        q("Circulation around a closed curve vanishes for every closed curve when:",
          ["The field is conservative", "Divergence is zero", "The curve is a circle"], 0,
          "Equivalent to path independence."),
        q("Unit tangent work with $\\mathbf F=\\langle 1,0\\rangle$ along the segment from $(0,0)$ to $(2,0)$ equals:",
          ["$2$", "$0$", "$1$"], 0,
          "$\\int_0^2 1\\,dx=2$."),
        q("If a potential exists, curl of $\\mathbf F$ must be:",
          ["$\\mathbf 0$", "Nonzero", "Equal to $\\mathbf F$"], 0,
          "Necessary condition."),
    ]

    banks["VECTOR_IDENTITY_QUIZ"] = [
        q("Identity: $\\nabla\\times(\\nabla f)$ equals:",
          ["$\\mathbf 0$", "$\\nabla^2 f$", "$f$"], 0, "Curl of a gradient vanishes."),
        q("Identity: $\\nabla\\cdot(\\nabla\\times\\mathbf F)$ equals:",
          ["$0$", "$\\|\\nabla\\times\\mathbf F\\|$", "$\\nabla\\cdot\\mathbf F$"], 0,
          "Divergence of a curl vanishes."),
        q("Product rule: $\\nabla\\cdot(f\\mathbf F)$ expands to:",
          ["$f\\nabla\\cdot\\mathbf F+\\nabla f\\cdot\\mathbf F$", "$f\\nabla\\times\\mathbf F$", "$\\nabla f\\times\\mathbf F$"], 0,
          "Standard identity."),
        q("For $f=xyz$ and $\\mathbf F=\\langle 1,0,0\\rangle$, $\\nabla\\cdot(f\\mathbf F)$ equals:",
          ["$yz$", "$xy$", "$0$"], 0,
          "$f\\nabla\\cdot\\mathbf F+\\nabla f\\cdot\\mathbf F=0+\\langle yz,xz,xy\\rangle\\cdot\\langle 1,0,0\\rangle=yz$."),
        q("Laplacian $\\nabla^2 f$ in Cartesian 3D is:",
          ["$f_{xx}+f_{yy}+f_{zz}$", "$f_x+f_y+f_z$", "$\\|\\nabla f\\|^2$"], 0,
          "Definition."),
        q("Compute $\\nabla^2(x^2+y^2+z^2)$.",
          ["$6$", "$2$", "$0$"], 0, "Second derivatives sum to $6$."),
        q("For $\\mathbf F=\\langle -y,x,0\\rangle$, $\\nabla\\cdot(\\nabla\\times\\mathbf F)$ equals:",
          ["$0$", "$2$", "$-2$"], 0, "Identity forces zero."),
        q("Expand $\\nabla\\times(f\\mathbf F)$ schematically includes:",
          ["$f(\\nabla\\times\\mathbf F)+\\nabla f\\times\\mathbf F$", "Only $f\\nabla\\cdot\\mathbf F$", "Only $\\nabla^2 f$"], 0,
          "Curl product rule."),
        q("If $\\mathbf F=\\nabla\\times\\mathbf A$, then automatically $\\nabla\\cdot\\mathbf F$ equals:",
          ["$0$", "$\\|\\mathbf A\\|$", "$\\nabla\\times\\mathbf A$"], 0,
          "Divergence of a curl."),
        q("Surface element on graph $z=g(x,y)$ uses the vector:",
          ["$\\langle -g_x,-g_y,1\\rangle\\,dx\\,dy$", "$\\langle 1,0,0\\rangle\\,dx\\,dy$", "$\\langle g_x,g_y,0\\rangle$"], 0,
          "Upward graph orientation."),
        q("For $f=e^{x}$, $\\nabla^2 f$ equals:",
          ["$e^{x}$", "$0$", "$2e^{x}$"], 0, "Only $f_{xx}=e^x$."),
        q("Verify $\\nabla\\times\\langle y,z,x\\rangle$ then take divergence: result is:",
          ["$0$", "$1$", "$3$"], 0, "Must be zero by identity."),
        q("Harmonic functions satisfy $\\nabla^2 f=0$. Is $f=x$ harmonic?",
          ["Yes", "No, because $f_{xx}=1$", "Only on the unit ball"], 0,
          "All second derivatives vanish."),
        q("Parameterized surface $\\mathbf r(u,v)$ has normal factor:",
          ["$\\mathbf r_u\\times\\mathbf r_v$", "$\\mathbf r_u\\cdot\\mathbf r_v$", "$\\|\\mathbf r\\|$"], 0,
          "Standard surface Jacobian vector."),
        q("If $\\nabla\\times\\mathbf F=\\mathbf 0$ and $\\nabla\\cdot\\mathbf F=0$, then in Cartesian coordinates $F$ is both:",
          ["Irrotational and solenoidal", "Only conservative in name", "Necessarily constant"], 0,
          "Both differential conditions."),
    ]

    banks["DIV_THEOREM_QUIZ"] = [
        q("Divergence theorem equates $\\iint_S\\mathbf F\\cdot\\mathbf n\\,dS$ with:",
          ["$\\iiint_E\\nabla\\cdot\\mathbf F\\,dV$", "$\\oint_C\\mathbf F\\cdot d\\mathbf r$", "$\\iint_S(\\nabla\\times\\mathbf F)\\cdot\\mathbf n\\,dS$"], 0,
          "Flux equals triple integral of divergence."),
        q("Hypotheses require $S$ to be:",
          ["Closed and oriented outward", "An open disk only", "A graph over $xy$ only"], 0,
          "Closed surface with outward normal."),
        q("For $\\mathbf F=\\langle x,y,z\\rangle$ on the unit sphere, flux equals:",
          ["$4\\pi$", "$4\\pi/3$", "$0$"], 0,
          "$\\nabla\\cdot\\mathbf F=3$, volume $4\\pi/3$, product $4\\pi$."),
        q("Flux of $\\mathbf F=\\langle x,y,z\\rangle$ through the sphere of radius $a$ equals:",
          ["$4\\pi a^3$", "$4\\pi a^2$", "$\\dfrac{4}{3}\\pi a^3$"], 0,
          "$\\nabla\\cdot\\mathbf F=3$ and volume $\\dfrac{4}{3}\\pi a^3$ give $4\\pi a^3$."),
        q("If $\\nabla\\cdot\\mathbf F=0$ in $E$, flux through $\\partial E$ is:",
          ["$0$", "$1$", "Equal to surface area"], 0,
          "Triple integral of zero."),
        q("Box $[0,1]^3$ and $\\mathbf F=\\langle x,0,0\\rangle$: flux outward equals:",
          ["$1$", "$0$", "$3$"], 0,
          "$\\nabla\\cdot\\mathbf F=1$, volume $1$."),
        q("For $\\mathbf F=\\langle 0,0,z\\rangle$ on the unit ball, flux equals:",
          ["$4\\pi/3$", "$0$", "$2\\pi$"], 0,
          "Divergence $1$ times volume $4\\pi/3$."),
        q("Outward flux through two closed surfaces bounding a shell equals the triple integral of divergence over:",
          ["The region between them", "Only the inner cavity", "All of $\\mathbb{R}^3$"], 0,
          "Apply the theorem to the shell region."),
        q("Compute outward flux of $\\langle 2x,3y,-5z\\rangle$ through any closed surface enclosing volume $V$:",
          ["$0$", "$V$", "$10V$"], 0,
          "Divergence $2+3-5=0$."),
        q("Unit cube and $\\mathbf F=\\langle xy,0,0\\rangle$: $\\nabla\\cdot\\mathbf F=y$, flux equals:",
          ["$1/2$", "$1$", "$0$"], 0,
          "$\\int_0^1\\int_0^1\\int_0^1 y\\,dx\\,dy\\,dz=1/2$."),
        q("Gauss theorem fails for the Coulomb field through a sphere about the origin because:",
          ["The field is not $C^1$ at the origin inside", "Divergence is zero so flux must be zero anyway", "The sphere is not closed"], 0,
          "Singularity at the origin violates hypotheses."),
        q("Cylinder $x^2+y^2\\le 1$, $0\\le z\\le 1$, field $\\langle 0,0,1\\rangle$: outward flux equals:",
          ["$0$", "$\\pi$", "$2\\pi$"], 0,
          "Divergence is $0$, so the triple integral vanishes."),
        q("Same cylinder, field $\\langle 0,0,z\\rangle$: outward flux equals:",
          ["$\\pi$", "$0$", "$1$"], 0,
          "Divergence $1$, volume $\\pi$."),
        q("If flux out of every closed surface is zero, then (smooth case) $\\nabla\\cdot\\mathbf F$ is:",
          ["Identically $0$", "Identically $1$", "Equal to curl"], 0,
          "Localize the triple integral."),
        q("Orientation: divergence theorem uses the:",
          ["Outward unit normal", "Inward normal only", "Tangent to every curve"], 0,
          "Standard orientation convention."),
    ]

    banks["STOKES_THEOREM_QUIZ"] = [
        q("Stokes equates $\\oint_C\\mathbf F\\cdot d\\mathbf r$ with:",
          ["$\\iint_S(\\nabla\\times\\mathbf F)\\cdot\\mathbf n\\,dS$", "$\\iiint\\nabla\\cdot\\mathbf F\\,dV$", "$\\iint_S\\mathbf F\\cdot\\mathbf n\\,dS$"], 0,
          "Circulation equals curl flux."),
        q("Green's theorem is Stokes for a flat region in the $xy$-plane with normal:",
          ["$\\mathbf k$", "$\\mathbf i$", "$-\\mathbf j$"], 0,
          "Flat case."),
        q("If $S_1$ and $S_2$ share oriented boundary $C$, curl fluxes through them:",
          ["Are equal", "Differ by volume enclosed", "Must both vanish"], 0,
          "Both equal the same circulation."),
        q("For $\\mathbf F=\\langle -y,x,0\\rangle$ on the unit circle, Stokes on the disk yields circulation:",
          ["$2\\pi$", "$\\pi$", "$0$"], 0,
          "Curl $2\\mathbf k$; area $\\pi$."),
        q("Orientation: right-hand rule ties:",
          ["Boundary direction to the chosen normal", "Divergence to curl", "Only arc length to flux"], 0,
          "Consistent orientation."),
        q("Curl flux through a closed surface (no boundary) is:",
          ["$0$", "$4\\pi$", "Equal to enclosed volume"], 0,
          "Boundary empty $\\Rightarrow$ Stokes gives $0$; also div(curl)=0."),
        q("Replacing the upper hemisphere by the equatorial disk for Stokes is valid because:",
          ["They share the same oriented boundary circle", "They have equal area", "Curl is zero"], 0,
          "Shared boundary."),
        q("If $\\nabla\\times\\mathbf F=\\mathbf 0$, circulation on any $C=\\partial S$ is:",
          ["$0$", "$1$", "Path-dependent"], 0,
          "Stokes integral of zero."),
        q("For $\\mathbf F=\\langle z,x,y\\rangle$, $\\nabla\\times\\mathbf F=\\langle 1,1,1\\rangle$. Curl flux through unit disk $z=0$ upward:",
          ["$\\pi$", "$0$", "$1$"], 0,
          "Only $z$-component contributes: area $\\pi$."),
        q("Green integrand $Q_x-P_y$ for $\\langle -y,x\\rangle$ equals:",
          ["$2$", "$0$", "$1$"], 0, "$1-(-1)=2$."),
        q("Stokes requires $\\mathbf F$ to be:",
          ["$C^1$ near the surface", "Only continuous", "Polynomial"], 0,
          "Need continuous partials to form curl."),
        q("Circulation of a conservative field on a closed curve is:",
          ["$0$", "Equal to $\\|\\mathbf F\\|$", "Nonzero in general"], 0,
          "Fundamental theorem / Stokes."),
        q("If two surfaces have opposite normals on the same geometric set with the same rim, Stokes integrals:",
          ["Differ by a sign", "Are unrelated", "Both double"], 0,
          "Orientation reversal."),
        q("Ampere-type reading: circulation of $\\mathbf B$ relates to flux of:",
          ["A curl-like current density through a spanning surface", "Only $\\nabla\\cdot\\mathbf E$", "Scalar potential alone"], 0,
          "Stokes-type physical law."),
        q("For the unit circle as boundary, the paraboloid $z=1-x^2-y^2$ ($z\\ge 0$) is interchangeable with:",
          ["The unit disk in $z=0$", "The sphere of radius $2$", "The plane $z=2$"], 0,
          "Same rim $x^2+y^2=1$, $z=0$."),
    ]

    banks["DIVCURL_CHALLENGE_QUIZ"] = [
        q("Flux of $\\langle x,y,z\\rangle$ out of the sphere $x^2+y^2+z^2=4$ equals:",
          ["$32\\pi$", "$16\\pi$", "$4\\pi$"], 0,
          "Radius $2$, volume $\\tfrac{32}{3}\\pi$, times $3$ gives $32\\pi$."),
        q("Circulation of $\\langle -y,x,0\\rangle$ around $x^2+y^2=9$, $z=0$, via the disk:",
          ["$18\\pi$", "$9\\pi$", "$6\\pi$"], 0,
          "Curl $2\\mathbf k$; area $9\\pi$; product $18\\pi$."),
        q("Cheapest tool for outward flux of a divergence-free field through a closed surface:",
          ["Conclude the flux is $0$ immediately", "Parametrize the whole surface", "Convert to Stokes"], 0,
          "Divergence theorem with zero integrand."),
        q("Field $\\langle -y/(x^2+y^2),x/(x^2+y^2),0\\rangle$ on the unit circle has circulation $2\\pi$ even though curl vanishes off the origin because:",
          ["The singularity at the origin blocks a naive Stokes application on the disk", "Divergence theorem applies instead", "The field is conservative on $\\mathbb{R}^2$"], 0,
          "Classic counterexample domain issue."),
        q("Compute $\\nabla\\times\\langle yz,xz,xy\\rangle$ then $\\nabla\\cdot$ of that curl:",
          ["$0$", "$1$", "$xyz$"], 0, "Identity."),
        q("Outward flux of $\\langle 4x,y,-5z\\rangle$ through the unit sphere:",
          ["$0$", "$4\\pi$", "$4\\pi/3$"], 0,
          "Divergence $4+1-5=0$."),
        q("For $\\mathbf F=\\langle 0,-z,y\\rangle$, circulation around the unit circle in the $yz$-plane via Stokes on the unit disk in $x=0$:",
          ["$2\\pi$", "$0$", "$\\pi$"], 0,
          "Curl $\\langle 2,0,0\\rangle$; flux through disk normal $\\mathbf i$ is $2\\pi$."),
        q("Maxwell-style: if $\\mathbf B=\\nabla\\times\\mathbf A$, then $\\nabla\\cdot\\mathbf B$ equals:",
          ["$0$", "$\\|\\mathbf A\\|$", "$\\nabla\\cdot\\mathbf A$"], 0,
          "Divergence of curl."),
        q("Volume of the region enclosed equals flux of $\\tfrac13\\langle x,y,z\\rangle$ because:",
          ["Divergence is $1$", "Curl is $\\mathbf 0$", "The field is constant"], 0,
          "$\\nabla\\cdot(\\tfrac13\\langle x,y,z\\rangle)=1$."),
        q("Flux of $\\langle x^3,y^3,z^3\\rangle$ out of the unit ball: use divergence $3(x^2+y^2+z^2)$ and symmetry — the integral equals:",
          ["$12\\pi/5$", "$4\\pi/3$", "$0$"], 0,
          "In spherical coordinates one obtains $12\\pi/5$."),
        q("Decide tool: compute $\\oint_C\\langle -y,x,z\\rangle\\cdot d\\mathbf r$ for $C$ the unit circle $z=0$. Best first step:",
          ["Apply Stokes on the unit disk", "Parametrize a helix", "Use divergence theorem on a ball"], 0,
          "Closed curve in a plane — Stokes is natural."),
        q("That circulation equals:",
          ["$2\\pi$", "$0$", "$\\pi$"], 0,
          "Curl $\\langle 0,0,2\\rangle$; flux $2\\pi$."),
        q("If $\\nabla\\cdot\\mathbf F=2$ constantly, flux out of a ball of radius $1$ is:",
          ["$8\\pi/3$", "$4\\pi/3$", "$2$"], 0,
          "$2\\times$ volume $4\\pi/3$."),
        q("For $\\mathbf F=\\langle 2xy,x^2,0\\rangle$, curl is $\\mathbf 0$ and a potential is:",
          ["$f=x^2y$", "$f=xy$", "$f=x^2+y$"], 0,
          "$\\nabla(x^2y)=\\langle 2xy,x^2,0\\rangle$."),
        q("Closed-surface flux of $\\nabla\\times\\mathbf G$ for smooth $\\mathbf G$ is:",
          ["Always $0$", "Equal to $\\|\\mathbf G\\|$", "The enclosed volume"], 0,
          "div(curl)=0 or Stokes with empty boundary."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "mvDivCurlQuizzes.js",
        "/** Study-guide quiz banks for the Divergence & Curl guide — 15 MCQs per section. */",
        build(),
    )
