# -*- coding: utf-8 -*-
"""Emit laSystemsEigenQuizzes.js — LA systems and eigenvalues banks."""
from _quiz_emit import q, emit_file, OUT


def build():
    banks = {}

    banks["LA_S_INTRO_QUIZ"] = [
        q("Solve the system $x+y=5$, $x-y=1$.",
          ["$x=3,\\ y=2$", "$x=2,\\ y=3$", "$x=4,\\ y=1$"], 0,
          "Adding gives $2x=6$, so $x=3$ and $y=2$."),
        q("Which equation is linear in $x$ and $y$?",
          ["$2x-3y=7$", "$x^2+y=1$", "$xy=4$"], 0,
          "A linear equation has no products or powers of unknowns."),
        q("The system $x+y=1$, $2x+2y=3$ has:",
          ["No solution", "A unique solution", "Infinitely many solutions"], 0,
          "The second row is inconsistent with twice the first."),
        q("The homogeneous system $A\\mathbf{x}=\\mathbf{0}$ always has:",
          ["At least the trivial solution $\\mathbf{x}=\\mathbf{0}$", "No solution", "Exactly one nonzero solution"], 0,
          "Substituting $\\mathbf{0}$ always works."),
        q("Write $x-y=4$, $2x+y=5$ as $A\\mathbf{x}=\\mathbf{b}$. Then $A$ is:",
          ["$\\begin{pmatrix}1&-1\\\\2&1\\end{pmatrix}$", "$\\begin{pmatrix}1&2\\\\-1&1\\end{pmatrix}$", "$\\begin{pmatrix}4\\\\5\\end{pmatrix}$"], 0,
          "Coefficient matrix of the unknowns."),
        q("Solve $2x=6$, $y=-1$.",
          ["$x=3,\\ y=-1$", "$x=6,\\ y=-1$", "$x=3,\\ y=1$"], 0,
          "Divide the first equation by $2$."),
        q("An augmented matrix for $x+2y=3$, $4x-y=1$ is:",
          ["$\\begin{pmatrix}1&2&3\\\\4&-1&1\\end{pmatrix}$", "$\\begin{pmatrix}1&2\\\\4&-1\\end{pmatrix}$", "$\\begin{pmatrix}3&1\\\\1&4\\end{pmatrix}$"], 0,
          "Coefficients plus the right-hand side column."),
        q("The system $x+y+z=0$, $x-y=0$, $y-z=0$ has:",
          ["Only the trivial solution", "A line of solutions", "No solution"], 0,
          "Forces $x=y=z=0$."),
        q("If two distinct lines in the plane intersect at exactly one point, the $2\\times 2$ system has:",
          ["A unique solution", "No solution", "Infinitely many solutions"], 0,
          "One intersection point means one solution pair."),
        q("Solve $x+2y=4$, $3x+6y=12$.",
          ["Infinitely many solutions", "No solution", "The unique solution $x=4$, $y=0$"], 0,
          "The second equation is three times the first."),
        q("Consistency of a linear system means:",
          ["At least one solution exists", "The solution is unique", "All variables are free"], 0,
          "Consistent means nonempty solution set."),
        q("For $x-y=2$, $x-y=5$, the solution set is:",
          ["Empty", "A single point", "A line"], 0,
          "Contradictory parallel equations."),
        q("Solve $x=1$, $y=2$, $z=3$ written as three equations. The solution is:",
          ["$(1,2,3)$", "$(0,0,0)$", "Infinitely many triples"], 0,
          "Each variable is already determined."),
        q("A $3\\times 3$ system with a unique solution has coefficient matrix that is:",
          ["Invertible", "Singular", "The zero matrix"], 0,
          "Unique solution iff $A$ is invertible."),
        q("The equation $0\\cdot x+0\\cdot y=1$ in a system forces:",
          ["Inconsistency", "A free variable only", "The trivial solution"], 0,
          "A false statement $0=1$ appears."),
    ]

    banks["LA_S_GAUSS_QUIZ"] = [
        q("Which is an elementary row operation?",
          ["Swap two rows", "Delete a row", "Square every entry"], 0,
          "The three elementary operations include row swaps."),
        q("A pivot position in a row is:",
          ["The first nonzero entry in that row of an echelon form", "Any zero entry", "The last column always"], 0,
          "Pivots lead the nonzero rows in echelon form."),
        q("The row $[0\\ 0\\ 0\\mid 5]$ in an augmented matrix means the system is:",
          ["Inconsistent", "Homogeneous", "Underdetermined only"], 0,
          "It asserts $0=5$."),
        q("Back-substitute from $\\begin{pmatrix}1&2&3\\\\0&1&4\\end{pmatrix}$: if variables are $x,y$, then:",
          ["$y=4$, $x=3-8=-5$", "$y=4$, $x=3$", "$y=0$, $x=3$"], 0,
          "From $y=4$ and $x+2y=3$ get $x=-5$."),
        q("Reduced row echelon form requires pivots to be $1$ and:",
          ["The only nonzero entry in their columns", "All entries above pivots nonzero", "A square matrix"], 0,
          "RREF clears above and below each pivot."),
        q("How many free variables does $\\begin{pmatrix}1&2&0\\\\0&0&1\\end{pmatrix}$ (coefficient part) suggest for three unknowns?",
          ["$1$", "$0$", "$2$"], 0,
          "Two pivot columns leave one free variable."),
        q("Row-reducing $\\begin{pmatrix}1&1&2\\\\2&2&4\\end{pmatrix}$ can produce:",
          ["$\\begin{pmatrix}1&1&2\\\\0&0&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0&0\\\\0&1&0\\end{pmatrix}$", "A pivot in every column"], 0,
          "The second row is a multiple of the first."),
        q("An echelon form never has a nonzero entry:",
          ["Below a pivot in the same column", "Above a pivot", "On the diagonal"], 0,
          "Zeros below pivots define row echelon form."),
        q("Starting from $\\begin{pmatrix}2&4&6\\\\1&1&1\\end{pmatrix}$, a useful first step is:",
          ["Swap rows or scale the first row", "Add a new variable", "Delete the second row"], 0,
          "Create a convenient pivot, often $1$."),
        q("If the only nonzero row of a $2\\times 3$ coefficient echelon form is $[1\\ 2\\ 3]$, the number of free variables is:",
          ["$2$", "$1$", "$0$"], 0,
          "One pivot among three columns."),
        q("Back substitution on $x+y=5$, $y=2$ gives:",
          ["$x=3$", "$x=5$", "$x=2$"], 0,
          "$x+2=5$ so $x=3$."),
        q("Replacing $R_2$ by $R_2-3R_1$ is:",
          ["An elementary row operation", "Not allowed in Gaussian elimination", "A column operation"], 0,
          "Adding a multiple of one row to another is elementary."),
        q("A pivot cannot occur in a column that is:",
          ["Entirely zero in the working matrix", "The last column of a square matrix", "The first column"], 0,
          "All-zero columns have no pivot."),
        q("After elimination, $\\begin{pmatrix}1&0&2\\\\0&1&-1\\\\0&0&0\\end{pmatrix}\\mid\\begin{pmatrix}3\\\\4\\\\0\\end{pmatrix}$ describes:",
          ["A line of solutions", "No solution", "A unique solution"], 0,
          "One free variable with a consistent zero row."),
        q("Counting roughly, eliminating an $n\\times n$ system with dense Gaussian elimination costs on the order of:",
          ["$n^3$ arithmetic operations", "$n$ operations", "$2^n$ operations"], 0,
          "Classic cubic complexity of Gaussian elimination."),
    ]

    banks["LA_S_RANK_QUIZ"] = [
        q("The rank of $\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$ is:",
          ["$2$", "$1$", "$0$"], 0,
          "Two pivot positions."),
        q("Rank-nullity for an $m\\times n$ matrix $A$ says:",
          ["$\\operatorname{rank}A+\\operatorname{nullity}A=n$", "$\\operatorname{rank}A+\\operatorname{nullity}A=m$", "$\\operatorname{rank}A=\\operatorname{nullity}A$"], 0,
          "Nullity counts free variables among $n$ unknowns."),
        q("If $\\operatorname{rank}A=2$ and $\\operatorname{rank}[A\\mid\\mathbf{b}]=3$, the system $A\\mathbf{x}=\\mathbf{b}$ is:",
          ["Inconsistent", "Consistent with unique solution", "Consistent with free variables"], 0,
          "Augmented rank larger than $\\operatorname{rank}A$ means inconsistency."),
        q("Nullity of a $3\\times 3$ invertible matrix is:",
          ["$0$", "$3$", "$1$"], 0,
          "Full rank implies trivial nullspace."),
        q("Dimension of the column space equals:",
          ["The rank", "The number of rows always", "The nullity"], 0,
          "Rank is $\\dim\\operatorname{Col}A$."),
        q("For $A=\\begin{pmatrix}1&2&3\\\\0&0&0\\end{pmatrix}$, $\\operatorname{rank}A$ equals:",
          ["$1$", "$2$", "$3$"], 0,
          "One nonzero row after echelon thoughts."),
        q("Number of free variables equals:",
          ["$n-\\operatorname{rank}A$", "$\\operatorname{rank}A$", "$m-\\operatorname{rank}A$ always"], 0,
          "Nullity $=n-\\operatorname{rank}$."),
        q("If $\\operatorname{rank}A=\\operatorname{rank}[A\\mid\\mathbf{b}]=2$ for a $3\\times 4$ matrix, then:",
          ["The system is consistent with $2$ free variables", "The system is inconsistent", "There is a unique solution"], 0,
          "Consistency holds; nullity $=4-2=2$."),
        q("The rank of the zero $2\\times 2$ matrix is:",
          ["$0$", "$2$", "$1$"], 0,
          "No pivots."),
        q("If columns of $A$ are independent and $A$ is $3\\times 2$, then $\\operatorname{rank}A$ is:",
          ["$2$", "$3$", "$1$"], 0,
          "Two independent columns give rank $2$."),
        q("Dimension of $\\operatorname{Nul}A$ for $A=\\begin{pmatrix}1&1\\\\2&2\\end{pmatrix}$ is:",
          ["$1$", "$0$", "$2$"], 0,
          "Rank $1$ and $n=2$ so nullity $1$."),
        q("Reading rank from echelon form means counting:",
          ["Nonzero rows (pivots)", "Total rows including zeros", "The right-hand side entries"], 0,
          "Each pivot row contributes one to the rank."),
        q("For a consistent system, $\\operatorname{rank}A$ equals:",
          ["$\\operatorname{rank}[A\\mid\\mathbf{b}]$", "$n$", "Always $m$"], 0,
          "Consistency criterion."),
        q("$\\operatorname{rank}\\begin{pmatrix}0&1&0\\\\0&0&1\\\\0&0&0\\end{pmatrix}$ equals:",
          ["$2$", "$3$", "$1$"], 0,
          "Two pivot columns."),
        q("If $\\operatorname{rank}A=n$ for an $n\\times n$ matrix, then $A\\mathbf{x}=\\mathbf{b}$ has:",
          ["A unique solution for every $\\mathbf{b}$", "No solution for some $\\mathbf{b}$", "Infinitely many solutions always"], 0,
          "Full rank square matrices are invertible."),
    ]

    banks["LA_S_GEO_QUIZ"] = [
        q("The solution set of a consistent $2\\times 2$ system with one free variable is geometrically:",
          ["A line", "A single point", "A plane"], 0,
          "One parameter yields a line in the plane."),
        q("Two distinct parallel lines in $\\mathbb{R}^2$ as equations give:",
          ["No common solution", "Infinitely many solutions", "Exactly one solution"], 0,
          "Parallel distinct lines never meet."),
        q("If two planes in $\\mathbb{R}^3$ intersect and are not coincident, their intersection is typically:",
          ["A line", "A single point", "All of $\\mathbb{R}^3$"], 0,
          "Two independent plane equations leave one free variable."),
        q("A particular solution $\\mathbf{x}_p$ plus the nullspace describes:",
          ["The full solution set of $A\\mathbf{x}=\\mathbf{b}$", "Only homogeneous solutions", "Only inconsistent systems"], 0,
          "Affine translate of the homogeneous solution space."),
        q("Parametric form $\\mathbf{x}=\\begin{pmatrix}1\\\\0\\end{pmatrix}+t\\begin{pmatrix}2\\\\1\\end{pmatrix}$ is:",
          ["A line through $(1,0)$", "A plane", "Only the origin"], 0,
          "Point plus span of one direction vector."),
        q("Three planes with no common point correspond to:",
          ["An inconsistent $3\\times 3$ system", "A unique solution", "A line of solutions"], 0,
          "Empty intersection means no solution."),
        q("Coincident lines (same line twice) as a $2\\times 2$ system give:",
          ["Infinitely many solutions", "No solution", "Exactly two solutions"], 0,
          "Redundant equations describe the same line."),
        q("A singular coefficient matrix geometrically often means:",
          ["Parallel or dependent constraint hyperplanes", "Always a unique intersection point", "Orthogonal rows"], 0,
          "Dependent rows fail to cut down dimension fully."),
        q("The homogeneous solution set always contains:",
          ["The origin", "Exactly one nonzero vector", "No vectors"], 0,
          "It is a subspace."),
        q("Solution set $\\{\\mathbf{0}\\}$ for $A\\mathbf{x}=\\mathbf{0}$ means columns of $A$ are:",
          ["Independent (trivial nullspace)", "Dependent", "Parallel to $\\mathbf{b}$"], 0,
          "Only the zero combination works."),
        q("In $\\mathbb{R}^3$, one linear equation typically describes:",
          ["A plane", "A line", "A point"], 0,
          "One constraint leaves two free variables."),
        q("If $\\mathbf{x}=\\mathbf{x}_p+\\mathbf{v}_h$ with $A\\mathbf{v}_h=\\mathbf{0}$, then $A\\mathbf{x}$ equals:",
          ["$\\mathbf{b}$ whenever $A\\mathbf{x}_p=\\mathbf{b}$", "$\\mathbf{0}$", "$\\mathbf{v}_h$"], 0,
          "Linearity: $A\\mathbf{x}_p+A\\mathbf{v}_h=\\mathbf{b}$."),
        q("Intersecting $x+y+z=1$ and $x+y+z=2$ in $\\mathbb{R}^3$ yields:",
          ["The empty set", "A plane", "A line"], 0,
          "Parallel distinct planes."),
        q("A unique solution of a $3\\times 3$ system is a:",
          ["Single point in $\\mathbb{R}^3$", "Line", "Plane"], 0,
          "Zero free variables."),
        q("Parametric vector form with two free parameters in $\\mathbb{R}^3$ describes:",
          ["A plane (through a particular point)", "A line", "Only a point"], 0,
          "Two independent directions span a plane."),
    ]

    banks["LA_E_INTRO_QUIZ"] = [
        q("If $A\\mathbf{v}=3\\mathbf{v}$ with $\\mathbf{v}\\ne\\mathbf{0}$, then $\\mathbf{v}$ is an eigenvector with eigenvalue:",
          ["$3$", "$0$", "$1$"], 0,
          "Definition: $A\\mathbf{v}=\\lambda\\mathbf{v}$."),
        q("For $A=\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$, an eigenvalue is:",
          ["$2$", "$1$", "$7$"], 0,
          "Diagonal entries are the eigenvalues."),
        q("Does $\\mathbf{v}=\\begin{pmatrix}1\\\\0\\end{pmatrix}$ satisfy $A\\mathbf{v}=\\lambda\\mathbf{v}$ for $A=\\begin{pmatrix}4&1\\\\0&2\\end{pmatrix}$?",
          ["Yes, with $\\lambda=4$", "Yes, with $\\lambda=2$", "No"], 0,
          "$A\\mathbf{v}=\\begin{pmatrix}4\\\\0\\end{pmatrix}=4\\mathbf{v}$."),
        q("Eigenvalue $0$ for $A$ means:",
          ["$A$ is singular", "$A$ is the identity", "$A$ is diagonal"], 0,
          "$A\\mathbf{v}=\\mathbf{0}$ for some nonzero $\\mathbf{v}$."),
        q("If $\\mathbf{v}$ is an eigenvector, then $5\\mathbf{v}$ is:",
          ["An eigenvector for the same eigenvalue", "Never an eigenvector", "An eigenvector for eigenvalue $5$"], 0,
          "Any nonzero multiple remains an eigenvector."),
        q("Eigenvalues of the triangular matrix $\\begin{pmatrix}3&7\\\\0&-1\\end{pmatrix}$ are:",
          ["$3$ and $-1$", "$7$ and $0$", "$3$ and $7$"], 0,
          "For triangular matrices, eigenvalues sit on the diagonal."),
        q("The eigenspace for $\\lambda$ is:",
          ["$\\operatorname{Nul}(A-\\lambda I)$", "$\\operatorname{Col}A$", "$\\operatorname{Nul}A$ only when $\\lambda=1$"], 0,
          "Solve $(A-\\lambda I)\\mathbf{v}=\\mathbf{0}$."),
        q("Can $\\mathbf{0}$ be called an eigenvector?",
          ["No; eigenvectors must be nonzero", "Yes; for every $\\lambda$", "Yes; only for $\\lambda=0$"], 0,
          "The definition excludes the zero vector."),
        q("If $A\\begin{pmatrix}1\\\\1\\end{pmatrix}=\\begin{pmatrix}2\\\\2\\end{pmatrix}$, the corresponding eigenvalue is:",
          ["$2$", "$1$", "$0$"], 0,
          "The image is $2$ times the vector."),
        q("For $I_2$, every nonzero vector is an eigenvector with eigenvalue:",
          ["$1$", "$0$", "$2$"], 0,
          "$I\\mathbf{v}=1\\cdot\\mathbf{v}$."),
        q("A $2\\times 2$ matrix can have at most how many distinct eigenvalues?",
          ["$2$", "$4$", "$1$ always"], 0,
          "Degree of the characteristic polynomial is $2$."),
        q("If $A\\mathbf{v}=\\lambda\\mathbf{v}$, then $A(2\\mathbf{v})$ equals:",
          ["$\\lambda(2\\mathbf{v})$", "$2\\lambda^2\\mathbf{v}$", "$\\mathbf{v}$"], 0,
          "Linearity preserves the same $\\lambda$."),
        q("For $A=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$, a nonzero eigenvector for $\\lambda=0$ is:",
          ["$\\begin{pmatrix}1\\\\0\\end{pmatrix}$", "$\\begin{pmatrix}0\\\\1\\end{pmatrix}$", "$\\begin{pmatrix}1\\\\1\\end{pmatrix}$"], 0,
          "$A\\begin{pmatrix}1\\\\0\\end{pmatrix}=\\mathbf{0}$."),
        q("Eigenvectors for distinct eigenvalues of a real matrix are:",
          ["Linearly independent", "Always orthogonal", "Always parallel"], 0,
          "Standard independence theorem for distinct eigenvalues."),
        q("If every vector is an eigenvector of $A$, then $A$ must be:",
          ["A scalar multiple of $I$", "Singular", "Nilpotent"], 0,
          "Only scalar matrices act by the same factor on every vector."),
    ]

    banks["LA_E_CHAR_QUIZ"] = [
        q("The characteristic polynomial of $A$ is:",
          ["$\\det(A-\\lambda I)$", "$\\det(A+\\lambda I)$", "$\\operatorname{tr}(A-\\lambda I)$"], 0,
          "Roots are the eigenvalues."),
        q("For $A=\\begin{pmatrix}1&2\\\\0&3\\end{pmatrix}$, eigenvalues are:",
          ["$1$ and $3$", "$2$ and $0$", "$1$ and $2$"], 0,
          "Triangular: diagonal entries."),
        q("Characteristic polynomial of $\\begin{pmatrix}0&1\\\\-2&-3\\end{pmatrix}$ is:",
          ["$\\lambda^2+3\\lambda+2$", "$\\lambda^2-3\\lambda+2$", "$\\lambda^2+3\\lambda-2$"], 0,
          "$\\det\\begin{pmatrix}-\\lambda&1\\\\-2&-3-\\lambda\\end{pmatrix}=\\lambda^2+3\\lambda+2$."),
        q("Sum of eigenvalues of $\\begin{pmatrix}4&1\\\\2&5\\end{pmatrix}$ equals:",
          ["$9$", "$20$", "$3$"], 0,
          "Trace equals $4+5=9$."),
        q("Product of eigenvalues of $\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$ equals:",
          ["$6$", "$5$", "$1$"], 0,
          "Determinant equals the product of eigenvalues."),
        q("Algebraic multiplicity of $\\lambda$ is:",
          ["Its multiplicity as a root of the characteristic polynomial", "The dimension of the eigenspace", "Always $1$"], 0,
          "Definition of algebraic multiplicity."),
        q("Rotation by $90^\\circ$, matrix $\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$, has eigenvalues:",
          ["$\\pm i$", "$\\pm 1$", "$0$ (double)"], 0,
          "Characteristic polynomial $\\lambda^2+1=0$."),
        q("For $A=\\begin{pmatrix}5&0\\\\0&5\\end{pmatrix}$, the characteristic polynomial is:",
          ["$(5-\\lambda)^2$", "$(5-\\lambda)$", "$\\lambda^2-5$"], 0,
          "Both eigenvalues are $5$."),
        q("If $\\det A=0$, then $\\lambda=0$ is:",
          ["An eigenvalue", "Never an eigenvalue", "Always simple"], 0,
          "Singular matrices have $0$ as an eigenvalue."),
        q("Expanding $\\det\\begin{pmatrix}2-\\lambda&1\\\\0&3-\\lambda\\end{pmatrix}$ gives:",
          ["$(2-\\lambda)(3-\\lambda)$", "$(2-\\lambda)+(3-\\lambda)$", "$\\lambda^2-5$"], 0,
          "Upper triangular factorisation."),
        q("A $3\\times 3$ matrix has characteristic polynomial of degree:",
          ["$3$", "$2$", "$9$"], 0,
          "Degree equals the matrix size."),
        q("Eigenvalues of $\\begin{pmatrix}1&4\\\\2&3\\end{pmatrix}$ solve:",
          ["$(1-\\lambda)(3-\\lambda)-8=0$", "$(1-\\lambda)(3-\\lambda)+8=0$", "$\\lambda^2=0$"], 0,
          "$\\det=\\lambda^2-4\\lambda-5$; equivalently $(1-\\lambda)(3-\\lambda)-8=0$."),
        q("If eigenvalues are $2,2,5$, the trace is:",
          ["$9$", "$20$", "$5$"], 0,
          "Sum with multiplicity: $2+2+5=9$."),
        q("Complex conjugate eigenvalues appear for real matrices because:",
          ["Real characteristic polynomials have conjugate roots when complex", "Determinants are imaginary", "Trace must be zero"], 0,
          "Coefficients are real."),
        q("For $A=\\begin{pmatrix}0&-2\\\\1&3\\end{pmatrix}$, $\\det(A-\\lambda I)$ equals:",
          ["$\\lambda^2-3\\lambda+2$", "$\\lambda^2+3\\lambda+2$", "$\\lambda^2-3\\lambda-2$"], 0,
          "$\\det\\begin{pmatrix}-\\lambda&-2\\\\1&3-\\lambda\\end{pmatrix}=\\lambda(\\lambda-3)+2=\\lambda^2-3\\lambda+2$."),
    ]

    banks["LA_E_DIAG_QUIZ"] = [
        q("Diagonalization means writing $A$ as:",
          ["$PDP^{-1}$ with $D$ diagonal", "$P+D$", "$A^T A$"], 0,
          "Similarity to a diagonal matrix."),
        q("A $2\\times 2$ matrix with two independent eigenvectors is:",
          ["Diagonalizable", "Singular", "Defective"], 0,
          "Enough independent eigenvectors to form $P$."),
        q("If geometric multiplicity is less than algebraic multiplicity for some $\\lambda$, the matrix is:",
          ["Not diagonalizable (defective for that $\\lambda$)", "Orthogonally diagonalizable", "Invertible"], 0,
          "Shortage of eigenvectors blocks diagonalization."),
        q("For $A=\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$, one may take $P=I$ and $D=$:",
          ["$\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$", "$\\begin{pmatrix}0&2\\\\3&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$"], 0,
          "Already diagonal."),
        q("If $A=PDP^{-1}$, then $A^k$ equals:",
          ["$PD^k P^{-1}$", "$P^k D P^{-1}$", "$D^k$ alone"], 0,
          "Powers pass onto the diagonal factor."),
        q("Symmetric real matrices are:",
          ["Orthogonally diagonalizable", "Never diagonalizable", "Always defective"], 0,
          "Spectral theorem for real symmetric matrices."),
        q("Building $P$ means placing:",
          ["Independent eigenvectors as columns", "Eigenvalues on the diagonal of $P$", "Rows of $A$"], 0,
          "$AP=PD$ uses eigenvector columns."),
        q("The matrix $\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$ is:",
          ["Not diagonalizable", "Diagonalizable with $D=0$", "Orthogonal"], 0,
          "Only a one-dimensional eigenspace for $\\lambda=0$."),
        q("If $D=\\begin{pmatrix}2&0\\\\0&2\\end{pmatrix}$ and $P$ is invertible, $PDP^{-1}$ equals:",
          ["$2I$", "$P$", "$D$ only when $P=I$"], 0,
          "$P(2I)P^{-1}=2I$."),
        q("Geometric multiplicity is:",
          ["$\\dim\\operatorname{Nul}(A-\\lambda I)$", "The exponent of $(t-\\lambda)$ in $\\det(A-tI)$", "Always equal to $n$"], 0,
          "Dimension of the eigenspace."),
        q("For diagonalizable $A$ with eigenvalues $1$ and $4$, $A^2$ has eigenvalues:",
          ["$1$ and $16$", "$2$ and $8$", "$1$ and $4$"], 0,
          "Eigenvalues of $A^k$ are $\\lambda^k$."),
        q("A sufficient condition for a $3\\times 3$ matrix to be diagonalizable is:",
          ["Three distinct eigenvalues", "Trace zero", "Determinant zero"], 0,
          "Distinct eigenvalues give independent eigenvectors."),
        q("If $P=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$ and $D=\\begin{pmatrix}2&0\\\\0&3\\end{pmatrix}$, then $A=PDP^{-1}$ has eigenvalues:",
          ["$2$ and $3$", "$1$ and $1$", "$0$ and $1$"], 0,
          "Similar matrices share eigenvalues; here those of $D$."),
        q("Orthogonal diagonalization uses $P$ with:",
          ["$P^T P=I$", "$P=D$", "$\\det P=0$"], 0,
          "Orthonormal eigenvector basis."),
        q("Computing $A^{10}$ via diagonalization is efficient when:",
          ["$A$ is diagonalizable so $D^{10}$ is cheap", "$A$ is singular only", "$n$ is infinite"], 0,
          "Diagonal powers are entrywise."),
    ]

    banks["LA_E_APPS_QUIZ"] = [
        q("For a Markov transition matrix, long-run behavior is governed by:",
          ["The eigenvalue $1$ and its eigenvector (steady state)", "Only negative eigenvalues", "The trace alone"], 0,
          "Stochastic matrices have dominant eigenvalue $1$ under mild conditions."),
        q("A discrete system $\\mathbf{x}_{k+1}=A\\mathbf{x}_k$ tends to $\\mathbf{0}$ if all eigenvalues satisfy:",
          ["$|\\lambda|<1$", "$\\lambda>1$", "$\\lambda=0$ only"], 0,
          "Each mode scales by $\\lambda^k\\to 0$ when $|\\lambda|<1$."),
        q("The power method primarily approximates:",
          ["The dominant eigenvalue and a corresponding eigenvector", "The smallest singular value only", "The determinant"], 0,
          "Repeated multiplication amplifies the largest $|\\lambda|$ direction."),
        q("For $\\mathbf{x}'=A\\mathbf{x}$, solutions behave like $e^{\\lambda t}\\mathbf{v}$ along eigenvectors. Stability of the origin needs:",
          ["All $\\operatorname{Re}(\\lambda)<0$", "All $\\lambda>0$", "Trace positive"], 0,
          "Negative real parts give exponential decay."),
        q("Principal component directions are eigenvectors of:",
          ["A covariance (or correlation) matrix", "A Markov matrix only", "Any singular matrix"], 0,
          "PCA diagonalizes the covariance."),
        q("If the dominant eigenvalue of a positive transition structure is $1$ and others have $|\\lambda|<1$, iterates approach:",
          ["A steady-state multiple of the dominant eigenvector", "Zero always", "Oscillation with growing amplitude"], 0,
          "Transient modes die out."),
        q("Vibrational modes of a linear mechanical model often correspond to:",
          ["Eigenpairs of a stiffness/mass generalized problem", "Only the determinant", "Row sums of $A$"], 0,
          "Modal analysis is an eigenvalue problem."),
        q("If $A$ has eigenvalues $2$ and $1/2$, then $A^k\\mathbf{v}$ for a generic $\\mathbf{v}$ grows like:",
          ["$2^k$ along the dominant mode", "$(1/2)^k$", "$k$"], 0,
          "The larger magnitude eigenvalue dominates."),
        q("A $2\\times 2$ rotation by a non-multiple of $180^\\circ$ has $|\\lambda|=1$ and complex $\\lambda$, so powers:",
          ["Rotate without radial growth", "Tend to zero", "Tend to infinity"], 0,
          "Eigenvalues lie on the unit circle."),
        q("In population projection matrices, the long-term growth rate is:",
          ["The dominant eigenvalue", "The nullity", "The number of states"], 0,
          "Leslie/Lefkovitch models use the spectral radius."),
        q("If all $|\\lambda|>1$, the discrete iteration $\\mathbf{x}\\mapsto A\\mathbf{x}$ typically:",
          ["Diverges for nonzero starts", "Converges to zero", "Stays on a sphere"], 0,
          "Every mode amplifies."),
        q("Diagonalization helps solve $\\mathbf{x}'=A\\mathbf{x}$ by:",
          ["Decoupling into scalar ODEs in eigen-coordinates", "Removing all eigenvalues", "Forcing $A=0$"], 0,
          "Change of basis $\\mathbf{x}=P\\mathbf{y}$."),
        q("For a symmetric covariance matrix, PCA axes are:",
          ["Orthogonal eigenvectors", "Always the standard basis", "Singular vectors of a rectangular data matrix only, never of covariance"], 0,
          "Real symmetric eigenbases can be chosen orthonormal."),
        q("If $\\lambda=1$ is simple and dominant for a stochastic matrix with positive entries, the steady state is:",
          ["Unique up to scaling (and can be normalized to a probability vector)", "Every vector", "Only $\\mathbf{0}$"], 0,
          "Perron–Frobenius type conclusions."),
        q("The spectral radius $\\rho(A)<1$ implies that $A^k\\to 0$, which is used to conclude:",
          ["Asymptotic stability of $\\mathbf{x}\\mapsto A\\mathbf{x}$", "That $A$ is orthogonal", "That $\\det A=1$"], 0,
          "All modes decay."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "laSystemsEigenQuizzes.js",
        "/** Study-guide quiz banks for the Linear Algebra Systems and Eigenvalues guides — 15 MCQs per section. */",
        build(),
    )
