# -*- coding: utf-8 -*-
"""Emit mvPartialQuizzes.js — Multivariable Partial Derivatives banks."""
from _quiz_emit import q, emit_file, OUT


def build():
    banks = {}

    banks["MV_141_QUIZ"] = [
        q("For $f(x,y)=\\ln(9-x^2-y^2)$, which points are in the domain?",
          ["All $(x,y)$ with $x^2+y^2<9$", "All $(x,y)$ with $x^2+y^2\\le 9$", "All $(x,y)$ with $x^2+y^2>9$"], 0,
          "The logarithm needs a strictly positive argument, so $9-x^2-y^2>0$."),
        q("Evaluate $f(2,1)$ for $f(x,y)=x^2y-3y$.",
          ["$1$", "$4$", "$-1$"], 0, "$4\\cdot 1-3\\cdot 1=1$."),
        q("The range of $f(x,y)=e^{x^2+y^2}$ is:",
          ["$[1,\\infty)$", "$(0,1]$", "$(-\\infty,\\infty)$"], 0,
          "$x^2+y^2\\ge 0$ so $e^{x^2+y^2}\\ge e^0=1$."),
        q("A level curve of $f(x,y)=x^2+y^2$ at height $c=4$ is:",
          ["The circle $x^2+y^2=4$", "The line $x+y=4$", "The plane $z=4$"], 0,
          "Set $f(x,y)=4$."),
        q("For $g(x,y)=\\sqrt{4-x-y}$, the domain requires:",
          ["$x+y\\le 4$", "$x+y\\ge 4$", "$x^2+y^2\\le 4$"], 0,
          "The radicand must be nonnegative."),
        q("Evaluate $h(1,2,3)$ for $h(x,y,z)=xyz-z$.",
          ["$3$", "$6$", "$0$"], 0, "$1\\cdot 2\\cdot 3-3=3$."),
        q("The surface $z=x^2+y^2$ is a:",
          ["Paraboloid opening upward", "Hyperboloid of one sheet", "Plane through the origin"], 0,
          "Circular paraboloid $z=r^2$."),
        q("A trace of $z=4-x^2-y^2$ in the plane $y=0$ is:",
          ["$z=4-x^2$", "$z=4-y^2$", "$x^2+y^2=4$"], 0,
          "Substitute $y=0$ into the surface equation."),
        q("Level surfaces of $F(x,y,z)=x^2+y^2+z^2$ are:",
          ["Spheres centered at the origin", "Planes $x+y+z=c$", "Cylinders along the $z$-axis"], 0,
          "$F=c$ gives $x^2+y^2+z^2=c$ for $c>0$."),
        q("For $f(x,y)=\\dfrac{1}{x-y}$, the domain excludes:",
          ["The line $y=x$", "The line $y=0$", "The circle $x^2+y^2=1$"], 0,
          "Denominator zero when $x=y$."),
        q("Contour map level sets of $f(x,y)=x+2y$ are:",
          ["Parallel lines $x+2y=c$", "Circles centered at the origin", "Hyperbolas $xy=c$"], 0,
          "Each fixed height is a straight line."),
        q("If $f(x,y)=\\sin(xy)$, then $f(\\pi/2,1)$ equals:",
          ["$1$", "$0$", "$\\pi/2$"], 0, "$\\sin(\\pi/2)=1$."),
        q("The projection of the domain of $f(x,y)=\\sqrt{1-x^2-y^2}$ onto the $xy$-plane is:",
          ["The closed unit disk", "The open unit disk", "The entire plane"], 0,
          "$x^2+y^2\\le 1$."),
        q("For $f(x,y)=xy$, the level curve through $(2,3)$ has equation:",
          ["$xy=6$", "$x+y=5$", "$x^2+y^2=13$"], 0, "$f(2,3)=6$."),
        q("A function of three variables $w=F(x,y,z)$ has level sets that are typically:",
          ["Surfaces in $\\mathbb{R}^3$", "Curves in $\\mathbb{R}^2$", "Single points only"], 0,
          "$F(x,y,z)=c$ is generally a surface."),
    ]

    banks["MV_142_QUIZ"] = [
        q("Along the path $y=0$, $\\lim_{(x,y)\\to(0,0)}\\dfrac{x^2y}{x^4+y^2}$ equals:",
          ["$0$", "$1$", "$1/2$"], 0, "On $y=0$ the quotient is $0$."),
        q("Along $y=x^2$, $\\lim_{(x,y)\\to(0,0)}\\dfrac{x^2y}{x^4+y^2}$ equals:",
          ["$1/2$", "$0$", "$1$"], 0,
          "Substitute $y=x^2$: $\\dfrac{x^4}{x^4+x^4}=1/2$."),
        q("Because those two path limits differ, $\\lim_{(x,y)\\to(0,0)}\\dfrac{x^2y}{x^4+y^2}$:",
          ["Does not exist", "Equals $0$", "Equals $1/2$"], 0,
          "Different path limits imply the 2D limit fails."),
        q("In polar, $\\lim_{(x,y)\\to(0,0)}\\dfrac{x^2}{\\sqrt{x^2+y^2}}$ becomes:",
          ["$\\lim_{r\\to 0} r\\cos^2\\theta=0$", "$\\lim_{r\\to 0}\\cos^2\\theta$", "$\\lim_{r\\to 0}1/r$"], 0,
          "$x=r\\cos\\theta$ yields $r\\cos^2\\theta\\to 0$ uniformly."),
        q("If $0\\le |f(x,y)|\\le x^2+y^2$ near $(0,0)$, then $\\lim_{(x,y)\\to(0,0)}f(x,y)$ equals:",
          ["$0$", "$1$", "Need not exist"], 0, "Squeeze with $x^2+y^2\\to 0$."),
        q("Evaluate $\\lim_{(x,y)\\to(1,2)}(3x-y)$.",
          ["$1$", "$5$", "$0$"], 0, "Polynomials are continuous: $3-2=1$."),
        q("Along $x=0$, $\\lim_{(x,y)\\to(0,0)}\\dfrac{2xy}{x^2+2y^2}$ equals:",
          ["$0$", "$1$", "$1/2$"], 0, "Numerator vanishes on $x=0$."),
        q("Along $y=x$, $\\lim_{(x,y)\\to(0,0)}\\dfrac{2xy}{x^2+2y^2}$ equals:",
          ["$2/3$", "$0$", "$1$"], 0, "$\\dfrac{2x^2}{x^2+2x^2}=2/3$."),
        q("Hence $\\lim_{(x,y)\\to(0,0)}\\dfrac{2xy}{x^2+2y^2}$:",
          ["Does not exist", "Equals $0$", "Equals $2/3$"], 0,
          "Path disagreement."),
        q("$f(x,y)=\\begin{cases}\\dfrac{xy^2}{x^2+y^4}&(x,y)\\ne(0,0)\\\\0&(x,y)=(0,0)\\end{cases}$ fails continuity at the origin because:",
          ["Some path limits disagree with $f(0,0)$", "All path limits equal $0$", "$f$ is a polynomial"], 0,
          "Along $x=y^2$ the limit is $1/2$, not $0$."),
        q("Evaluate $\\lim_{(x,y)\\to(2,-1)}(x^2y+3)$.",
          ["$-1$", "$7$", "$1$"], 0, "$4\\cdot(-1)+3=-1$."),
        q("Polar form of $x^2+y^2$ is:",
          ["$r^2$", "$r$", "$r\\cos\\theta$"], 0, "By definition $r^2=x^2+y^2$."),
        q("If $|g(x,y)|\\le 5\\sqrt{x^2+y^2}$ near the origin, then $\\lim_{(x,y)\\to(0,0)}g(x,y)$ equals:",
          ["$0$", "$5$", "Need not exist"], 0, "Squeeze: bound tends to $0$."),
        q("For continuous $f$ on $\\mathbb{R}^2$, $\\lim_{(x,y)\\to(a,b)}f(x,y)$ equals:",
          ["$f(a,b)$", "$0$", "$f_x(a,b)$"], 0, "Continuity definition."),
        q("Along $y=mx$, $\\lim_{(x,y)\\to(0,0)}\\dfrac{x^3-y^3}{x^2+y^2}$ equals:",
          ["$0$", "$m$", "$1-m$"], 0,
          "The expression simplifies to $x\\dfrac{1-m^3}{1+m^2}\\to 0$."),
    ]

    banks["MV_143_QUIZ"] = [
        q("For $f(x,y)=x^3y+2y$, $f_x$ equals:",
          ["$3x^2y$", "$x^3+2$", "$3x^2y+2$"], 0, "Differentiate in $x$, treat $y$ as constant."),
        q("For the same $f$, $f_y(1,2)$ equals:",
          ["$3$", "$1$", "$5$"], 0, "$f_y=x^3+2$; at $(1,2)$: $1+2=3$."),
        q("If $g(x,y)=e^{xy}$, then $g_x$ equals:",
          ["$y e^{xy}$", "$x e^{xy}$", "$e^{xy}$"], 0, "Chain rule with inner $xy$."),
        q("For $f(x,y)=x^2y^3$, the mixed partial $f_{xy}$ equals:",
          ["$6xy^2$", "$2xy^3$", "$6x^2y$"], 0, "$f_x=2xy^3$, then $f_{xy}=6xy^2$."),
        q("Clairaut's theorem says that if the second partials are continuous, then:",
          ["$f_{xy}=f_{yx}$", "$f_{xx}=f_{yy}$", "$f_x=f_y$"], 0, "Equality of mixed partials."),
        q("For $u(x,y)=\\ln(x^2+y^2)$ with $(x,y)\\ne(0,0)$, $u_x$ equals:",
          ["$\\dfrac{2x}{x^2+y^2}$", "$\\dfrac{1}{x}$", "$\\dfrac{x}{x^2+y^2}$"], 0,
          "Derivative of $\\ln(x^2+y^2)$ in $x$."),
        q("Second pure partial $f_{xx}$ for $f(x,y)=\\sin(x)+y^2$ equals:",
          ["$-\\sin x$", "$\\cos x$", "$2$"], 0, "$f_x=\\cos x$, $f_{xx}=-\\sin x$."),
        q("Implicitly, if $x^2+y^2+z^2=9$ and $z=z(x,y)$, then $z_x$ equals:",
          ["$-x/z$", "$-y/z$", "$x/z$"], 0, "$2x+2z z_x=0$."),
        q("For $f(x,y,z)=xyz$, $f_z$ at $(2,3,4)$ equals:",
          ["$6$", "$24$", "$12$"], 0, "$f_z=xy=6$."),
        q("Check Laplace $u_{xx}+u_{yy}=0$ for $u=x^3-3xy^2$:",
          ["Holds: both sides $0$", "Fails: left side $6x$", "Fails: left side $6y$"], 0,
          "$u_{xx}=6x$, $u_{yy}=-6x$, sum $0$."),
        q("For $f(x,y)=\\arctan(y/x)$ with $x>0$, $f_y$ equals:",
          ["$\\dfrac{x}{x^2+y^2}$", "$\\dfrac{y}{x^2+y^2}$", "$\\dfrac{1}{1+(y/x)^2}$"], 0,
          "Chain rule yields $\\dfrac{x}{x^2+y^2}$."),
        q("If $f(x,y)=x^4+y^4$, then $f_{xy}(1,1)$ equals:",
          ["$0$", "$12$", "$4$"], 0, "No mixed $xy$ term; mixed partial is $0$."),
        q("For $w=\\sqrt{x^2+y^2+z^2}$, $w_x$ equals:",
          ["$\\dfrac{x}{\\sqrt{x^2+y^2+z^2}}$", "$\\dfrac{1}{2\\sqrt{x^2+y^2+z^2}}$", "$x$"], 0,
          "Chain rule on the square root."),
        q("Evaluate $f_x(0,\\pi)$ for $f(x,y)=x\\cos y$.",
          ["$-1$", "$0$", "$1$"], 0, "$f_x=\\cos y$; $\\cos\\pi=-1$."),
        q("For $f(x,y)=e^x\\sin y$, $f_{yy}$ equals:",
          ["$-e^x\\sin y$", "$e^x\\cos y$", "$e^x\\sin y$"], 0,
          "$f_y=e^x\\cos y$, $f_{yy}=-e^x\\sin y$."),
    ]

    banks["MV_144_QUIZ"] = [
        q("If $z=x^2+y^2$, $x=t$, $y=t^2$, then $dz/dt$ at $t=1$ equals:",
          ["$6$", "$4$", "$2$"], 0,
          "$z_x=2x$, $z_y=2y$; $2(1)(1)+2(1)(2)=6$."),
        q("For $z=f(x,y)$ with $x=x(s,t)$, $y=y(s,t)$, $\\partial z/\\partial s$ equals:",
          ["$f_x x_s+f_y y_s$", "$f_x+f_y$", "$f_x x_t+f_y y_t$"], 0, "Chain rule tree."),
        q("Let $z=xy$, $x=s+t$, $y=st$. Then $\\partial z/\\partial t$ equals:",
          ["$s^2+2st$", "$s+t$", "$st$"], 0,
          "$z_x=y$, $z_y=x$; $y\\cdot 1+x\\cdot s=st+(s+t)s=s^2+2st$."),
        q("If $F(x,y)=x^2+y^2-1=0$, then $dy/dx$ equals:",
          ["$-x/y$", "$x/y$", "$-y/x$"], 0, "$-F_x/F_y=-2x/(2y)$."),
        q("Related rates: $z=x^2+y^2$, $dx/dt=3$, $dy/dt=4$ at $(1,2)$. Then $dz/dt$ equals:",
          ["$22$", "$14$", "$7$"], 0, "$2x(3)+2y(4)=6+16=22$."),
        q("If $w=f(u)$, $u=x^2+y^2$, then $w_x$ equals:",
          ["$f'(u)\\cdot 2x$", "$f'(u)$", "$2x$"], 0, "Single-variable chain through $u$."),
        q("For $z=e^{x-y}$, $x=t^2$, $y=t$, $dz/dt$ at $t=0$ equals:",
          ["$-1$", "$1$", "$0$"], 0,
          "At $t=0$: $z_x\\cdot 0+z_y\\cdot 1=-1$."),
        q("Tree diagram for $z=f(x(s,t),y(s,t))$ has how many first-generation edges from $z$?",
          ["$2$", "$1$", "$4$"], 0, "Edges to the two intermediates $x$ and $y$."),
        q("If $x=r\\cos\\theta$, $y=r\\sin\\theta$, $z=x^2+y^2$, then $\\partial z/\\partial r$ equals:",
          ["$2r$", "$2$", "$0$"], 0, "$z=r^2$, so $z_r=2r$."),
        q("Implicit $F(x,y,z)=0$ gives $z_x=-F_x/F_z$ provided:",
          ["$F_z\\ne 0$", "$F_x\\ne 0$", "$F=0$ alone"], 0, "Nonvanishing denominator."),
        q("Let $u=x^2y$, $x=2s$, $y=s+t$. Then $\\partial u/\\partial s$ at $(s,t)=(1,0)$ equals:",
          ["$12$", "$8$", "$4$"], 0,
          "At $x=2$, $y=1$: $u_x=4$, $u_y=4$; $4\\cdot 2+4\\cdot 1=12$."),
        q("If $z=\\sin(x+2y)$, $x=t$, $y=t^2$, then $dz/dt$ equals:",
          ["$\\cos(x+2y)\\,(1+4t)$", "$\\cos(x+2y)$", "$\\sin(x+2y)\\,(1+2t)$"], 0,
          "Chain: $\\cos(\\cdot)(1+4t)$."),
        q("For $f(x,y)=x/y$ with $x=e^t$, $y=e^{-t}$, $df/dt$ equals:",
          ["$2e^{2t}$", "$0$", "$e^{2t}$"], 0,
          "$f=e^{2t}$, derivative $2e^{2t}$."),
        q("Two-variable chain: if both intermediates depend on $t$ only, $dz/dt$ is a:",
          ["Ordinary derivative", "Partial in $x$ only", "Gradient magnitude"], 0,
          "Composition with one parameter."),
        q("If $F(x,y)=xe^y+y-2=0$ near $(2,0)$, then $dy/dx$ at that point equals:",
          ["$-1/3$", "$-1$", "$1/3$"], 0,
          "$F_x=e^y=1$, $F_y=xe^y+1=3$, so $dy/dx=-1/3$."),
    ]

    banks["MV_145_QUIZ"] = [
        q("For $f(x,y)=x^2+3y$, $\\nabla f$ equals:",
          ["$\\langle 2x,3\\rangle$", "$\\langle 2x,3y\\rangle$", "$\\langle x^2,3\\rangle$"], 0,
          "Partials $f_x=2x$, $f_y=3$."),
        q("At $(1,2)$, $\\nabla f$ for $f(x,y)=xy^2$ equals:",
          ["$\\langle 4,4\\rangle$", "$\\langle 2,2\\rangle$", "$\\langle 4,2\\rangle$"], 0,
          "$f_x=y^2=4$, $f_y=2xy=4$."),
        q("Unit vector in direction $\\langle 3,4\\rangle$ is:",
          ["$\\langle 3/5,4/5\\rangle$", "$\\langle 3,4\\rangle$", "$\\langle 1,1\\rangle$"], 0,
          "Divide by length $5$."),
        q("Directional derivative of $f(x,y)=x^2+y^2$ at $(1,0)$ toward $\\langle 3,4\\rangle$ equals:",
          ["$6/5$", "$2$", "$6$"], 0,
          "$\\nabla f=\\langle 2,0\\rangle$, unit $\\mathbf u=\\langle 3/5,4/5\\rangle$, dot $6/5$."),
        q("Maximum rate of increase of $f$ at a point is:",
          ["$|\\nabla f|$", "$\\nabla f\\cdot\\mathbf i$", "$0$"], 0, "Gradient length."),
        q("Direction of fastest increase of $f(x,y)=x-2y$ at $(0,0)$ is parallel to:",
          ["$\\langle 1,-2\\rangle$", "$\\langle -1,2\\rangle$", "$\\langle 2,1\\rangle$"], 0,
          "$\\nabla f=\\langle 1,-2\\rangle$."),
        q("If $\\nabla f(P)=\\mathbf 0$, then every directional derivative at $P$ is:",
          ["$0$", "$1$", "Undefined"], 0, "Dot product with zero vector."),
        q("Gradient $\\nabla f$ is orthogonal to:",
          ["Level curves of $f$", "The $x$-axis always", "Every vector field"], 0,
          "Level-set geometry."),
        q("For $f(x,y,z)=xyz$, $\\nabla f(1,2,3)$ equals:",
          ["$\\langle 6,3,2\\rangle$", "$\\langle 1,2,3\\rangle$", "$\\langle 6,6,6\\rangle$"], 0,
          "$\\langle yz,xz,xy\\rangle=\\langle 6,3,2\\rangle$."),
        q("$D_{\\mathbf u}f$ with unit $\\mathbf u$ equals:",
          ["$\\nabla f\\cdot\\mathbf u$", "$|\\nabla f|\\,|\\mathbf u|$", "$\\nabla f\\times\\mathbf u$"], 0,
          "Definition."),
        q("A direction of zero change for $f(x,y)=2x+y$ is parallel to:",
          ["$\\langle 1,-2\\rangle$", "$\\langle 2,1\\rangle$", "$\\langle 1,1\\rangle$"], 0,
          "Perpendicular to $\\nabla f=\\langle 2,1\\rangle$."),
        q("At $(3,4)$, $|\\nabla f|$ for $f=x^2+y^2$ equals:",
          ["$10$", "$5$", "$25$"], 0, "$\\nabla f=\\langle 6,8\\rangle$, length $10$."),
        q("If $\\mathbf u$ is unit and $\\theta$ is the angle with $\\nabla f$, then $D_{\\mathbf u}f$ equals:",
          ["$|\\nabla f|\\cos\\theta$", "$|\\nabla f|\\sin\\theta$", "$|\\nabla f|$"], 0,
          "Dot-product identity."),
        q("Directional derivative of $f(x,y)=e^{x+y}$ at $(0,0)$ in direction $\\langle 1/\\sqrt{2},1/\\sqrt{2}\\rangle$ equals:",
          ["$\\sqrt{2}$", "$1$", "$0$"], 0,
          "$\\nabla f=\\langle 1,1\\rangle$ at origin; dot unit vector is $\\sqrt{2}$."),
        q("Steepest descent direction is parallel to:",
          ["$-\\nabla f$", "$\\nabla f$", "A tangent to the level curve only"], 0,
          "Opposite the gradient."),
    ]

    banks["MV_146_QUIZ"] = [
        q("Tangent plane to $z=x^2+y^2$ at $(1,2,5)$ is:",
          ["$z=2x+4y-5$", "$z=2x+4y+5$", "$z=x+y-5$"], 0,
          "$z=5+2(x-1)+4(y-2)$ simplifies to $z=2x+4y-5$."),
        q("For level surface $F(x,y,z)=x^2+y^2+z^2=14$ at $(1,2,3)$, a normal vector is:",
          ["$\\langle 2,4,6\\rangle$", "$\\langle 1,2,3\\rangle$", "$\\langle 1,1,1\\rangle$"], 0,
          "$\\nabla F=\\langle 2x,2y,2z\\rangle$."),
        q("Tangent plane to $x^2+y^2+z^2=14$ at $(1,2,3)$ is:",
          ["$x+2y+3z=14$", "$x+2y+3z=0$", "$2x+4y+6z=14$"], 0,
          "$1(x-1)+2(y-2)+3(z-3)=0$ gives $x+2y+3z=14$."),
        q("Linear approximation of $f(x,y)=\\sqrt{x+y}$ near $(4,5)$ uses:",
          ["$f(4,5)+f_x(4,5)(x-4)+f_y(4,5)(y-5)$", "Only $f(4,5)$", "$f_{xx}$ terms"], 0,
          "First-order Taylor in two variables."),
        q("Total differential of $z=x^2y$ is:",
          ["$dz=2xy\\,dx+x^2\\,dy$", "$dz=x^2\\,dx+2xy\\,dy$", "$dz=2x\\,dx$"], 0,
          "$z_x=2xy$, $z_y=x^2$."),
        q("Approximate $(1.02)^2(0.99)$ via differentials from $(1,1)$:",
          ["$1.03$", "$1.02$", "$0.99$"], 0,
          "$f=x^2y$; $df=2(0.02)+(-0.01)=0.03$."),
        q("Normal line to $z=xy$ at $(2,3,6)$ has direction:",
          ["$\\langle 3,2,-1\\rangle$", "$\\langle 2,3,6\\rangle$", "$\\langle 1,1,0\\rangle$"], 0,
          "For $F=xy-z$, $\\nabla F=\\langle 3,2,-1\\rangle$."),
        q("If $|dx|=0.01$, $|dy|=0.02$ and $z=3x+4y$, max $|dz|$ estimate is:",
          ["$0.11$", "$0.03$", "$0.06$"], 0, "$|dz|\\le 3(0.01)+4(0.02)=0.11$."),
        q("Tangent plane to $z=e^{x-y}$ at $(0,0,1)$ is:",
          ["$z=1+x-y$", "$z=1+x+y$", "$z=x-y$"], 0,
          "$f_x=1$, $f_y=-1$ at the origin."),
        q("Percentage error estimate uses roughly:",
          ["$|dz/z|\\times 100\\%$", "$|dx|+|dy|$ only", "$|\\nabla f|$ alone"], 0,
          "Relative differential."),
        q("For $F(x,y,z)=xyz-1$, at $(1,1,1)$ the tangent plane is:",
          ["$x+y+z=3$", "$xyz=1$", "$x+y+z=1$"], 0,
          "$\\nabla F=\\langle 1,1,1\\rangle$ yields $x+y+z=3$."),
        q("Linearization of $f(x,y)=x^2-y^2$ at $(2,1)$ is:",
          ["$L=3+4(x-2)-2(y-1)$", "$L=4x-2y$", "$L=x^2-y^2$"], 0,
          "$f=3$, $f_x=4$, $f_y=-2$."),
        q("Differential $dz$ for $z=\\ln(x^2+y^2)$ equals:",
          ["$\\dfrac{2x\\,dx+2y\\,dy}{x^2+y^2}$", "$\\dfrac{dx}{x}+\\dfrac{dy}{y}$", "$2x\\,dx+2y\\,dy$"], 0,
          "Gradient dotted with $(dx,dy)$."),
        q("At $(1,1,1)$ on $x^2+y^2-z=1$, a normal vector is:",
          ["$\\langle 2,2,-1\\rangle$", "$\\langle 1,1,1\\rangle$", "$\\langle 2,2,1\\rangle$"], 0,
          "$F=x^2+y^2-z-1$, $\\nabla F=\\langle 2,2,-1\\rangle$."),
        q("Estimate $f(1.1,0.9)$ for $f(x,y)=x/y$ using $(1,1)$:",
          ["$1.2$", "$1.0$", "$0.9$"], 0,
          "$df=(1)\\,dx+(-1)\\,dy=0.1+0.1=0.2$, so $1.2$."),
    ]

    banks["MV_147_QUIZ"] = [
        q("Critical points of $f(x,y)$ satisfy:",
          ["$f_x=0$ and $f_y=0$ (where defined)", "Only $f_{xx}=0$", "Only $f=0$"], 0,
          "Interior critical-point condition."),
        q("For $f(x,y)=x^2+y^2-2x$, a critical point is:",
          ["$(1,0)$", "$(0,0)$", "$(2,1)$"], 0, "$f_x=2x-2=0$, $f_y=2y=0$."),
        q("Hessian discriminant $D=f_{xx}f_{yy}-f_{xy}^2$. If $D>0$ and $f_{xx}>0$, the point is a:",
          ["Local minimum", "Local maximum", "Saddle"], 0, "Second-derivative test."),
        q("If $D<0$ at a critical point, the point is a:",
          ["Saddle", "Local min", "Local max"], 0, "Second-derivative test."),
        q("For $f(x,y)=xy$, the critical point $(0,0)$ is a:",
          ["Saddle", "Local min", "Local max"], 0, "$D=-1<0$."),
        q("For $f(x,y)=x^2+4y^2$, at $(0,0)$ one has $D$ equal to:",
          ["$16$", "$0$", "$-16$"], 0, "$f_{xx}=2$, $f_{yy}=8$, $f_{xy}=0$."),
        q("Absolute extrema of continuous $f$ on a closed bounded region occur at:",
          ["Critical points or boundary points", "Only saddles", "Only where $D=0$"], 0,
          "Extreme Value Theorem in 2D."),
        q("On the disk $x^2+y^2\\le 1$, maximize $f=x$. The maximum is:",
          ["$1$", "$0$", "$-1$"], 0, "Attained at $(1,0)$ on the boundary."),
        q("For $f(x,y)=x^2-y^2$, critical point $(0,0)$ has $D$ equal to:",
          ["$-4$", "$4$", "$0$"], 0, "$f_{xx}=2$, $f_{yy}=-2$, $f_{xy}=0$."),
        q("Classify $(0,0)$ for $f(x,y)=x^2-y^2$:",
          ["Saddle", "Local min", "Local max"], 0, "$D=-4<0$."),
        q("For $f(x,y)=(x-1)^2+(y+2)^2$, the global minimum value is:",
          ["$0$", "$1$", "$5$"], 0, "Squared distance; min at $(1,-2)$."),
        q("If $D=0$ at a critical point, the second-derivative test is:",
          ["Inconclusive", "Always a saddle", "Always a min"], 0, "Need higher-order analysis."),
        q("Boundary of the square $[0,1]\\times[0,1]$ consists of:",
          ["Four edges (including corners)", "Only the four corners", "The open square"], 0,
          "Closed boundary of the region."),
        q("For $f(x,y)=x^2+y^2$ on $x^2+y^2=4$, the minimum of $f$ on that circle is:",
          ["$4$", "$0$", "$2$"], 0, "On the circle $f=4$ constantly."),
        q("Local max requires $D>0$ and:",
          ["$f_{xx}<0$", "$f_{xx}>0$", "$f_{xy}=0$"], 0, "Second-derivative test."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "mvPartialQuizzes.js",
        "/** Study-guide quiz banks for the Multivariable Partial Derivatives guide — 15 MCQs per section. */",
        build(),
    )
