# -*- coding: utf-8 -*-
"""Emit laVectorsMatricesQuizzes.js — LA vectors and matrices banks."""
from _quiz_emit import q, emit_file, OUT


def build():
    banks = {}

    banks["LA_V_INTRO_QUIZ"] = [
        q("What is the magnitude of $\\mathbf{v}=\\langle 3,-4\\rangle$?",
          ["$5$", "$7$", "$\\sqrt{7}$"], 0,
          "The magnitude is $\\sqrt{3^2+(-4)^2}=\\sqrt{25}=5$."),
        q("The second component of $\\mathbf{u}=(5,-2,9)$ is:",
          ["$-2$", "$5$", "$9$"], 0,
          "Components are listed in order; the second entry is $-2$."),
        q("A unit vector in the direction of $\\mathbf{w}=(0,8)$ is:",
          ["$(0,1)$", "$(0,8)$", "$(0,1/8)$"], 0,
          "$\\|\\mathbf{w}\\|=8$, so $\\mathbf{w}/8=(0,1)$."),
        q("Distance between $P=(1,2,2)$ and $Q=(4,6,2)$ equals:",
          ["$5$", "$3$", "$7$"], 0,
          "$\\sqrt{(4-1)^2+(6-2)^2+(2-2)^2}=\\sqrt{9+16}=5$."),
        q("If $\\mathbf{x}=(2,1,-2)$, then $\\|\\mathbf{x}\\|^2$ equals:",
          ["$9$", "$3$", "$5$"], 0,
          "$2^2+1^2+(-2)^2=4+1+4=9$."),
        q("The zero vector in $\\mathbb{R}^3$ is:",
          ["$(0,0,0)$", "$(0,0)$", "$(1,1,1)$"], 0,
          "Every component must be zero in three dimensions."),
        q("Two vectors $\\mathbf{a}=(1,4)$ and $\\mathbf{b}=(1,4)$ are equal because:",
          ["Matching components in the same order", "Equal magnitudes only", "They are orthogonal"], 0,
          "Vector equality means corresponding components agree."),
        q("The position vector of the point $(-3,5)$ is:",
          ["$\\langle -3,5\\rangle$", "$\\langle 3,-5\\rangle$", "$\\langle -3,-5\\rangle$"], 0,
          "The position vector runs from the origin to the point."),
        q("A unit vector parallel to $\\mathbf{v}=\\langle 6,-8\\rangle$ is:",
          ["$\\langle 3/5,-4/5\\rangle$", "$\\langle 6,-8\\rangle$", "$\\langle 3/4,-1\\rangle$"], 0,
          "$\\|\\mathbf{v}\\|=10$, so divide by $10$ to get $\\langle 3/5,-4/5\\rangle$."),
        q("If $\\|\\mathbf{u}\\|=4$ and $\\mathbf{u}$ points in the same direction as $\\langle 1,0\\rangle$, then $\\mathbf{u}$ is:",
          ["$\\langle 4,0\\rangle$", "$\\langle 1,0\\rangle$", "$\\langle 0,4\\rangle$"], 0,
          "Scale the unit vector $\\langle 1,0\\rangle$ by length $4$."),
        q("Distance from $(0,0,0)$ to $(2,3,6)$ equals:",
          ["$7$", "$11$", "$\\sqrt{11}$"], 0,
          "$\\sqrt{4+9+36}=\\sqrt{49}=7$."),
        q("If $\\mathbf{p}=(a,b)$ and $\\mathbf{q}=(c,d)$ are equal, then necessarily:",
          ["$a=c$ and $b=d$", "$a+b=c+d$ only", "$\\|\\mathbf{p}\\|=\\|\\mathbf{q}\\|$ only"], 0,
          "Equality requires both components to match."),
        q("The geometric length of $\\mathbf{r}=\\langle 1,2,2\\rangle$ is:",
          ["$3$", "$5$", "$\\sqrt{5}$"], 0,
          "$\\sqrt{1+4+4}=3$."),
        q("Which vector has magnitude $13$?",
          ["$\\langle 5,12\\rangle$", "$\\langle 5,10\\rangle$", "$\\langle 3,4\\rangle$"], 0,
          "$\\sqrt{25+144}=13$."),
        q("In $\\mathbb{R}^2$, the tip of the position vector $\\langle -1,4\\rangle$ is the point:",
          ["$(-1,4)$", "$(1,-4)$", "$(4,-1)$"], 0,
          "The tip is the point with those coordinates."),
    ]

    banks["LA_V_OPS_QUIZ"] = [
        q("Compute $\\langle 2,-1\\rangle+\\langle 3,4\\rangle$.",
          ["$\\langle 5,3\\rangle$", "$\\langle 5,5\\rangle$", "$\\langle -1,5\\rangle$"], 0,
          "Add components: $2+3=5$ and $-1+4=3$."),
        q("Compute $3\\langle 1,-2,4\\rangle$.",
          ["$\\langle 3,-6,12\\rangle$", "$\\langle 3,-2,4\\rangle$", "$\\langle 1,-6,12\\rangle$"], 0,
          "Multiply each component by $3$."),
        q("The dot product $\\langle 1,2,3\\rangle\\cdot\\langle 4,-1,0\\rangle$ equals:",
          ["$2$", "$4$", "$-2$"], 0,
          "$1\\cdot 4+2\\cdot(-1)+3\\cdot 0=4-2=2$."),
        q("Are $\\mathbf{u}=\\langle 2,-1\\rangle$ and $\\mathbf{v}=\\langle 1,2\\rangle$ orthogonal?",
          ["Yes, because $\\mathbf{u}\\cdot\\mathbf{v}=0$", "No, because $\\mathbf{u}\\cdot\\mathbf{v}=2$", "Yes, because they have equal length"], 0,
          "$2\\cdot 1+(-1)\\cdot 2=0$, so they are orthogonal."),
        q("If $\\mathbf{a}\\cdot\\mathbf{b}=6$, $\\|\\mathbf{a}\\|=3$, $\\|\\mathbf{b}\\|=4$, then $\\cos\\theta$ equals:",
          ["$1/2$", "$1/2\\sqrt{2}$", "$2$"], 0,
          "$\\cos\\theta=(\\mathbf{a}\\cdot\\mathbf{b})/(\\|\\mathbf{a}\\|\\|\\mathbf{b}\\|)=6/12=1/2$."),
        q("The projection $\\operatorname{proj}_{\\mathbf{u}}\\mathbf{v}$ for $\\mathbf{u}=\\langle 1,0\\rangle$, $\\mathbf{v}=\\langle 3,4\\rangle$ is:",
          ["$\\langle 3,0\\rangle$", "$\\langle 3,4\\rangle$", "$\\langle 0,4\\rangle$"], 0,
          "$(\\mathbf{v}\\cdot\\mathbf{u}/\\|\\mathbf{u}\\|^2)\\mathbf{u}=3\\langle 1,0\\rangle$."),
        q("$\\mathbf{i}\\times\\mathbf{j}$ equals:",
          ["$\\mathbf{k}$", "$-\\mathbf{k}$", "$\\mathbf{0}$"], 0,
          "Right-hand rule: $\\mathbf{i}\\times\\mathbf{j}=\\mathbf{k}$."),
        q("Compute $\\langle 1,2,0\\rangle\\times\\langle 0,3,4\\rangle$.",
          ["$\\langle 8,-4,3\\rangle$", "$\\langle 8,4,-3\\rangle$", "$\\langle -8,4,3\\rangle$"], 0,
          "Determinant formula yields $\\langle 8,-4,3\\rangle$."),
        q("Area of the parallelogram spanned by $\\langle 1,0,0\\rangle$ and $\\langle 1,1,0\\rangle$ is:",
          ["$1$", "$\\sqrt{2}$", "$2$"], 0,
          "Cross product is $\\langle 0,0,1\\rangle$ with magnitude $1$."),
        q("The scalar triple product $\\mathbf{a}\\cdot(\\mathbf{b}\\times\\mathbf{c})$ for $\\mathbf{a}=\\langle 1,0,0\\rangle$, $\\mathbf{b}=\\langle 0,1,0\\rangle$, $\\mathbf{c}=\\langle 0,0,1\\rangle$ equals:",
          ["$1$", "$0$", "$-1$"], 0,
          "$\\mathbf{b}\\times\\mathbf{c}=\\mathbf{i}$ and $\\mathbf{a}\\cdot\\mathbf{i}=1$."),
        q("Compute $\\langle 4,1\\rangle-\\langle 1,-3\\rangle$.",
          ["$\\langle 3,4\\rangle$", "$\\langle 5,-2\\rangle$", "$\\langle 3,-4\\rangle$"], 0,
          "$4-1=3$ and $1-(-3)=4$."),
        q("If $\\mathbf{u}\\cdot\\mathbf{v}=-\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|$, the angle between them is:",
          ["$\\pi$", "$\\pi/2$", "$0$"], 0,
          "$\\cos\\theta=-1$ means the vectors are opposite."),
        q("For $\\mathbf{u}=\\langle 2,2\\rangle$ and $\\mathbf{v}=\\langle 1,0\\rangle$, $\\operatorname{proj}_{\\mathbf{u}}\\mathbf{v}$ equals:",
          ["$\\langle 1/2,1/2\\rangle$", "$\\langle 1,1\\rangle$", "$\\langle 2,0\\rangle$"], 0,
          "$(\\mathbf{v}\\cdot\\mathbf{u}/\\|\\mathbf{u}\\|^2)\\mathbf{u}=(2/8)\\langle 2,2\\rangle=\\langle 1/2,1/2\\rangle$."),
        q("For $\\mathbf{a}=\\langle 1,2,2\\rangle$ and $\\mathbf{b}=\\langle 2,0,0\\rangle$, $\\|\\mathbf{a}\\times\\mathbf{b}\\|$ equals:",
          ["$4\\sqrt{2}$", "$4$", "$2\\sqrt{2}$"], 0,
          "Cross product $\\langle 0,4,-4\\rangle$ has magnitude $\\sqrt{32}=4\\sqrt{2}$."),
        q("The vector $\\langle 1,-1,2\\rangle\\times\\langle 2,0,1\\rangle$ equals:",
          ["$\\langle -1,3,2\\rangle$", "$\\langle 1,-3,-2\\rangle$", "$\\langle -1,-3,2\\rangle$"], 0,
          "$\\mathbf{i}((-1)(1)-2\\cdot 0)-\\mathbf{j}(1\\cdot 1-2\\cdot 2)+\\mathbf{k}(0-(-2))=\\langle -1,3,2\\rangle$."),
    ]

    banks["LA_V_SPAN_QUIZ"] = [
        q("The span of $\\{\\langle 1,0\\rangle\\}$ in $\\mathbb{R}^2$ is:",
          ["The $x$-axis", "All of $\\mathbb{R}^2$", "Only the origin"], 0,
          "Scalar multiples of $\\langle 1,0\\rangle$ fill the horizontal axis."),
        q("Does $\\langle 2,4\\rangle$ lie in $\\operatorname{Span}\\{\\langle 1,2\\rangle\\}$?",
          ["Yes, because $\\langle 2,4\\rangle=2\\langle 1,2\\rangle$", "No, the vectors are orthogonal", "Only if both are unit vectors"], 0,
          "It is exactly twice $\\langle 1,2\\rangle$."),
        q("The set $\\{\\langle 1,0\\rangle,\\langle 0,1\\rangle\\}$ spans:",
          ["$\\mathbb{R}^2$", "Only a line", "Only the origin"], 0,
          "These are the standard basis vectors of $\\mathbb{R}^2$."),
        q("If $\\mathbf{v}=2\\mathbf{u}$, then $\\operatorname{Span}\\{\\mathbf{u},\\mathbf{v}\\}$ is:",
          ["A line through the origin (or $\\{\\mathbf{0}\\}$)", "All of $\\mathbb{R}^2$", "A plane"], 0,
          "The two vectors are parallel, so their span is one-dimensional."),
        q("Coordinates of $\\langle 5,7\\rangle$ relative to the standard basis of $\\mathbb{R}^2$ are:",
          ["$(5,7)$", "$(7,5)$", "$(1,1)$"], 0,
          "$\\langle 5,7\\rangle=5\\mathbf{e}_1+7\\mathbf{e}_2$."),
        q("A basis of a subspace must be:",
          ["Linearly independent and spanning", "Any spanning set", "Any independent set of size 2"], 0,
          "Both independence and spanning are required."),
        q("Dimension of $\\operatorname{Span}\\{\\langle 1,0,0\\rangle,\\langle 0,1,0\\rangle\\}$ is:",
          ["$2$", "$3$", "$1$"], 0,
          "Two independent vectors span a $2$-dimensional subspace of $\\mathbb{R}^3$."),
        q("Does $\\{\\langle 1,1\\rangle,\\langle 2,3\\rangle\\}$ span $\\mathbb{R}^2$?",
          ["Yes; the vectors are independent in $\\mathbb{R}^2$", "No; they are parallel", "Only the first vector is needed"], 0,
          "The matrix with these columns has nonzero determinant $1$."),
        q("The standard basis of $\\mathbb{R}^3$ is:",
          ["$\\{\\mathbf{e}_1,\\mathbf{e}_2,\\mathbf{e}_3\\}$", "$\\{\\mathbf{0}\\}$", "$\\{\\langle 1,1,1\\rangle\\}$"], 0,
          "The three unit coordinate vectors form the standard basis."),
        q("Is $\\langle 0,1,1\\rangle$ in $\\operatorname{Span}\\{\\langle 1,0,0\\rangle,\\langle 0,1,0\\rangle\\}$?",
          ["No; the third component cannot be produced", "Yes; take coefficients $0$ and $1$", "Yes; any vector in $\\mathbb{R}^3$ is"], 0,
          "Linear combinations have third component $0$."),
        q("If $B=\\{\\mathbf{b}_1,\\mathbf{b}_2\\}$ is a basis of $\\mathbb{R}^2$ and $[\\mathbf{x}]_B=(3,-1)$, then $\\mathbf{x}$ equals:",
          ["$3\\mathbf{b}_1-\\mathbf{b}_2$", "$\\mathbf{b}_1+3\\mathbf{b}_2$", "$-3\\mathbf{b}_1+\\mathbf{b}_2$"], 0,
          "Coordinates are the weights in the linear combination."),
        q("Any spanning set of $\\mathbb{R}^3$ must contain at least how many vectors?",
          ["$3$", "$2$", "$1$"], 0,
          "Dimension $3$ requires at least three spanning vectors."),
        q("The span of the empty set is conventionally:",
          ["$\\{\\mathbf{0}\\}$", "$\\mathbb{R}^n$", "Undefined always"], 0,
          "The empty linear combination is the zero vector."),
        q("If three vectors in $\\mathbb{R}^2$ span $\\mathbb{R}^2$, then:",
          ["They are linearly dependent", "They form a basis", "They must be orthogonal"], 0,
          "More than $2$ vectors in $\\mathbb{R}^2$ cannot be independent."),
        q("For $\\mathbf{u}=\\langle 1,2,3\\rangle$ and $\\mathbf{v}=\\langle 2,4,6\\rangle$, $\\operatorname{Span}\\{\\mathbf{u},\\mathbf{v}\\}$ equals:",
          ["$\\operatorname{Span}\\{\\mathbf{u}\\}$", "$\\mathbb{R}^3$", "A plane through three non-collinear points"], 0,
          "$\\mathbf{v}=2\\mathbf{u}$, so both generate the same line."),
    ]

    banks["LA_V_INDEP_QUIZ"] = [
        q("The set $\\{\\langle 1,0\\rangle,\\langle 0,1\\rangle\\}$ is:",
          ["Linearly independent", "Linearly dependent", "Neither, because it spans"], 0,
          "Only the trivial combination gives the zero vector."),
        q("Is $\\{\\langle 1,2\\rangle,\\langle 2,4\\rangle\\}$ linearly independent?",
          ["No; the second is twice the first", "Yes; both are nonzero", "Yes; they span $\\mathbb{R}^2$"], 0,
          "A nontrivial relation $2\\mathbf{v}_1-\\mathbf{v}_2=\\mathbf{0}$ exists."),
        q("Three vectors in $\\mathbb{R}^2$ must be:",
          ["Linearly dependent", "Linearly independent", "A basis of $\\mathbb{R}^2$"], 0,
          "Any set with more than $n$ vectors in $\\mathbb{R}^n$ is dependent."),
        q("The equation $c_1\\mathbf{v}_1+c_2\\mathbf{v}_2=\\mathbf{0}$ has only the trivial solution iff:",
          ["$\\{\\mathbf{v}_1,\\mathbf{v}_2\\}$ is independent", "The vectors have equal length", "Their span is a line"], 0,
          "That is the definition of linear independence."),
        q("Columns of $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ are independent because:",
          ["$\\det= -2\\ne 0$", "$\\det=0$", "The matrix is symmetric"], 0,
          "Nonzero determinant means full column rank."),
        q("For $\\{\\langle 1,1,0\\rangle,\\langle 0,1,1\\rangle,\\langle 1,2,1\\rangle\\}$, a dependence relation is:",
          ["$\\mathbf{v}_1+\\mathbf{v}_2-\\mathbf{v}_3=\\mathbf{0}$", "$\\mathbf{v}_1-\\mathbf{v}_2=\\mathbf{0}$", "Only the zero combination works"], 0,
          "$\\langle 1,1,0\\rangle+\\langle 0,1,1\\rangle=\\langle 1,2,1\\rangle$."),
        q("If $A$ is $3\\times 3$ with $\\operatorname{rank}(A)=2$, its columns are:",
          ["Linearly dependent", "Linearly independent", "A basis of $\\mathbb{R}^3$"], 0,
          "Rank less than $3$ means the three columns are dependent."),
        q("The set $\\{\\mathbf{0},\\langle 1,0\\rangle\\}$ is:",
          ["Dependent, because it contains $\\mathbf{0}$", "Independent", "A basis of $\\mathbb{R}^2$"], 0,
          "Any set containing the zero vector is dependent."),
        q("Two nonzero parallel vectors in $\\mathbb{R}^n$ are:",
          ["Dependent", "Independent", "Orthogonal"], 0,
          "One is a scalar multiple of the other."),
        q("If $\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}=0$, the columns are:",
          ["Dependent", "Independent", "Orthogonal"], 0,
          "Vanishing determinant means dependent columns."),
        q("Independence of $\\{\\langle 1,0,0\\rangle,\\langle 0,1,0\\rangle,\\langle 0,0,1\\rangle\\}$ follows because:",
          ["They form the standard basis", "There are three of them", "Their sum is nonzero"], 0,
          "The standard basis is independent by construction."),
        q("A set of $4$ vectors in $\\mathbb{R}^3$:",
          ["Cannot be independent", "Must be a basis", "Must span $\\mathbb{R}^3$"], 0,
          "More vectors than the ambient dimension forces dependence."),
        q("If the only solution of $A\\mathbf{x}=\\mathbf{0}$ is $\\mathbf{x}=\\mathbf{0}$ for a square $A$, then the columns of $A$ are:",
          ["Independent", "Dependent", "Orthogonal to each other"], 0,
          "Trivial nullspace means independent columns."),
        q("For $\\mathbf{u}=\\langle 1,2\\rangle$, $\\mathbf{v}=\\langle 3,1\\rangle$, solving $c_1\\mathbf{u}+c_2\\mathbf{v}=\\mathbf{0}$ yields:",
          ["Only $c_1=c_2=0$", "$c_1=3$, $c_2=-1$", "Infinitely many solutions"], 0,
          "Determinant $1\\cdot 1-2\\cdot 3=-5\\ne 0$."),
        q("If columns of a $2\\times 2$ matrix are independent, then $\\operatorname{rank}(A)$ equals:",
          ["$2$", "$1$", "$0$"], 0,
          "Two independent columns give full rank."),
    ]

    banks["LA_M_INTRO_QUIZ"] = [
        q("The matrix $\\begin{pmatrix}1&2&3\\\\4&5&6\\end{pmatrix}$ has size:",
          ["$2\\times 3$", "$3\\times 2$", "$6\\times 1$"], 0,
          "Two rows and three columns."),
        q("Entry $a_{21}$ of $\\begin{pmatrix}7&8\\\\9&10\\end{pmatrix}$ is:",
          ["$9$", "$8$", "$7$"], 0,
          "Row $2$, column $1$ is $9$."),
        q("The standard matrix of reflection across the $x$-axis in $\\mathbb{R}^2$ is:",
          ["$\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}$", "$\\begin{pmatrix}-1&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$"], 0,
          "$(x,y)\\mapsto(x,-y)$."),
        q("The $2\\times 2$ identity matrix is:",
          ["$\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$", "$\\begin{pmatrix}1&1\\\\1&1\\end{pmatrix}$"], 0,
          "Ones on the diagonal and zeros elsewhere."),
        q("A diagonal matrix can have nonzero entries only:",
          ["On the main diagonal", "In the first row", "Above the diagonal"], 0,
          "Off-diagonal entries must be zero."),
        q("The transpose of $\\begin{pmatrix}1&2\\\\3&4\\\\5&6\\end{pmatrix}$ is:",
          ["$\\begin{pmatrix}1&3&5\\\\2&4&6\\end{pmatrix}$", "$\\begin{pmatrix}1&2&3\\\\4&5&6\\end{pmatrix}$", "$\\begin{pmatrix}6&5\\\\4&3\\\\2&1\\end{pmatrix}$"], 0,
          "Rows become columns."),
        q("The zero matrix of size $2\\times 2$ is:",
          ["$\\begin{pmatrix}0&0\\\\0&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$"], 0,
          "Every entry is $0$."),
        q("A symmetric matrix satisfies:",
          ["$A^T=A$", "$A^T=-A$", "$A^2=I$"], 0,
          "Equals its own transpose."),
        q("The standard matrix for scaling by $3$ in $\\mathbb{R}^2$ is:",
          ["$\\begin{pmatrix}3&0\\\\0&3\\end{pmatrix}$", "$\\begin{pmatrix}3&3\\\\3&3\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&3\\end{pmatrix}$"], 0,
          "Both axes stretch by factor $3$."),
        q("Upper triangular $3\\times 3$ matrices have zeros:",
          ["Strictly below the diagonal", "Strictly above the diagonal", "On the diagonal"], 0,
          "Entries $a_{ij}$ with $i>j$ vanish."),
        q("Rotation by $90^\\circ$ counterclockwise in $\\mathbb{R}^2$ has matrix:",
          ["$\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$", "$\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}$"], 0,
          "$(x,y)\\mapsto(-y,x)$."),
        q("Projection onto the $x$-axis has standard matrix:",
          ["$\\begin{pmatrix}1&0\\\\0&0\\end{pmatrix}$", "$\\begin{pmatrix}0&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}1&1\\\\0&0\\end{pmatrix}$"], 0,
          "$(x,y)\\mapsto(x,0)$."),
        q("If $A$ is $m\\times n$, it maps $\\mathbb{R}^n$ into:",
          ["$\\mathbb{R}^m$", "$\\mathbb{R}^n$", "$\\mathbb{R}^{mn}$"], 0,
          "Columns live in $\\mathbb{R}^m$."),
        q("Entry $a_{13}$ of $\\begin{pmatrix}2&0&5\\\\1&3&4\\end{pmatrix}$ is:",
          ["$5$", "$4$", "$0$"], 0,
          "First row, third column."),
        q("A linear map $T:\\mathbb{R}^2\\to\\mathbb{R}^2$ is completely determined by:",
          ["$T(\\mathbf{e}_1)$ and $T(\\mathbf{e}_2)$", "Only $T(\\mathbf{0})$", "Its determinant alone"], 0,
          "Images of the standard basis form the columns of the matrix."),
    ]

    banks["LA_M_OPS_QUIZ"] = [
        q("Compute $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}+\\begin{pmatrix}5&0\\\\1&1\\end{pmatrix}$.",
          ["$\\begin{pmatrix}6&2\\\\4&5\\end{pmatrix}$", "$\\begin{pmatrix}6&2\\\\4&4\\end{pmatrix}$", "$\\begin{pmatrix}5&2\\\\3&5\\end{pmatrix}$"], 0,
          "Add entrywise."),
        q("Compute $2\\begin{pmatrix}1&-1\\\\0&3\\end{pmatrix}$.",
          ["$\\begin{pmatrix}2&-2\\\\0&6\\end{pmatrix}$", "$\\begin{pmatrix}2&-1\\\\0&3\\end{pmatrix}$", "$\\begin{pmatrix}1&-2\\\\0&6\\end{pmatrix}$"], 0,
          "Scale every entry by $2$."),
        q("Product $\\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}\\begin{pmatrix}3&0\\\\1&4\\end{pmatrix}$ equals:",
          ["$\\begin{pmatrix}5&8\\\\1&4\\end{pmatrix}$", "$\\begin{pmatrix}3&0\\\\1&4\\end{pmatrix}$", "$\\begin{pmatrix}5&8\\\\0&4\\end{pmatrix}$"], 0,
          "Row-column: first entry $1\\cdot 3+2\\cdot 1=5$, and so on."),
        q("Can a $2\\times 3$ matrix multiply a $2\\times 2$ matrix on the right?",
          ["No; inner dimensions $3$ and $2$ disagree", "Yes; always", "Only if both are square"], 0,
          "Need the middle sizes to match."),
        q("In general $AB$ and $BA$:",
          ["Need not be equal", "Are always equal", "Are always negatives"], 0,
          "Matrix multiplication is not commutative."),
        q("If $A=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$, then $A^2$ equals:",
          ["$\\begin{pmatrix}0&0\\\\0&0\\end{pmatrix}$", "$A$", "$I$"], 0,
          "Direct multiplication yields the zero matrix."),
        q("$(AB)^T$ equals:",
          ["$B^TA^T$", "$A^TB^T$", "$AB$"], 0,
          "Transpose reverses the product order."),
        q("$\\operatorname{tr}\\begin{pmatrix}2&7\\\\0&5\\end{pmatrix}$ equals:",
          ["$7$", "$2$", "$10$"], 0,
          "Trace is the sum of diagonal entries $2+5=7$."),
        q("$\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$ equals:",
          ["$\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$", "$\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}$"], 0,
          "Compute the product of the two factors."),
        q("If $A$ is $3\\times 2$ and $B$ is $2\\times 4$, then $AB$ has size:",
          ["$3\\times 4$", "$2\\times 2$", "$4\\times 3$"], 0,
          "Outer dimensions give the product size."),
        q("$\\operatorname{tr}(A+B)$ equals:",
          ["$\\operatorname{tr}A+\\operatorname{tr}B$", "$\\operatorname{tr}(AB)$", "$(\\operatorname{tr}A)(\\operatorname{tr}B)$"], 0,
          "Trace is linear."),
        q("For $A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$, $A^3$ equals:",
          ["$\\begin{pmatrix}1&3\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}$"], 0,
          "Inductively $A^n=\\begin{pmatrix}1&n\\\\0&1\\end{pmatrix}$."),
        q("Scalar multiple: $(-1)\\begin{pmatrix}2&3\\\\4&5\\end{pmatrix}$ equals:",
          ["$\\begin{pmatrix}-2&-3\\\\-4&-5\\end{pmatrix}$", "$\\begin{pmatrix}2&-3\\\\-4&5\\end{pmatrix}$", "$\\begin{pmatrix}-2&3\\\\4&-5\\end{pmatrix}$"], 0,
          "Negate every entry."),
        q("If $A$ is square, $\\operatorname{tr}(A^T)$ equals:",
          ["$\\operatorname{tr}A$", "$-\\operatorname{tr}A$", "$0$"], 0,
          "Diagonal entries are unchanged by transpose."),
        q("Product $\\begin{pmatrix}2&1\\end{pmatrix}\\begin{pmatrix}3\\\\4\\end{pmatrix}$ equals:",
          ["$\\begin{pmatrix}10\\end{pmatrix}$", "$\\begin{pmatrix}6&4\\end{pmatrix}$", "$\\begin{pmatrix}5\\end{pmatrix}$"], 0,
          "$2\\cdot 3+1\\cdot 4=10$ as a $1\\times 1$ matrix."),
    ]

    banks["LA_M_DET_QUIZ"] = [
        q("$\\det\\begin{pmatrix}3&1\\\\2&4\\end{pmatrix}$ equals:",
          ["$10$", "$14$", "$5$"], 0,
          "$3\\cdot 4-1\\cdot 2=12-2=10$."),
        q("$\\det\\begin{pmatrix}1&2&0\\\\0&3&4\\\\0&0&5\\end{pmatrix}$ equals:",
          ["$15$", "$0$", "$12$"], 0,
          "Triangular: product of diagonal entries $1\\cdot 3\\cdot 5=15$."),
        q("If $\\det A=4$ and $\\det B=3$ for $n\\times n$ matrices, $\\det(AB)$ equals:",
          ["$12$", "$7$", "$1$"], 0,
          "$\\det(AB)=\\det A\\det B$."),
        q("Swapping two rows of a matrix multiplies the determinant by:",
          ["$-1$", "$2$", "$0$"], 0,
          "An elementary row swap changes the sign."),
        q("If $\\det A=5$ for a $2\\times 2$ matrix, $\\det(3A)$ equals:",
          ["$45$", "$15$", "$5/3$"], 0,
          "$\\det(kA)=k^n\\det A$ with $n=2$: $9\\cdot 5=45$."),
        q("A square matrix is singular precisely when its determinant is:",
          ["$0$", "$1$", "Negative"], 0,
          "Zero determinant iff noninvertible."),
        q("$\\det\\begin{pmatrix}2&0&0\\\\1&3&0\\\\4&5&6\\end{pmatrix}$ equals:",
          ["$36$", "$0$", "$18$"], 0,
          "Lower triangular: $2\\cdot 3\\cdot 6=36$."),
        q("If $\\det A=2$, then $\\det(A^{-1})$ equals:",
          ["$1/2$", "$2$", "$-2$"], 0,
          "$\\det(A^{-1})=1/\\det A$."),
        q("Cofactor expansion of $\\begin{pmatrix}1&0&2\\\\0&3&0\\\\4&0&5\\end{pmatrix}$ along the middle row yields determinant:",
          ["$-9$", "$9$", "$15$"], 0,
          "Only the middle entry $3$ survives: $3(-1)^{2+2}\\det\\begin{pmatrix}1&2\\\\4&5\\end{pmatrix}=3(5-8)=-9$."),
        q("Area of the parallelogram with sides $\\langle 2,0\\rangle$ and $\\langle 1,3\\rangle$ equals:",
          ["$6$", "$5$", "$3$"], 0,
          "$|\\det\\begin{pmatrix}2&1\\\\0&3\\end{pmatrix}|=6$."),
        q("Multiplying one row by $4$ multiplies $\\det$ by:",
          ["$4$", "$16$", "$1/4$"], 0,
          "A single-row scale scales the determinant by the same factor."),
        q("If two rows of $A$ are identical, $\\det A$ equals:",
          ["$0$", "$1$", "$2$"], 0,
          "Dependent rows force a zero determinant."),
        q("$\\det I_n$ equals:",
          ["$1$", "$0$", "$n$"], 0,
          "Identity is triangular with ones on the diagonal."),
        q("For $A=\\begin{pmatrix}0&1\\\\-2&3\\end{pmatrix}$, $\\det A$ equals:",
          ["$2$", "$-2$", "$3$"], 0,
          "$0\\cdot 3-1\\cdot(-2)=2$."),
        q("Volume of the parallelepiped from columns of $\\begin{pmatrix}1&0&0\\\\0&2&0\\\\0&0&3\\end{pmatrix}$ equals:",
          ["$6$", "$5$", "$1$"], 0,
          "Absolute value of the determinant $1\\cdot 2\\cdot 3=6$."),
    ]

    banks["LA_M_INV_QUIZ"] = [
        q("The inverse of $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ is:",
          ["$\\begin{pmatrix}-2&1\\\\3/2&-1/2\\end{pmatrix}$", "$\\begin{pmatrix}4&-2\\\\-3&1\\end{pmatrix}$", "$\\begin{pmatrix}1&-2\\\\-3&4\\end{pmatrix}$"], 0,
          "$\\det=-2$; formula gives $(-1/2)\\begin{pmatrix}4&-2\\\\-3&1\\end{pmatrix}=\\begin{pmatrix}-2&1\\\\3/2&-1/2\\end{pmatrix}$."),
        q("A $2\\times 2$ matrix is invertible iff its determinant is:",
          ["Nonzero", "Positive", "Equal to $1$"], 0,
          "Invertibility is equivalent to $\\det\\ne 0$."),
        q("$(AB)^{-1}$ equals:",
          ["$B^{-1}A^{-1}$", "$A^{-1}B^{-1}$", "$AB$"], 0,
          "Inverse reverses the product order."),
        q("If $A\\mathbf{x}=\\mathbf{b}$ and $A$ is invertible, then $\\mathbf{x}$ equals:",
          ["$A^{-1}\\mathbf{b}$", "$A\\mathbf{b}$", "$\\mathbf{b}A^{-1}$"], 0,
          "Multiply both sides on the left by $A^{-1}$."),
        q("The matrix $\\begin{pmatrix}1&2\\\\2&4\\end{pmatrix}$ fails to be invertible because:",
          ["Its determinant is $0$", "It is symmetric", "It has positive entries"], 0,
          "$1\\cdot 4-2\\cdot 2=0$."),
        q("Inverse of $\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$ is:",
          ["$\\begin{pmatrix}1/2&0\\\\0&1/5\\end{pmatrix}$", "$\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$", "$\\begin{pmatrix}5&0\\\\0&2\\end{pmatrix}$"], 0,
          "Invert the diagonal entries."),
        q("For invertible $A$, $A A^{-1}$ equals:",
          ["$I$", "$A$", "$0$"], 0,
          "Definition of the inverse."),
        q("Using the adjugate, $A^{-1}=(1/\\det A)\\operatorname{adj}A$ when:",
          ["$\\det A\\ne 0$", "$A$ is symmetric", "$A$ is triangular"], 0,
          "The formula requires a nonzero determinant."),
        q("Solve $\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}\\mathbf{x}=\\begin{pmatrix}3\\\\2\\end{pmatrix}$ using the inverse.",
          ["$\\mathbf{x}=\\begin{pmatrix}1\\\\2\\end{pmatrix}$", "$\\mathbf{x}=\\begin{pmatrix}3\\\\2\\end{pmatrix}$", "$\\mathbf{x}=\\begin{pmatrix}2\\\\1\\end{pmatrix}$"], 0,
          "Inverse is $\\begin{pmatrix}1&-1\\\\0&1\\end{pmatrix}$; product gives $(1,2)$."),
        q("If $A^{-1}=\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$, then $A$ equals:",
          ["$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}0&-1\\\\-1&0\\end{pmatrix}$"], 0,
          "This matrix is its own inverse."),
        q("Gauss-Jordan finds $A^{-1}$ by row-reducing:",
          ["$[A\\mid I]$ to $[I\\mid A^{-1}]$", "$[A\\mid\\mathbf{0}]$", "$A$ alone to RREF"], 0,
          "Augment with the identity and reduce."),
        q("If $\\det A=-4$, then $\\det(A^{-1})$ equals:",
          ["$-1/4$", "$4$", "$1/4$"], 0,
          "$1/\\det A=-1/4$."),
        q("The inverse of $\\begin{pmatrix}1&0\\\\4&1\\end{pmatrix}$ is:",
          ["$\\begin{pmatrix}1&0\\\\-4&1\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\4&-1\\end{pmatrix}$", "$\\begin{pmatrix}-1&0\\\\-4&-1\\end{pmatrix}$"], 0,
          "Check product is $I$, or use the $2\\times 2$ formula."),
        q("If $A$ is invertible and $AB=AC$, then:",
          ["$B=C$", "$B=-C$", "Nothing about $B$ and $C$"], 0,
          "Multiply on the left by $A^{-1}$."),
        q("For $A=\\begin{pmatrix}4&1\\\\1&1\\end{pmatrix}$, $A^{-1}$ equals:",
          ["$\\dfrac{1}{3}\\begin{pmatrix}1&-1\\\\-1&4\\end{pmatrix}$", "$\\begin{pmatrix}1&-1\\\\-1&4\\end{pmatrix}$", "$\\dfrac{1}{3}\\begin{pmatrix}4&-1\\\\-1&1\\end{pmatrix}$"], 0,
          "$\\det=3$; adjugate formula gives $(1/3)\\begin{pmatrix}1&-1\\\\-1&4\\end{pmatrix}$."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "laVectorsMatricesQuizzes.js",
        "/** Study-guide quiz banks for the Linear Algebra Vectors and Matrices guides — 15 MCQs per section. */",
        build(),
    )
