# -*- coding: utf-8 -*-
"""Emit psProbRvQuizzes.js — Probability basics and random variables banks."""
from _quiz_emit import q, emit_file, OUT


def build():
    banks = {}

    banks["PS_B_INTRO_QUIZ"] = [
        q("A fair six-sided die is rolled once. What is $P(\\text{the result is at least }5)$?",
          ["$1/3$", "$1/6$", "$1/2$"], 0,
          "Favorable outcomes are $5$ and $6$, so $2/6=1/3$."),
        q("A fair coin is flipped twice. The sample space size is:",
          ["$4$", "$2$", "$3$"], 0,
          "Outcomes HH, HT, TH, TT."),
        q("If $P(A)=0.3$, then $P(A^c)$ equals:",
          ["$0.7$", "$0.3$", "$1.3$"], 0,
          "Complement rule: $1-0.3=0.7$."),
        q("For events with $P(A)=0.4$, $P(B)=0.5$, $P(A\\cap B)=0.1$, $P(A\\cup B)$ equals:",
          ["$0.8$", "$0.9$", "$0.4$"], 0,
          "$0.4+0.5-0.1=0.8$."),
        q("Two events that cannot occur together are called:",
          ["Disjoint (mutually exclusive)", "Independent", "Complements only if probabilities match"], 0,
          "Disjoint means empty intersection."),
        q("A spinner with four equal sectors labeled $1$–$4$ gives $P(\\text{even})$:",
          ["$1/2$", "$1/4$", "$3/4$"], 0,
          "Sectors $2$ and $4$ of four equally likely outcomes."),
        q("From a standard $52$-card deck, $P(\\text{drawing an ace})$ equals:",
          ["$1/13$", "$1/52$", "$4/13$"], 0,
          "$4$ aces among $52$ cards: $4/52=1/13$."),
        q("If odds in favor of $E$ are $2:1$, then $P(E)$ equals:",
          ["$2/3$", "$1/2$", "$2$"], 0,
          "Odds $a:b$ mean probability $a/(a+b)$."),
        q("For a fair die, $P(\\text{prime face})$ with primes $\\{2,3,5\\}$ equals:",
          ["$1/2$", "$1/3$", "$2/3$"], 0,
          "Three of six faces."),
        q("If $A$ and $B$ are disjoint and $P(A)=0.2$, $P(B)=0.3$, then $P(A\\cup B)$ equals:",
          ["$0.5$", "$0.06$", "$0.1$"], 0,
          "Add probabilities when the intersection is empty."),
        q("A sample space for one roll of a fair tetrahedral die labeled $1$–$4$ is:",
          ["$\\{1,2,3,4\\}$", "$\\{0,1,2,3\\}$", "$\\{1,2\\}$"], 0,
          "The four face values."),
        q("Axiomatically, probabilities of outcomes in a finite sample space must:",
          ["Be nonnegative and sum to $1$", "Each equal $1/2$", "All be zero"], 0,
          "Nonnegativity and normalization."),
        q("If $P(A\\cup B)=0.9$, $P(A)=0.6$, $P(B)=0.5$, then $P(A\\cap B)$ equals:",
          ["$0.2$", "$0.4$", "$1.1$"], 0,
          "Rearrange inclusion-exclusion: $0.6+0.5-0.9=0.2$."),
        q("Drawing one card, $P(\\text{heart or king})$ equals:",
          ["$16/52$", "$17/52$", "$13/52$"], 0,
          "$13$ hearts plus $3$ non-heart kings: $16/52$."),
        q("For any event $A$, $P(A)$ lies in:",
          ["$[0,1]$", "$(1,\\infty)$", "$(-1,1)$"], 0,
          "Probability bounds from the axioms."),
    ]

    banks["PS_B_COMBO_QUIZ"] = [
        q("The number of ways to choose $2$ committee members from $5$ people is:",
          ["$10$", "$20$", "$5$"], 0,
          "$\\binom{5}{2}=10$."),
        q("$P(5,2)$ equals:",
          ["$20$", "$10$", "$25$"], 0,
          "$5\\times 4=20$."),
        q("A password of $3$ distinct digits has how many possibilities?",
          ["$10\\times 9\\times 8=720$", "$10^3=1000$", "$\\binom{10}{3}$"], 0,
          "Ordered without repetition."),
        q("Arrangements of the letters in MISSISSIPPI: number of distinct permutations is:",
          ["$\\dfrac{11!}{4!4!2!}$", "$11!$", "$\\binom{11}{4}$"], 0,
          "Account for repeated I, S, and P."),
        q("From $52$ cards, ways to choose a $5$-card hand:",
          ["$\\binom{52}{5}$", "$P(52,5)$", "$52^5$"], 0,
          "Unordered hands use combinations."),
        q("A fair coin flipped $3$ times: $P(\\text{exactly two heads})$ equals:",
          ["$3/8$", "$1/8$", "$1/2$"], 0,
          "$\\binom{3}{2}/8=3/8$."),
        q("Multiplication principle: $4$ shirts and $3$ pants give how many outfits?",
          ["$12$", "$7$", "$4$"], 0,
          "$4\\times 3=12$."),
        q("$\\binom{6}{3}$ equals:",
          ["$20$", "$120$", "$18$"], 0,
          "$6!/(3!3!)=20$."),
        q("Number of injective functions from a $2$-set to a $5$-set is:",
          ["$20$", "$10$", "$25$"], 0,
          "$P(5,2)=20$."),
        q("A bag has $3$ red and $2$ blue marbles. Probability both drawn (without replacement, order ignored) are red:",
          ["$\\binom{3}{2}/\\binom{5}{2}=3/10$", "$3/5$", "$2/5$"], 0,
          "Favorable pairs over total pairs."),
        q("License plates with $2$ letters then $3$ digits (repeats allowed, $26$ letters) count:",
          ["$26^2\\cdot 10^3$", "$26\\cdot 25\\cdot 10\\cdot 9\\cdot 8$", "$P(26,2)\\cdot P(10,3)$ only"], 0,
          "Independent choices with repetition."),
        q("Ways to seat $4$ people in $4$ chairs in a row:",
          ["$24$", "$4$", "$16$"], 0,
          "$4!=24$."),
        q("Probability a random permutation of $\\{1,2,3\\}$ is sorted ascending:",
          ["$1/6$", "$1/3$", "$1/2$"], 0,
          "One of $6$ permutations."),
        q("$\\binom{10}{0}$ equals:",
          ["$1$", "$0$", "$10$"], 0,
          "One way to choose nothing."),
        q("Choosing a president and treasurer from $8$ distinct people (different roles):",
          ["$P(8,2)=56$", "$\\binom{8}{2}=28$", "$8$"], 0,
          "Order of roles matters."),
    ]

    banks["PS_B_COND_QUIZ"] = [
        q("If $P(A\\cap B)=0.1$ and $P(B)=0.5$, then $P(A\\mid B)$ equals:",
          ["$0.2$", "$0.5$", "$0.1$"], 0,
          "$0.1/0.5=0.2$."),
        q("A fair die is rolled. $P(\\text{even}\\mid \\text{at least }4)$ equals:",
          ["$2/3$", "$1/2$", "$1/3$"], 0,
          "Conditioning on $\\{4,5,6\\}$; even among them: $4,6$."),
        q("Two cards without replacement from a $52$-card deck: $P(\\text{second ace}\\mid\\text{first ace})$ equals:",
          ["$3/51$", "$4/52$", "$3/52$"], 0,
          "Three aces remain among $51$ cards."),
        q("Events $A,B$ are independent if:",
          ["$P(A\\cap B)=P(A)P(B)$", "$P(A\\cup B)=P(A)+P(B)$", "$P(A\\mid B)=0$"], 0,
          "Product rule characterization."),
        q("From a two-way table: $60$ men, $40$ women; $18$ men and $12$ women own pets. $P(\\text{owns pet}\\mid\\text{woman})$ equals:",
          ["$12/40=0.3$", "$18/60$", "$30/100$"], 0,
          "Restrict to the $40$ women."),
        q("Law of total probability with partition $\\{B,B^c\\}$: $P(A)$ equals:",
          ["$P(A\\mid B)P(B)+P(A\\mid B^c)P(B^c)$", "$P(A\\mid B)$ only", "$P(B\\mid A)$"], 0,
          "Average the conditional probabilities."),
        q("If $P(A)=0.4$, $P(B)=0.5$, and $A,B$ independent, $P(A\\cap B)$ equals:",
          ["$0.2$", "$0.9$", "$0.1$"], 0,
          "$0.4\\times 0.5=0.2$."),
        q("A bag has $2$ white and $3$ black balls. Draw two without replacement. $P(\\text{second white}\\mid\\text{first black})$ equals:",
          ["$2/4$", "$2/5$", "$3/4$"], 0,
          "After a black draw, $2$ white among $4$ left."),
        q("Multiplication rule: $P(A\\cap B)$ equals:",
          ["$P(A\\mid B)P(B)$", "$P(A)+P(B)$", "$P(A)/P(B)$"], 0,
          "Definition of conditional probability rearranged."),
        q("If $P(A\\mid B)=P(A)$, then $A$ and $B$ are:",
          ["Independent (when $P(B)>0$)", "Disjoint", "Complements"], 0,
          "Conditional equals marginal."),
        q("An urn holds $4$ red and $6$ blue balls. Given the ball is not blue, $P(\\text{red})$ equals:",
          ["$1$", "$4/10$", "$0$"], 0,
          "Not blue means the ball is red."),
        q("Two fair dice: $P(\\text{sum }=7\\mid\\text{first die shows }2)$ equals:",
          ["$1/6$", "$1/12$", "$1/2$"], 0,
          "Need second die to show $5$; one of six faces."),
        q("Sampling with replacement: successive draws are typically modeled as:",
          ["Independent", "Mutually exclusive", "Complements"], 0,
          "Restoring the item keeps probabilities fixed."),
        q("If $P(B)=0$, then $P(A\\mid B)$ is:",
          ["Undefined", "$0$", "$1$"], 0,
          "Cannot condition on a zero-probability event."),
        q("Partition check: if $P(A\\mid B_1)=0.2$, $P(A\\mid B_2)=0.5$, $P(B_1)=P(B_2)=1/2$, then $P(A)$ equals:",
          ["$0.35$", "$0.7$", "$0.2$"], 0,
          "$0.2\\cdot 1/2+0.5\\cdot 1/2=0.35$."),
    ]

    banks["PS_B_BAYES_QUIZ"] = [
        q("A disease has prevalence $1\\%$. A test is $99\\%$ sensitive and $95\\%$ specific. Approximate $P(\\text{disease}\\mid +)$ is closest to:",
          ["About $0.17$", "About $0.99$", "About $0.01$"], 0,
          "Bayes: with $10000$ people, about $99$ true $+$ and $495$ false $+$; $99/(99+495)\\approx 0.17$."),
        q("Bayes' theorem states $P(H\\mid E)$ equals:",
          ["$\\dfrac{P(E\\mid H)P(H)}{P(E)}$", "$P(E\\mid H)$", "$P(H)/P(E)$"], 0,
          "Posterior proportional to likelihood times prior."),
        q("Prior $P(H)=0.2$, likelihood $P(E\\mid H)=0.6$, $P(E\\mid H^c)=0.1$. Then $P(E)$ equals:",
          ["$0.2$", "$0.12$", "$0.08$"], 0,
          "$0.6\\cdot 0.2+0.1\\cdot 0.8=0.12+0.08=0.2$."),
        q("Using the previous numbers, $P(H\\mid E)$ equals:",
          ["$0.6$", "$0.2$", "$0.12$"], 0,
          "$(0.6\\cdot 0.2)/0.2=0.6$."),
        q("In a spam filter, $P(\\text{spam})=0.4$, $P(\\text{word}\\mid\\text{spam})=0.5$, $P(\\text{word}\\mid\\text{ham})=0.1$. Then $P(\\text{spam}\\mid\\text{word})$ equals:",
          ["$10/13$", "$1/2$", "$4/10$"], 0,
          "$P(\\text{word})=0.5\\cdot 0.4+0.1\\cdot 0.6=0.26$; posterior $0.2/0.26=10/13$."),
        q("Rare conditions yield many false positives because:",
          ["The base rate is low relative to the false-positive mass", "Sensitivity must be zero", "Specificity exceeds $1$"], 0,
          "Even a small false-positive rate hits many healthy people."),
        q("Factory: lines A,B produce $60\\%$ and $40\\%$ of items; defect rates $2\\%$ and $5\\%$. $P(\\text{from A}\\mid\\text{defect})$ equals:",
          ["$3/8$", "$2/5$", "$6/10$"], 0,
          "$P(D)=0.012+0.02=0.032$; $P(A\\mid D)=0.012/0.032=3/8$."),
        q("After observing evidence, the updated probability of a hypothesis is the:",
          ["Posterior", "Prior only", "Likelihood alone"], 0,
          "Posterior $=P(H\\mid E)$."),
        q("Three hypotheses $H_1,H_2,H_3$ with posteriors $0.2$, $0.5$, $0.3$ after data. They sum to:",
          ["$1$", "$0.5$", "$1.5$"], 0,
          "A complete posterior distribution normalizes to $1$."),
        q("Likelihood $P(E\\mid H)$ is:",
          ["Probability of the evidence given the hypothesis", "The prior", "Always equal to the posterior"], 0,
          "It is not the same as $P(H\\mid E)$."),
        q("Updating twice with independent reports multiplies likelihood factors into the:",
          ["Posterior (up to renormalization)", "Prior without change", "Sample space size only"], 0,
          "Sequential Bayes multiplies likelihoods."),
        q("If prior odds of $H$ are $1:3$ and the likelihood ratio $P(E\\mid H)/P(E\\mid H^c)=6$, posterior odds are:",
          ["$2:1$", "$6:3$", "$1:18$"], 0,
          "Posterior odds $=$ prior odds $\\times$ likelihood ratio: $(1/3)\\times 6=2$."),
        q("Medical test: $P(+\\mid D)=0.9$, $P(+\\mid D^c)=0.2$, $P(D)=0.1$. Then $P(D\\mid +)$ equals:",
          ["$1/3$", "$0.9$", "$0.1$"], 0,
          "$P(+)=0.09+0.18=0.27$, so $0.09/0.27=1/3$."),
        q("A sensor false-alarm rate is $P(+\\mid\\text{no event})=0.01$ with rare events. Without Bayes one might wrongly treat:",
          ["$P(+\\mid\\text{no event})$ as if it were $P(\\text{event}\\mid +)$", "Prevalence as $1$", "Sensitivity as specificity"], 0,
          "Confusing $P(+\\mid H^c)$ with $P(H\\mid +)$."),
        q("If new evidence has likelihood ratio $1$ for $H$ vs $H^c$, the posterior equals:",
          ["The prior", "Zero", "One"], 0,
          "Uninformative evidence leaves beliefs unchanged."),
    ]

    banks["PS_RV_INTRO_QUIZ"] = [
        q("A pmf $p(x)$ on a discrete support must satisfy:",
          ["$p(x)\\ge 0$ and $\\sum p(x)=1$", "$p(x)\\le 0$", "$\\sum p(x)=0$"], 0,
          "Nonnegative probabilities summing to one."),
        q("For $X$ with $P(X=1)=0.2$, $P(X=2)=0.5$, $P(X=3)=0.3$, $P(X\\le 2)$ equals:",
          ["$0.7$", "$0.5$", "$0.3$"], 0,
          "$0.2+0.5=0.7$."),
        q("The cdf $F(a)=P(X\\le a)$. If $F(2)=0.4$ and $F(3)=0.9$ for integer-valued $X$, then $P(X=3)$ equals:",
          ["$0.5$", "$0.9$", "$0.4$"], 0,
          "$F(3)-F(2)=0.5$."),
        q("Support of a discrete RV is:",
          ["The set of values with positive probability", "Always all real numbers", "Only the mean"], 0,
          "Where the pmf is positive."),
        q("An indicator $I_A$ equals $1$ on $A$ and $0$ otherwise. Then $E[I_A]$ equals:",
          ["$P(A)$", "$1$", "$0$"], 0,
          "Expectation of an indicator is the probability."),
        q("Fair die $X$: $P(X=6)$ equals:",
          ["$1/6$", "$1$", "$1/2$"], 0,
          "Six equally likely faces."),
        q("If $p(0)=0.4$, $p(1)=0.4$, $p(2)=0.3$, this cannot be a pmf because:",
          ["The values sum to $1.1\\ne 1$", "Some values are positive", "The support is finite"], 0,
          "Probabilities must sum to $1$."),
        q("For a fair coin, let $X=1$ for heads and $0$ for tails. Then $P(X=1)$ equals:",
          ["$1/2$", "$1$", "$0$"], 0,
          "Fair coin."),
        q("If $X$ takes values $1,2,3$ equally likely, $P(X\\ge 2)$ equals:",
          ["$2/3$", "$1/3$", "$1$"], 0,
          "Two of three outcomes."),
        q("A valid assignment $p(1)=1/2$, $p(2)=1/3$, $p(3)=1/6$ is a pmf because:",
          ["Entries are nonnegative and sum to $1$", "They are all equal", "The mean is $2$"], 0,
          "$1/2+1/3+1/6=1$."),
        q("For discrete $X$, $P(X<a)$ for integer $a$ equals:",
          ["$F(a-1)$ when $X$ is integer-valued", "$F(a)$", "$1-F(a)$ always"], 0,
          "Strict inequality stops at $a-1$."),
        q("Two independent fair coin indicators $I,J$: $P(I+J=2)$ equals:",
          ["$1/4$", "$1/2$", "$1$"], 0,
          "Both heads: $(1/2)^2$."),
        q("The pmf of a constant $X=7$ is:",
          ["$p(7)=1$", "$p(7)=7$", "$p(x)=1/7$ for all $x$"], 0,
          "All mass at a single point."),
        q("If $F$ is a cdf of discrete $X$, then $F$ is:",
          ["Nondecreasing and right-continuous with jumps at atoms", "Always continuous", "Always strictly decreasing"], 0,
          "Discrete cdfs jump at support points."),
        q("Construct pmf from rolling a die and setting $Y=1$ if face $>4$, else $0$. Then $P(Y=1)$ equals:",
          ["$1/3$", "$1/2$", "$2/3$"], 0,
          "Faces $5,6$ of six."),
    ]

    banks["PS_RV_MOMENTS_QUIZ"] = [
        q("For $X$ with $P(X=1)=0.2$, $P(X=2)=0.5$, $P(X=3)=0.3$, $E[X]$ equals:",
          ["$2.1$", "$2$", "$1.5$"], 0,
          "$1\\cdot 0.2+2\\cdot 0.5+3\\cdot 0.3=2.1$."),
        q("If $E[X]=2$ and $E[X^2]=5$, then $\\operatorname{Var}(X)$ equals:",
          ["$1$", "$3$", "$5$"], 0,
          "$5-2^2=1$."),
        q("Standard deviation is:",
          ["$\\sqrt{\\operatorname{Var}(X)}$", "$\\operatorname{Var}(X)$", "$E[X]$"], 0,
          "Square root of variance."),
        q("If $E[X]=4$, then $E[3X+1]$ equals:",
          ["$13$", "$12$", "$7$"], 0,
          "Linearity: $3\\cdot 4+1=13$."),
        q("$\\operatorname{Var}(3X+1)$ equals:",
          ["$9\\operatorname{Var}(X)$", "$3\\operatorname{Var}(X)$", "$\\operatorname{Var}(X)+1$"], 0,
          "Constants shift mean only; variance scales by $a^2$."),
        q("A game pays $5$ dollars with probability $1/2$ and $0$ otherwise. Expected payout is:",
          ["$2.5$ dollars", "$5$ dollars", "$0$ dollars"], 0,
          "$5\\cdot 1/2=2.5$."),
        q("For independent $X,Y$, $\\operatorname{Var}(X+Y)$ equals:",
          ["$\\operatorname{Var}(X)+\\operatorname{Var}(Y)$", "$\\operatorname{Var}(X)\\operatorname{Var}(Y)$", "$\\operatorname{Var}(X)-\\operatorname{Var}(Y)$"], 0,
          "Variances add under independence."),
        q("Bernoulli $X$ with $P(X=1)=p$ has variance:",
          ["$p(1-p)$", "$p$", "$1-p$"], 0,
          "$E[X^2]=p$ and $E[X]=p$."),
        q("If $X$ takes $-1$ and $1$ each with probability $1/2$, $\\operatorname{Var}(X)$ equals:",
          ["$1$", "$0$", "$1/2$"], 0,
          "$E[X]=0$, $E[X^2]=1$."),
        q("$E[X-E[X]]$ equals:",
          ["$0$", "$\\operatorname{Var}(X)$", "$E[X]$"], 0,
          "Centered variable has mean zero."),
        q("If $\\operatorname{Var}(X)=4$, then $\\operatorname{Var}(X/2)$ equals:",
          ["$1$", "$2$", "$4$"], 0,
          "$(1/2)^2\\cdot 4=1$."),
        q("For $X$ uniform on $\\{1,2,3,4\\}$, $E[X]$ equals:",
          ["$2.5$", "$4$", "$1$"], 0,
          "Average of $1$ through $4$."),
        q("A raffle: win $10$ dollars with probability $0.1$, else $0$. Expected gain is:",
          ["$1$ dollar", "$10$ dollars", "$0.1$ dollars"], 0,
          "$10\\cdot 0.1=1$."),
        q("If $X$ and $Y$ are independent with variances $2$ and $3$, $\\operatorname{Var}(X-Y)$ equals:",
          ["$5$", "$-1$", "$1$"], 0,
          "$\\operatorname{Var}(X)+\\operatorname{Var}(-Y)=2+3$."),
        q("Given pmf $p(0)=1/2$, $p(4)=1/2$, $E[X^2]$ equals:",
          ["$8$", "$2$", "$4$"], 0,
          "$0+16\\cdot 1/2=8$."),
    ]

    banks["PS_RV_CONT_QUIZ"] = [
        q("A pdf $f$ on $\\mathbb{R}$ must satisfy $f\\ge 0$ and:",
          ["$\\int_{-\\infty}^{\\infty}f(x)\\,dx=1$", "$\\sum f(x)=1$", "$f(x)\\le 1$ everywhere"], 0,
          "Continuous analogue of a pmf."),
        q("If $f(x)=c$ on $[0,2]$ and $0$ elsewhere, the normalizing $c$ equals:",
          ["$1/2$", "$2$", "$1$"], 0,
          "$\\int_0^2 c\\,dx=2c=1$."),
        q("For that uniform density, $P(0.5<X<1.5)$ equals:",
          ["$1/2$", "$1$", "$1/4$"], 0,
          "Length $1$ times height $1/2$."),
        q("For a continuous RV, $P(X=c)$ equals:",
          ["$0$", "$f(c)$", "$F(c)$"], 0,
          "Points have probability zero under a density."),
        q("If $F$ is the cdf, then $f(x)$ equals:",
          ["$F'(x)$ at continuity points of $f$", "$F(x)$", "$1-F(x)$"], 0,
          "Density is the derivative of the cdf."),
        q("Exponential pdf $f(x)=\\lambda e^{-\\lambda x}$ for $x>0$. If $\\lambda=2$, $P(X>1)$ equals:",
          ["$e^{-2}$", "$1-e^{-2}$", "$2e^{-2}$"], 0,
          "Survival $e^{-\\lambda x}$."),
        q("Uniform on $[0,1]$: $E[X]$ equals:",
          ["$1/2$", "$1$", "$0$"], 0,
          "$\\int_0^1 x\\,dx=1/2$."),
        q("Median $m$ of a continuous RV satisfies:",
          ["$F(m)=1/2$", "$f(m)=1/2$", "$E[X]=m$ always"], 0,
          "Half the mass on each side."),
        q("Pdf $f(x)=3x^2$ on $[0,1]$: $P(X<1/2)$ equals:",
          ["$1/8$", "$1/2$", "$3/8$"], 0,
          "$\\int_0^{1/2}3x^2\\,dx=(1/2)^3=1/8$."),
        q("For continuous $X$, $P(a\\le X\\le b)$ equals:",
          ["$\\int_a^b f(x)\\,dx$", "$f(b)-f(a)$", "$F(a)-F(b)$"], 0,
          "Integrate the density."),
        q("Exponential with mean $2$ has rate $\\lambda$ equal to:",
          ["$1/2$", "$2$", "$1$"], 0,
          "Mean $1/\\lambda$."),
        q("If $f(x)=0$ for $x<0$ and $x>1$, and $f(x)=2x$ on $[0,1]$, then $\\int f=1$ holds because:",
          ["$\\int_0^1 2x\\,dx=1$", "$2\\cdot 1=2$", "$f(1)=2$"], 0,
          "Check normalization."),
        q("Cdf of Uniform$[0,2]$ at $x=1$ equals:",
          ["$1/2$", "$1$", "$2$"], 0,
          "$F(x)=x/2$ on the interval."),
        q("Expectation $\\int_{-\\infty}^{\\infty} x f(x)\\,dx$ for a pdf $f$ is:",
          ["$E[X]$", "$\\operatorname{Var}(X)$", "$F(x)$"], 0,
          "Definition of the mean for continuous RVs."),
        q("If $X$ has pdf $f(x)=e^{-x}$ for $x>0$, the median solves $1-e^{-m}=1/2$, so $m$ equals:",
          ["$\\ln 2$", "$1$", "$1/2$"], 0,
          "$e^{-m}=1/2$."),
    ]

    banks["PS_RV_NAMED_QUIZ"] = [
        q("Binomial $n=10$, $p=0.3$: mean equals:",
          ["$3$", "$10$", "$0.3$"], 0,
          "$np=3$."),
        q("Same binomial: variance equals:",
          ["$2.1$", "$3$", "$0.21$"], 0,
          "$np(1-p)=10\\cdot 0.3\\cdot 0.7=2.1$."),
        q("Poisson with $\\lambda=2$: $P(X=0)$ equals:",
          ["$e^{-2}$", "$2e^{-2}$", "$1-e^{-2}$"], 0,
          "$e^{-\\lambda}\\lambda^0/0!$."),
        q("Geometric number of trials until first success with success probability $p=1/3$: mean equals:",
          ["$3$", "$1/3$", "$2/3$"], 0,
          "Mean $1/p$ for this convention."),
        q("Normal: if $X\\sim N(\\mu,\\sigma^2)$ and $Z=(X-\\mu)/\\sigma$, then $Z$ is:",
          ["Standard normal", "Uniform", "Poisson"], 0,
          "Standardization."),
        q("Empirical rule: about $95\\%$ of normal data lie within:",
          ["$2$ standard deviations of the mean", "$1$ SD", "$0.5$ SD"], 0,
          "68-95-99.7 rule."),
        q("Exponential memorylessness: $P(X>s+t\\mid X>s)$ equals:",
          ["$P(X>t)$", "$P(X>s)$", "$P(X>s+t)$"], 0,
          "No aging property."),
        q("Counting rare events per unit time is often modeled by:",
          ["Poisson", "Binomial with $n=2$ only", "Uniform continuous"], 0,
          "Poisson process counts."),
        q("Number of successes in $n$ independent Bernoulli trials is:",
          ["Binomial", "Normal always exact", "Geometric"], 0,
          "Definition of binomial."),
        q("If $X\\sim N(10,4)$ so $\\sigma=2$, then $P(8<X<12)$ is about:",
          ["$0.68$", "$0.95$", "$0.50$"], 0,
          "Within one SD of the mean."),
        q("Poisson mean $\\lambda=4$: variance equals:",
          ["$4$", "$2$", "$16$"], 0,
          "Mean and variance both $\\lambda$."),
        q("Binomial $n=5$, $p=1/2$: $P(X=5)$ equals:",
          ["$1/32$", "$1/2$", "$5/32$"], 0,
          "$(1/2)^5=1/32$."),
        q("Waiting time for a bus with constant hazard rate suggests an:",
          ["Exponential distribution", "Binomial distribution", "Hypergeometric only"], 0,
          "Continuous memoryless waits."),
        q("z-score of $x=7$ for $N(5,1)$ equals:",
          ["$2$", "$-2$", "$7$"], 0,
          "$(7-5)/1=2$."),
        q("Choosing a distribution: binary outcome per trial with fixed $n$ independent trials points to:",
          ["Binomial", "Exponential", "Uniform continuous on $[0,1]$ only"], 0,
          "Classic Bernoulli-sum model."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "psProbRvQuizzes.js",
        "/** Study-guide quiz banks for the Probability Basics and Random Variables guides — 15 MCQs per section. */",
        build(),
    )
