# -*- coding: utf-8 -*-
"""Emit mvLagrangeQuizzes.js — Lagrange Multipliers guide banks."""
from _quiz_emit import q, emit_file, OUT


def build():
    banks = {}

    banks["LAGRANGE_GEOMETRY_QUIZ"] = [
        q("At a constrained optimum of $f$ on $g(x,y)=k$, the level curve of $f$ and the constraint are:",
          ["Tangent to each other", "Perpendicular to each other", "Always parallel straight lines"], 0,
          "If they crossed transversally you could slide along the constraint and change $f$."),
        q("At such a tangency point, $\\nabla f$ and $\\nabla g$ are:",
          ["Parallel", "Always orthogonal", "Always zero"], 0,
          "Shared tangent means normals are parallel."),
        q("The geometric content of $\\nabla f=\\lambda\\nabla g$ is that:",
          ["The gradients point along the same line", "$f$ equals $g$", "Level curves of $f$ are circles"], 0,
          "$\\lambda$ scales one normal onto the other."),
        q("If $\\nabla f$ is not parallel to $\\nabla g$ at a constraint point, then:",
          ["You can move along $g=k$ to change $f$ to first order", "The point must be a global max", "$\\lambda$ must be infinite"], 0,
          "A nonzero tangential derivative of $f$ remains."),
        q("On a contour map, an optimum on a constraint curve occurs where a level curve of $f$:",
          ["Just touches the constraint", "Crosses the constraint at $45^\\circ$", "Is farthest from the origin"], 0,
          "Tangency is the geometric picture."),
        q("For $f(x,y)=x^2+y^2$ and constraint $x+y=2$, at the minimum the gradients are parallel to:",
          ["$\\langle 1,1\\rangle$", "$\\langle 1,-1\\rangle$", "$\\langle 2,-1\\rangle$"], 0,
          "$\\nabla g=\\langle 1,1\\rangle$; optimum at $(1,1)$."),
        q("Level curves of $f(x,y)=xy$ near $(2,2)$ look locally like:",
          ["Hyperbolas $xy=c$", "Circles $x^2+y^2=c$", "Lines $x+y=c$"], 0,
          "Product level sets are rectangular hyperbolas."),
        q("Constraint $x^2+y^2=8$ is a circle; $\\nabla g$ at $(2,2)$ equals:",
          ["$\\langle 4,4\\rangle$", "$\\langle 2,2\\rangle$", "$\\langle 1,0\\rangle$"], 0,
          "$g=x^2+y^2$, so $\\nabla g=\\langle 2x,2y\\rangle$."),
        q("If two curves cross at a nonzero angle, their normals are:",
          ["Not parallel", "Always parallel", "Always equal"], 0,
          "Non-tangency means independent normals."),
        q("Steepest ascent of $f$ is along $\\nabla f$. Constrained motion must stay in the:",
          ["Tangent to $g=k$", "Normal to $g=k$", "Direction of $\\nabla f$ only"], 0,
          "Feasible directions are tangential to the constraint."),
        q("For $f=x+2y$ on $x^2+y^2=5$, $\\nabla f$ is the constant vector:",
          ["$\\langle 1,2\\rangle$", "$\\langle 2,1\\rangle$", "$\\langle x,y\\rangle$"], 0,
          "Partial derivatives of a linear function."),
        q("A picture where every level curve of $f$ crosses $g=k$ transversally implies:",
          ["No constrained critical point of Lagrange type", "Infinitely many optima", "$\\nabla g=\\mathbf 0$ everywhere"], 0,
          "No tangency means the parallel-gradient condition fails."),
        q("At $(0,2)$ on $x^2+y^2=4$, a unit tangent to the circle is parallel to:",
          ["$\\langle 1,0\\rangle$", "$\\langle 0,1\\rangle$", "$\\langle 2,2\\rangle$"], 0,
          "Radius is vertical, so tangent is horizontal."),
        q("Why $\\lambda$ appears geometrically: it is the factor making:",
          ["$\\nabla f$ a scalar multiple of $\\nabla g$", "$f=g$", "The constraint linear"], 0,
          "Parallel normals differ by a scale factor."),
        q("For $f(x,y)=3x+4y$ and $g=x^2+y^2$, the point where level lines of $f$ are tangent to $g=25$ is:",
          ["$\\pm(3,4)$ scaled to the circle, i.e. $\\pm(3,4)$", "$(5,0)$ only", "$(0,0)$"], 0,
          "$\\nabla f\\parallel\\nabla g$ gives $(x,y)$ parallel to $(3,4)$; on the circle of radius $5$ you get $\\pm(3,4)$."),
    ]

    banks["LAGRANGE_MATH_QUIZ"] = [
        q("The Lagrangian with constraint $g=k$ is often written:",
          ["$\\mathcal{L}=f-\\lambda(g-k)$", "$\\mathcal{L}=f+g$", "$\\mathcal{L}=\\nabla f\\cdot\\nabla g$"], 0,
          "Stationarity of $\\mathcal{L}$ recovers Lagrange plus the constraint."),
        q("The full Lagrange system in two variables with one constraint has how many scalar equations?",
          ["$3$", "$2$", "$4$"], 0,
          "Two from $\\nabla f=\\lambda\\nabla g$ plus $g=k$."),
        q("Unknowns in that 2D one-constraint problem are:",
          ["$x$, $y$, and $\\lambda$", "Only $x$ and $y$", "Only $\\lambda$"], 0,
          "Point plus multiplier."),
        q("A regularity condition needed for the basic method is:",
          ["$\\nabla g\\ne\\mathbf 0$ at the point", "$f=0$", "$\\lambda=1$"], 0,
          "Constraint qualification / nonvanishing gradient."),
        q("For $f(x,y)=xy$ and $g=x^2+y^2-8$, the equation $\\partial\\mathcal{L}/\\partial x=0$ reads:",
          ["$y=\\lambda(2x)$", "$x=\\lambda(2y)$", "$xy=8$"], 0,
          "$f_x=\\lambda g_x$."),
        q("Same setup: $\\partial\\mathcal{L}/\\partial y=0$ gives:",
          ["$x=\\lambda(2y)$", "$y=\\lambda(2x)$", "$x+y=0$"], 0,
          "$f_y=\\lambda g_y$."),
        q("From $f_x=\\lambda g_x$ and $f_y=\\lambda g_y$ with $\\nabla g\\ne\\mathbf 0$, one may eliminate $\\lambda$ by:",
          ["Cross-multiplying $f_x g_y=f_y g_x$", "Setting $f=g$", "Setting $\\lambda=0$ always"], 0,
          "Parallel vectors satisfy that determinant condition."),
        q("If $f_x g_y-f_y g_x=0$ and $g=k$ hold at $P$ with $\\nabla g(P)\\ne\\mathbf 0$, then:",
          ["$P$ satisfies the Lagrange necessary condition", "$P$ is always a maximum", "$\\lambda$ cannot exist"], 0,
          "Equivalent to existence of some $\\lambda$."),
        q("The multiplier $\\lambda$ has units/meaning as a sensitivity:",
          ["Approximately $df^*/dk$", "Always the optimal $f$", "The Hessian determinant"], 0,
          "Shadow price / rate of change of optimal value."),
        q("If $\\nabla g(P)=\\mathbf 0$ while $g(P)=k$, the standard Lagrange equation:",
          ["May miss a constrained critical point", "Always still works unchanged", "Forces $f$ constant"], 0,
          "Need a separate check at singular constraint points."),
        q("Counting: three variables, one constraint $g=k$ gives how many equations?",
          ["$4$", "$3$", "$6$"], 0,
          "Three gradient components plus the constraint."),
        q("Sign of $\\lambda$: if increasing $k$ raises the optimal $f^*$, then typically:",
          ["$\\lambda>0$ in the $f-\\lambda(g-k)$ convention used here", "$\\lambda$ must be zero", "$\\lambda$ is undefined"], 0,
          "Positive shadow price."),
        q("Stationary points of $\\mathcal{L}(x,y,\\lambda)$ satisfy:",
          ["$\\nabla_{x,y}\\mathcal{L}=\\mathbf 0$ and $\\partial\\mathcal{L}/\\partial\\lambda=0$", "Only $f=0$", "Only $\\lambda=0$"], 0,
          "Critical-point conditions for the Lagrangian."),
        q("For linear $f(x,y)=ax+by$ on a smooth closed curve, optima occur where:",
          ["$\\langle a,b\\rangle$ is normal to the curve", "$f=0$", "The curve has a corner only"], 0,
          "Parallel to $\\nabla g$."),
        q("Writing $g(x,y)-k=0$ instead of $g=k$ changes $\\nabla g$ by:",
          ["Nothing: same gradient", "A factor of $k$", "Sign flip of $f$"], 0,
          "Constant $k$ disappears upon differentiating."),
    ]

    banks["LAGRANGE_FIELDS_QUIZ"] = [
        q("Maximize area $xy$ of a rectangle with perimeter $2x+2y=20$. Objective $f$ is:",
          ["$xy$", "$2x+2y$", "$x+y$"], 0, "Area is the objective."),
        q("In that problem the constraint function can be taken as:",
          ["$g=x+y$ with $k=10$", "$g=xy$ with $k=20$", "$g=2x$ with $k=20$"], 0,
          "Simplify $2x+2y=20$ to $x+y=10$."),
        q("Minimize distance from $(0,0)$ to the line $x+2y=4$. A valid objective is:",
          ["$f=x^2+y^2$", "$f=x+2y$", "$f=4$"], 0,
          "Squared distance avoids a square root."),
        q("For budget $3x+5y=60$ maximizing utility $u=x^{1/2}y^{1/2}$, the constraint $g$ is:",
          ["$3x+5y$", "$x^{1/2}y^{1/2}$", "$xy$"], 0, "Cost is constrained; utility is $f$."),
        q("Compute $\\nabla f$ for $f(x,y)=x^2y$:",
          ["$\\langle 2xy,x^2\\rangle$", "$\\langle x^2,y\\rangle$", "$\\langle 2x,1\\rangle$"], 0,
          "Product rule in each variable."),
        q("Compute $\\nabla g$ for $g(x,y)=x^2+4y^2$:",
          ["$\\langle 2x,8y\\rangle$", "$\\langle 2x,4y\\rangle$", "$\\langle x,4y\\rangle$"], 0,
          "Partials $2x$ and $8y$."),
        q("Word problem: \"cheapest mix of inputs $x,y$ costing $2x+3y$ to produce level $xy=12$\". Here $f$ is:",
          ["$2x+3y$", "$xy$", "$x+y$"], 0, "Minimize cost; production level is the constraint."),
        q("Mis-stated constraint: writing $x^2+y^2=8$ as $g=x^2+y^2-8$ with $k=0$ is:",
          ["Valid and equivalent", "Invalid because $k$ must be $8$", "Invalid because $g$ must be linear"], 0,
          "Absorbing the constant into $g$ is fine."),
        q("For $f(x,y,z)=xyz$ and plane $x+y+z=6$, $\\nabla f$ at $(2,2,2)$ equals:",
          ["$\\langle 4,4,4\\rangle$", "$\\langle 2,2,2\\rangle$", "$\\langle 1,1,1\\rangle$"], 0,
          "$\\langle yz,xz,xy\\rangle=\\langle 4,4,4\\rangle$."),
        q("Same plane: $\\nabla g$ for $g=x+y+z$ equals:",
          ["$\\langle 1,1,1\\rangle$", "$\\langle x,y,z\\rangle$", "$\\langle 2,2,2\\rangle$"], 0,
          "Constant gradient."),
        q("Identify $f$ vs $g$: maximize $f=3x+4y$ on the ellipse $x^2/4+y^2/9=1$. Then $g$ is:",
          ["$x^2/4+y^2/9$", "$3x+4y$", "$xy$"], 0, "Ellipse is the constraint."),
        q("Compute $\\nabla(x^2/4+y^2/9)$:",
          ["$\\langle x/2,\\,2y/9\\rangle$", "$\\langle 2x,2y\\rangle$", "$\\langle x/4,y/9\\rangle$"], 0,
          "Derivative of $x^2/4$ is $x/2$."),
        q("Fixed surface area $2(xy+xz+yz)=S$ for a box; to maximize volume, $f$ is:",
          ["$xyz$", "$xy+xz+yz$", "$x+y+z$"], 0, "Volume is the objective."),
        q("Constraint $g(x,y)=e^{x}+e^{y}$ with $k=4$ means feasible points satisfy:",
          ["$e^{x}+e^{y}=4$", "$e^{x}+e^{y}=0$", "$xy=4$"], 0, "Definition of $g=k$."),
        q("For $f=\\ln(xy)$ on $x+y=4$ with $x,y>0$, $\\nabla f$ equals:",
          ["$\\langle 1/x,\\,1/y\\rangle$", "$\\langle y,x\\rangle$", "$\\langle 1,1\\rangle$"], 0,
          "Derivative of $\\ln x+\\ln y$."),
    ]

    banks["LAGRANGE_CALC_QUIZ"] = [
        q("Extremize $f=xy$ on $x^2+y^2=8$. A critical point is:",
          ["$(2,2)$", "$(0,\\sqrt{8})$", "$(1,1)$"], 0,
          "From $y=2\\lambda x$, $x=2\\lambda y$ get $x=\\pm y$; with $x^2+y^2=8$, $(2,2)$ works."),
        q("On $x^2+y^2=8$, the maximum of $xy$ equals:",
          ["$4$", "$8$", "$2$"], 0, "At $(2,2)$ or $(-2,-2)$, $f=4$."),
        q("On $x^2+y^2=8$, the minimum of $xy$ equals:",
          ["$-4$", "$0$", "$-8$"], 0, "At $(2,-2)$ and $(-2,2)$."),
        q("Extremize $f=x+2y$ on $x^2+y^2=5$. Then $\\lambda$ satisfies $\\langle 1,2\\rangle=\\lambda\\langle 2x,2y\\rangle$, so $(x,y)$ is parallel to:",
          ["$\\langle 1,2\\rangle$", "$\\langle 2,1\\rangle$", "$\\langle 1,-2\\rangle$"], 0,
          "Gradient of $f$ fixed."),
        q("Maximum of $x+2y$ on $x^2+y^2=5$ equals:",
          ["$5$", "$\\sqrt{10}$", "$3$"], 0,
          "$|\\langle 1,2\\rangle|=\\sqrt{5}$ and radius $\\sqrt{5}$, so max is $5$."),
        q("Minimum of $x+2y$ on $x^2+y^2=5$ equals:",
          ["$-5$", "$0$", "$-\\sqrt{5}$"], 0, "Opposite direction on the circle."),
        q("Minimize $f=x^2+y^2$ on $x+2y=4$. The closest point is:",
          ["$(4/5,\\,8/5)$", "$(2,1)$", "$(4,0)$"], 0,
          "$\\langle 2x,2y\\rangle=\\lambda\\langle 1,2\\rangle$ and $x+2y=4$ give that point."),
        q("Minimum distance squared from origin to $x+2y=4$ equals:",
          ["$16/5$", "$4$", "$8/5$"], 0, "$(4/5)^2+(8/5)^2=16/5$."),
        q("Maximize $f=xyz$ on $x+y+z=6$ with $x,y,z>0$. By symmetry the max occurs at:",
          ["$(2,2,2)$", "$(3,3,0)$", "$(6,0,0)$"], 0,
          "Equal variables from $\\nabla f=\\lambda\\nabla g$."),
        q("That maximal volume $xyz$ equals:",
          ["$8$", "$6$", "$27$"], 0, "$2\\cdot 2\\cdot 2=8$."),
        q("For $f=xy$ on $x^2+y^2=8$ at $(2,2)$, the multiplier with $g=x^2+y^2$ satisfies $y=\\lambda 2x$, so $\\lambda$ equals:",
          ["$1/2$", "$2$", "$1$"], 0, "$2=\\lambda\\cdot 4\\Rightarrow\\lambda=1/2$."),
        q("Maximize $f=3x+4y$ on $x^2+y^2=25$. The maximum value is:",
          ["$25$", "$5$", "$7$"], 0,
          "$|\\langle 3,4\\rangle|\\cdot 5=5\\cdot 5=25$."),
        q("A box with square base side $x$ and height $y$ has volume $x^2 y=100$. Minimize surface $S=x^2+4xy$. At the optimum, $y$ equals:",
          ["$x/2$", "$x$", "$2x$"], 0,
          "Lagrange/substitution yields $y=x/2$."),
        q("Extremize $f=x^2+y^2$ on $xy=1$. Minimum value is:",
          ["$2$", "$1$", "$0$"], 0, "At $(\\pm 1,\\pm 1)$, $f=2$."),
        q("On $x^2+y^2=1$, maximize $f=x^2+2y^2$. The maximum is:",
          ["$2$", "$1$", "$3$"], 0, "Largest when $|y|=1$: value $2$."),
    ]

    banks["LAGRANGE_MULTI_QUIZ"] = [
        q("With two constraints $g=a$ and $h=b$, the vector equation is:",
          ["$\\nabla f=\\lambda\\nabla g+\\mu\\nabla h$", "$\\nabla f=\\lambda\\nabla g$ only", "$\\nabla f=\\mathbf 0$"], 0,
          "Linear combination of both constraint normals."),
        q("In $\\mathbb{R}^3$ with two constraints, the full scalar system has how many equations?",
          ["$5$", "$3$", "$6$"], 0,
          "Three from the gradient relation plus two constraints."),
        q("Unknowns are then:",
          ["$x,y,z,\\lambda,\\mu$", "Only $x,y,z$", "Only $\\lambda,\\mu$"], 0,
          "Point plus two multipliers."),
        q("Extremize $f=x+y+z$ on $x+y=1$ and $x^2+y^2+z^2=1$. Feasible set is:",
          ["Intersection of a plane and a sphere (a circle)", "A single point", "The whole sphere"], 0,
          "Plane cut of the sphere."),
        q("On that set, $\\nabla f=\\langle 1,1,1\\rangle$. At an optimum, $\\langle 1,1,1\\rangle$ lies in the span of:",
          ["$\\langle 1,1,0\\rangle$ and $\\langle 2x,2y,2z\\rangle$", "Only $\\langle 1,0,0\\rangle$", "Only $\\langle 0,0,1\\rangle$"], 0,
          "Normals to the two constraints."),
        q("For $f=z$ on $x^2+y^2=1$ and $z=0$ (unit circle in $xy$-plane), every point is critical and $f$ equals:",
          ["$0$", "$1$", "$-1$"], 0, "Constraint forces $z=0$."),
        q("Optimize $f=x$ on the intersection of $x^2+y^2+z^2=4$ and $z=1$. Max $x$ equals:",
          ["$\\sqrt{3}$", "$2$", "$1$"], 0,
          "Circle $x^2+y^2=3$, $z=1$; max $x=\\sqrt{3}$."),
        q("Min $x$ on that same intersection equals:",
          ["$-\\sqrt{3}$", "$0$", "$-2$"], 0, "Opposite side of the circle."),
        q("If $\\nabla g$ and $\\nabla h$ are parallel at a feasible point, the two-constraint method:",
          ["May be invalid there (dependent constraints)", "Always works", "Forces $f$ maximal"], 0,
          "Need independent constraint gradients."),
        q("Intersection of cylinder $x^2+y^2=1$ and plane $x+z=2$ is a:",
          ["Closed curve (ellipse in the plane)", "Pair of lines", "Single point"], 0,
          "Plane cuts the cylinder."),
        q("Extremize $f=y$ on $x^2+y^2=1$, $z=0$. Max $y$ equals:",
          ["$1$", "$0$", "$\\sqrt{2}$"], 0, "Top of the unit circle."),
        q("System count check: two variables, two constraints generally gives:",
          ["Isolated feasible points (0-dimensional)", "A curve of candidates", "A surface"], 0,
          "Two equations in two unknowns."),
        q("For $f=x^2+y^2+z^2$ on $x+y+z=3$ and $x+2y+3z=6$, the geometry is:",
          ["Nearest/farthest origin point on a line (plane∩plane)", "Optimization on a sphere", "Unconstrained in $\\mathbb{R}^3$"], 0,
          "Two planes meet in a line."),
        q("Multipliers $(\\lambda,\\mu)$ exist at a regular point iff $\\nabla f$ is in:",
          ["$\\mathrm{span}\\{\\nabla g,\\nabla h\\}$", "The tangent plane only", "The $xy$-plane"], 0,
          "Normal-space condition."),
        q("On $x^2+y^2+z^2=6$ and $x+y+z=0$, maximize $f=x$. With $y=z$ at the maximizer, $x$ equals:",
          ["$2$", "$\\sqrt{2}$", "$0$"], 0,
          "$y=z=-x/2$ and $x^2+2(x^2/4)=6$ give $x^2=4$, so max $x=2$."),
    ]

    banks["LAGRANGE_VERIFY_QUIZ"] = [
        q("Candidates for $f=xy$ on $x^2+y^2=8$ give values $4$ and $-4$. Therefore the maximum is:",
          ["$4$", "$-4$", "$0$"], 0, "Compare candidate values."),
        q("The second-derivative test for unconstrained critical points:",
          ["Does not apply directly to Lagrange candidates", "Always classifies constrained points", "Replaces the constraint"], 0,
          "Need bordered Hessian or value comparison on a compact set."),
        q("After solving Lagrange, you must still check:",
          ["That each candidate satisfies $g=k$", "Only that $\\lambda>0$", "Only that $f=0$"], 0,
          "Feasibility of the constraint."),
        q("On a compact constraint set (closed bounded), continuous $f$:",
          ["Attains both max and min", "Need not attain either", "Attains only a max"], 0,
          "Extreme Value Theorem."),
        q("Constraint $xy=1$ in the plane is unbounded. For $f=x+y$:",
          ["There is no global max; candidates need careful interpretation", "EVT guarantees a max", "Only $\\lambda$ matters"], 0,
          "Hyperbola is not compact."),
        q("Values $f(2,2)=4$ and $f(2,-2)=-4$ on the circle: the constrained minimum is:",
          ["$-4$", "$4$", "$2$"], 0, "Smaller candidate wins for min."),
        q("If two candidates give the same $f$ value on a connected constraint, that value:",
          ["May be both max and min only if $f$ is constant there", "Must be a saddle in 3D", "Is never optimal"], 0,
          "Compare all critical values."),
        q("Point $(0,0)$ solves $\\nabla f=\\lambda\\nabla g$ for $f=x^2+y^2$, $g=x+y$ with $k=0$, but $g(0,0)=0$. Is it on $x+y=1$?",
          ["No: constraint $k=1$ fails", "Yes", "Only if $\\lambda=0$"], 0,
          "Check $g=k$ with the intended $k$."),
        q("For $f=x$ on the closed unit disk $x^2+y^2\\le 1$, Lagrange on the boundary finds endpoints; the interior critical points of $f$:",
          ["Do not exist ($\\nabla f\\ne\\mathbf 0$)", "Are at the origin", "Fill the disk"], 0,
          "$\\nabla f=\\langle 1,0\\rangle$ never zero; max on boundary."),
        q("Comparing $f^*=5$ and $f^*=-5$ on a circle, the range of $f$ on that circle includes:",
          ["Both extremes", "Only the positive one", "Neither"], 0,
          "Compact connected image is an interval."),
        q("A candidate with $\\nabla g=\\mathbf 0$ should be:",
          ["Checked separately as a singular point", "Automatically discarded", "Always the global max"], 0,
          "Constraint qualification failed."),
        q("If the constraint is a closed curve and you found exactly two critical values, typically:",
          ["One is max and one is min", "Both are maxima", "Neither is extreme"], 0,
          "Generic Morse picture on a circle."),
        q("Verifying $(2,2)$ on $x^2+y^2=8$: $4+4$ equals:",
          ["$8$", "$4$", "$2$"], 0, "Constraint holds."),
        q("Unbounded ray constraint $x\\ge 0$, $y=0$ for $f=-x$ has:",
          ["No minimum (goes to $-\\infty$)", "Minimum at the origin", "Maximum at infinity"], 0,
          "Not coercive on an unbounded set."),
        q("After listing candidates, classification by sorting $f$-values works when:",
          ["The feasible set is compact (or you otherwise know extrema exist)", "$\\lambda$ is an integer", "$f$ is linear only"], 0,
          "Need existence before comparing."),
    ]

    banks["LAGRANGE_INDUSTRY_QUIZ"] = [
        q("Utility $u=x^{1/2}y^{1/2}$ with budget $2x+2y=40$ dollars. At the optimum, $x$ equals:",
          ["$10$", "$20$", "$5$"], 0,
          "Equal spending: $2x=2y=20$ so $x=y=10$."),
        q("Same problem: optimal utility value is:",
          ["$10$", "$20$", "$5$"], 0, "$\\sqrt{10\\cdot 10}=10$."),
        q("Cobb-Douglas $f=x^{1/3}y^{2/3}$ with cost $x+4y=12$. Optimal $y$ equals:",
          ["$2$", "$1$", "$3$"], 0,
          "Spend fraction $2/3$ of budget on $y$: $4y=8\\Rightarrow y=2$."),
        q("Minimize can surface area $2\\pi r h+2\\pi r^2$ for volume $\\pi r^2 h=16\\pi$. Optimal $h$ in terms of $r$ is:",
          ["$h=2r$", "$h=r$", "$h=4r$"], 0,
          "Classic result $h=2r$ for a closed cylinder."),
        q("Least-cost inputs: minimize $3x+5y$ subject to $xy=15$. Optimal $x$ equals:",
          ["$5$", "$3$", "$15$"], 0,
          "From $3=\\lambda y$, $5=\\lambda x$ get $3x=5y$; with $xy=15$, $x=5$, $y=3$."),
        q("Shadow price: if relaxing a resource constraint by one unit raises optimal profit by $7$ dollars, then $\\lambda$ is about:",
          ["$7$", "$1$", "$0$"], 0, "Interpretation of the multiplier."),
        q("Entropy-style: maximize $-p\\ln p-(1-p)\\ln(1-p)$ for $p\\in(0,1)$ with no further constraint. Critical point at:",
          ["$p=1/2$", "$p=1$", "$p=0$"], 0, "Binary entropy peaks at equal probabilities."),
        q("Production $q=\\min\\{2x,3y\\}$ is not smooth; on the ray $2x=3y=q$ with cost $x+y$ minimized for $q=6$, $x$ equals:",
          ["$3$", "$2$", "$6$"], 0, "$2x=6\\Rightarrow x=3$, and $y=2$."),
        q("Budget $p_x x+p_y y=m$ with $u=\\ln x+\\ln y$. Demand $x$ equals:",
          ["$m/(2p_x)$", "$m/p_x$", "$p_x/m$"], 0, "Equal budget shares."),
        q("Material cost proportional to surface $4xy+2x^2$ for a lidless box volume $x^2 y=500$. At optimum $y$ equals:",
          ["$x$", "$2x$", "$x/2$"], 0,
          "From Lagrange/substitution $y=x$."),
        q("Firm maximizes profit $\\pi=12q-c(q)$ with capacity $q\\le 10$. If unconstrained max is at $q=12$, the capacity constraint is:",
          ["Active at $q=10$", "Inactive", "Impossible"], 0,
          "Optimum pushed to the boundary."),
        q("Diet cost $2x+3y$ with protein $x+2y\\ge 10$. At a vertex optimum with both nutrients binding in equality form used by Lagrange, solve $x+2y=10$ with gradients — if only protein binds and fat is free, interior of edge uses:",
          ["Ordinary one-constraint Lagrange on the binding nutrient", "No optimization", "Two free variables"], 0,
          "Active-set idea."),
        q("Max $f=xy$ with $x+y=12$ (hours split). Optimal product is:",
          ["$36$", "$24$", "$12$"], 0, "$x=y=6$, product $36$."),
        q("Insurance: maximize expected utility with actuarially fair premium — Lagrange on the budget typically equalizes:",
          ["Marginal utilities across states (up to probabilities)", "Raw wealth in every state to zero", "Only the premium"], 0,
          "First-order conditions."),
        q("If a budget increases from $40$ to $41$ dollars and optimal utility rises by about $0.25$, the multiplier magnitude is near:",
          ["$0.25$", "$40$", "$1$"], 0, "$\\Delta u^*/\\Delta m\\approx\\lambda$."),
    ]

    banks["LAGRANGE_CHALLENGE_QUIZ"] = [
        q("Sensitivity: if $f^*$ on $g=k$ has $\\lambda=3$ in $\\nabla f=\\lambda\\nabla g$, then $df^*/dk$ is approximately:",
          ["$3$", "$-3$", "$0$"], 0, "Envelope theorem / shadow price."),
        q("Inequality $g\\le k$ at an interior feasible point with $g<k$ means the multiplier for that inequality is:",
          ["$0$ (inactive)", "Forced nonzero", "Infinite"], 0, "Complementary slackness."),
        q("Degenerate case: $g(x,y)=x^2+y^2$ at $(0,0)$ with $k=0$. Then $\\nabla g(0,0)$ equals:",
          ["$\\mathbf 0$", "$\\langle 1,0\\rangle$", "$\\langle 1,1\\rangle$"], 0, "Singular constraint point."),
        q("Extremize $f=x^2+y^2+z^2$ on $x^4+y^4+z^4=1$. By symmetry a maximizer can be taken with:",
          ["Two coordinates zero", "All coordinates equal only", "$x=1,y=1,z=1$"], 0,
          "Max of $r^2$ on $L^4$ unit sphere occurs on axes."),
        q("On $x^4+y^4+z^4=1$, maximum of $x^2+y^2+z^2$ equals:",
          ["$1$", "$\\sqrt{3}$", "$3^{1/2}$"], 0, "At $(\\pm 1,0,0)$ etc., value $1$."),
        q("Minimum of $x^2+y^2+z^2$ on $x^4+y^4+z^4=1$ equals:",
          ["$3^{1/2}$", "$1$", "$3$"], 0,
          "Equal coordinates $|x|=3^{-1/4}$, sum of squares $3\\cdot 3^{-1/2}=3^{1/2}$."),
        q("For $f=xy+yz+zx$ on $x+y+z=3$, the unconstrained-on-plane critical point is:",
          ["$(1,1,1)$", "$(3,0,0)$", "$(0,0,3)$"], 0, "Symmetry / Lagrange."),
        q("Value of $xy+yz+zx$ at $(1,1,1)$ equals:",
          ["$3$", "$1$", "$9$"], 0, "Three products of $1$."),
        q("Mix geometry: max $f=x$ on $x^2+y^2=1$ occurs where the vertical line is tangent to the circle, i.e. at:",
          ["$(1,0)$", "$(0,1)$", "$(1/\\sqrt{2},1/\\sqrt{2})$"], 0, "Rightmost point."),
        q("Active inequality: maximize $f=- (x^2+y^2)$ on $x\\ge 0$. Unconstrained max of $f$ is at origin; since origin is feasible,",
          ["The inequality is inactive and optimum is $(0,0)$", "Must use $\\lambda\\ne 0$ on $x=0$ only", "No optimum"], 0,
          "Interior of the half-plane relative to the soft constraint."),
        q("Three variables: $f=x+2y+3z$ on $x^2+y^2+z^2=14$. Max equals:",
          ["$14$", "$7$", "$\\sqrt{14}$"], 0,
          "$|\\langle 1,2,3\\rangle|=\\sqrt{14}$ and radius $\\sqrt{14}$, so max is $14$."),
        q("If $\\nabla g=\\mathbf 0$ only at points off the level $g=k$, then on $g=k$ the basic method:",
          ["Applies at all feasible points (regular)", "Never applies", "Needs three multipliers"], 0,
          "Constraint qualification holds on the level set."),
        q("Symmetric collapse: $f=x^2+y^2$ on $(x-1)^2+(y-1)^2=1$. Closest point to origin lies on the line:",
          ["$y=x$", "$y=0$", "$x=1$"], 0, "Symmetry across $y=x$."),
        q("That minimum distance from origin to the circle center $(1,1)$ radius $1$ equals:",
          ["$\\sqrt{2}-1$", "$\\sqrt{2}$", "$1$"], 0, "Along the ray: $\\sqrt{2}-1$."),
        q("For $f^*=k^2$ on constraint radius related problem with $\\lambda=2k$, consistency with $df^*/dk=2k$ shows:",
          ["$\\lambda$ matches the sensitivity", "$\\lambda$ contradicts sensitivity", "$\\lambda$ must be $0$"], 0,
          "Envelope check."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "mvLagrangeQuizzes.js",
        "/** Study-guide quiz banks for the Lagrange Multipliers guide — 15 MCQs per section. */",
        build(),
    )
