# -*- coding: utf-8 -*-
"""Emit psProbRvQuizzes.js and psStatsQuizzes.js — Probability, RV, and Stats banks."""
from _quiz_emit import q, emit_file, OUT


def build_prob_rv():
    banks = {}

    # ---------- Probability basics ----------
    banks["PS_B_INTRO_QUIZ"] = [
        q("A fair six-sided die is rolled once. What is $P(\\text{the result is at least }5)$?",
          ["$1/3$", "$1/6$", "$1/2$"], 0,
          "Favorable outcomes are $5$ and $6$, so $2/6=1/3$."),
        q("Two fair coins are flipped. How many equally likely outcomes are in the sample space?",
          ["$4$", "$2$", "$8$"], 0,
          "The outcomes are HH, HT, TH, TT."),
        q("If $P(A)=0.28$, then $P(A^{c})$ equals:",
          ["$0.72$", "$0.28$", "$1.28$"], 0,
          "Complement rule: $1-0.28=0.72$."),
        q("From a standard $52$-card deck, one card is drawn. $P(\\text{ace})$ equals:",
          ["$1/13$", "$1/4$", "$4/13$"], 0,
          "There are $4$ aces among $52$ cards: $4/52=1/13$."),
        q("Given $P(A)=0.55$, $P(B)=0.40$, and $P(A\\cap B)=0.15$, find $P(A\\cup B)$.",
          ["$0.80$", "$0.95$", "$0.70$"], 0,
          "Inclusion-exclusion: $0.55+0.40-0.15=0.80$."),
        q("Two fair dice are rolled. $P(\\text{sum}=9)$ equals:",
          ["$4/36$", "$5/36$", "$1/6$"], 0,
          "Pairs $(3,6),(4,5),(5,4),(6,3)$ give sum $9$, so $4/36$."),
        q("A spinner has equal sectors labeled $1$ through $8$. $P(\\text{odd})$ equals:",
          ["$1/2$", "$3/8$", "$5/8$"], 0,
          "Odds are $1,3,5,7$: four of eight sectors."),
        q("Events $A$ and $B$ are disjoint with $P(A)=0.22$ and $P(B)=0.31$. Then $P(A\\cup B)$ equals:",
          ["$0.53$", "$0.09$", "$0.68$"], 0,
          "Disjoint means $P(A\\cap B)=0$, so $P(A\\cup B)=0.22+0.31$."),
        q("If the odds in favor of $E$ are $3$ to $2$, then $P(E)$ equals:",
          ["$3/5$", "$3/2$", "$2/5$"], 0,
          "Odds $3:2$ means $P(E)=3/(3+2)=3/5$."),
        q("A fair coin is flipped three times. $P(\\text{exactly two heads})$ equals:",
          ["$3/8$", "$1/2$", "$1/8$"], 0,
          "Three equally likely sequences HHT, HTH, THH among $8$ outcomes."),
        q("If $P(A\\cup B)=0.71$, $P(A)=0.48$, and $P(B)=0.39$, then $P(A\\cap B)$ equals:",
          ["$0.16$", "$0.23$", "$0.10$"], 0,
          "Rearrange inclusion-exclusion: $0.48+0.39-0.71=0.16$."),
        q("A bag holds $5$ red and $7$ blue marbles. One marble is drawn at random. $P(\\text{red})$ equals:",
          ["$5/12$", "$5/7$", "$7/12$"], 0,
          "Total $12$ marbles; five are red."),
        q("Which statement is true for any event $A$?",
          ["$0\\le P(A)\\le 1$", "$P(A)$ must be at least $1/2$", "$P(A)+P(A^{c})$ can exceed $1$"], 0,
          "The probability axioms force every probability into $[0,1]$."),
        q("A fair die is rolled. $P(\\text{prime face})$ equals (primes among $1$–$6$: $2,3,5$):",
          ["$1/2$", "$1/3$", "$2/3$"], 0,
          "Three prime faces out of six: $3/6=1/2$."),
        q("If $P(A)=0.6$ and $P(B)=0.5$ with $A,B$ not necessarily disjoint, the largest possible $P(A\\cap B)$ is:",
          ["$0.5$", "$0.6$", "$1.1$"], 0,
          "Intersection cannot exceed either margin, so at most $\\min(0.6,0.5)=0.5$."),
    ]

    banks["PS_B_COMBO_QUIZ"] = [
        q("A password uses $3$ letters from a $26$-letter alphabet, order matters, repeats allowed. How many passwords?",
          ["$26^3$", "$P(26,3)$", "$\\binom{26}{3}$"], 0,
          "Multiplication principle with replacement: $26\\times 26\\times 26$."),
        q("Evaluate $P(7,2)$.",
          ["$42$", "$21$", "$14$"], 0,
          "$P(7,2)=7\\times 6=42$."),
        q("Evaluate $\\binom{8}{3}$.",
          ["$56$", "$336$", "$24$"], 0,
          "$\\binom{8}{3}=\\dfrac{8\\cdot 7\\cdot 6}{3\\cdot 2\\cdot 1}=56$."),
        q("How many $5$-card hands can be dealt from $52$ cards?",
          ["$\\binom{52}{5}$", "$P(52,5)$", "$52^5$"], 0,
          "Order within a hand does not matter, so combinations."),
        q("A committee of $4$ is chosen from $9$ people. How many committees?",
          ["$126$", "$3024$", "$36$"], 0,
          "$\\binom{9}{4}=126$."),
        q("The word BOOK has how many distinct letter arrangements?",
          ["$12$", "$24$", "$4$"], 0,
          "$4!/2!=12$ because O is repeated twice."),
        q("A fair die is rolled twice. Number of equally likely ordered outcomes is:",
          ["$36$", "$12$", "$6$"], 0,
          "$6\\times 6=36$ ordered pairs."),
        q("From $10$ songs, playlist of $3$ distinct songs in order. How many playlists?",
          ["$720$", "$120$", "$30$"], 0,
          "$P(10,3)=10\\times 9\\times 8=720$."),
        q("A coin is flipped $4$ times. Number of sequences with exactly $3$ heads is:",
          ["$4$", "$6$", "$8$"], 0,
          "$\\binom{4}{3}=4$ positions for the single tail."),
        q("Choose a president and a treasurer from $8$ people (roles distinct). How many ways?",
          ["$56$", "$28$", "$16$"], 0,
          "$P(8,2)=8\\times 7=56$."),
        q("A bag has $4$ red and $6$ green balls. Two are drawn without replacement. Number of equally likely unordered pairs is:",
          ["$\\binom{10}{2}$", "$10\\times 9$", "$4\\times 6$"], 0,
          "All unordered $2$-subsets of $10$ balls are equally likely."),
        q("Evaluate $\\binom{6}{0}+\\binom{6}{6}$.",
          ["$2$", "$1$", "$12$"], 0,
          "Each binomial coefficient equals $1$."),
        q("License plates: $2$ letters then $3$ digits, repeats allowed. How many plates?",
          ["$26^2\\cdot 10^3$", "$P(26,2)\\cdot P(10,3)$", "$26\\cdot 25\\cdot 10\\cdot 9\\cdot 8$"], 0,
          "Each letter has $26$ choices and each digit $10$."),
        q("From a $52$-card deck, $P(\\text{both cards aces})$ when two cards are drawn without replacement (unordered) equals:",
          ["$\\dfrac{\\binom{4}{2}}{\\binom{52}{2}}$", "$\\dfrac{4}{52}\\cdot\\dfrac{4}{52}$", "$\\dfrac{4}{52}$"], 0,
          "Favorable pairs of aces over all $2$-card hands."),
        q("How many ways to arrange the letters of LEVEL?",
          ["$30$", "$120$", "$60$"], 0,
          "$5!/(2!\\cdot 2!)=30$ for the repeated L and E."),
    ]

    banks["PS_B_COND_QUIZ"] = [
        q("If $P(A\\cap B)=0.12$ and $P(B)=0.40$, then $P(A\\mid B)$ equals:",
          ["$0.30$", "$0.12$", "$0.52$"], 0,
          "$P(A\\mid B)=0.12/0.40=0.30$."),
        q("A two-way table: $P(A)=0.35$, $P(B)=0.50$, $P(A\\cap B)=0.20$. Find $P(A\\mid B)$.",
          ["$0.40$", "$0.20$", "$0.70$"], 0,
          "$0.20/0.50=0.40$."),
        q("An urn has $3$ red and $5$ blue balls. Two are drawn without replacement. $P(\\text{second red}\\mid\\text{first red})$ equals:",
          ["$2/7$", "$3/8$", "$3/7$"], 0,
          "After one red is removed, $2$ red remain among $7$ balls."),
        q("Events $A,B$ satisfy $P(A)=0.4$, $P(B)=0.5$, $P(A\\cap B)=0.2$. Are they independent?",
          ["Yes, because $P(A)P(B)=P(A\\cap B)$", "No, because $P(A\\cap B)\\ne 0$", "No, because $P(A)\\ne P(B)$"], 0,
          "$0.4\\cdot 0.5=0.2$, matching the intersection."),
        q("Given $P(A\\mid B)=0.6$ and $P(B)=0.25$, find $P(A\\cap B)$.",
          ["$0.15$", "$0.85$", "$0.024$"], 0,
          "Multiplication rule: $0.6\\cdot 0.25=0.15$."),
        q("A fair die is rolled. Let $A=\\{2,4,6\\}$ and $B=\\{4,5,6\\}$. Then $P(A\\mid B)$ equals:",
          ["$2/3$", "$1/2$", "$1/3$"], 0,
          "$A\\cap B=\\{4,6\\}$ has two outcomes among the three in $B$."),
        q("Cards: draw two without replacement from $52$. $P(\\text{second is king}\\mid\\text{first is king})$ equals:",
          ["$3/51$", "$4/52$", "$4/51$"], 0,
          "Three kings remain among $51$ cards."),
        q("Law of total probability: $P(B\\mid A_1)=0.2$, $P(B\\mid A_2)=0.5$, with $P(A_1)=0.4$, $P(A_2)=0.6$ and $\\{A_1,A_2\\}$ a partition. $P(B)$ equals:",
          ["$0.38$", "$0.70$", "$0.30$"], 0,
          "$0.2\\cdot 0.4+0.5\\cdot 0.6=0.08+0.30=0.38$."),
        q("If $A$ and $B$ are independent with $P(A)=0.3$ and $P(B)=0.4$, then $P(A\\cup B)$ equals:",
          ["$0.58$", "$0.12$", "$0.70$"], 0,
          "$P(A\\cap B)=0.12$, so $0.3+0.4-0.12=0.58$."),
        q("A class: $60\\%$ take math, $40\\%$ take physics, $25\\%$ take both. Given a random math student, $P(\\text{also physics})$ equals:",
          ["$5/12$", "$0.25$", "$0.40$"], 0,
          "$P(\\text{physics}\\mid\\text{math})=0.25/0.60=5/12$."),
        q("Two cards without replacement. $P(\\text{ace then king})$ equals:",
          ["$\\dfrac{4}{52}\\cdot\\dfrac{4}{51}$", "$\\dfrac{4}{52}\\cdot\\dfrac{4}{52}$", "$\\dfrac{8}{52}$"], 0,
          "Multiply sequential conditional probabilities."),
        q("If $P(A\\mid B)=P(A)$, then $A$ and $B$ are:",
          ["Independent", "Disjoint", "Equally likely"], 0,
          "That equality is the definition of independence (when $P(B)>0$)."),
        q("Box: $2$ defective and $8$ good items. Two drawn without replacement. $P(\\text{both defective})$ equals:",
          ["$\\dfrac{2}{10}\\cdot\\dfrac{1}{9}$", "$\\dfrac{2}{10}\\cdot\\dfrac{2}{10}$", "$\\dfrac{2}{10}$"], 0,
          "After one defective is taken, one defective remains among nine."),
        q("Given $P(A)=0.5$, $P(B\\mid A)=0.4$, $P(B\\mid A^{c})=0.8$. Find $P(B)$.",
          ["$0.60$", "$0.40$", "$1.20$"], 0,
          "$0.4\\cdot 0.5+0.8\\cdot 0.5=0.2+0.4=0.60$."),
        q("A fair coin is flipped twice. $P(\\text{HH}\\mid\\text{at least one H})$ equals:",
          ["$1/3$", "$1/2$", "$1/4$"], 0,
          "Conditioning space is $\\{HH,HT,TH\\}$; only HH qualifies."),
    ]

    banks["PS_B_BAYES_QUIZ"] = [
        q("Disease rate $1\\%$. Test: $P(+\\mid D)=0.99$, $P(+\\mid D^{c})=0.05$. Find $P(D\\mid +)$ (approx).",
          ["$0.167$", "$0.99$", "$0.01$"], 0,
          "Bayes: $\\dfrac{0.99\\cdot 0.01}{0.99\\cdot 0.01+0.05\\cdot 0.99}=\\dfrac{0.0099}{0.0594}\\approx 0.167$."),
        q("In that medical-test setup, why is $P(D\\mid +)$ far below $0.99$?",
          ["The prior is tiny, so most positives come from healthy people", "The sensitivity is too low", "Bayes theorem does not apply to rare events"], 0,
          "With prevalence $1\\%$, false positives from the $99\\%$ healthy group dominate."),
        q("Spam prior $P(S)=0.20$. Word $W$ has $P(W\\mid S)=0.60$, $P(W\\mid S^{c})=0.10$. Find $P(S\\mid W)$.",
          ["$0.60$", "$0.20$", "$0.75$"], 0,
          "$\\dfrac{0.60\\cdot 0.20}{0.60\\cdot 0.20+0.10\\cdot 0.80}=\\dfrac{0.12}{0.20}=0.60$."),
        q("Factories: $A$ makes $70\\%$ of parts, $B$ makes $30\\%$. Defect rates $2\\%$ and $5\\%$. A random defective part: $P(\\text{from }A)$ equals:",
          ["$14/29$", "$0.70$", "$2/7$"], 0,
          "$P(D)=0.014+0.015=0.029$; $P(A\\mid D)=0.014/0.029=14/29$."),
        q("Prior $P(H)=0.4$, likelihood $P(E\\mid H)=0.7$, $P(E\\mid H^{c})=0.2$. Posterior $P(H\\mid E)$ equals:",
          ["$0.70$", "$0.40$", "$0.28$"], 0,
          "$\\dfrac{0.7\\cdot 0.4}{0.7\\cdot 0.4+0.2\\cdot 0.6}=\\dfrac{0.28}{0.40}=0.70$."),
        q("Three equally likely hypotheses $H_1,H_2,H_3$ with likelihoods $0.1,0.3,0.6$ for data $D$. Then $P(H_3\\mid D)$ equals:",
          ["$0.6$", "$1/3$", "$0.9$"], 0,
          "Posteriors proportional to $0.1,0.3,0.6$; normalize by $1.0$ to get $0.6$."),
        q("Which quantity is the prior in Bayes' theorem for $P(H\\mid D)$?",
          ["$P(H)$", "$P(D\\mid H)$", "$P(H\\mid D)$"], 0,
          "The prior is the belief about $H$ before seeing the data."),
        q("Screening: prevalence $2\\%$, sensitivity $95\\%$, false-positive rate $10\\%$. $P(\\text{disease}\\mid +)$ equals:",
          ["$19/117$", "$0.95$", "$0.02$"], 0,
          "$\\dfrac{0.95\\cdot 0.02}{0.95\\cdot 0.02+0.10\\cdot 0.98}=\\dfrac{0.019}{0.117}=19/117$."),
        q("After one update, posterior $P(H\\mid E_1)=0.75$. A second independent test has $P(E_2\\mid H)=0.8$, $P(E_2\\mid H^{c})=0.4$. New posterior equals:",
          ["$0.857$", "$0.75$", "$0.60$"], 0,
          "Use $0.75$ as prior: $\\dfrac{0.8\\cdot 0.75}{0.8\\cdot 0.75+0.4\\cdot 0.25}=\\dfrac{0.60}{0.70}\\approx 0.857$."),
        q("Machine $A$ vs $B$ each produce half the items. Defect rates $1\\%$ and $4\\%$. Given a good item, $P(\\text{from }A)$ equals:",
          ["$99/195$", "$1/2$", "$99/100$"], 0,
          "$P(G)=0.495+0.48=0.975$; $P(A\\mid G)=0.495/0.975=99/195$."),
        q("If posteriors for three mutually exclusive hypotheses are $0.2$, $0.5$, and $x$, then $x$ must be:",
          ["$0.3$", "$0.5$", "$1.0$"], 0,
          "Posteriors over a partition sum to $1$."),
        q("Email filter: $P(\\text{spam})=0.3$, $P(\\text{word}\\mid\\text{spam})=0.9$, $P(\\text{word}\\mid\\text{ham})=0.2$. $P(\\text{spam}\\mid\\text{word})$ equals:",
          ["$27/41$", "$0.9$", "$0.3$"], 0,
          "$\\dfrac{0.9\\cdot 0.3}{0.9\\cdot 0.3+0.2\\cdot 0.7}=\\dfrac{0.27}{0.41}=27/41$."),
        q("Likelihood $P(D\\mid H)$ is best described as:",
          ["How probable the data are if $H$ is true", "The posterior probability of $H$", "The prior probability of $H$"], 0,
          "Likelihood treats $H$ as given and evaluates the data."),
        q("Urns: Urn 1 ($P=1/2$) has $2$ white $2$ black; Urn 2 has $3$ white $1$ black. A white ball is drawn. $P(\\text{Urn }1\\mid\\text{white})$ equals:",
          ["$2/5$", "$1/2$", "$1/4$"], 0,
          "$P(W)=0.25+0.375=0.625$; $P(U_1\\mid W)=0.25/0.625=0.4=2/5$."),
        q("Rare condition ($0.1\\%$), perfect sensitivity, $1\\%$ false-positive rate. Approx $P(\\text{condition}\\mid +)$ is:",
          ["$0.091$", "$0.99$", "$0.001$"], 0,
          "$\\dfrac{0.001}{0.001+0.01\\cdot 0.999}\\approx 0.001/0.011\\approx 0.091$."),
    ]

    # ---------- Random variables ----------
    banks["PS_RV_INTRO_QUIZ"] = [
        q("A discrete RV $X$ has pmf $p(1)=0.2$, $p(2)=0.5$, $p(3)=0.3$. Is this a valid pmf?",
          ["Yes, because probabilities are nonnegative and sum to $1$", "No, because $p(2)$ exceeds $1/2$", "No, because support is finite"], 0,
          "$0.2+0.5+0.3=1$ with all entries $\\ge 0$."),
        q("For that same pmf, $P(X\\le 2)$ equals:",
          ["$0.7$", "$0.5$", "$0.3$"], 0,
          "$p(1)+p(2)=0.2+0.5=0.7$."),
        q("If $F$ is the cdf of $X$ above, $F(2)$ equals:",
          ["$0.7$", "$0.5$", "$1.0$"], 0,
          "By definition $F(2)=P(X\\le 2)=0.7$."),
        q("A fair die $X$. The support of $X$ is:",
          ["$\\{1,2,3,4,5,6\\}$", "$\\{0,1\\}$", "$(0,1)$"], 0,
          "Those six faces are the only values with positive probability."),
        q("Let $I=1$ if a fair coin lands heads and $0$ otherwise. Then $P(I=1)$ equals:",
          ["$1/2$", "$1$", "$0$"], 0,
          "Indicator of a fair-coin heads event."),
        q("Two fair coins; $X=$ number of heads. Then $p_X(1)$ equals:",
          ["$1/2$", "$1/4$", "$3/4$"], 0,
          "HT and TH give exactly one head: $2/4=1/2$."),
        q("Which fails to be a pmf on $\\{0,1,2\\}$?",
          ["$p(0)=0.5$, $p(1)=0.6$, $p(2)=-0.1$", "$p(0)=0.2$, $p(1)=0.3$, $p(2)=0.5$", "$p(0)=1$, $p(1)=0$, $p(2)=0$"], 0,
          "Negative probabilities are forbidden."),
        q("For $X$ with $p(0)=0.1$, $p(1)=0.4$, $p(2)=0.5$, $P(X>0)$ equals:",
          ["$0.9$", "$0.4$", "$0.5$"], 0,
          "$1-p(0)=0.9$."),
        q("A discrete cdf jumps only at support points. Between jumps, $F$ is:",
          ["Constant (flat)", "Strictly increasing", "Always zero"], 0,
          "No probability mass means the cdf does not rise."),
        q("Roll two fair dice; $S=$ sum. Then $P(S=2)$ equals:",
          ["$1/36$", "$1/6$", "$2/36$"], 0,
          "Only $(1,1)$ yields sum $2$."),
        q("If $p_X(k)=c/2^k$ for $k=1,2,3$ and $0$ elsewhere, the normalizing $c$ equals:",
          ["$8/7$", "$1$", "$2$"], 0,
          "$c(1/2+1/4+1/8)=c\\cdot 7/8=1$ so $c=8/7$."),
        q("For a discrete RV, $P(X=a)$ equals:",
          ["The jump size of the cdf at $a$", "Always zero", "The derivative of the cdf at $a$"], 0,
          "$P(X=a)=F(a)-\\lim_{x\\uparrow a}F(x)$."),
        q("Indicator $I_A$ of event $A$ with $P(A)=0.3$ has $E[I_A]$ equal to:",
          ["$0.3$", "$0$", "$1$"], 0,
          "$E[I_A]=P(A)$."),
        q("pmf table: $x\\in\\{−1,0,1\\}$ with probabilities $0.25,0.50,0.25$. Then $P(|X|=1)$ equals:",
          ["$0.50$", "$0.25$", "$0.75$"], 0,
          "$P(X=-1)+P(X=1)=0.5$."),
        q("A valid discrete pmf must satisfy:",
          ["$\\sum_x p(x)=1$ and $p(x)\\ge 0$", "$p(x)\\le 1/2$ for all $x$", "$\\sum_x p(x)=0$"], 0,
          "Nonnegativity and total mass $1$ are the pmf axioms."),
    ]

    banks["PS_RV_MOMENTS_QUIZ"] = [
        q("pmf: $P(X=1)=0.2$, $P(X=2)=0.5$, $P(X=3)=0.3$. Then $E[X]$ equals:",
          ["$2.1$", "$2.0$", "$1.5$"], 0,
          "$1\\cdot 0.2+2\\cdot 0.5+3\\cdot 0.3=2.1$."),
        q("For that $X$, $E[X^2]$ equals:",
          ["$4.9$", "$4.41$", "$2.1$"], 0,
          "$1\\cdot 0.2+4\\cdot 0.5+9\\cdot 0.3=0.2+2+2.7=4.9$."),
        q("Hence $\\operatorname{Var}(X)$ equals:",
          ["$0.49$", "$4.9$", "$2.1$"], 0,
          "$E[X^2]-(E[X])^2=4.9-4.41=0.49$."),
        q("If $E[X]=4$ and $\\operatorname{Var}(X)=9$, then the standard deviation is:",
          ["$3$", "$9$", "$2$"], 0,
          "$\\mathrm{SD}=\\sqrt{\\operatorname{Var}}=3$."),
        q("If $E[X]=5$, then $E[3X-2]$ equals:",
          ["$13$", "$15$", "$3$"], 0,
          "Linearity: $3\\cdot 5-2=13$."),
        q("If $\\operatorname{Var}(X)=4$, then $\\operatorname{Var}(3X-7)$ equals:",
          ["$36$", "$12$", "$4$"], 0,
          "$\\operatorname{Var}(aX+b)=a^2\\operatorname{Var}(X)=9\\cdot 4=36$."),
        q("A game pays $10$ dollars with probability $0.3$ and $0$ otherwise. Expected payout is:",
          ["$3$ dollars", "$10$ dollars", "$0.3$ dollars"], 0,
          "$10\\cdot 0.3+0\\cdot 0.7=3$ dollars."),
        q("Independent $X,Y$ with $\\operatorname{Var}(X)=2$, $\\operatorname{Var}(Y)=5$. Then $\\operatorname{Var}(X+Y)$ equals:",
          ["$7$", "$10$", "$3$"], 0,
          "Independence implies variances add."),
        q("Fair die $X$. $E[X]$ equals:",
          ["$3.5$", "$3$", "$6$"], 0,
          "$(1+2+3+4+5+6)/6=21/6=3.5$."),
        q("pmf $P(Y=0)=1/2$, $P(Y=4)=1/2$. Then $\\operatorname{Var}(Y)$ equals:",
          ["$4$", "$2$", "$8$"], 0,
          "$E[Y]=2$, $E[Y^2]=8$, variance $8-4=4$."),
        q("If $E[X]=−2$ and $E[X^2]=10$, then $\\operatorname{Var}(X)$ equals:",
          ["$6$", "$8$", "$12$"], 0,
          "$10-(-2)^2=10-4=6$."),
        q("A raffle: pay $2$ dollars to play; win $10$ dollars (net $+8$) with probability $0.1$, else lose the stake (net $-2$). Expected net is:",
          ["$-1$ dollar", "$0$ dollars", "$8$ dollars"], 0,
          "$0.1\\cdot 8+0.9\\cdot(-2)=0.8-1.8=-1$."),
        q("If $X$ takes values $0$ and $10$ each with probability $1/2$, $\\mathrm{SD}(X)$ equals:",
          ["$5$", "$25$", "$10$"], 0,
          "$E[X]=5$, $E[X^2]=50$, $\\operatorname{Var}=25$, SD $=5$."),
        q("Linearity fails for which statement in general?",
          ["$E[XY]=E[X]E[Y]$ without independence", "$E[X+Y]=E[X]+E[Y]$", "$E[cX]=cE[X]$"], 0,
          "Product expectation needs independence (or uncorrelatedness)."),
        q("Independent copies $X_1,X_2$ each with variance $3$. $\\operatorname{Var}(X_1-X_2)$ equals:",
          ["$6$", "$0$", "$3$"], 0,
          "$\\operatorname{Var}(X_1)+\\operatorname{Var}(-X_2)=3+3=6$."),
    ]

    banks["PS_RV_CONT_QUIZ"] = [
        q("pdf $f(x)=c$ on $[0,4]$ and $0$ elsewhere. The constant $c$ equals:",
          ["$1/4$", "$4$", "$1$"], 0,
          "Integrate: $4c=1$ so $c=1/4$."),
        q("For that uniform density, $P(1<X<3)$ equals:",
          ["$1/2$", "$1/4$", "$3/4$"], 0,
          "Length $2$ over total length $4$."),
        q("pdf $f(x)=2x$ on $[0,1]$. Then $P(X\\le 1/2)$ equals:",
          ["$1/4$", "$1/2$", "$1$"], 0,
          "$\\int_0^{1/2}2x\\,dx=x^2\\big|_0^{1/2}=1/4$."),
        q("For continuous $X$, $P(X=2)$ equals:",
          ["$0$", "$f(2)$", "$F(2)$"], 0,
          "A single point has Lebesgue measure zero under a pdf."),
        q("If $F$ is a continuous cdf that is differentiable, then $f(x)$ equals:",
          ["$F'(x)$", "$F(x)$", "$1-F(x)$"], 0,
          "The pdf is the derivative of the cdf."),
        q("Exponential pdf $f(x)=\\lambda e^{-\\lambda x}$ for $x>0$ with $\\lambda=2$. $P(X>1)$ equals:",
          ["$e^{-2}$", "$1-e^{-2}$", "$2e^{-2}$"], 0,
          "Survival: $e^{-\\lambda x}=e^{-2}$."),
        q("Uniform on $[2,6]$. The median equals:",
          ["$4$", "$2$", "$6$"], 0,
          "Midpoint of a symmetric uniform interval."),
        q("pdf $f(x)=3x^2$ on $[0,1]$. Then $E[X]$ equals:",
          ["$3/4$", "$1/2$", "$1$"], 0,
          "$\\int_0^1 x\\cdot 3x^2\\,dx=3/4$."),
        q("Find $c$ so $f(x)=cx$ on $[0,2]$ is a pdf.",
          ["$1/2$", "$1$", "$2$"], 0,
          "$\\int_0^2 cx\\,dx=2c=1$ implies $c=1/2$."),
        q("cdf $F(x)=1-e^{-x}$ for $x>0$. Then $f(x)$ equals:",
          ["$e^{-x}$", "$1-e^{-x}$", "$-e^{-x}$"], 0,
          "Differentiate the cdf."),
        q("Uniform$[0,1]$. $P(0.2<X<0.7)$ equals:",
          ["$0.5$", "$0.9$", "$0.2$"], 0,
          "Interval length $0.5$."),
        q("pdf $f(x)=1/2$ on $[-1,1]$. $P(|X|<1/2)$ equals:",
          ["$1/2$", "$1$", "$1/4$"], 0,
          "From $-1/2$ to $1/2$ has length $1$; times density $1/2$ gives $1/2$."),
        q("For continuous $X$ with cdf $F$, the median $m$ solves:",
          ["$F(m)=1/2$", "$f(m)=1/2$", "$E[X]=m$"], 0,
          "Definition of the median via the cdf."),
        q("Exponential with mean $4$ (so $\\lambda=1/4$). $P(X\\le 4)$ equals:",
          ["$1-e^{-1}$", "$e^{-1}$", "$1/4$"], 0,
          "$F(4)=1-e^{-\\lambda\\cdot 4}=1-e^{-1}$."),
        q("pdf $f(x)=\\dfrac{1}{9}x^2$ on $[0,3]$. Check total mass: $\\int_0^3 f$ equals:",
          ["$1$", "$3$", "$1/3$"], 0,
          "$\\dfrac{1}{9}\\cdot\\dfrac{x^3}{3}\\big|_0^3=1$."),
    ]

    banks["PS_RV_NAMED_QUIZ"] = [
        q("Binomial $n=5$, $p=0.4$. Mean $E[X]$ equals:",
          ["$2$", "$5$", "$1.2$"], 0,
          "$np=5\\cdot 0.4=2$."),
        q("Same binomial: $\\operatorname{Var}(X)$ equals:",
          ["$1.2$", "$2$", "$0.4$"], 0,
          "$np(1-p)=5\\cdot 0.4\\cdot 0.6=1.2$."),
        q("Binomial $n=4$, $p=1/2$. $P(X=2)$ equals:",
          ["$6/16$", "$4/16$", "$1/2$"], 0,
          "$\\binom{4}{2}(1/2)^4=6/16$."),
        q("Poisson with $\\lambda=3$. $E[X]$ equals:",
          ["$3$", "$\\sqrt{3}$", "$9$"], 0,
          "Poisson mean equals $\\lambda$."),
        q("Poisson $\\lambda=2$. $P(X=0)$ equals:",
          ["$e^{-2}$", "$2e^{-2}$", "$1-e^{-2}$"], 0,
          "$e^{-\\lambda}\\lambda^0/0!=e^{-2}$."),
        q("Geometric (trials until first success) with $p=1/3$. Mean number of trials is:",
          ["$3$", "$1/3$", "$2$"], 0,
          "Mean $1/p=3$."),
        q("Normal $X\\sim N(\\mu=10,\\sigma=2)$. The $z$-score of $x=14$ is:",
          ["$2$", "$4$", "$0.5$"], 0,
          "$z=(14-10)/2=2$."),
        q("Empirical rule: for a normal variable, about what percent lies within $1$ SD of the mean?",
          ["$68\\%$", "$95\\%$", "$99.7\\%$"], 0,
          "The $68$-$95$-$99.7$ rule."),
        q("Exponential waiting time is memoryless. If $\\lambda=1$ and no event by time $3$, $P(X>5\\mid X>3)$ equals:",
          ["$P(X>2)$", "$P(X>5)$", "$P(X>3)$"], 0,
          "Memorylessness: $P(X>s+t\\mid X>s)=P(X>t)$."),
        q("Number of successes in $20$ independent Bernoulli($0.1$) trials is modeled by:",
          ["Binomial$(20,0.1)$", "Poisson$(0.1)$", "Normal$(0,1)$"], 0,
          "Fixed $n$ independent trials with constant $p$."),
        q("Counts of rare events per hour with mean $4$ are typically modeled as:",
          ["Poisson$(4)$", "Binomial$(4,1/2)$", "Uniform$[0,4]$"], 0,
          "Poisson is the classic count model with mean $\\lambda=4$."),
        q("Normal $N(50,5^2)$. About $95\\%$ of values lie between:",
          ["$40$ and $60$", "$45$ and $55$", "$35$ and $65$"], 0,
          "Roughly $\\mu\\pm 2\\sigma=50\\pm 10$."),
        q("Binomial $n=10$, $p=0.2$. $P(X=0)$ equals:",
          ["$0.8^{10}$", "$0.2^{10}$", "$0.8$"], 0,
          "$(1-p)^n=0.8^{10}$."),
        q("Geometric $p=0.25$ (until first success). $P(X=3)$ equals:",
          ["$(0.75)^2(0.25)$", "$(0.25)^3$", "$(0.75)^3$"], 0,
          "Two failures then a success."),
        q("If $Z\\sim N(0,1)$ and $P(Z\\le z)=0.975$ approx, $z$ is about:",
          ["$1.96$", "$1.00$", "$2.58$"], 0,
          "Standard normal $97.5$th percentile ≈ $1.96$."),
    ]

    return banks


def build_stats():
    banks = {}

    banks["PS_D_CENTER_QUIZ"] = [
        q("Find the mean of the data set $2,4,6,8,10$.",
          ["$6$", "$5$", "$8$"], 0,
          "$(2+4+6+8+10)/5=6$."),
        q("Find the median of $2,5,7,8,20$.",
          ["$7$", "$8.4$", "$5$"], 0,
          "With five ordered values the median is the third, which is $7$."),
        q("Find the mode of $3,3,5,7,7,7,9$.",
          ["$7$", "$3$", "$5$"], 0,
          "$7$ appears three times, more than any other value."),
        q("Data $4,5,6,7,100$. Which measure is most pulled upward by the outlier?",
          ["The mean", "The median", "The mode"], 0,
          "Means are sensitive to extreme values; the median stays near $6$."),
        q("If each value in a data set is increased by $5$, the mean:",
          ["Increases by $5$", "Is multiplied by $5$", "Is unchanged"], 0,
          "Adding a constant shifts the mean by that constant."),
        q("If each value is multiplied by $3$, the median:",
          ["Is multiplied by $3$", "Increases by $3$", "Is unchanged"], 0,
          "Scaling multiplies all order statistics by $3$."),
        q("Weighted mean of scores $80$ and $90$ with weights $2$ and $3$ equals:",
          ["$86$", "$85$", "$84$"], 0,
          "$(2\\cdot 80+3\\cdot 90)/(2+3)=430/5=86$."),
        q("Group A ($n=10$) has mean $70$; group B ($n=30$) has mean $90$. Combined mean equals:",
          ["$85$", "$80$", "$160$"], 0,
          "$(10\\cdot 70+30\\cdot 90)/40=3400/40=85$."),
        q("For a strongly right-skewed income distribution, which is typically larger?",
          ["Mean", "Median", "They must be equal"], 0,
          "A long right tail pulls the mean above the median."),
        q("Data $1,2,2,3$. The mean equals:",
          ["$2$", "$2.5$", "$1.5$"], 0,
          "Sum $8$ over $4$ observations."),
        q("Ordered data $10,12,15,18$. The median equals:",
          ["$13.5$", "$15$", "$12$"], 0,
          "Average of the two middle values: $(12+15)/2=13.5$."),
        q("When summarizing house prices with a few mansions, prefer:",
          ["Median", "Mean", "Range"], 0,
          "Median resists the high-end outliers."),
        q("Data $5,5,5,5$. Mean and median both equal:",
          ["$5$", "$0$", "$20$"], 0,
          "All values identical."),
        q("Adding the point $100$ to $10,20,30$ changes the mean from $20$ to:",
          ["$40$", "$30$", "$25$"], 0,
          "New mean $(160)/4=40$."),
        q("Scores $60,70,80$ with equal weights. Mean equals:",
          ["$70$", "$210$", "$80$"], 0,
          "$(60+70+80)/3=70$."),
    ]

    banks["PS_D_QUANT_QUIZ"] = [
        q("Ordered data $2,4,6,8,10,12,14$. The median $Q_2$ equals:",
          ["$8$", "$7$", "$10$"], 0,
          "The fourth of seven values is $8$."),
        q("For that same set, $Q_1$ (median of lower half $2,4,6$) equals:",
          ["$4$", "$2$", "$6$"], 0,
          "Middle of the lower half is $4$."),
        q("And $Q_3$ (median of upper half $10,12,14$) equals:",
          ["$12$", "$10$", "$14$"], 0,
          "Middle of the upper half is $12$."),
        q("IQR for that set equals:",
          ["$8$", "$12$", "$4$"], 0,
          "$Q_3-Q_1=12-4=8$."),
        q("Five-number summary uses which five values?",
          ["Min, $Q_1$, median, $Q_3$, max", "Mean, median, mode, range, SD", "Min, mean, median, mode, max"], 0,
          "Classic Tukey five-number summary."),
        q("Data $1,3,5,7,9,11$. Approximate $25$th percentile (median of lower half $1,3,5$) is:",
          ["$3$", "$1$", "$5$"], 0,
          "Lower-half median is $3$."),
        q("Using $1.5\\times\\mathrm{IQR}$ with $Q_1=10$, $Q_3=22$, an observation above what is a high outlier?",
          ["$40$", "$22$", "$34$"], 0,
          "IQR $=12$; upper fence $22+1.5\\cdot 12=40$."),
        q("With fences $40$ upper as above, is $41$ an outlier?",
          ["Yes", "No", "Only if it is the maximum"], 0,
          "$41>40$, so beyond the upper fence."),
        q("Ordered $n=9$ values; the $5$th ordered value is the:",
          ["Median (50th percentile)", "First quartile", "90th percentile"], 0,
          "For odd $n$, the middle order statistic is the median."),
        q("Deciles divide ordered data into how many equal-count parts?",
          ["$10$", "$4$", "$100$"], 0,
          "Nine cut points create ten tenths."),
        q("Data $4,5,6,7,8,9,10,20$. IQR using $Q_1=5.5$, $Q_3=9.5$ equals:",
          ["$4$", "$16$", "$5.5$"], 0,
          "$9.5-5.5=4$."),
        q("Percentile rank: in ordered list of $20$ distinct scores, the $4$th smallest is at about which percentile?",
          ["$20$", "$4$", "$50$"], 0,
          "Roughly $4/20=0.20$, the $20$th percentile."),
        q("If $Q_1=12$ and $Q_3=18$, then IQR equals:",
          ["$6$", "$15$", "$30$"], 0,
          "$18-12=6$."),
        q("The second quartile $Q_2$ is identical to the:",
          ["Median", "Mean", "Mode"], 0,
          "By definition $Q_2$ is the median."),
        q("Ordered $3,6,9,12,15,18,21,24$. Median equals:",
          ["$13.5$", "$12$", "$15$"], 0,
          "Average of $12$ and $15$."),
    ]

    banks["PS_D_SPREAD_QUIZ"] = [
        q("Sample variance of data $2,4,6$ (divide by $n-1$) equals:",
          ["$4$", "$8/3$", "$2$"], 0,
          "Mean $4$; squared deviations $4+0+4=8$; $8/2=4$."),
        q("Population variance of the same three numbers (divide by $n$) equals:",
          ["$8/3$", "$4$", "$2$"], 0,
          "$8/3$ when dividing by $3$."),
        q("Sample standard deviation of $2,4,6$ equals:",
          ["$2$", "$4$", "$\\sqrt{8/3}$"], 0,
          "Square root of sample variance $4$."),
        q("Range of $3,9,12,20$ equals:",
          ["$17$", "$20$", "$9$"], 0,
          "$20-3=17$."),
        q("CV (SD/mean) for mean $50$ and SD $5$ equals:",
          ["$0.10$", "$10$", "$45$"], 0,
          "$5/50=0.10$."),
        q("z-score of $x=85$ when $\\bar x=70$ and $s=5$ equals:",
          ["$3$", "$15$", "$1.5$"], 0,
          "$(85-70)/5=3$."),
        q("A z-score of $-2$ means the value is:",
          ["Two SDs below the mean", "Two SDs above the mean", "Half the mean"], 0,
          "Sign indicates direction from the mean."),
        q("If every value is multiplied by $4$, the SD:",
          ["Is multiplied by $4$", "Increases by $4$", "Is multiplied by $16$"], 0,
          "SD scales by $|a|$ under $x\\mapsto ax+b$."),
        q("Adding $10$ to every observation changes the SD by:",
          ["$0$", "$10$", "A factor of $10$"], 0,
          "Shifts cancel in deviations from the mean."),
        q("Empirical rule: within $2$ SDs of a normal mean lies about:",
          ["$95\\%$", "$68\\%$", "$50\\%$"], 0,
          "The middle tier of $68$-$95$-$99.7$."),
        q("Data $1,1,1,1$. Sample variance equals:",
          ["$0$", "$1$", "Undefined"], 0,
          "All deviations from the mean are zero."),
        q("For sample SD, we divide the sum of squared deviations by:",
          ["$n-1$", "$n$", "$n-2$"], 0,
          "Bessel's correction for an unbiased sample variance."),
        q("If $\\bar x=100$, $s=15$, the z-score of $70$ equals:",
          ["$-2$", "$2$", "$-30$"], 0,
          "$(70-100)/15=-2$."),
        q("Variance is in what units relative to the data?",
          ["Squared units of the data", "Same units as the data", "Unitless always"], 0,
          "Variance squares deviations; SD restores original units."),
        q("Sample variance of $5,7$ equals:",
          ["$2$", "$1$", "$4$"], 0,
          "Mean $6$; squared deviations $1+1=2$; divide by $1$."),
    ]

    banks["PS_D_PLOTS_QUIZ"] = [
        q("A histogram with a long right tail is described as:",
          ["Right-skewed", "Left-skewed", "Symmetric"], 0,
          "The elongated tail points to the right."),
        q("On a box plot, the box spans from:",
          ["$Q_1$ to $Q_3$", "Min to max", "Mean ± SD"], 0,
          "The box marks the interquartile range."),
        q("Box-plot whiskers typically extend to:",
          ["The most extreme non-outlier points within the fences", "Always the min and max", "The mean ± 2 SD"], 0,
          "Standard construction stops whiskers at adjacent non-outliers."),
        q("A stem-and-leaf plot of $23,25,31$ with stem $=$ tens shows leaf digits:",
          ["$3,5$ on stem $2$ and $1$ on stem $3$", "Only $2$ and $3$", "$23,25,31$ as leaves"], 0,
          "Leaves are the units digits."),
        q("A scatterplot is primarily used to display:",
          ["Relationship between two quantitative variables", "Counts in categories", "A single variable's five-number summary"], 0,
          "Each point is an $(x,y)$ pair."),
        q("A histogram with two clear peaks is called:",
          ["Bimodal", "Uniform", "Bell-shaped"], 0,
          "Two modes appear as two peaks."),
        q("For categorical counts, a natural display is a:",
          ["Bar chart", "Histogram", "Box plot"], 0,
          "Bars for categories; histograms are for quantitative bins."),
        q("A point plotted beyond a box-plot fence is flagged as:",
          ["An outlier", "The median", "Q1"], 0,
          "Points outside fences are marked separately."),
        q("If a box plot's median line sits near $Q_1$, the distribution is often:",
          ["Right-skewed", "Left-skewed", "Perfectly symmetric"], 0,
          "More spread in the upper half suggests a right skew."),
        q("Reading a histogram: tallest bar indicates:",
          ["The modal class (most frequent bin)", "The mean bin", "The range"], 0,
          "Mode corresponds to highest frequency."),
        q("Compared with a histogram, a stem-and-leaf plot additionally:",
          ["Preserves individual data values", "Shows time order", "Removes all outliers automatically"], 0,
          "Leaves retain the actual digits."),
        q("A flat histogram across equal-width bins suggests a:",
          ["Roughly uniform distribution", "Strong right skew", "Bimodal pattern"], 0,
          "Similar heights mean similar frequencies."),
        q("Side-by-side box plots are useful to compare:",
          ["Distributions of a quantitative variable across groups", "Only means", "Only sample sizes"], 0,
          "Each box summarizes one group's spread and center."),
        q("A scatterplot with points tightly following an upward line suggests:",
          ["Strong positive linear association", "No association", "Strong negative association"], 0,
          "Tight upward trend means strong positive linear relationship."),
        q("Which plot alone cannot show skewness of one quantitative variable?",
          ["A pie chart of unrelated categories", "A histogram", "A box plot"], 0,
          "Pie charts are for parts of a whole, not distribution shape."),
    ]

    banks["PS_H_FRAMEWORK_QUIZ"] = [
        q("Testing whether a coin is fair: appropriate $H_0$ is:",
          ["$p=0.5$", "$p\\ne 0.5$", "$p>0.5$"], 0,
          "Null states the status-quo fair-coin value."),
        q("For that coin, a two-sided alternative is:",
          ["$p\\ne 0.5$", "$p=0.5$", "$p>0.7$"], 0,
          "Two-sided means departure in either direction."),
        q("The significance level $\\alpha$ is:",
          ["The probability of Type I error under $H_0$", "The power of the test", "The p-value"], 0,
          "$\\alpha=P(\\text{reject }H_0\\mid H_0\\text{ true})$."),
        q("Rejecting $H_0$ means:",
          ["The data are sufficiently inconsistent with $H_0$ at level $\\alpha$", "$H_0$ is proved false with certainty", "$H_a$ has probability $1$"], 0,
          "Rejection is a decision rule, not absolute proof."),
        q("Why do we not say we \"accept $H_0$\"?",
          ["Failure to reject does not prove $H_0$ true", "Because $H_0$ is always false", "Because $\\alpha$ must be $0$"], 0,
          "Lack of evidence against $H_0$ is not confirmation."),
        q("Choose $\\alpha$:",
          ["Before looking at the data", "After computing the p-value", "Only if the test rejects"], 0,
          "Pre-specifying $\\alpha$ avoids data snooping."),
        q("One-tailed test for \"new drug increases mean response\" uses $H_a$:",
          ["$\\mu>\\mu_0$", "$\\mu\\ne\\mu_0$", "$\\mu=\\mu_0$"], 0,
          "The research claim is a one-sided increase."),
        q("A test statistic measures:",
          ["How far the estimate sits from the null value, in SE units", "The prior probability of $H_0$", "Always the sample size only"], 0,
          "Standardized distance under $H_0$."),
        q("If $\\alpha=0.01$ instead of $0.05$, rejecting $H_0$ becomes:",
          ["Harder (need stronger evidence)", "Easier", "Impossible"], 0,
          "Smaller $\\alpha$ means a stricter rejection threshold."),
        q("Null hypothesis about a mean is typically written with:",
          ["Equality, e.g. $\\mu=\\mu_0$", "Only $\\mu>\\mu_0$", "Only $\\mu\\ne\\mu_0$"], 0,
          "$H_0$ pins down a specific null parameter value."),
        q("In \"test $H_0:\\mu=10$ vs $H_a:\\mu<10$\", the test is:",
          ["Left-tailed", "Right-tailed", "Two-tailed"], 0,
          "Alternative points to smaller values."),
        q("Statistical significance at level $\\alpha$ means:",
          ["The p-value is $\\le\\alpha$", "The effect is large in practice", "$H_0$ is true"], 0,
          "Compare p-value to the prechosen $\\alpha$."),
        q("The parameter symbol in $H_0:p=0.2$ refers to:",
          ["A population proportion", "A sample proportion", "A p-value"], 0,
          "Hypotheses are about population parameters."),
        q("If we reject $H_0$ at $\\alpha=0.05$, then necessarily:",
          ["We would also reject at any larger $\\alpha$ (e.g. $0.10$)", "We reject at $\\alpha=0.01$", "The Type II error rate is $0$"], 0,
          "Larger $\\alpha$ makes rejection easier."),
        q("A hypothesis test's conclusion is based on:",
          ["Sample data summarized by a test statistic / p-value", "Census of the entire population always", "Only the value of $\\alpha$ with no data"], 0,
          "Inference uses sample evidence under a model."),
    ]

    banks["PS_H_TESTS_QUIZ"] = [
        q("z-test: $\\bar x=52$, $\\mu_0=50$, $\\sigma=4$, $n=16$. Test statistic equals:",
          ["$2$", "$0.5$", "$8$"], 0,
          "$(52-50)/(4/\\sqrt{16})=2/1=2$."),
        q("For a one-sample t-test with $n=20$, degrees of freedom equal:",
          ["$19$", "$20$", "$18$"], 0,
          "df $=n-1$."),
        q("Use t instead of z for a mean when:",
          ["$\\sigma$ is unknown and $s$ estimates it", "$\\sigma$ is known", "$n=2$ only"], 0,
          "Unknown population SD leads to the t procedure."),
        q("One-proportion z: $\\hat p=0.42$, $p_0=0.40$, $n=100$. SE under $H_0$ is:",
          ["$\\sqrt{0.40\\cdot 0.60/100}$", "$\\sqrt{0.42\\cdot 0.58/100}$", "$0.40/10$"], 0,
          "Null SE uses $p_0$, not $\\hat p$."),
        q("With that SE $=\\sqrt{0.0024}=0.049\\approx 0.05$, $z\\approx(0.42-0.40)/0.05$ equals about:",
          ["$0.4$", "$2$", "$4$"], 0,
          "$0.02/0.05=0.4$."),
        q("Critical value for two-sided $z$-test at $\\alpha=0.05$ is about:",
          ["$\\pm 1.96$", "$\\pm 1.645$", "$\\pm 2.576$"], 0,
          "Standard normal $2.5\\%$ tails each side."),
        q("Right-tailed $z$-test at $\\alpha=0.05$ rejects when $z$ exceeds about:",
          ["$1.645$", "$1.96$", "$0.05$"], 0,
          "Upper $5\\%$ point of $N(0,1)$."),
        q("$\\bar x=18$, $\\mu_0=20$, $s=5$, $n=25$. t-statistic equals:",
          ["$-2$", "$2$", "$-0.4$"], 0,
          "$(18-20)/(5/5)=-2/1=-2$."),
        q("A $95\\%$ CI for $\\mu$ that excludes $\\mu_0$ corresponds to:",
          ["Rejecting $H_0:\\mu=\\mu_0$ at $\\alpha=0.05$ (two-sided)", "Accepting $H_0$ at $\\alpha=0.05$", "A one-sided test only"], 0,
          "CI/test duality for two-sided level $0.05$."),
        q("Known $\\sigma=10$, $n=100$, $\\bar x=103$, $H_0:\\mu=100$. $z$ equals:",
          ["$3$", "$0.3$", "$30$"], 0,
          "$(103-100)/(10/10)=3$."),
        q("Proportion test needs $np_0$ and $n(1-p_0)$ both at least about $10$ to:",
          ["Justify the normal approximation", "Make $\\alpha=0$", "Guarantee power $1$"], 0,
          "Success-failure condition for the z-approximation."),
        q("If $z=1.0$ for $H_0:\\mu=\\mu_0$ two-sided $\\alpha=0.05$, decision is:",
          ["Fail to reject $H_0$", "Reject $H_0$", "Accept $H_a$ with certainty"], 0,
          "$|1.0|<1.96$, not in the rejection region."),
        q("t critical value for two-sided $\\alpha=0.05$ with large df is near:",
          ["$1.96$", "$1.00$", "$0.05$"], 0,
          "t approaches the z critical value as df grows."),
        q("Test statistic $(\\hat p-p_0)/\\sqrt{p_0(1-p_0)/n}$ is for:",
          ["One-proportion z-test", "Two-sample t-test for means", "Chi-square goodness of fit only"], 0,
          "Standardized sample proportion under $H_0$."),
        q("$n=9$, $s=6$, $\\bar x=50$, $\\mu_0=47$. SE $=s/\\sqrt{n}$ equals:",
          ["$2$", "$6$", "$3$"], 0,
          "$6/3=2$."),
    ]

    banks["PS_H_PVAL_QUIZ"] = [
        q("A p-value is best described as:",
          ["$P(\\text{data as or more extreme}\\mid H_0\\text{ true})$", "$P(H_0\\text{ is true}\\mid\\text{data})$", "Always equal to $\\alpha$"], 0,
          "Tail probability of the test statistic under $H_0$."),
        q("For right-tailed $z=1.645$, the p-value is about:",
          ["$0.05$", "$0.10$", "$0.025$"], 0,
          "Upper-tail probability beyond $1.645$ is ≈ $0.05$."),
        q("Two-sided p-value when one-sided tail is $0.03$ equals:",
          ["$0.06$", "$0.03$", "$0.015$"], 0,
          "Double a one-sided p-value for a symmetric two-sided test."),
        q("If p-value $=0.02$ and $\\alpha=0.05$, then:",
          ["Reject $H_0$", "Fail to reject $H_0$", "Accept $H_0$"], 0,
          "$0.02\\le 0.05$ triggers rejection."),
        q("If p-value $=0.08$ and $\\alpha=0.05$, then:",
          ["Fail to reject $H_0$", "Reject $H_0$", "$H_0$ is true"], 0,
          "$0.08>0.05$."),
        q("A p-value is NOT:",
          ["The probability that $H_0$ is true", "A tail probability under $H_0$", "Comparable to $\\alpha$ for a decision"], 0,
          "It does not equal $P(H_0\\mid\\text{data})$."),
        q("Larger samples with the same effect size tend to make p-values:",
          ["Smaller", "Larger", "Unchanged always"], 0,
          "SE shrinks, so the test statistic grows."),
        q("For left-tailed $z=-2.0$, p-value ≈:",
          ["$0.023$", "$0.05$", "$0.977$"], 0,
          "$\\Phi(-2)\\approx 0.0228$."),
        q("Borderline: p-value $=0.049$ at $\\alpha=0.05$ means:",
          ["Reject $H_0$, but the evidence is barely past the cutoff", "Fail to reject", "Proof of $H_a$"], 0,
          "Just under $\\alpha$, so reject cautiously."),
        q("If $|z|=2.58$ two-sided, p-value is about:",
          ["$0.01$", "$0.05$", "$0.10$"], 0,
          "Two tails beyond ±$2.58$ total ≈ $0.01$."),
        q("Reporting only \"p < 0.05\" without the actual p-value:",
          ["Hides how strong the evidence is", "Is required by theory", "Makes $\\alpha$ unnecessary"], 0,
          "Exact p-values communicate strength better."),
        q("Under $H_0$, a correctly computed p-value is:",
          ["Uniformly distributed on $(0,1)$ (continuous case)", "Always near $0$", "Always near $1$"], 0,
          "Classic result for continuous test statistics."),
        q("One-sided p-value $0.04$ corresponds to two-sided p-value:",
          ["$0.08$", "$0.04$", "$0.02$"], 0,
          "Double it for the two-sided test."),
        q("A very small p-value means:",
          ["Data are unusual if $H_0$ were true", "$H_0$ has prior probability near $0$", "Type II error occurred"], 0,
          "It measures extremity under the null, not a prior."),
        q("If $z=0$, the two-sided p-value equals:",
          ["$1$", "$0$", "$0.5$"], 0,
          "No extremity; both tails cover the whole distribution."),
    ]

    banks["PS_H_ERRORS_QUIZ"] = [
        q("Type I error means:",
          ["Rejecting $H_0$ when $H_0$ is true", "Failing to reject $H_0$ when $H_a$ is true", "Using the wrong sample size"], 0,
          "False positive rejection of a true null."),
        q("Type II error means:",
          ["Failing to reject $H_0$ when $H_a$ is true", "Rejecting a true $H_0$", "Setting $\\alpha=0$"], 0,
          "Missed detection of a real effect."),
        q("$\\alpha$ equals the probability of:",
          ["Type I error", "Type II error", "Power"], 0,
          "Significance level is the Type I rate."),
        q("$\\beta$ denotes the probability of:",
          ["Type II error", "Type I error", "Rejecting $H_0$ correctly"], 0,
          "Standard notation for Type II risk."),
        q("Power equals:",
          ["$1-\\beta$", "$\\alpha$", "$\\beta$"], 0,
          "Power is the chance of correctly rejecting a false $H_0$."),
        q("Increasing sample size, other things fixed, typically:",
          ["Increases power", "Increases $\\beta$", "Increases Type I error above $\\alpha$"], 0,
          "Larger $n$ shrinks SE and separates hypotheses."),
        q("Larger true effect size typically:",
          ["Increases power", "Decreases power", "Changes $\\alpha$ automatically"], 0,
          "Easier to detect bigger departures from $H_0$."),
        q("Decreasing $\\alpha$ (stricter test), with other factors fixed, tends to:",
          ["Increase $\\beta$ (reduce power)", "Decrease $\\beta$", "Leave power unchanged"], 0,
          "Harder rejection means more Type II errors."),
        q("Drug trial: $H_0:$ no benefit. Approving a useless drug is:",
          ["Type I error", "Type II error", "Correct decision"], 0,
          "Rejecting a true null of no benefit."),
        q("Failing to detect a truly effective drug is:",
          ["Type II error", "Type I error", "Power"], 0,
          "Missed rejection when $H_a$ holds."),
        q("If power is $0.80$, then $\\beta$ equals:",
          ["$0.20$", "$0.80$", "$0.05$"], 0,
          "$\\beta=1-\\text{power}$."),
        q("Trade-off: making Type I errors rarer generally makes Type II errors:",
          ["More common (unless $n$ increases)", "Impossible", "Exactly equal to $\\alpha$"], 0,
          "Stricter thresholds miss more real effects."),
        q("Holding $\\alpha$ and effect size fixed, doubling $n$ usually:",
          ["Raises power", "Raises $\\alpha$", "Forces $\\beta=1$"], 0,
          "More data improves detection ability."),
        q("Power is computed under:",
          ["A specific alternative (effect size)", "Only $H_0$", "Only $\\alpha=0$"], 0,
          "Need a concrete $H_a$ value to evaluate power."),
        q("If $\\alpha=0.05$ and the null is true, long-run rejection rate is:",
          ["$5\\%$", "$95\\%$", "$0\\%$"], 0,
          "That is the definition of Type I error rate."),
    ]

    banks["PS_R_CORR_QUIZ"] = [
        q("The correlation coefficient $r$ always lies in:",
          ["$[-1,1]$", "$[0,1]$", "$(-\\infty,\\infty)$"], 0,
          "By Cauchy–Schwarz / definition of Pearson $r$."),
        q("If $r=0.9$, the linear association is:",
          ["Strong and positive", "Strong and negative", "Weak"], 0,
          "Near $+1$ means tight upward linear trend."),
        q("If $r=-0.2$, then $r^2$ equals:",
          ["$0.04$", "$-0.04$", "$0.2$"], 0,
          "$(-0.2)^2=0.04$."),
        q("$r^2=0.64$ means about what fraction of $y$-variance is linearly explained by $x$?",
          ["$64\\%$", "$0.64\\%$", "$36\\%$"], 0,
          "$r^2$ is the coefficient of determination."),
        q("Changing units from meters to centimeters for $x$ changes $r$ by:",
          ["$0$ (unchanged)", "A factor of $100$", "Adding $100$"], 0,
          "$r$ is invariant under positive linear rescaling."),
        q("A strong curved relationship can have $r$ near:",
          ["$0$", "$1$ always", "$-1$ always"], 0,
          "Pearson $r$ only captures linear association."),
        q("An outlier far from the cloud can:",
          ["Change $r$ dramatically", "Never affect $r$", "Only change the median"], 0,
          "Pearson $r$ is outlier-sensitive."),
        q("If the least-squares slope is negative, then $r$ is:",
          ["Negative", "Positive", "Zero always"], 0,
          "Sign of $r$ matches sign of the slope."),
        q("Perfect negative linear association has $r$ equal to:",
          ["$-1$", "$0$", "$1$"], 0,
          "All points on a downward line."),
        q("If $r=0$, then necessarily:",
          ["No linear association (nonlinear patterns still possible)", "X and Y are independent", "The scatter is empty"], 0,
          "Zero correlation ≠ full independence."),
        q("Both $x$ and $y$ standardized to z-scores; their correlation equals:",
          ["The same $r$ as before", "$0$", "$1$"], 0,
          "Standardizing is a linear rescaling."),
        q("Which $r$ indicates the strongest linear association?",
          ["$-0.95$", "$0.50$", "$0.10$"], 0,
          "Strength uses $|r|$; $0.95$ beats $0.50$."),
        q("If $r=0.5$, then $r^2$ equals:",
          ["$0.25$", "$0.5$", "$0.75$"], 0,
          "$0.5^2=0.25$."),
        q("Correlation has units:",
          ["None (unitless)", "Same as $y$", "Same as $x\\cdot y$"], 0,
          "Standardization removes units."),
        q("Swapping the roles of $x$ and $y$ changes $r$ to:",
          ["The same value", "Its reciprocal", "Its negative"], 0,
          "Pearson $r$ is symmetric in $x$ and $y$."),
    ]

    banks["PS_R_ASSOC_QUIZ"] = [
        q("High correlation between ice cream sales and drowning rates most likely reflects:",
          ["A lurking variable such as temperature / season", "Ice cream causing drowning", "Drowning causing ice cream sales"], 0,
          "Classic confounding by weather."),
        q("Correlation alone does not establish:",
          ["Causation", "Association strength", "Direction of a linear trend"], 0,
          "Causal claims need design, not $r$ alone."),
        q("A randomized experiment differs from an observational study mainly by:",
          ["Random assignment of treatments", "Larger sample size always", "Using only qualitative variables"], 0,
          "Randomization balances confounders."),
        q("Simpson's paradox occurs when:",
          ["A trend reverses after aggregating or disaggregating groups", "$r$ equals $1$", "All lurking variables vanish"], 0,
          "Group-wise associations disagree with the aggregate."),
        q("Predicting $y$ far beyond the observed $x$-range is:",
          ["Extrapolation (risky)", "Always accurate if $r$ is large", "Called interpolation"], 0,
          "The fitted pattern may fail outside the data."),
        q("Ecological correlation means:",
          ["Correlation based on group averages, which can mislead about individuals", "Correlation that proves causation", "Correlation of residuals only"], 0,
          "Aggregates can inflate apparent association."),
        q("Describe scatter: points rise left-to-right in a straight band. Direction/form/strength:",
          ["Positive, linear, and strength depends on tightness", "Negative, curved, weak", "No direction, random form"], 0,
          "Use those three vocabulary pieces."),
        q("A confounder is a variable that:",
          ["Influences both explanatory and response, distorting association", "Is equal to the residual", "Must be the response"], 0,
          "Confounding muddies causal interpretation."),
        q("Observational study can show association but struggles to show:",
          ["Causal effect", "Sample mean", "Correlation sign"], 0,
          "Without assignment, alternatives remain plausible."),
        q("\"Association\" is a broader term than \"correlation\" because:",
          ["Association includes nonlinear relationships; correlation often means Pearson $r$", "Association requires causation", "Correlation ignores scatterplots"], 0,
          "Not every association is linear."),
        q("If a lurking variable drives both $x$ and $y$, the $x$–$y$ correlation may be:",
          ["Spurious for causal claims", "Proof of causation", "Always zero"], 0,
          "Shared cause creates noncausal association."),
        q("Randomly assigning fertilizer levels to plots helps:",
          ["Reduce confounding of treatment effects", "Guarantee $r=1$", "Eliminate all sampling error"], 0,
          "Randomization is the causal design tool."),
        q("Extrapolating a human-height vs age line to age $200$ years is problematic because:",
          ["It leaves the range where the linear pattern was fit", "$r$ becomes undefined", "Age is categorical"], 0,
          "Far extrapolation is unjustified."),
        q("A scatterplot description should mention:",
          ["Direction, form, and strength (and outliers)", "Only the mean of $x$", "Only sample size"], 0,
          "Standard residual/association vocabulary."),
        q("Hospital survival rates look worse at hospital A overall, but better in each severity class. This pattern is:",
          ["Simpson's paradox", "Perfect negative correlation", "A randomized block with $r=0$"], 0,
          "Aggregate reversal versus subgroup trends."),
    ]

    banks["PS_R_FIT_QUIZ"] = [
        q("Given $r=0.8$, $s_y=10$, $s_x=4$, slope $b=r s_y/s_x$ equals:",
          ["$2$", "$0.32$", "$20$"], 0,
          "$0.8\\cdot 10/4=2$."),
        q("With $\\bar x=5$, $\\bar y=20$, $b=2$, intercept $a=\\bar y-b\\bar x$ equals:",
          ["$10$", "$15$", "$30$"], 0,
          "$20-2\\cdot 5=10$."),
        q("Using $\\hat y=10+2x$, predict at $x=7$:",
          ["$24$", "$14$", "$10$"], 0,
          "$10+14=24$."),
        q("The least-squares line always passes through:",
          ["$(\\bar x,\\bar y)$", "$(0,0)$", "$(1,r)$"], 0,
          "Follows from the normal equations / intercept formula."),
        q("Slope $b=3$ means that when $x$ increases by $1$, $\\hat y$:",
          ["Increases by $3$ on average", "Increases by $1$", "Is multiplied by $3$"], 0,
          "Slope is the predicted change per unit $x$."),
        q("Least squares minimizes:",
          ["Sum of squared residuals", "Sum of absolute residuals only", "The correlation $r$"], 0,
          "That is the defining criterion."),
        q("If $r=-0.6$, $s_y=5$, $s_x=2$, then $b$ equals:",
          ["$-1.5$", "$1.5$", "$-0.24$"], 0,
          "$-0.6\\cdot 5/2=-1.5$."),
        q("Influential points are especially dangerous when they have:",
          ["High leverage (extreme $x$) and large residual", "Average $x$ and tiny residual", "Only large $n$"], 0,
          "Leverage × discrepancy drives influence."),
        q("$\\bar x=10$, $\\bar y=50$, $b=-2$. Then $a$ equals:",
          ["$70$", "$30$", "$-20$"], 0,
          "$50-(-2)\\cdot 10=70$."),
        q("Prediction $\\hat y=a+bx$ at $x=\\bar x$ yields:",
          ["$\\bar y$", "$0$", "$a$"], 0,
          "The line through the centroid."),
        q("If $s_x$ doubles and $r,s_y$ fixed, the slope $b$:",
          ["Halves", "Doubles", "Is unchanged"], 0,
          "$b\\propto 1/s_x$."),
        q("Residual for observation $(x,y)$ is:",
          ["$y-\\hat y$", "$\\hat y-x$", "$y-\\bar y$"], 0,
          "Observed minus fitted."),
        q("A point with extreme $x$ but lying close to the line has:",
          ["High leverage but may not be influential", "Zero leverage", "Undefined residual"], 0,
          "Leverage is about $x$-extremity; influence needs pull on the fit."),
        q("For $\\hat y=4-0.5x$, when $x$ increases by $4$, $\\hat y$ changes by:",
          ["$-2$", "$2$", "$-0.5$"], 0,
          "$b\\cdot 4=-2$."),
        q("If $r=0$, the least-squares slope equals:",
          ["$0$", "$1$", "$s_y/s_x$"], 0,
          "$b=r s_y/s_x=0$."),
    ]

    banks["PS_R_RESID_QUIZ"] = [
        q("Fitted $\\hat y=10$, observed $y=13$. Residual equals:",
          ["$3$", "$-3$", "$23$"], 0,
          "$y-\\hat y=13-10=3$."),
        q("For a least-squares line, the residuals sum to:",
          ["$0$", "$1$", "$n$"], 0,
          "Normal equation implies $\\sum(y_i-\\hat y_i)=0$."),
        q("A residual plot showing a clear U-shape suggests:",
          ["Nonlinear relationship; linear model inadequate", "Perfect linear fit", "Constant variance only"], 0,
          "Curvature in residuals flags wrong form."),
        q("Fan-shaped residual plot (spread growing with $\\hat y$) indicates:",
          ["Non-constant variance (heteroscedasticity)", "Zero correlation", "No outliers ever"], 0,
          "Variance should look roughly stable for simple LS assumptions."),
        q("High-leverage points have unusual:",
          ["$x$-values", "$y$-values only", "Residuals equal to $r$"], 0,
          "Leverage measures extremity in the predictor space."),
        q("An influential point is one that:",
          ["Substantially changes the fitted line if removed", "Always has residual $0$", "Must be the mean point"], 0,
          "Influence = impact on estimates."),
        q("If $y=8$ and $\\hat y=11$, residual equals:",
          ["$-3$", "$3$", "$19$"], 0,
          "$8-11=-3$."),
        q("Standard error of the estimate $s_e$ measures:",
          ["Typical size of residuals about the line", "The correlation $r$", "Only the slope"], 0,
          "Residual SD summary."),
        q("Random scatter in a residual plot with no pattern supports:",
          ["A linear model being reasonable", "That $r=0$", "That extrapolation is safe"], 0,
          "Form assumption looks okay."),
        q("A point with large residual but average $x$ is:",
          ["An outlier in $y$ (vertical outlier)", "High leverage by definition", "Never influential"], 0,
          "Unusual response at typical $x$."),
        q("If residuals are $2,-1,-1$, their sum is:",
          ["$0$", "$2$", "$-1$"], 0,
          "$2-1-1=0$, as required."),
        q("Curvature remaining after a linear fit means you should consider:",
          ["A nonlinear model or transform", "Deleting $\\bar x$", "Setting $r=1$"], 0,
          "Linear residual structure is violated."),
        q("Leverage focuses on the:",
          ["Explanatory-variable extremity", "Sign of $r$ only", "Value of $\\alpha$"], 0,
          "Hat-matrix / $x$-distance idea."),
        q("Predicted $12$, observed $12$. Residual equals:",
          ["$0$", "$12$", "$1$"], 0,
          "Perfect fit for that point."),
        q("A linear model is inappropriate when residual plots show:",
          ["Systematic curves or changing spread", "Only a horizontal band of noise", "Residuals summing to zero"], 0,
          "Patterns contradict the linear equal-spread story."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "psProbRvQuizzes.js",
        "/** Study-guide quiz banks for the Probability Basics and Random Variables guides — 15 MCQs per section. */",
        build_prob_rv(),
    )
    emit_file(
        OUT / "psStatsQuizzes.js",
        "/** Study-guide quiz banks for the Descriptive Statistics, Hypothesis Testing and Regression guides — 15 MCQs per section. */",
        build_stats(),
    )
