# -*- coding: utf-8 -*-
"""Emit laVectorsMatricesQuizzes.js and laSystemsEigenQuizzes.js."""
from _quiz_emit import q, emit_file, OUT


def build_vectors_matrices():
    banks = {}

    banks["LA_V_INTRO_QUIZ"] = [
        q("What is the magnitude of $\\mathbf{v}=\\langle 3,-4\\rangle$?",
          ["$5$", "$7$", "$\\sqrt{7}$"], 0,
          "The magnitude is $\\sqrt{3^2+(-4)^2}=\\sqrt{25}=5$."),
        q("The second component of $\\mathbf{u}=(5,-2,9)$ is:",
          ["$-2$", "$5$", "$9$"], 0,
          "Components are listed in order; the second entry is $-2$."),
        q("A unit vector in the direction of $\\mathbf{w}=(0,8)$ is:",
          ["$(0,1)$", "$(0,8)$", "$(0,1/8)$"], 0,
          "$\\|\\mathbf{w}\\|=8$, so $\\mathbf{w}/8=(0,1)$."),
        q("Distance between $P=(1,2,2)$ and $Q=(4,6,2)$ equals:",
          ["$5$", "$3$", "$7$"], 0,
          "$\\sqrt{(4-1)^2+(6-2)^2+(2-2)^2}=\\sqrt{9+16}=5$."),
        q("If $\\mathbf{x}=(2,1,-2)$, then $\\|\\mathbf{x}\\|^2$ equals:",
          ["$9$", "$3$", "$5$"], 0,
          "$2^2+1^2+(-2)^2=4+1+4=9$."),
        q("The zero vector in $\\mathbb{R}^3$ is:",
          ["$(0,0,0)$", "$(0,0)$", "$(1,1,1)$"], 0,
          "Every component must be zero in three dimensions."),
        q("Two vectors $\\mathbf{a}=(1,4)$ and $\\mathbf{b}=(1,4)$ are equal because:",
          ["Matching components in the same order", "Equal magnitudes only", "They are orthogonal"], 0,
          "Vector equality means corresponding components agree."),
        q("The position vector of the point $(-3,5)$ is:",
          ["$\\langle -3,5\\rangle$", "$\\langle 3,-5\\rangle$", "$\\langle -3,-5\\rangle$"], 0,
          "The position vector runs from the origin to the point."),
        q("A unit vector parallel to $\\mathbf{v}=\\langle 6,-8\\rangle$ is:",
          ["$\\langle 3/5,-4/5\\rangle$", "$\\langle 6,-8\\rangle$", "$\\langle 3/4,-1\\rangle$"], 0,
          "$\\|\\mathbf{v}\\|=10$, so divide by $10$ to get $\\langle 3/5,-4/5\\rangle$."),
        q("If $\\|\\mathbf{u}\\|=4$ and $\\mathbf{u}$ points in the same direction as $\\langle 1,0\\rangle$, then $\\mathbf{u}$ is:",
          ["$\\langle 4,0\\rangle$", "$\\langle 1,0\\rangle$", "$\\langle 0,4\\rangle$"], 0,
          "Scale the unit vector $\\langle 1,0\\rangle$ by length $4$."),
        q("Distance from $(0,0,0)$ to $(2,3,6)$ equals:",
          ["$7$", "$11$", "$\\sqrt{11}$"], 0,
          "$\\sqrt{4+9+36}=\\sqrt{49}=7$."),
        q("If $\\mathbf{p}=(a,b)$ and $\\mathbf{q}=(c,d)$ are equal, then necessarily:",
          ["$a=c$ and $b=d$", "$a+b=c+d$ only", "$\\|\\mathbf{p}\\|=\\|\\mathbf{q}\\|$ only"], 0,
          "Equality requires both components to match."),
        q("The geometric length of $\\mathbf{r}=\\langle 1,2,2\\rangle$ is:",
          ["$3$", "$5$", "$\\sqrt{5}$"], 0,
          "$\\sqrt{1+4+4}=3$."),
        q("Which vector has magnitude $13$?",
          ["$\\langle 5,12\\rangle$", "$\\langle 5,10\\rangle$", "$\\langle 3,4\\rangle$"], 0,
          "$\\sqrt{25+144}=13$."),
        q("In $\\mathbb{R}^2$, the tip of the position vector $\\langle -1,4\\rangle$ is the point:",
          ["$(-1,4)$", "$(1,-4)$", "$(4,-1)$"], 0,
          "The tip is the point with those coordinates."),
    ]

    banks["LA_V_OPS_QUIZ"] = [
        q("Compute $\\langle 2,-1\\rangle+\\langle 3,4\\rangle$.",
          ["$\\langle 5,3\\rangle$", "$\\langle 5,5\\rangle$", "$\\langle -1,5\\rangle$"], 0,
          "Add components: $2+3=5$ and $-1+4=3$."),
        q("Compute $3\\langle 1,-2,4\\rangle$.",
          ["$\\langle 3,-6,12\\rangle$", "$\\langle 3,-2,4\\rangle$", "$\\langle 1,-6,12\\rangle$"], 0,
          "Multiply each component by $3$."),
        q("The dot product $\\langle 1,2,3\\rangle\\cdot\\langle 4,-1,0\\rangle$ equals:",
          ["$2$", "$4$", "$-2$"], 0,
          "$1\\cdot 4+2\\cdot(-1)+3\\cdot 0=4-2=2$."),
        q("Are $\\mathbf{u}=\\langle 2,-1\\rangle$ and $\\mathbf{v}=\\langle 1,2\\rangle$ orthogonal?",
          ["Yes, because $\\mathbf{u}\\cdot\\mathbf{v}=0$", "No, because $\\mathbf{u}\\cdot\\mathbf{v}=2$", "Yes, because they have equal length"], 0,
          "$2\\cdot 1+(-1)\\cdot 2=0$, so they are orthogonal."),
        q("If $\\mathbf{a}\\cdot\\mathbf{b}=6$, $\\|\\mathbf{a}\\|=3$, $\\|\\mathbf{b}\\|=4$, then $\\cos\\theta$ equals:",
          ["$1/2$", "$1/2\\sqrt{2}$", "$2$"], 0,
          "$\\cos\\theta=(\\mathbf{a}\\cdot\\mathbf{b})/(\\|\\mathbf{a}\\|\\|\\mathbf{b}\\|)=6/12=1/2$."),
        q("The projection $\\operatorname{proj}_{\\mathbf{u}}\\mathbf{v}$ for $\\mathbf{u}=\\langle 1,0\\rangle$, $\\mathbf{v}=\\langle 3,4\\rangle$ is:",
          ["$\\langle 3,0\\rangle$", "$\\langle 3,4\\rangle$", "$\\langle 0,4\\rangle$"], 0,
          "$(\\mathbf{v}\\cdot\\mathbf{u}/\\|\\mathbf{u}\\|^2)\\mathbf{u}=3\\langle 1,0\\rangle$."),
        q("$\\mathbf{i}\\times\\mathbf{j}$ equals:",
          ["$\\mathbf{k}$", "$-\\mathbf{k}$", "$\\mathbf{0}$"], 0,
          "Right-hand rule: $\\mathbf{i}\\times\\mathbf{j}=\\mathbf{k}$."),
        q("Compute $\\langle 1,2,0\\rangle\\times\\langle 0,3,4\\rangle$.",
          ["$\\langle 8,-4,3\\rangle$", "$\\langle 8,4,-3\\rangle$", "$\\langle -8,4,3\\rangle$"], 0,
          "Determinant formula yields $\\langle 8,-4,3\\rangle$."),
        q("Area of the parallelogram spanned by $\\langle 1,0,0\\rangle$ and $\\langle 1,1,0\\rangle$ is:",
          ["$1$", "$\\sqrt{2}$", "$2$"], 0,
          "Cross product is $\\langle 0,0,1\\rangle$ with magnitude $1$."),
        q("The scalar triple product $\\mathbf{a}\\cdot(\\mathbf{b}\\times\\mathbf{c})$ for $\\mathbf{a}=\\langle 1,0,0\\rangle$, $\\mathbf{b}=\\langle 0,1,0\\rangle$, $\\mathbf{c}=\\langle 0,0,1\\rangle$ equals:",
          ["$1$", "$0$", "$-1$"], 0,
          "$\\mathbf{b}\\times\\mathbf{c}=\\mathbf{i}$ and $\\mathbf{a}\\cdot\\mathbf{i}=1$."),
        q("Compute $\\langle 4,1\\rangle-\\langle 1,-3\\rangle$.",
          ["$\\langle 3,4\\rangle$", "$\\langle 5,-2\\rangle$", "$\\langle 3,-4\\rangle$"], 0,
          "$4-1=3$ and $1-(-3)=4$."),
        q("If $\\mathbf{u}\\cdot\\mathbf{v}=-\\|\\mathbf{u}\\|\\|\\mathbf{v}\\|$, the angle between them is:",
          ["$\\pi$", "$\\pi/2$", "$0$"], 0,
          "$\\cos\\theta=-1$ means the vectors are opposite."),
        q("For $\\mathbf{u}=\\langle 2,2\\rangle$ and $\\mathbf{v}=\\langle 1,0\\rangle$, $\\operatorname{proj}_{\\mathbf{u}}\\mathbf{v}$ equals:",
          ["$\\langle 1/2,1/2\\rangle$", "$\\langle 1,1\\rangle$", "$\\langle 2,0\\rangle$"], 0,
          "$(\\mathbf{v}\\cdot\\mathbf{u}/\\|\\mathbf{u}\\|^2)\\mathbf{u}=(2/8)\\langle 2,2\\rangle=\\langle 1/2,1/2\\rangle$."),
        q("For $\\mathbf{a}=\\langle 1,2,2\\rangle$ and $\\mathbf{b}=\\langle 2,0,0\\rangle$, $\\|\\mathbf{a}\\times\\mathbf{b}\\|$ equals:",
          ["$4\\sqrt{2}$", "$4$", "$2\\sqrt{2}$"], 0,
          "Cross product $\\langle 0,4,-4\\rangle$ has magnitude $\\sqrt{32}=4\\sqrt{2}$."),
        q("The vector $\\langle 1,-1,2\\rangle\\times\\langle 2,0,1\\rangle$ equals:",
          ["$\\langle -1,3,2\\rangle$", "$\\langle 1,-3,-2\\rangle$", "$\\langle -1,-3,2\\rangle$"], 0,
          "$\\mathbf{i}((-1)(1)-2\\cdot 0)-\\mathbf{j}(1\\cdot 1-2\\cdot 2)+\\mathbf{k}(0-(-2))=\\langle -1,3,2\\rangle$."),
    ]

    banks["LA_V_SPAN_QUIZ"] = [
        q("The span of $\\{\\langle 1,0\\rangle\\}$ in $\\mathbb{R}^2$ is:",
          ["The $x$-axis", "All of $\\mathbb{R}^2$", "Only the origin"], 0,
          "Scalar multiples of $\\langle 1,0\\rangle$ fill the horizontal axis."),
        q("Does $\\langle 2,4\\rangle$ lie in $\\operatorname{Span}\\{\\langle 1,2\\rangle\\}$?",
          ["Yes, because $\\langle 2,4\\rangle=2\\langle 1,2\\rangle$", "No, the vectors are orthogonal", "Only if both are unit vectors"], 0,
          "It is exactly twice $\\langle 1,2\\rangle$."),
        q("The set $\\{\\langle 1,0\\rangle,\\langle 0,1\\rangle\\}$ spans:",
          ["$\\mathbb{R}^2$", "Only a line", "Only the origin"], 0,
          "These are the standard basis vectors of $\\mathbb{R}^2$."),
        q("If $\\mathbf{v}=2\\mathbf{u}$, then $\\operatorname{Span}\\{\\mathbf{u},\\mathbf{v}\\}$ is:",
          ["A line through the origin (or $\\{\\mathbf{0}\\}$)", "All of $\\mathbb{R}^2$", "A plane"], 0,
          "The two vectors are parallel, so their span is one-dimensional."),
        q("Coordinates of $\\langle 5,7\\rangle$ relative to the standard basis of $\\mathbb{R}^2$ are:",
          ["$(5,7)$", "$(7,5)$", "$(1,1)$"], 0,
          "$\\langle 5,7\\rangle=5\\mathbf{e}_1+7\\mathbf{e}_2$."),
        q("A basis of a subspace must be:",
          ["Linearly independent and spanning", "Any spanning set", "Any independent set of size 2"], 0,
          "Both independence and spanning are required."),
        q("Dimension of $\\operatorname{Span}\\{\\langle 1,0,0\\rangle,\\langle 0,1,0\\rangle\\}$ is:",
          ["$2$", "$3$", "$1$"], 0,
          "Two independent vectors span a $2$-dimensional subspace of $\\mathbb{R}^3$."),
        q("Does $\\{\\langle 1,1\\rangle,\\langle 2,3\\rangle\\}$ span $\\mathbb{R}^2$?",
          ["Yes; the vectors are independent in $\\mathbb{R}^2$", "No; they are parallel", "Only the first vector is needed"], 0,
          "The matrix with these columns has nonzero determinant $1$."),
        q("The standard basis of $\\mathbb{R}^3$ is:",
          ["$\\{\\mathbf{e}_1,\\mathbf{e}_2,\\mathbf{e}_3\\}$", "$\\{\\mathbf{0}\\}$", "$\\{\\langle 1,1,1\\rangle\\}$"], 0,
          "The three unit coordinate vectors form the standard basis."),
        q("Is $\\langle 0,1,1\\rangle$ in $\\operatorname{Span}\\{\\langle 1,0,0\\rangle,\\langle 0,1,0\\rangle\\}$?",
          ["No; the third component cannot be produced", "Yes; take coefficients $0$ and $1$", "Yes; any vector in $\\mathbb{R}^3$ is"], 0,
          "Linear combinations have third component $0$."),
        q("If $B=\\{\\mathbf{b}_1,\\mathbf{b}_2\\}$ is a basis of $\\mathbb{R}^2$ and $[\\mathbf{x}]_B=(3,-1)$, then $\\mathbf{x}$ equals:",
          ["$3\\mathbf{b}_1-\\mathbf{b}_2$", "$\\mathbf{b}_1+3\\mathbf{b}_2$", "$-3\\mathbf{b}_1+\\mathbf{b}_2$"], 0,
          "Coordinates are the weights in the linear combination."),
        q("Any spanning set of $\\mathbb{R}^3$ must contain at least how many vectors?",
          ["$3$", "$2$", "$1$"], 0,
          "Dimension $3$ requires at least three spanning vectors."),
        q("The span of the empty set is conventionally:",
          ["$\\{\\mathbf{0}\\}$", "$\\mathbb{R}^n$", "Undefined always"], 0,
          "The empty linear combination is the zero vector."),
        q("If three vectors in $\\mathbb{R}^2$ span $\\mathbb{R}^2$, then:",
          ["They are linearly dependent", "They form a basis", "They must be orthogonal"], 0,
          "More than $2$ vectors in $\\mathbb{R}^2$ cannot be independent."),
        q("For $\\mathbf{u}=\\langle 1,2,3\\rangle$ and $\\mathbf{v}=\\langle 2,4,6\\rangle$, $\\operatorname{Span}\\{\\mathbf{u},\\mathbf{v}\\}$ equals:",
          ["$\\operatorname{Span}\\{\\mathbf{u}\\}$", "$\\mathbb{R}^3$", "A plane through three non-collinear points"], 0,
          "$\\mathbf{v}=2\\mathbf{u}$, so both generate the same line."),
    ]

    banks["LA_V_INDEP_QUIZ"] = [
        q("The set $\\{\\langle 1,0\\rangle,\\langle 0,1\\rangle\\}$ is:",
          ["Linearly independent", "Linearly dependent", "Neither, because it spans"], 0,
          "Only the trivial combination gives the zero vector."),
        q("Is $\\{\\langle 1,2\\rangle,\\langle 2,4\\rangle\\}$ linearly independent?",
          ["No; the second is twice the first", "Yes; both are nonzero", "Yes; they span $\\mathbb{R}^2$"], 0,
          "A nontrivial relation $2\\mathbf{v}_1-\\mathbf{v}_2=\\mathbf{0}$ exists."),
        q("Three vectors in $\\mathbb{R}^2$ must be:",
          ["Linearly dependent", "Linearly independent", "A basis of $\\mathbb{R}^2$"], 0,
          "Any set with more than $n$ vectors in $\\mathbb{R}^n$ is dependent."),
        q("The equation $c_1\\mathbf{v}_1+c_2\\mathbf{v}_2=\\mathbf{0}$ has only the trivial solution iff:",
          ["$\\{\\mathbf{v}_1,\\mathbf{v}_2\\}$ is independent", "The vectors have equal length", "Their span is a line"], 0,
          "That is the definition of linear independence."),
        q("Columns of $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ are independent because:",
          ["$\\det=-2\\ne 0$", "$\\det=0$", "The matrix is symmetric"], 0,
          "Nonzero determinant means full column rank."),
        q("For $\\{\\langle 1,1,0\\rangle,\\langle 0,1,1\\rangle,\\langle 1,2,1\\rangle\\}$, a dependence relation is:",
          ["$\\mathbf{v}_1+\\mathbf{v}_2-\\mathbf{v}_3=\\mathbf{0}$", "$\\mathbf{v}_1-\\mathbf{v}_2=\\mathbf{0}$", "Only the zero combination works"], 0,
          "$\\langle 1,1,0\\rangle+\\langle 0,1,1\\rangle=\\langle 1,2,1\\rangle$."),
        q("If $A$ is $3\\times 3$ with $\\operatorname{rank}(A)=2$, its columns are:",
          ["Linearly dependent", "Linearly independent", "A basis of $\\mathbb{R}^3$"], 0,
          "Rank less than $3$ means the three columns are dependent."),
        q("The set $\\{\\mathbf{0},\\langle 1,0\\rangle\\}$ is:",
          ["Dependent, because it contains $\\mathbf{0}$", "Independent", "A basis of $\\mathbb{R}^2$"], 0,
          "Any set containing the zero vector is dependent."),
        q("Two nonzero parallel vectors in $\\mathbb{R}^n$ are:",
          ["Dependent", "Independent", "Orthogonal"], 0,
          "One is a scalar multiple of the other."),
        q("If $\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}=0$, the columns are:",
          ["Dependent", "Independent", "Orthogonal"], 0,
          "Vanishing determinant means dependent columns."),
        q("Independence of $\\{\\langle 1,0,0\\rangle,\\langle 0,1,0\\rangle,\\langle 0,0,1\\rangle\\}$ follows because:",
          ["They form the standard basis", "There are three of them", "Their sum is nonzero"], 0,
          "The standard basis is independent by construction."),
        q("A set of $4$ vectors in $\\mathbb{R}^3$:",
          ["Cannot be independent", "Must be a basis", "Must span $\\mathbb{R}^3$"], 0,
          "More vectors than the ambient dimension forces dependence."),
        q("If the only solution of $A\\mathbf{x}=\\mathbf{0}$ is $\\mathbf{x}=\\mathbf{0}$ for a square $A$, then the columns of $A$ are:",
          ["Independent", "Dependent", "Orthogonal to each other"], 0,
          "Trivial nullspace means independent columns."),
        q("For $\\mathbf{u}=\\langle 1,2\\rangle$, $\\mathbf{v}=\\langle 3,1\\rangle$, solving $c_1\\mathbf{u}+c_2\\mathbf{v}=\\mathbf{0}$ yields:",
          ["Only $c_1=c_2=0$", "$c_1=3$, $c_2=-1$", "Infinitely many solutions"], 0,
          "Determinant $1\\cdot 1-2\\cdot 3=-5\\ne 0$."),
        q("If columns of a $2\\times 2$ matrix are independent, then $\\operatorname{rank}(A)$ equals:",
          ["$2$", "$1$", "$0$"], 0,
          "Two independent columns give full rank."),
    ]

    banks["LA_M_INTRO_QUIZ"] = [
        q("The matrix $\\begin{pmatrix}1&2&3\\\\4&5&6\\end{pmatrix}$ has size:",
          ["$2\\times 3$", "$3\\times 2$", "$6\\times 1$"], 0,
          "Two rows and three columns."),
        q("Entry $a_{21}$ of $\\begin{pmatrix}7&8\\\\9&10\\end{pmatrix}$ is:",
          ["$9$", "$8$", "$7$"], 0,
          "Row $2$, column $1$ is $9$."),
        q("The standard matrix of reflection across the $x$-axis in $\\mathbb{R}^2$ is:",
          ["$\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}$", "$\\begin{pmatrix}-1&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$"], 0,
          "$(x,y)\\mapsto(x,-y)$."),
        q("The $2\\times 2$ identity matrix is:",
          ["$\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$", "$\\begin{pmatrix}1&1\\\\1&1\\end{pmatrix}$"], 0,
          "Ones on the diagonal and zeros elsewhere."),
        q("A diagonal matrix can have nonzero entries only:",
          ["On the main diagonal", "In the first row", "Above the diagonal"], 0,
          "Off-diagonal entries must be zero."),
        q("The transpose of $\\begin{pmatrix}1&2\\\\3&4\\\\5&6\\end{pmatrix}$ is:",
          ["$\\begin{pmatrix}1&3&5\\\\2&4&6\\end{pmatrix}$", "$\\begin{pmatrix}1&2&3\\\\4&5&6\\end{pmatrix}$", "$\\begin{pmatrix}6&5\\\\4&3\\\\2&1\\end{pmatrix}$"], 0,
          "Rows become columns."),
        q("The zero matrix of size $2\\times 2$ is:",
          ["$\\begin{pmatrix}0&0\\\\0&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$"], 0,
          "Every entry is $0$."),
        q("A symmetric matrix satisfies:",
          ["$A^T=A$", "$A^T=-A$", "$A^2=I$"], 0,
          "Equals its own transpose."),
        q("The standard matrix for scaling by $3$ in $\\mathbb{R}^2$ is:",
          ["$\\begin{pmatrix}3&0\\\\0&3\\end{pmatrix}$", "$\\begin{pmatrix}3&3\\\\3&3\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&3\\end{pmatrix}$"], 0,
          "Both axes stretch by factor $3$."),
        q("Upper triangular $3\\times 3$ matrices have zeros:",
          ["Strictly below the diagonal", "Strictly above the diagonal", "On the diagonal"], 0,
          "Entries $a_{ij}$ with $i>j$ vanish."),
        q("Rotation by $90^\\circ$ counterclockwise in $\\mathbb{R}^2$ has matrix:",
          ["$\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$", "$\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}$"], 0,
          "$(x,y)\\mapsto(-y,x)$."),
        q("Projection onto the $x$-axis has standard matrix:",
          ["$\\begin{pmatrix}1&0\\\\0&0\\end{pmatrix}$", "$\\begin{pmatrix}0&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}1&1\\\\0&0\\end{pmatrix}$"], 0,
          "$(x,y)\\mapsto(x,0)$."),
        q("If $A$ is $m\\times n$, it maps $\\mathbb{R}^n$ into:",
          ["$\\mathbb{R}^m$", "$\\mathbb{R}^n$", "$\\mathbb{R}^{mn}$"], 0,
          "Columns live in $\\mathbb{R}^m$."),
        q("Entry $a_{13}$ of $\\begin{pmatrix}2&0&5\\\\1&3&4\\end{pmatrix}$ is:",
          ["$5$", "$4$", "$0$"], 0,
          "First row, third column."),
        q("A linear map $T:\\mathbb{R}^2\\to\\mathbb{R}^2$ is completely determined by:",
          ["$T(\\mathbf{e}_1)$ and $T(\\mathbf{e}_2)$", "Only $T(\\mathbf{0})$", "Its determinant alone"], 0,
          "Images of the standard basis form the columns of the matrix."),
    ]

    banks["LA_M_OPS_QUIZ"] = [
        q("Compute $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}+\\begin{pmatrix}5&0\\\\1&1\\end{pmatrix}$.",
          ["$\\begin{pmatrix}6&2\\\\4&5\\end{pmatrix}$", "$\\begin{pmatrix}6&2\\\\4&4\\end{pmatrix}$", "$\\begin{pmatrix}5&2\\\\3&5\\end{pmatrix}$"], 0,
          "Add entrywise."),
        q("Compute $2\\begin{pmatrix}1&-1\\\\0&3\\end{pmatrix}$.",
          ["$\\begin{pmatrix}2&-2\\\\0&6\\end{pmatrix}$", "$\\begin{pmatrix}2&-1\\\\0&3\\end{pmatrix}$", "$\\begin{pmatrix}1&-2\\\\0&6\\end{pmatrix}$"], 0,
          "Scale every entry by $2$."),
        q("Product $\\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}\\begin{pmatrix}3&0\\\\1&4\\end{pmatrix}$ equals:",
          ["$\\begin{pmatrix}5&8\\\\1&4\\end{pmatrix}$", "$\\begin{pmatrix}3&0\\\\1&4\\end{pmatrix}$", "$\\begin{pmatrix}5&8\\\\0&4\\end{pmatrix}$"], 0,
          "Row-column: first entry $1\\cdot 3+2\\cdot 1=5$, and so on."),
        q("Can a $2\\times 3$ matrix multiply a $2\\times 2$ matrix on the right?",
          ["No; inner dimensions $3$ and $2$ disagree", "Yes; always", "Only if both are square"], 0,
          "Need the middle sizes to match."),
        q("In general $AB$ and $BA$:",
          ["Need not be equal", "Are always equal", "Are always negatives"], 0,
          "Matrix multiplication is not commutative."),
        q("If $A=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$, then $A^2$ equals:",
          ["$\\begin{pmatrix}0&0\\\\0&0\\end{pmatrix}$", "$A$", "$I$"], 0,
          "Direct multiplication yields the zero matrix."),
        q("$(AB)^T$ equals:",
          ["$B^TA^T$", "$A^TB^T$", "$AB$"], 0,
          "Transpose reverses the product order."),
        q("$\\operatorname{tr}\\begin{pmatrix}2&7\\\\0&5\\end{pmatrix}$ equals:",
          ["$7$", "$2$", "$10$"], 0,
          "Trace is the sum of diagonal entries $2+5=7$."),
        q("$\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$ equals:",
          ["$\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$", "$\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}$"], 0,
          "Compute the product of the two factors."),
        q("If $A$ is $3\\times 2$ and $B$ is $2\\times 4$, then $AB$ has size:",
          ["$3\\times 4$", "$2\\times 2$", "$4\\times 3$"], 0,
          "Outer dimensions give the product size."),
        q("$\\operatorname{tr}(A+B)$ equals:",
          ["$\\operatorname{tr}A+\\operatorname{tr}B$", "$\\operatorname{tr}(AB)$", "$(\\operatorname{tr}A)(\\operatorname{tr}B)$"], 0,
          "Trace is linear."),
        q("For $A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$, $A^3$ equals:",
          ["$\\begin{pmatrix}1&3\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}$"], 0,
          "Inductively $A^n=\\begin{pmatrix}1&n\\\\0&1\\end{pmatrix}$."),
        q("Scalar multiple: $(-1)\\begin{pmatrix}2&3\\\\4&5\\end{pmatrix}$ equals:",
          ["$\\begin{pmatrix}-2&-3\\\\-4&-5\\end{pmatrix}$", "$\\begin{pmatrix}2&-3\\\\-4&5\\end{pmatrix}$", "$\\begin{pmatrix}-2&3\\\\4&-5\\end{pmatrix}$"], 0,
          "Negate every entry."),
        q("If $A$ is square, $\\operatorname{tr}(A^T)$ equals:",
          ["$\\operatorname{tr}A$", "$-\\operatorname{tr}A$", "$0$"], 0,
          "Diagonal entries are unchanged by transpose."),
        q("Product $\\begin{pmatrix}2&1\\end{pmatrix}\\begin{pmatrix}3\\\\4\\end{pmatrix}$ equals:",
          ["$\\begin{pmatrix}10\\end{pmatrix}$", "$\\begin{pmatrix}6&4\\end{pmatrix}$", "$\\begin{pmatrix}5\\end{pmatrix}$"], 0,
          "$2\\cdot 3+1\\cdot 4=10$ as a $1\\times 1$ matrix."),
    ]

    banks["LA_M_DET_QUIZ"] = [
        q("$\\det\\begin{pmatrix}3&1\\\\2&4\\end{pmatrix}$ equals:",
          ["$10$", "$14$", "$5$"], 0,
          "$3\\cdot 4-1\\cdot 2=12-2=10$."),
        q("$\\det\\begin{pmatrix}1&2&0\\\\0&3&4\\\\0&0&5\\end{pmatrix}$ equals:",
          ["$15$", "$0$", "$12$"], 0,
          "Triangular: product of diagonal entries $1\\cdot 3\\cdot 5=15$."),
        q("If $\\det A=4$ and $\\det B=3$ for $n\\times n$ matrices, $\\det(AB)$ equals:",
          ["$12$", "$7$", "$1$"], 0,
          "$\\det(AB)=\\det A\\det B$."),
        q("Swapping two rows of a matrix multiplies the determinant by:",
          ["$-1$", "$2$", "$0$"], 0,
          "An elementary row swap changes the sign."),
        q("If $\\det A=5$ for a $2\\times 2$ matrix, $\\det(3A)$ equals:",
          ["$45$", "$15$", "$5/3$"], 0,
          "$\\det(kA)=k^n\\det A$ with $n=2$: $9\\cdot 5=45$."),
        q("A square matrix is singular precisely when its determinant is:",
          ["$0$", "$1$", "Negative"], 0,
          "Zero determinant iff noninvertible."),
        q("$\\det\\begin{pmatrix}2&0&0\\\\1&3&0\\\\4&5&6\\end{pmatrix}$ equals:",
          ["$36$", "$0$", "$18$"], 0,
          "Lower triangular: $2\\cdot 3\\cdot 6=36$."),
        q("If $\\det A=2$, then $\\det(A^{-1})$ equals:",
          ["$1/2$", "$2$", "$-2$"], 0,
          "$\\det(A^{-1})=1/\\det A$."),
        q("Cofactor expansion of $\\begin{pmatrix}1&0&2\\\\0&3&0\\\\4&0&5\\end{pmatrix}$ along the middle row yields determinant:",
          ["$-9$", "$9$", "$15$"], 0,
          "Only the middle entry $3$ survives: $3(-1)^{2+2}\\det\\begin{pmatrix}1&2\\\\4&5\\end{pmatrix}=3(5-8)=-9$."),
        q("Area of the parallelogram with sides $\\langle 2,0\\rangle$ and $\\langle 1,3\\rangle$ equals:",
          ["$6$", "$5$", "$3$"], 0,
          "$|\\det\\begin{pmatrix}2&1\\\\0&3\\end{pmatrix}|=6$."),
        q("Multiplying one row by $4$ multiplies $\\det$ by:",
          ["$4$", "$16$", "$1/4$"], 0,
          "A single-row scale scales the determinant by the same factor."),
        q("If two rows of $A$ are identical, $\\det A$ equals:",
          ["$0$", "$1$", "$2$"], 0,
          "Dependent rows force a zero determinant."),
        q("$\\det I_n$ equals:",
          ["$1$", "$0$", "$n$"], 0,
          "Identity is triangular with ones on the diagonal."),
        q("For $A=\\begin{pmatrix}0&1\\\\-2&3\\end{pmatrix}$, $\\det A$ equals:",
          ["$2$", "$-2$", "$3$"], 0,
          "$0\\cdot 3-1\\cdot(-2)=2$."),
        q("Volume of the parallelepiped from columns of $\\begin{pmatrix}1&0&0\\\\0&2&0\\\\0&0&3\\end{pmatrix}$ equals:",
          ["$6$", "$5$", "$1$"], 0,
          "Absolute value of the determinant $1\\cdot 2\\cdot 3=6$."),
    ]

    banks["LA_M_INV_QUIZ"] = [
        q("The inverse of $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ is:",
          ["$\\begin{pmatrix}-2&1\\\\3/2&-1/2\\end{pmatrix}$", "$\\begin{pmatrix}4&-2\\\\-3&1\\end{pmatrix}$", "$\\begin{pmatrix}1&-2\\\\-3&4\\end{pmatrix}$"], 0,
          "$\\det=-2$; formula gives $(-1/2)\\begin{pmatrix}4&-2\\\\-3&1\\end{pmatrix}=\\begin{pmatrix}-2&1\\\\3/2&-1/2\\end{pmatrix}$."),
        q("A $2\\times 2$ matrix is invertible iff its determinant is:",
          ["Nonzero", "Positive", "Equal to $1$"], 0,
          "Invertibility is equivalent to $\\det\\ne 0$."),
        q("$(AB)^{-1}$ equals:",
          ["$B^{-1}A^{-1}$", "$A^{-1}B^{-1}$", "$AB$"], 0,
          "Inverse reverses the product order."),
        q("If $A\\mathbf{x}=\\mathbf{b}$ and $A$ is invertible, then $\\mathbf{x}$ equals:",
          ["$A^{-1}\\mathbf{b}$", "$A\\mathbf{b}$", "$\\mathbf{b}A^{-1}$"], 0,
          "Multiply both sides on the left by $A^{-1}$."),
        q("The matrix $\\begin{pmatrix}1&2\\\\2&4\\end{pmatrix}$ fails to be invertible because:",
          ["Its determinant is $0$", "It is symmetric", "It has positive entries"], 0,
          "$1\\cdot 4-2\\cdot 2=0$."),
        q("Inverse of $\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$ is:",
          ["$\\begin{pmatrix}1/2&0\\\\0&1/5\\end{pmatrix}$", "$\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$", "$\\begin{pmatrix}5&0\\\\0&2\\end{pmatrix}$"], 0,
          "Invert the diagonal entries."),
        q("For invertible $A$, $A A^{-1}$ equals:",
          ["$I$", "$A$", "$0$"], 0,
          "Definition of the inverse."),
        q("Using the adjugate, $A^{-1}=(1/\\det A)\\operatorname{adj}A$ when:",
          ["$\\det A\\ne 0$", "$A$ is symmetric", "$A$ is triangular"], 0,
          "The formula requires a nonzero determinant."),
        q("Solve $\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}\\mathbf{x}=\\begin{pmatrix}3\\\\2\\end{pmatrix}$ using the inverse.",
          ["$\\mathbf{x}=\\begin{pmatrix}1\\\\2\\end{pmatrix}$", "$\\mathbf{x}=\\begin{pmatrix}3\\\\2\\end{pmatrix}$", "$\\mathbf{x}=\\begin{pmatrix}2\\\\1\\end{pmatrix}$"], 0,
          "Inverse is $\\begin{pmatrix}1&-1\\\\0&1\\end{pmatrix}$; product gives $(1,2)$."),
        q("If $A^{-1}=\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$, then $A$ equals:",
          ["$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$", "$\\begin{pmatrix}0&-1\\\\-1&0\\end{pmatrix}$"], 0,
          "This matrix is its own inverse."),
        q("Gauss-Jordan finds $A^{-1}$ by row-reducing:",
          ["$[A\\mid I]$ to $[I\\mid A^{-1}]$", "$[A\\mid\\mathbf{0}]$", "$A$ alone to RREF"], 0,
          "Augment with the identity and reduce."),
        q("If $\\det A=-4$, then $\\det(A^{-1})$ equals:",
          ["$-1/4$", "$4$", "$1/4$"], 0,
          "$1/\\det A=-1/4$."),
        q("The inverse of $\\begin{pmatrix}1&0\\\\4&1\\end{pmatrix}$ is:",
          ["$\\begin{pmatrix}1&0\\\\-4&1\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\4&-1\\end{pmatrix}$", "$\\begin{pmatrix}-1&0\\\\-4&-1\\end{pmatrix}$"], 0,
          "Check product is $I$, or use the $2\\times 2$ formula."),
        q("If $A$ is invertible and $AB=AC$, then:",
          ["$B=C$", "$B=-C$", "Nothing about $B$ and $C$"], 0,
          "Multiply on the left by $A^{-1}$."),
        q("For $A=\\begin{pmatrix}4&1\\\\1&1\\end{pmatrix}$, $A^{-1}$ equals:",
          ["$\\dfrac{1}{3}\\begin{pmatrix}1&-1\\\\-1&4\\end{pmatrix}$", "$\\begin{pmatrix}1&-1\\\\-1&4\\end{pmatrix}$", "$\\dfrac{1}{3}\\begin{pmatrix}4&-1\\\\-1&1\\end{pmatrix}$"], 0,
          "$\\det=3$; adjugate formula gives $(1/3)\\begin{pmatrix}1&-1\\\\-1&4\\end{pmatrix}$."),
    ]

    return banks


def build_systems_eigen():
    banks = {}

    banks["LA_S_INTRO_QUIZ"] = [
        q("Solve the system $x+y=5$, $x-y=1$.",
          ["$x=3,\\ y=2$", "$x=2,\\ y=3$", "$x=4,\\ y=1$"], 0,
          "Adding the equations gives $2x=6$, so $x=3$ and $y=2$."),
        q("Which equation is linear in $x$ and $y$?",
          ["$2x-3y=7$", "$x^2+y=1$", "$xy=4$"], 0,
          "A linear equation has no products or powers of the unknowns."),
        q("The homogeneous system $A\\mathbf{x}=\\mathbf{0}$ always has:",
          ["At least the trivial solution $\\mathbf{x}=\\mathbf{0}$", "No solutions", "Exactly one nonzero solution"], 0,
          "Substituting $\\mathbf{x}=\\mathbf{0}$ always works."),
        q("Write $x-2y=3$, $4x+y=1$ as $A\\mathbf{x}=\\mathbf{b}$. The matrix $A$ is:",
          ["$\\begin{pmatrix}1&-2\\\\4&1\\end{pmatrix}$", "$\\begin{pmatrix}1&4\\\\-2&1\\end{pmatrix}$", "$\\begin{pmatrix}3\\\\1\\end{pmatrix}$"], 0,
          "Coefficients of the unknowns form the rows of $A$."),
        q("The system $x+y=1$, $2x+2y=3$ has:",
          ["No solution", "A unique solution", "Infinitely many solutions"], 0,
          "The second equation contradicts twice the first."),
        q("The system $x+y=2$, $2x+2y=4$ has:",
          ["Infinitely many solutions", "No solution", "Exactly one solution"], 0,
          "The second equation is a multiple of the first, so one free variable remains."),
        q("Solve $2x+y=7$, $x-y=2$.",
          ["$x=3,\\ y=1$", "$x=1,\\ y=3$", "$x=2,\\ y=3$"], 0,
          "Adding yields $3x=9$, so $x=3$ and $y=1$."),
        q("An augmented matrix for $x+2y=0$, $3x-y=5$ is:",
          ["$\\begin{pmatrix}1&2&0\\\\3&-1&5\\end{pmatrix}$", "$\\begin{pmatrix}1&2\\\\3&-1\\end{pmatrix}$", "$\\begin{pmatrix}0&5\\end{pmatrix}$"], 0,
          "Coefficients and right-hand side appear in one array."),
        q("A consistent linear system is one that has:",
          ["At least one solution", "No solutions", "Only the trivial solution"], 0,
          "Consistency means the solution set is nonempty."),
        q("Solve $x+y+z=6$, $y+z=3$, $z=1$.",
          ["$x=3,\\ y=2,\\ z=1$", "$x=2,\\ y=3,\\ z=1$", "$x=1,\\ y=2,\\ z=3$"], 0,
          "Back-substitute: $z=1$, then $y=2$, then $x=3$."),
        q("For a square coefficient matrix with $\\det A\\ne 0$, the system $A\\mathbf{x}=\\mathbf{b}$ has:",
          ["Exactly one solution", "No solution", "Infinitely many solutions"], 0,
          "Nonsingular $A$ is invertible, so $\\mathbf{x}=A^{-1}\\mathbf{b}$ is unique."),
        q("The equation $0\\cdot x+0\\cdot y=5$ in a system forces:",
          ["Inconsistency", "A free variable", "A unique solution"], 0,
          "The false statement $0=5$ means no solution exists."),
        q("How many solutions can a linear system have?",
          ["Zero, one, or infinitely many", "Any finite number", "Only zero or one"], 0,
          "Linearity forbids exactly two distinct solutions."),
        q("Solve $3x-y=4$, $x+y=4$.",
          ["$x=2,\\ y=2$", "$x=1,\\ y=3$", "$x=4,\\ y=0$"], 0,
          "Adding gives $4x=8$, so $x=2$ and $y=2$."),
        q("If $A$ is $2\\times 2$ singular and $A\\mathbf{x}=\\mathbf{b}$ is consistent, the number of solutions is:",
          ["Infinitely many", "Exactly one", "Zero"], 0,
          "Singular consistent systems have a free variable."),
    ]

    banks["LA_S_GAUSS_QUIZ"] = [
        q("Which is an elementary row operation?",
          ["Swap two rows", "Delete a column", "Replace $A$ by $A^T$"], 0,
          "Allowed moves are row swaps, scaling a row, and adding a multiple of one row to another."),
        q("The row echelon form of $\\begin{pmatrix}1&2&3\\\\0&0&0\\\\0&1&4\\end{pmatrix}$ after swapping rows $2$ and $3$ begins with pivots in columns:",
          ["$1$ and $2$", "$1$ and $3$", "$2$ only"], 0,
          "After the swap the nonzero rows have leading ones in columns $1$ and $2$."),
        q("Back-substitute from $\\begin{pmatrix}1&2&5\\\\0&1&3\\end{pmatrix}$ to get:",
          ["$x=-1,\\ y=3$", "$x=5,\\ y=3$", "$x=1,\\ y=2$"], 0,
          "From $y=3$ and $x+2y=5$: $x+6=5$ so $x=-1$."),
        q("An inconsistent row in an augmented matrix looks like:",
          ["$[0\\ 0\\ 0\\mid 5]$", "$[1\\ 0\\ 0\\mid 2]$", "$[0\\ 1\\ 0\\mid 0]$"], 0,
          "The equation $0=5$ cannot hold."),
        q("Reduced row echelon form requires that each pivot is $1$ and:",
          ["Is the only nonzero entry in its column", "Lies only on the diagonal", "Equals the right-hand side"], 0,
          "Above and below each pivot the column is cleared."),
        q("For $\\begin{pmatrix}1&3&|-1\\\\2&6&|4\\end{pmatrix}$, after $R_2\\leftarrow R_2-2R_1$ one obtains:",
          ["$\\begin{pmatrix}1&3&|-1\\\\0&0&|6\\end{pmatrix}$", "$\\begin{pmatrix}1&3&|-1\\\\0&0&|0\\end{pmatrix}$", "$\\begin{pmatrix}1&3&|-1\\\\0&6&|4\\end{pmatrix}$"], 0,
          "$4-2(-1)=6$, yielding the inconsistent row $[0\\ 0\\mid 6]$."),
        q("A free variable appears when a column:",
          ["Has no pivot", "Has two pivots", "Is the right-hand side"], 0,
          "Nonpivot columns correspond to free unknowns."),
        q("Row-reduce $\\begin{pmatrix}1&1&2\\\\0&1&3\\end{pmatrix}$ to RREF. The result is:",
          ["$\\begin{pmatrix}1&0&-1\\\\0&1&3\\end{pmatrix}$", "$\\begin{pmatrix}1&1&2\\\\0&1&3\\end{pmatrix}$", "$\\begin{pmatrix}1&0&2\\\\0&1&3\\end{pmatrix}$"], 0,
          "Subtract row $2$ from row $1$: $2-3=-1$."),
        q("The pivot positions of $\\begin{pmatrix}0&2&3\\\\0&0&5\\\\0&0&0\\end{pmatrix}$ are in columns:",
          ["$2$ and $3$", "$1$ and $2$", "$1$ and $3$"], 0,
          "Leading nonzero entries sit in columns $2$ and $3$."),
        q("Starting from $\\begin{pmatrix}2&4&6\\\\1&1&1\\end{pmatrix}$, a first useful step is:",
          ["Swap rows or scale row $1$ by $1/2$", "Compute the determinant only", "Delete the second column"], 0,
          "Either swap to get a leading $1$, or scale the first row."),
        q("After elimination, $\\begin{pmatrix}1&2&3&|1\\\\0&0&0&|0\\\\0&0&1&|2\\end{pmatrix}$ has how many free variables among $x,y,z$?",
          ["One ($y$)", "None", "Two"], 0,
          "Pivots in columns $1$ and $3$ leave $y$ free."),
        q("Gaussian elimination on a consistent $2\\times 2$ system with two pivots ends with:",
          ["A unique solution via back substitution", "A free variable", "An inconsistent row"], 0,
          "Two pivots in two unknowns means a unique solution."),
        q("The operation $R_1\\leftarrow R_1+3R_2$:",
          ["Does not change the solution set", "Multiplies the determinant by $3$", "Always creates a free variable"], 0,
          "Adding a multiple of one row to another is reversible."),
        q("From REF $\\begin{pmatrix}1&-1&2\\\\0&1&4\\end{pmatrix}$, solve for $(x,y)$:",
          ["$x=6,\\ y=4$", "$x=2,\\ y=4$", "$x=4,\\ y=6$"], 0,
          "$y=4$ and $x-y=2$ give $x=6$."),
        q("If a $3\\times 3$ augmented matrix reduces to three nonzero pivot rows and no inconsistent row, the system has:",
          ["A unique solution", "Infinitely many solutions", "No solution"], 0,
          "Three pivots in three unknowns determine $\\mathbf{x}$ uniquely."),
    ]

    banks["LA_S_RANK_QUIZ"] = [
        q("The rank of $\\begin{pmatrix}1&0&0\\\\0&1&0\\\\0&0&0\\end{pmatrix}$ is:",
          ["$2$", "$3$", "$1$"], 0,
          "There are two nonzero pivot rows."),
        q("Rank-nullity for an $m\\times n$ matrix says $\\operatorname{rank}(A)+\\operatorname{nullity}(A)$ equals:",
          ["$n$", "$m$", "$m+n$"], 0,
          "Nullity is the dimension of the nullspace in the domain $\\mathbb{R}^n$."),
        q("A system $A\\mathbf{x}=\\mathbf{b}$ is consistent iff:",
          ["$\\operatorname{rank}(A)=\\operatorname{rank}([A\\mid\\mathbf{b}])$", "$\\operatorname{rank}(A)=0$", "$\\det A=0$"], 0,
          "The augmented matrix must not gain an extra pivot."),
        q("If $A$ is $3\\times 5$ with $\\operatorname{rank}(A)=3$, then $\\operatorname{nullity}(A)$ equals:",
          ["$2$", "$3$", "$5$"], 0,
          "$5-3=2$ free variables."),
        q("The column space of $A$ has dimension equal to:",
          ["$\\operatorname{rank}(A)$", "$\\operatorname{nullity}(A)$", "The number of rows always"], 0,
          "Rank is defined as the dimension of the column space."),
        q("For $A=\\begin{pmatrix}1&2\\\\2&4\\\\3&6\\end{pmatrix}$, $\\operatorname{rank}(A)$ equals:",
          ["$1$", "$2$", "$3$"], 0,
          "The second column is twice the first, so only one independent column."),
        q("Number of free variables in $A\\mathbf{x}=\\mathbf{0}$ equals:",
          ["$\\operatorname{nullity}(A)$", "$\\operatorname{rank}(A)$", "Always $0$"], 0,
          "Free variables parametrize the nullspace."),
        q("If $\\operatorname{rank}(A)=n$ for an $n\\times n$ matrix, then $A$ is:",
          ["Invertible", "Singular", "Zero"], 0,
          "Full rank square matrices are nonsingular."),
        q("Echelon form $\\begin{pmatrix}1&3&0\\\\0&0&1\\\\0&0&0\\end{pmatrix}$ has rank:",
          ["$2$", "$3$", "$1$"], 0,
          "Two pivot rows."),
        q("If $\\operatorname{rank}(A)=2$ and $\\operatorname{rank}([A\\mid\\mathbf{b}])=3$, the system is:",
          ["Inconsistent", "Consistent with a unique solution", "Consistent with free variables"], 0,
          "An extra pivot appears only in the augmented matrix."),
        q("Dimension of the nullspace of $\\begin{pmatrix}1&0&2\\\\0&1&3\\end{pmatrix}$ is:",
          ["$1$", "$2$", "$0$"], 0,
          "Two pivots in three columns leave one free variable."),
        q("For a $4\\times 4$ matrix of rank $4$, $\\dim\\operatorname{Col}(A)$ equals:",
          ["$4$", "$0$", "$3$"], 0,
          "Full column rank means the column space is all of $\\mathbb{R}^4$."),
        q("Rank of the zero $3\\times 3$ matrix is:",
          ["$0$", "$3$", "$1$"], 0,
          "There are no nonzero rows."),
        q("If $A$ is $2\\times 2$ with $\\operatorname{rank}(A)=1$, then $\\operatorname{nullity}(A)$ equals:",
          ["$1$", "$2$", "$0$"], 0,
          "$2-1=1$."),
        q("The row rank of any matrix equals its:",
          ["Column rank", "Nullity", "Number of zero rows"], 0,
          "Row rank and column rank coincide."),
    ]

    banks["LA_S_GEO_QUIZ"] = [
        q("The solution set of a consistent $2\\times 2$ system with one free variable is geometrically:",
          ["A line in $\\mathbb{R}^2$", "A single point", "The empty set"], 0,
          "One free parameter traces a line."),
        q("Two distinct parallel planes in $\\mathbb{R}^3$ have:",
          ["Empty intersection", "A line of intersection", "A unique common point"], 0,
          "Parallel distinct planes never meet."),
        q("If $A\\mathbf{x}=\\mathbf{b}$ has particular solution $\\mathbf{x}_p$ and nullspace spanned by $\\mathbf{v}$, the general solution is:",
          ["$\\mathbf{x}_p+t\\mathbf{v}$", "$\\mathbf{x}_p\\times\\mathbf{v}$", "$t\\mathbf{x}_p$ only"], 0,
          "Add any homogeneous solution to a particular solution."),
        q("Three planes with no common intersection correspond to an:",
          ["Inconsistent linear system", "Invertible coefficient matrix", "Homogeneous system only"], 0,
          "No point lies on all three planes."),
        q("Parametric form $\\mathbf{x}=(1,2)+t(3,-1)$ describes:",
          ["A line through $(1,2)$ in direction $(3,-1)$", "A plane through the origin", "Only the point $(1,2)$"], 0,
          "One free parameter yields a line."),
        q("A singular $2\\times 2$ coefficient matrix means the two lines:",
          ["Are parallel or coincident", "Always intersect at one point", "Are always perpendicular"], 0,
          "Dependent rows give parallel normals."),
        q("The homogeneous system $A\\mathbf{x}=\\mathbf{0}$ in $\\mathbb{R}^3$ with $\\operatorname{rank}(A)=1$ has solution set:",
          ["A plane through the origin", "A single point", "A line not through the origin"], 0,
          "Nullity $2$ yields a $2$-dimensional subspace."),
        q("Two planes intersecting in a line match a $3$-unknown system with:",
          ["Rank $2$ and consistency", "Rank $3$", "Rank $0$"], 0,
          "Two independent constraints leave one free variable."),
        q("Coincident lines $x+y=1$ and $2x+2y=2$ have solution set:",
          ["The entire line $x+y=1$", "A single point", "Empty"], 0,
          "The equations describe the same line."),
        q("If $A$ is invertible, the solution of $A\\mathbf{x}=\\mathbf{b}$ is geometrically:",
          ["A single point", "A line", "A plane"], 0,
          "Unique solution means one point in $\\mathbb{R}^n$."),
        q("Particular solution $(1,0,-1)$ plus nullspace span$\\{(2,1,0)\\}$ gives general solution:",
          ["$(1,0,-1)+t(2,1,0)$", "$(2,1,0)+t(1,0,-1)$", "$t(1,0,-1)$"], 0,
          "Translate the nullspace line by the particular solution."),
        q("An empty solution set for two lines in $\\mathbb{R}^2$ means the lines are:",
          ["Parallel and distinct", "The same line", "Intersecting"], 0,
          "No common point."),
        q("The set $\\{\\mathbf{x}:A\\mathbf{x}=\\mathbf{b}\\}$ for consistent nonsingular $A$ contains:",
          ["Exactly one vector", "A whole subspace", "No vectors"], 0,
          "Invertibility forces uniqueness."),
        q("Solution set $\\mathbf{x}=(0,0,1)+s(1,0,0)+t(0,1,0)$ is:",
          ["A plane parallel to the $xy$-plane through $(0,0,1)$", "A line", "All of $\\mathbb{R}^3$"], 0,
          "Two free parameters with fixed $z=1$."),
        q("If three planes meet at exactly one point, the coefficient matrix of the $3\\times 3$ system is:",
          ["Nonsingular", "The zero matrix", "Singular with nullity $1$"], 0,
          "A unique intersection point means full rank."),
    ]

    banks["LA_E_INTRO_QUIZ"] = [
        q("If $A\\mathbf{v}=\\lambda\\mathbf{v}$ with $\\mathbf{v}\\ne\\mathbf{0}$, then $\\mathbf{v}$ is called:",
          ["An eigenvector with eigenvalue $\\lambda$", "A free variable", "A pivot column"], 0,
          "That is the definition of an eigenpair."),
        q("For $A=\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$, an eigenvector for $\\lambda=2$ is:",
          ["$\\begin{pmatrix}1\\\\0\\end{pmatrix}$", "$\\begin{pmatrix}0\\\\1\\end{pmatrix}$", "$\\begin{pmatrix}1\\\\1\\end{pmatrix}$"], 0,
          "$A(1,0)^T=(2,0)^T=2(1,0)^T$."),
        q("Verify: is $\\mathbf{v}=(1,1)$ an eigenvector of $A=\\begin{pmatrix}3&1\\\\1&3\\end{pmatrix}$?",
          ["Yes, with $\\lambda=4$", "Yes, with $\\lambda=2$", "No"], 0,
          "$A\\mathbf{v}=(4,4)=4\\mathbf{v}$."),
        q("Eigenvalues of a triangular matrix are:",
          ["Its diagonal entries", "Always $0$", "The trace only"], 0,
          "$\\det(A-\\lambda I)$ factors using the diagonal."),
        q("If $0$ is an eigenvalue of $A$, then $A$ is:",
          ["Singular", "Invertible", "Orthogonal"], 0,
          "$A\\mathbf{v}=\\mathbf{0}$ for some $\\mathbf{v}\\ne\\mathbf{0}$."),
        q("If $\\mathbf{v}$ is an eigenvector, then $5\\mathbf{v}$ is:",
          ["An eigenvector for the same $\\lambda$", "Never an eigenvector", "An eigenvector for $5\\lambda$"], 0,
          "$A(5\\mathbf{v})=5\\lambda\\mathbf{v}=\\lambda(5\\mathbf{v})$."),
        q("For $A=\\begin{pmatrix}4&1\\\\0&4\\end{pmatrix}$, the eigenvalue $\\lambda=4$ has eigenspace spanned by:",
          ["$\\begin{pmatrix}1\\\\0\\end{pmatrix}$", "$\\begin{pmatrix}0\\\\1\\end{pmatrix}$", "$\\begin{pmatrix}1\\\\1\\end{pmatrix}$"], 0,
          "$(A-4I)\\mathbf{v}=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}\\mathbf{v}=\\mathbf{0}$ forces the second component to vanish."),
        q("The equation $(A-\\lambda I)\\mathbf{v}=\\mathbf{0}$ with $\\mathbf{v}\\ne\\mathbf{0}$ means:",
          ["$\\lambda$ is an eigenvalue", "$A$ is the identity", "$\\mathbf{v}$ is orthogonal to every row"], 0,
          "Nontrivial nullspace of $A-\\lambda I$ characterizes eigenvalues."),
        q("Diagonal matrix $\\operatorname{diag}(7,-3)$ has eigenvalues:",
          ["$7$ and $-3$", "$7$ only", "$0$ and $1$"], 0,
          "Diagonal entries are the eigenvalues."),
        q("Compute $A\\mathbf{v}$ for $A=\\begin{pmatrix}1&2\\\\0&3\\end{pmatrix}$, $\\mathbf{v}=(2,0)$. Is $\\mathbf{v}$ an eigenvector?",
          ["Yes; $A\\mathbf{v}=(2,0)=1\\cdot\\mathbf{v}$", "Yes; with $\\lambda=3$", "No; $A\\mathbf{v}$ is not parallel to $\\mathbf{v}$"], 0,
          "$A\\mathbf{v}=(2,0)$, a scalar multiple of $\\mathbf{v}$."),
        q("The eigenspace for $\\lambda$ is:",
          ["$\\operatorname{Null}(A-\\lambda I)$", "$\\operatorname{Col}(A)$", "$\\operatorname{Row}(A)$"], 0,
          "Solutions of $(A-\\lambda I)\\mathbf{v}=\\mathbf{0}$, including $\\mathbf{0}$."),
        q("If $A\\mathbf{v}=3\\mathbf{v}$ and $A\\mathbf{w}=3\\mathbf{w}$, then $A(\\mathbf{v}+\\mathbf{w})$ equals:",
          ["$3(\\mathbf{v}+\\mathbf{w})$", "$6(\\mathbf{v}+\\mathbf{w})$", "$\\mathbf{v}+\\mathbf{w}$"], 0,
          "Eigenspaces are subspaces."),
        q("For $A=\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$ and $\\mathbf{v}=(1,0)$, $A\\mathbf{v}$ equals:",
          ["$(0,1)$, not a real multiple of $\\mathbf{v}$", "$(1,0)$", "$(-1,0)$"], 0,
          "This rotation has no real eigenvectors in that direction."),
        q("An eigenvector must be:",
          [" nonzero", "A unit vector", "Orthogonal to every row of $A$"], 0,
          "The definition excludes the zero vector."),
        q("If $A=I_2$, every nonzero $\\mathbf{v}$ is an eigenvector with:",
          ["$\\lambda=1$", "$\\lambda=0$", "$\\lambda=2$"], 0,
          "$I\\mathbf{v}=1\\cdot\\mathbf{v}$."),
    ]

    banks["LA_E_CHAR_QUIZ"] = [
        q("The characteristic polynomial of $A$ is:",
          ["$\\det(A-\\lambda I)$", "$\\det(A+\\lambda I)$", "$\\operatorname{tr}(A-\\lambda I)$"], 0,
          "Roots of $\\det(A-\\lambda I)=0$ are the eigenvalues."),
        q("For $A=\\begin{pmatrix}2&1\\\\0&3\\end{pmatrix}$, $\\det(A-\\lambda I)$ equals:",
          ["$(2-\\lambda)(3-\\lambda)$", "$(2-\\lambda)+(3-\\lambda)$", "$\\lambda^2-5$"], 0,
          "Upper triangular: product of diagonal factors."),
        q("Eigenvalues of $\\begin{pmatrix}1&4\\\\2&3\\end{pmatrix}$ solve:",
          ["$\\lambda^2-4\\lambda-5=0$", "$\\lambda^2-4\\lambda+5=0$", "$\\lambda^2+4\\lambda-5=0$"], 0,
          "$\\det\\begin{pmatrix}1-\\lambda&4\\\\2&3-\\lambda\\end{pmatrix}=(1-\\lambda)(3-\\lambda)-8=\\lambda^2-4\\lambda-5$."),
        q("The roots of $\\lambda^2-4\\lambda-5=0$ are:",
          ["$\\lambda=5$ and $\\lambda=-1$", "$\\lambda=4$ and $\\lambda=1$", "$\\lambda=5$ and $\\lambda=1$"], 0,
          "$(\\lambda-5)(\\lambda+1)=0$."),
        q("For any square $A$, $\\operatorname{tr}(A)$ equals:",
          ["The sum of eigenvalues (counting multiplicity)", "The product of eigenvalues", "Always $0$"], 0,
          "Trace–eigenvalue identity."),
        q("$\\det A$ equals:",
          ["The product of the eigenvalues", "The sum of the eigenvalues", "The largest eigenvalue"], 0,
          "Constant term of the characteristic polynomial."),
        q("Algebraic multiplicity of an eigenvalue is:",
          ["Its multiplicity as a root of the characteristic polynomial", "The dimension of its eigenspace", "Always $1$"], 0,
          "That is the definition of algebraic multiplicity."),
        q("For $A=\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$, the characteristic polynomial is:",
          ["$\\lambda^2+1$", "$\\lambda^2-1$", "$\\lambda^2$"], 0,
          "$\\det\\begin{pmatrix}-\\lambda&-1\\\\1&-\\lambda\\end{pmatrix}=\\lambda^2+1$."),
        q("Eigenvalues of the $90^\\circ$ rotation matrix $\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$ are:",
          ["$\\pm i$", "$\\pm 1$", "$0$ (double)"], 0,
          "Roots of $\\lambda^2+1=0$."),
        q("Characteristic polynomial of $\\begin{pmatrix}5&0&0\\\\0&5&0\\\\0&0&2\\end{pmatrix}$ is:",
          ["$(5-\\lambda)^2(2-\\lambda)$", "$(5-\\lambda)(2-\\lambda)$", "$\\lambda^3-5$"], 0,
          "Diagonal matrix: product of $(a_{ii}-\\lambda)$."),
        q("If eigenvalues of a $2\\times 2$ matrix are $3$ and $7$, then $\\operatorname{tr}(A)$ equals:",
          ["$10$", "$21$", "$4$"], 0,
          "$3+7=10$."),
        q("If eigenvalues are $2$ and $-4$, then $\\det A$ equals:",
          ["$-8$", "$-2$", "$8$"], 0,
          "Product $2\\cdot(-4)=-8$."),
        q("For $A=\\begin{pmatrix}4&1\\\\0&4\\end{pmatrix}$, algebraic multiplicity of $\\lambda=4$ is:",
          ["$2$", "$1$", "$0$"], 0,
          "$\\det(A-\\lambda I)=(4-\\lambda)^2$."),
        q("Expand $\\det\\begin{pmatrix}1-\\lambda&2\\\\2&1-\\lambda\\end{pmatrix}$:",
          ["$(1-\\lambda)^2-4$", "$(1-\\lambda)^2+4$", "$1-\\lambda-4$"], 0,
          "Difference of products of diagonals minus off-diagonals."),
        q("A $3\\times 3$ matrix with eigenvalues $1,1,2$ has determinant:",
          ["$2$", "$4$", "$1$"], 0,
          "Product $1\\cdot 1\\cdot 2=2$."),
    ]

    banks["LA_E_DIAG_QUIZ"] = [
        q("A matrix $A$ is diagonalizable if $A=PDP^{-1}$ for invertible $P$ and diagonal $D$, which requires:",
          ["A basis of eigenvectors", "All eigenvalues equal", "$\\det A=0$"], 0,
          "Columns of $P$ must be independent eigenvectors."),
        q("For $A=\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$, one may take $P=I$ and $D=$:",
          ["$\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$", "$\\begin{pmatrix}0&2\\\\5&0\\end{pmatrix}$", "$I$"], 0,
          "Already diagonal."),
        q("Geometric multiplicity of $\\lambda$ is:",
          ["$\\dim\\operatorname{Null}(A-\\lambda I)$", "Its algebraic multiplicity always", "The trace of $A$"], 0,
          "Dimension of the eigenspace."),
        q("If algebraic multiplicity exceeds geometric multiplicity for some $\\lambda$, then $A$ is:",
          ["Not diagonalizable (defective)", "Orthogonally diagonalizable", "Singular only"], 0,
          "Too few independent eigenvectors."),
        q("Symmetric real matrices are:",
          ["Orthogonally diagonalizable", "Never diagonalizable", "Always singular"], 0,
          "Spectral theorem for real symmetric matrices."),
        q("For $A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$, geometric multiplicity of $\\lambda=1$ is:",
          ["$1$", "$2$", "$0$"], 0,
          "$(A-I)=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$ has nullity $1$, so $A$ is defective."),
        q("If $A=PDP^{-1}$ with $D=\\operatorname{diag}(2,3)$, then $A^5=PD^5P^{-1}$ with $D^5=$:",
          ["$\\operatorname{diag}(32,243)$", "$\\operatorname{diag}(10,15)$", "$\\operatorname{diag}(2,3)$"], 0,
          "Powers act entrywise on a diagonal matrix: $2^5=32$, $3^5=243$."),
        q("A $2\\times 2$ matrix with two distinct eigenvalues is:",
          ["Diagonalizable", "Defective", "Singular"], 0,
          "Distinct eigenvalues give independent eigenvectors."),
        q("Building $P$ for $A=\\begin{pmatrix}3&0\\\\0&1\\end{pmatrix}$ with eigenvalues $3,1$ can use columns:",
          ["$\\begin{pmatrix}1\\\\0\\end{pmatrix},\\begin{pmatrix}0\\\\1\\end{pmatrix}$", "$\\begin{pmatrix}1\\\\1\\end{pmatrix},\\begin{pmatrix}1\\\\1\\end{pmatrix}$", "$\\begin{pmatrix}0\\\\1\\end{pmatrix},\\begin{pmatrix}0\\\\1\\end{pmatrix}$"], 0,
          "Standard basis vectors are eigenvectors."),
        q("If $A$ has a full set of $n$ independent eigenvectors in $\\mathbb{R}^n$, then:",
          ["$A$ is diagonalizable", "$A$ has eigenvalue $0$", "$A$ is triangular"], 0,
          "Those vectors form the columns of $P$."),
        q("For defective $A=\\begin{pmatrix}4&1\\\\0&4\\end{pmatrix}$, which fails?",
          ["Finding two independent eigenvectors for $\\lambda=4$", "Computing $\\det(A-\\lambda I)$", "Finding algebraic multiplicity $2$"], 0,
          "Only a one-dimensional eigenspace exists."),
        q("If $D=\\operatorname{diag}(\\lambda_1,\\lambda_2)$ and $A=PDP^{-1}$, eigenvalues of $A$ are:",
          ["$\\lambda_1$ and $\\lambda_2$", "Always $1$", "The entries of $P$"], 0,
          "Similar matrices share eigenvalues."),
        q("Orthogonal diagonalization means $P$ may be chosen:",
          ["Orthogonal ($P^T=P^{-1}$)", "Singular", "Strictly triangular"], 0,
          "Orthonormal eigenvector basis."),
        q("Compute $A^2$ via diagonalization when $D=\\operatorname{diag}(1,-1)$: $D^2$ equals:",
          ["$I$", "$-I$", "$D$"], 0,
          "$1^2=(-1)^2=1$."),
        q("A $3\\times 3$ matrix with eigenvalues $2,2,2$ is diagonalizable iff:",
          ["Geometric multiplicity of $2$ is $3$", "Algebraic multiplicity is $1$", "$\\det A=0$"], 0,
          "Need three independent eigenvectors."),
    ]

    banks["LA_E_APPS_QUIZ"] = [
        q("For a Markov transition matrix, long-run behavior is governed by the eigenvalue:",
          ["$\\lambda=1$ (steady state)", "$\\lambda=0$ only", "The smallest $|\\lambda|$"], 0,
          "Stochastic matrices have dominant eigenvalue $1$ with a steady-state eigenvector."),
        q("The discrete system $\\mathbf{x}_{k+1}=A\\mathbf{x}_k$ is stable (tends to $\\mathbf{0}$) when every eigenvalue satisfies:",
          ["$|\\lambda|<1$", "$|\\lambda|>1$", "$\\lambda=1$"], 0,
          "Powers $\\lambda^k\\to 0$ iff $|\\lambda|<1$."),
        q("If $A=PDP^{-1}$ with $D=\\operatorname{diag}(0.5,0.2)$, then $A^k\\mathbf{x}$ tends to:",
          ["$\\mathbf{0}$", "A nonzero steady state", "Infinity"], 0,
          "Both $|\\lambda|<1$, so powers vanish."),
        q("Principal component directions of a covariance matrix are:",
          ["Its eigenvectors", "Its nullspace only", "Random unit vectors"], 0,
          "PCA diagonalizes the covariance via eigenvectors."),
        q("For $\\mathbf{x}'=A\\mathbf{x}$ with eigenvalues $-2$ and $-5$, the origin is:",
          ["Asymptotically stable", "Unstable", "A center with pure oscillation"], 0,
          "Negative real parts imply decay of solutions."),
        q("The power method approximates the eigenvector for:",
          ["The dominant eigenvalue (largest $|\\lambda|$)", "The smallest $|\\lambda|$", "Eigenvalue $0$ only"], 0,
          "Repeated multiplication amplifies the dominant mode."),
        q("If a mass-spring mode has eigenvalue $-\\omega^2$ for $A$ in $\\mathbf{x}''=A\\mathbf{x}$, the oscillation frequency relates to:",
          ["$\\omega$", "$\\omega^2$ alone as amplitude", "Trace of $A$ only"], 0,
          "Solutions behave like $\\cos(\\omega t)$ and $\\sin(\\omega t)$."),
        q("A transition matrix $P=\\begin{pmatrix}0.9&0.2\\\\0.1&0.8\\end{pmatrix}$ has steady state proportional to the eigenvector for:",
          ["$\\lambda=1$", "$\\lambda=0.7$", "$\\lambda=0$"], 0,
          "Columns sum to $1$; eigenvalue $1$ gives the invariant distribution."),
        q("If the dominant eigenvalue of $A$ is $3$ with eigenvector $\\mathbf{v}$, then $A^k\\mathbf{x}$ grows roughly like:",
          ["$3^k$ times a multiple of $\\mathbf{v}$", "$k^3\\mathbf{v}$", "$\\mathbf{v}$ only"], 0,
          "The dominant term is $c\\,3^k\\mathbf{v}$."),
        q("For $\\mathbf{x}'=A\\mathbf{x}$ with a pair of complex eigenvalues $a\\pm bi$ and $a>0$, solutions:",
          ["Spiral outward", "Spiral inward to $\\mathbf{0}$", "Stay on ellipses"], 0,
          "Positive real part produces growing amplitude."),
        q("In PCA, the first principal component maximizes variance along:",
          ["The eigenvector for the largest eigenvalue of the covariance", "The smallest eigenvalue direction", "A random orthogonal vector"], 0,
          "Largest eigenvalue means greatest variance."),
        q("If all $|\\lambda|$ of a transition matrix besides $\\lambda=1$ are less than $1$, iterates $P^k\\mathbf{x}$:",
          ["Converge to the steady state", "Diverge", "Oscillate with growing amplitude"], 0,
          "Transient modes decay."),
        q("A vibration mode shape is typically an:",
          ["Eigenvector of the system matrix", "Row of the identity only", "Arbitrary forcing vector"], 0,
          "Normal modes are eigen-directions."),
        q("For $A=\\begin{pmatrix}0.5&0\\\\0&2\\end{pmatrix}$, repeated application $A^k$ makes the second component:",
          ["Grow like $2^k$", "Decay like $(1/2)^k$", "Stay constant"], 0,
          "Eigenvalue $2$ dominates growth in that coordinate."),
        q("Stability of $\\mathbf{x}_{k+1}=A\\mathbf{x}_k$ fails if some eigenvalue has:",
          ["$|\\lambda|>1$", "$\\operatorname{Re}(\\lambda)<0$", "$\\lambda=0$"], 0,
          "Any spectral radius above $1$ causes blow-up."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "laVectorsMatricesQuizzes.js",
        "/** Study-guide quiz banks for the Linear Algebra Vectors and Matrices guides — 15 MCQs per section. */",
        build_vectors_matrices(),
    )
    emit_file(
        OUT / "laSystemsEigenQuizzes.js",
        "/** Study-guide quiz banks for the Linear Algebra Systems and Eigenvalues guides — 15 MCQs per section. */",
        build_systems_eigen(),
    )
