# -*- coding: utf-8 -*-
"""Emit mvIntegralsStokesQuizzes.js — Multiple Integrals and Stokes banks."""
from _quiz_emit import q, emit_file, OUT


def build():
    banks = {}

    banks["MV_INTEGRALS_P1_QUIZ"] = [
        q("Evaluate $\\int_0^1\\int_0^2 xy\\,dx\\,dy$.",
          ["$1$", "$2$", "$1/2$"], 0, "Inner integral gives $2y$; $\\int_0^1 2y\\,dy=1$."),
        q("Evaluate $\\int_0^1\\int_0^x 2\\,dy\\,dx$.",
          ["$1$", "$2$", "$1/2$"], 0, "Inner integral gives $2x$; $\\int_0^1 2x\\,dx=1$."),
        q("Region $0\\le y\\le 1-x$, $0\\le x\\le 1$ is Type I. Its area equals:",
          ["$1/2$", "$1$", "$2$"], 0, "$\\int_0^1(1-x)\\,dx=1/2$."),
        q("Switching order for $\\int_0^1\\int_x^1 f(x,y)\\,dy\\,dx$ yields:",
          ["$\\int_0^1\\int_0^y f(x,y)\\,dx\\,dy$", "$\\int_0^1\\int_0^x f\\,dx\\,dy$", "$\\int_0^1\\int_y^1 f\\,dx\\,dy$"], 0,
          "Triangle under $y=1$ and above $y=x$."),
        q("Volume under $z=1-x$ over $0\\le x\\le 1$, $0\\le y\\le 1$ equals:",
          ["$1/2$", "$1$", "$0$"], 0, "$\\int_0^1\\int_0^1(1-x)\\,dy\\,dx=1/2$."),
        q("Evaluate $\\int_0^2\\int_0^1 (2x+3y)\\,dy\\,dx$.",
          ["$7$", "$5$", "$4$"], 0, "Inner: $2x+3/2$; then $[x^2+(3/2)x]_0^2=4+3=7$."),
        q("For the box $[0,1]\\times[0,2]\\times[0,3]$, $\\iiint 1\\,dV$ equals:",
          ["$6$", "$5$", "$3$"], 0, "Product of side lengths."),
        q("Evaluate $\\int_0^1\\int_0^{1-x} dy\\,dx$.",
          ["$1/2$", "$1$", "$2$"], 0, "Area of the right triangle with legs of length $1$."),
        q("Set up $\\iint_D y\\,dA$ for $D$: $x^2\\le y\\le 1$, $-1\\le x\\le 1$ as:",
          ["$\\int_{-1}^1\\int_{x^2}^1 y\\,dy\\,dx$", "$\\int_0^1\\int_{-1}^1 y\\,dx\\,dy$", "$\\int_{-1}^1\\int_0^{x^2} y\\,dy\\,dx$"], 0,
          "Vertical strips from the parabola up to $y=1$."),
        q("Evaluate $\\int_1^2\\int_0^3 4\\,dx\\,dy$.",
          ["$12$", "$6$", "$24$"], 0, "Inner width $3$; $\\int_1^2 12\\,dy=12$."),
        q("If $R=[0,1]\\times[0,1]$ and $f(x,y)=x$, then $\\iint_R f\\,dA$ equals:",
          ["$1/2$", "$1$", "$0$"], 0, "$\\int_0^1\\int_0^1 x\\,dy\\,dx=1/2$."),
        q("Evaluate $\\int_0^1\\int_0^1\\int_0^1 (x+y+z)\\,dz\\,dy\\,dx$.",
          ["$3/2$", "$1$", "$2$"], 0, "Inner in $z$ gives $x+y+1/2$; then double integral equals $3/2$."),
        q("By Fubini, if $f$ is continuous on a closed rectangle, the two iterated integrals:",
          ["May be swapped freely", "Must keep the written order", "Equal only if $f=0$"], 0,
          "Continuity on a closed rectangle allows order swap."),
        q("Type II region describes $x$ as:",
          ["Functions of $y$ between horizontal lines", "Functions of $x$ between vertical lines", "Polar $r(\\theta)$ only"], 0,
          "Type II: $g_1(y)\\le x\\le g_2(y)$."),
        q("Evaluate $\\int_0^2\\int_y^2 e^{x}\\,dx\\,dy$.",
          ["$e^2+1$", "$e^2-1$", "$2e^2$"], 0,
          "Inner: $e^2-e^y$; then $\\int_0^2(e^2-e^y)\\,dy=e^2+1$."),
    ]

    banks["MV_INTEGRALS_P2_QUIZ"] = [
        q("In polar coordinates, $dA$ becomes:",
          ["$r\\,dr\\,d\\theta$", "$dr\\,d\\theta$", "$r^2\\,dr\\,d\\theta$"], 0, "Jacobian factor $r$."),
        q("Evaluate $\\iint_D (x^2+y^2)\\,dA$ over the unit disk using polar.",
          ["$\\pi/2$", "$\\pi$", "$1/2$"], 0, "$\\int_0^{2\\pi}\\int_0^1 r^2\\cdot r\\,dr\\,d\\theta=2\\pi/4=\\pi/2$."),
        q("Cylindrical coordinates use the volume element:",
          ["$r\\,dr\\,d\\theta\\,dz$", "$\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta$", "$dx\\,dy\\,dz$ only"], 0,
          "Cylindrical Jacobian."),
        q("Spherical volume element is:",
          ["$\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta$", "$\\rho\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta$", "$r\\,dr\\,d\\theta\\,dz$"], 0,
          "Standard spherical Jacobian."),
        q("Convert $x^2+y^2=4$ to polar:",
          ["$r=2$", "$r=4$", "$\\theta=2$"], 0, "$r^2=4\\Rightarrow r=2$."),
        q("Jacobian of $x=u+v$, $y=u-v$ has absolute value:",
          ["$2$", "$1$", "$0$"], 0, "$\\det\\begin{pmatrix}1&1\\\\1&-1\\end{pmatrix}=-2$."),
        q("For the unit ball in spherical coordinates, $\\iiint 1\\,dV$ equals:",
          ["$4\\pi/3$", "$2\\pi$", "$\\pi$"], 0, "Volume of the unit ball."),
        q("Polar limits for the quarter disk $x\\ge 0$, $y\\ge 0$, $x^2+y^2\\le 9$:",
          ["$0\\le\\theta\\le\\pi/2$, $0\\le r\\le 3$", "$0\\le\\theta\\le\\pi$, $0\\le r\\le 9$", "$0\\le\\theta\\le 2\\pi$, $0\\le r\\le 3$"], 0,
          "First quadrant, radius $3$."),
        q("Evaluate $\\int_0^{2\\pi}\\int_0^2 r\\,dr\\,d\\theta$.",
          ["$4\\pi$", "$2\\pi$", "$\\pi$"], 0, "Area of the disk of radius $2$."),
        q("Ice-cream cone region: $\\rho\\le 1$, $0\\le\\phi\\le\\pi/2$ has volume:",
          ["$2\\pi/3$", "$4\\pi/3$", "$\\pi/3$"], 0,
          "Upper hemisphere volume is half of $4\\pi/3$."),
        q("Centroid $\\bar x$ for a lamina of density $1$ is:",
          ["$\\dfrac{1}{A}\\iint_D x\\,dA$", "$\\iint_D x\\,dA$", "$\\iint_D y\\,dA$"], 0,
          "First moment divided by mass (here area)."),
        q("Evaluate $\\int_0^{\\pi/2}\\int_0^{\\cos\\theta} r\\,dr\\,d\\theta$.",
          ["$\\pi/8$", "$1/2$", "$\\pi/4$"], 0,
          "Inner: $(\\cos^2\\theta)/2$; $\\int_0^{\\pi/2}\\cos^2\\theta\\,d\\theta=\\pi/4$, so total $\\pi/8$."),
        q("In spherical coordinates, $\\rho$ measures:",
          ["Distance from the origin", "Distance from the $z$-axis", "The polar angle"], 0,
          "Definition of $\\rho$."),
        q("Cylindrical $r$ equals:",
          ["$\\sqrt{x^2+y^2}$", "$\\sqrt{x^2+y^2+z^2}$", "$|z|$"], 0,
          "Distance to the $z$-axis."),
        q("Mass of the unit disk with density $\\delta(x,y)=x^2+y^2$ equals:",
          ["$\\pi/2$", "$\\pi$", "$1/4$"], 0,
          "Same polar integral as $\\iint_D r^2\\,dA$ over the unit disk."),
    ]

    banks["MV_STOKES_F_QUIZ"] = [
        q("For $\\mathbf F=\\langle -y,x,0\\rangle$, $\\nabla\\times\\mathbf F$ equals:",
          ["$\\langle 0,0,2\\rangle$", "$\\langle 0,0,0\\rangle$", "$\\langle 0,0,1\\rangle$"], 0,
          "$Q_x-P_y=1-(-1)=2$."),
        q("Compute $\\nabla\\times\\langle yz,xz,xy\\rangle$:",
          ["$\\langle 0,0,0\\rangle$", "$\\langle 1,1,1\\rangle$", "$\\langle y,x,0\\rangle$"], 0,
          "Each curl component cancels."),
        q("Evaluate $\\nabla\\times\\langle 0,-z,y\\rangle$:",
          ["$\\langle 2,0,0\\rangle$", "$\\langle 0,0,0\\rangle$", "$\\langle 0,1,-1\\rangle$"], 0,
          "$\\mathbf i(1-(-1))=2\\mathbf i$."),
        q("For $\\mathbf F=\\langle -y,x\\rangle$ in 2D, the Green integrand $Q_x-P_y$ equals:",
          ["$2$", "$0$", "$1$"], 0, "$1-(-1)=2$."),
        q("Stokes' theorem equates $\\oint_C\\mathbf F\\cdot d\\mathbf r$ with:",
          ["$\\iint_S(\\nabla\\times\\mathbf F)\\cdot\\mathbf n\\,dS$", "$\\iiint_E\\nabla\\cdot\\mathbf F\\,dV$", "$\\iint_S\\mathbf F\\cdot\\mathbf n\\,dS$"], 0,
          "Circulation equals curl flux."),
        q("If $\\nabla\\times\\mathbf F=\\mathbf 0$ on a simply connected domain, circulation around a closed curve is:",
          ["$0$", "Always $1$", "Equal to flux"], 0, "Stokes gives zero."),
        q("The boundary of the upper unit hemisphere (equator) is:",
          ["The unit circle in $z=0$", "A meridian arc", "The whole sphere"], 0,
          "Equatorial circle."),
        q("Green's theorem is Stokes in the plane with normal:",
          ["$\\mathbf k$", "$\\mathbf i$", "$-\\mathbf j$"], 0, "Flat surface in the $xy$-plane."),
        q("Compute $\\nabla\\times\\langle z,x,y\\rangle$:",
          ["$\\langle 1,1,1\\rangle$", "$\\langle 0,0,0\\rangle$", "$\\langle 1,-1,1\\rangle$"], 0,
          "$\\langle 1-0,\\,1-0,\\,1-0\\rangle$."),
        q("Unit normal upward on the graph $z=g(x,y)$ is proportional to:",
          ["$\\langle -g_x,-g_y,1\\rangle$", "$\\langle g_x,g_y,1\\rangle$", "$\\langle 1,0,0\\rangle$"], 0,
          "Graph orientation with positive $z$-component."),
        q("If $S_1$ and $S_2$ share the oriented boundary $C$, Stokes says their curl fluxes:",
          ["Are equal", "Differ by volume", "Must both be zero"], 0,
          "Both equal $\\oint_C\\mathbf F\\cdot d\\mathbf r$."),
        q("Evaluate $(\\nabla\\times\\langle y,-x,z\\rangle)\\cdot\\mathbf k$:",
          ["$-2$", "$2$", "$0$"], 0, "$Q_x-P_y=-1-1=-2$."),
        q("Circulation of a conservative field around a closed curve is:",
          ["$0$", "Equal to $|\\mathbf F|$", "Path-dependent"], 0,
          "Fundamental theorem for line integrals."),
        q("For oriented surface $S$, the vector $\\mathbf n$ in Stokes is:",
          ["A continuous unit normal matching the orientation", "Always $\\langle 0,0,1\\rangle$", "The binormal of every curve"], 0,
          "Orientation data for the surface."),
        q("Orientation: the right-hand rule links:",
          ["Boundary direction to the chosen normal", "Curl to divergence", "Only path length to area"], 0,
          "Consistent orientation of $C$ and $\\mathbf n$."),
    ]

    banks["MV_STOKES_A_QUIZ"] = [
        q("For $\\mathbf F=\\langle -y,x,0\\rangle$ around the unit circle, Stokes on the unit disk gives circulation:",
          ["$2\\pi$", "$\\pi$", "$0$"], 0,
          "Curl is $2\\mathbf k$; flux $2\\cdot\\mathrm{area}=2\\pi$."),
        q("For the same field, using the upper hemisphere instead of the disk yields:",
          ["The same $2\\pi$", "$4\\pi$", "$0$"], 0,
          "Shared boundary; Stokes matches."),
        q("Compute $\\iint_S(\\nabla\\times\\langle y,-x,0\\rangle)\\cdot\\mathbf k\\,dA$ over the unit disk:",
          ["$-2\\pi$", "$2\\pi$", "$0$"], 0, "Curl $=-2\\mathbf k$; integral $-2\\pi$."),
        q("For $\\mathbf F=\\langle z,x,y\\rangle$, $\\nabla\\times\\mathbf F=\\langle 1,1,1\\rangle$. Upward curl flux through the unit disk $z=0$ is:",
          ["$\\pi$", "$0$", "$1$"], 0, "Only the $z$-component $1$ contributes: area $\\pi$."),
        q("Evaluate circulation of $\\langle -y,x,z\\rangle$ around $x^2+y^2=4$, $z=0$ via the disk:",
          ["$8\\pi$", "$4\\pi$", "$2\\pi$"], 0,
          "Curl $=\\langle 0,0,2\\rangle$; $2\\cdot 4\\pi=8\\pi$."),
        q("Compute $\\oint_C\\langle 0,0,x\\rangle\\cdot d\\mathbf r$ for the unit circle $z=0$ via Stokes on the disk:",
          ["$0$", "$\\pi$", "$1$"], 0,
          "Curl $=\\langle 0,-1,0\\rangle$; flux through a horizontal disk is $0$."),
        q("If $\\mathbf F=\\nabla f$, then for any closed $C$ bounding $S$:",
          ["$\\oint_C\\mathbf F\\cdot d\\mathbf r=0$", "Flux of curl is $1$", "Curl equals $\\mathbf F$"], 0,
          "Curl of a gradient vanishes."),
        q("Paraboloid $z=1-x^2-y^2$, $z\\ge 0$, shares its rim with:",
          ["The unit disk in $z=0$", "The sphere of radius $2$", "The plane $z=2$"], 0,
          "Rim is $x^2+y^2=1$, $z=0$."),
        q("Orientation mismatch (opposite normal) multiplies the Stokes integrals by:",
          ["$-1$", "$0$", "$2$"], 0, "Reversing orientation flips sign."),
        q("If curl flux through every surface with boundary $C$ is $5$, then $\\oint_C\\mathbf F\\cdot d\\mathbf r$ equals:",
          ["$5$", "$0$", "$10$"], 0, "Stokes identification."),
        q("For a conservative $\\mathbf F$ in 3D, $\\nabla\\times\\mathbf F$ equals:",
          ["$\\mathbf 0$", "$\\mathbf F$", "$\\nabla\\cdot\\mathbf F$"], 0, "Irrotational."),
        q("Choose the flat disk rather than a wiggly surface with the same rim when:",
          ["Curl is easy to integrate on the disk", "The field is undefined on the disk", "Stokes forbids flat surfaces"], 0,
          "Convenience under Stokes."),
        q("Fluid circulation around a loop equals the flux of:",
          ["Vorticity $\\nabla\\times\\mathbf v$", "Pressure gradient only", "$\\nabla\\cdot\\mathbf v$"], 0,
          "Stokes for the velocity field."),
        q("For $\\mathbf F=\\langle -z,0,x\\rangle$, curl flux through the unit disk $z=0$ upward equals:",
          ["$0$", "$\\pi$", "$-\\pi$"], 0,
          "$\\nabla\\times\\mathbf F=\\langle 0,-2,0\\rangle$; horizontal $z$-component of curl is $0$."),
        q("When verifying orientation, thumb along $\\mathbf n$ means fingers curl with:",
          ["The positive direction of $C$", "The opposite of $C$", "Any radial direction"], 0,
          "Right-hand rule."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "mvIntegralsStokesQuizzes.js",
        "/** Study-guide quiz banks for the Multiple Integrals and Stokes' Theorem guides — 15 MCQs per section. */",
        build(),
    )
