# -*- coding: utf-8 -*-
"""Emit psStatsQuizzes.js — Descriptive stats, hypothesis testing, regression."""
from _quiz_emit import q, emit_file, OUT


def build():
    banks = {}

    banks["PS_D_CENTER_QUIZ"] = [
        q("Find the median of the data set $2, 5, 7, 8, 20$.",
          ["$7$", "$8.4$", "$5$"], 0,
          "With five ordered values the median is the third, which is $7$."),
        q("Mean of $3, 5, 7, 9$ equals:",
          ["$6$", "$5$", "$7$"], 0,
          "$(3+5+7+9)/4=6$."),
        q("Mode of $2, 2, 3, 5, 5, 5, 8$ is:",
          ["$5$", "$2$", "$8$"], 0,
          "Five appears most often."),
        q("For $1, 2, 3, 4, 100$, which measure is most resistant to the outlier?",
          ["Median", "Mean", "Mean of squares"], 0,
          "Median uses order; one extreme barely moves it."),
        q("Adding $5$ to every value in a data set increases the mean by:",
          ["$5$", "$0$", "$25$"], 0,
          "Constants shift the mean by the same amount."),
        q("Multiplying every value by $3$ multiplies the mean by:",
          ["$3$", "$1/3$", "$9$"], 0,
          "Means scale with the data."),
        q("Weighted mean of scores $80$ and $90$ with weights $1$ and $3$ equals:",
          ["$87.5$", "$85$", "$90$"], 0,
          "$(80+270)/4=87.5$."),
        q("Group A mean $70$ with $n=10$; group B mean $90$ with $n=10$. Combined mean is:",
          ["$80$", "$70$", "$90$"], 0,
          "Equal sizes: average of means."),
        q("In a right-skewed distribution, typically:",
          ["Mean $>$ median", "Mean $<$ median", "Mean $=$ mode always"], 0,
          "The long right tail pulls the mean up."),
        q("Median of $4, 1, 9, 7$ (after ordering) equals:",
          ["$5.5$", "$4$", "$7$"], 0,
          "Ordered $1,4,7,9$; average of middle two is $5.5$."),
        q("Data $10, 10, 10, 10$ has mean:",
          ["$10$", "$0$", "$40$"], 0,
          "Constant data mean equals that constant."),
        q("If every observation doubles, the median:",
          ["Doubles", "Stays the same", "Increases by $2$"], 0,
          "Order statistics scale by the same factor."),
        q("For $2, 3, 3, 4$, the mean equals:",
          ["$3$", "$3.5$", "$2$"], 0,
          "Sum $12$ over $4$ observations."),
        q("When incomes are heavily right-skewed, a typical \"center\" report prefers the:",
          ["Median", "Mean alone", "Largest value"], 0,
          "Median better represents a typical income."),
        q("Mean of $-2, 0, 2$ equals:",
          ["$0$", "$2$", "$-2$"], 0,
          "Symmetric about zero."),
    ]

    banks["PS_D_QUANT_QUIZ"] = [
        q("For ordered data $1,3,5,7,9,11,13$, the median $Q_2$ is:",
          ["$7$", "$5$", "$9$"], 0,
          "Middle value of seven observations."),
        q("IQR equals:",
          ["$Q_3-Q_1$", "$Q_3+Q_1$", "$Q_2$"], 0,
          "Interquartile range definition."),
        q("Five-number summary consists of:",
          ["Min, $Q_1$, median, $Q_3$, max", "Mean and five SDs", "Only quartiles"], 0,
          "Classic box-plot ingredients."),
        q("Ordered $2,4,6,8,10,12$: using the common half-sample method, $Q_1$ is approximately:",
          ["$4$", "$2$", "$8$"], 0,
          "Lower half $2,4,6$; median of lower half is $4$."),
        q("A value below $Q_1-1.5\\cdot\\mathrm{IQR}$ is flagged as:",
          ["A low outlier by the $1.5\\cdot\\mathrm{IQR}$ rule", "Always the minimum", "A high outlier"], 0,
          "Tukey fence rule."),
        q("If $Q_1=10$, $Q_3=22$, then IQR equals:",
          ["$12$", "$32$", "$6$"], 0,
          "$22-10=12$."),
        q("Upper fence $Q_3+1.5\\cdot\\mathrm{IQR}$ with $Q_3=22$, $\\mathrm{IQR}=12$ equals:",
          ["$40$", "$34$", "$22$"], 0,
          "$22+18=40$."),
        q("Percentile rank: in ordered $n=20$ distinct scores, the $25$th percentile is near position:",
          ["$5$", "$25$", "$10$"], 0,
          "About $0.25\\times 20=5$."),
        q("Deciles divide ordered data into how many equal-count parts?",
          ["$10$", "$4$", "$100$"], 0,
          "Ten tenths."),
        q("For $1,2,3,4,5,6,7,8$, median equals:",
          ["$4.5$", "$4$", "$5$"], 0,
          "Average of $4$ and $5$."),
        q("If all values equal $7$, then $Q_1$ equals:",
          ["$7$", "$0$", "Undefined always"], 0,
          "Every quartile collapses to $7$."),
        q("Reading the $90$th percentile from a small ordered list means roughly:",
          ["A value with about $90\\%$ of data at or below it", "The mean times $0.9$", "Always the maximum"], 0,
          "Percentile definition."),
        q("For ordered data $1,2,3,4,20$ with $Q_1=1.5$, $Q_3=12$, the upper $1.5\\cdot\\mathrm{IQR}$ fence equals:",
          ["$27.75$", "$20$", "$12$"], 0,
          "IQR $=10.5$, so $12+1.5\\cdot 10.5=27.75$."),
        q("The second quartile $Q_2$ is identical to the:",
          ["Median", "Mean", "Mode always"], 0,
          "By definition."),
        q("Ordered $10,20,30,40,50$: $Q_3$ (median of upper half $30,40,50$) equals:",
          ["$40$", "$30$", "$50$"], 0,
          "Middle of the upper half."),
    ]

    banks["PS_D_SPREAD_QUIZ"] = [
        q("Sample variance of $2,4,6$ uses divisor:",
          ["$n-1=2$", "$n=3$", "$n+1$"], 0,
          "Unbiased sample variance divides by $n-1$."),
        q("For $2,4,6$, sample variance equals:",
          ["$4$", "$8/3$", "$2$"], 0,
          "Mean $4$; squared diffs $4+0+4=8$; $8/2=4$."),
        q("Sample SD of that data equals:",
          ["$2$", "$4$", "$1$"], 0,
          "$\\sqrt{4}=2$."),
        q("Range of $3, 9, 11$ equals:",
          ["$8$", "$11$", "$6$"], 0,
          "$11-3=8$."),
        q("z-score of $x=10$ when $\\bar x=7$, $s=2$ equals:",
          ["$1.5$", "$3$", "$-1.5$"], 0,
          "$(10-7)/2=1.5$."),
        q("Adding $5$ to every observation changes the SD by:",
          ["$0$", "$5$", "Multiplying by $5$"], 0,
          "Shifts cancel in deviations."),
        q("Multiplying every observation by $4$ multiplies the SD by:",
          ["$4$", "$16$", "$1$"], 0,
          "Spread scales by $|a|$."),
        q("Empirical rule: about $68\\%$ of normal data lie within:",
          ["$1$ SD of the mean", "$2$ SDs", "$3$ SDs"], 0,
          "68-95-99.7."),
        q("Coefficient of variation is often:",
          ["$s/\\bar x$ (when $\\bar x\\ne 0$)", "$s\\cdot\\bar x$", "$\\bar x-s$"], 0,
          "Relative spread."),
        q("Population variance of the finite list $1,3$ (divide by $N$) equals:",
          ["$1$", "$2$", "$0$"], 0,
          "Mean $2$; average of squared diffs $(1+1)/2=1$."),
        q("A z-score of $-2$ means the value is:",
          ["Two SDs below the mean", "Two SDs above the mean", "Equal to the mean"], 0,
          "Sign indicates direction."),
        q("If $s=0$, the data:",
          ["Are all equal", "Have mean zero", "Have range $1$"], 0,
          "No variability."),
        q("For normal data with mean $50$ and SD $5$, about $95\\%$ lie between:",
          ["$40$ and $60$", "$45$ and $55$", "$35$ and $65$"], 0,
          "Mean $\\pm 2$ SD."),
        q("Variance cannot be:",
          ["Negative", "Zero", "Positive"], 0,
          "Average of squared deviations."),
        q("If every z-score is computed from the same sample, the mean of the z-scores is:",
          ["$0$", "$1$", "$s$"], 0,
          "Standardization centers at zero."),
    ]

    banks["PS_D_PLOTS_QUIZ"] = [
        q("A histogram with a long right tail is described as:",
          ["Right-skewed", "Left-skewed", "Symmetric perfect bell always"], 0,
          "Tail direction names the skew."),
        q("In a box plot, the box spans roughly:",
          ["$Q_1$ to $Q_3$", "Mean $\\pm$ SD", "Min to max only"], 0,
          "The box is the IQR."),
        q("Whiskers on a standard Tukey box plot typically extend to:",
          ["The most extreme non-outlier points within the fences", "Always $\\pm 3$ SD", "Only the mean"], 0,
          "Outliers plotted beyond whiskers."),
        q("A stem-and-leaf plot preserves:",
          ["Individual data values", "Only the mean", "Only ranks"], 0,
          "Digits remain readable."),
        q("A scatterplot displays:",
          ["Paired $(x,y)$ observations", "A single categorical variable only", "Only means"], 0,
          "Two quantitative variables."),
        q("Two peaks in a histogram suggest:",
          ["Bimodality", "Zero variance", "Perfect normality"], 0,
          "Two modes."),
        q("For categorical counts, a natural display is a:",
          ["Bar chart", "Scatterplot of residuals only", "Normal QQ of means only"], 0,
          "Bars for categories."),
        q("A point plotted beyond the whiskers on a box plot is:",
          ["Flagged as a potential outlier", "Always deleted", "The median"], 0,
          "Visual outlier marker."),
        q("A symmetric unimodal histogram is consistent with a:",
          ["Bell-shaped (roughly normal) pattern", "Strong right skew only", "Deterministic line"], 0,
          "Mirror image about the center."),
        q("Comparing spreads side-by-side often uses:",
          ["Parallel box plots", "A single pie chart", "Only means"], 0,
          "Boxes show IQRs visually."),
        q("If a histogram is left-skewed, the left side has:",
          ["The longer tail", "No data", "Higher bars only on the right always"], 0,
          "Skew named by the long tail."),
        q("A time plot of a series against time helps spot:",
          ["Trends and seasonality", "Only the mode", "Independence automatically"], 0,
          "Temporal structure."),
        q("Dots stacked in a dotplot show:",
          ["Frequencies of values", "Regression slopes", "p-values"], 0,
          "Each dot is an observation."),
        q("A flat uniform-looking histogram suggests:",
          ["Roughly similar frequencies across bins", "A single spike", "Zero mean"], 0,
          "Even heights."),
        q("Choosing a plot: relationship between height and weight is best shown by a:",
          ["Scatterplot", "Pie chart", "Single box without axes"], 0,
          "Two quantitative variables."),
    ]

    banks["PS_H_FRAMEWORK_QUIZ"] = [
        q("To test if a coin is fair, a usual $H_0$ is:",
          ["$p=1/2$", "$p\\ne 1/2$", "$p>1/2$ only"], 0,
          "Null states the status-quo fairness."),
        q("The alternative $H_a:p>1/2$ is:",
          ["One-sided (right-tailed)", "Two-sided", "Not a hypothesis"], 0,
          "Direction specified."),
        q("Significance level $\\alpha$ is:",
          ["The Type I error rate threshold set before seeing data", "The p-value always", "Power"], 0,
          "Prechosen false-reject rate."),
        q("Rejecting $H_0$ means:",
          ["Data are sufficiently incompatible with $H_0$ at level $\\alpha$", "$H_0$ is proven false with certainty", "$H_a$ has probability $\\alpha$"], 0,
          "Decision under a chosen threshold."),
        q("We do not say we \"accept $H_0$\" because:",
          ["Failure to reject is not proof that $H_0$ is true", "p-values are always $1$", "$\\alpha$ must be $0$"], 0,
          "Absence of evidence is not evidence of absence."),
        q("A two-sided test of a mean uses $H_a$ of the form:",
          ["$\\mu\\ne \\mu_0$", "$\\mu>\\mu_0$ only", "$\\mu=\\mu_0$"], 0,
          "Both directions."),
        q("The test statistic measures:",
          ["How far the estimate sits from $H_0$, in SE units", "Only sample size", "Only $\\alpha$"], 0,
          "Standardized discrepancy."),
        q("Choose $\\alpha$:",
          ["Before looking at the p-value", "After maximizing the p-value", "Only after rejecting"], 0,
          "Avoid data-dependent thresholds."),
        q("If $H_0:\\mu=10$ and the interval estimate lies entirely above $10$, a two-sided test at the matching level tends to:",
          ["Reject $H_0$", "Increase $\\alpha$ automatically", "Prove $\\mu=10$"], 0,
          "CI/test duality."),
        q("For $H_0:\\mu=0$ vs $H_a:\\mu<0$, extreme negative statistics support:",
          ["$H_a$", "$H_0$", "Neither ever"], 0,
          "Left-tail alternatives."),
        q("Statistically significant at $5\\%$ means roughly:",
          ["p-value $\\le 0.05$", "p-value $=0.5$", "Sample size $<5$"], 0,
          "Compare $p$ to $\\alpha$."),
        q("Null hypotheses are often statements of:",
          ["No effect / no difference", "Surely large effects", "Randomization failure"], 0,
          "Baseline claims."),
        q("A hypothesis about a population parameter is:",
          ["A claim about the population, not about the sample alone", "Always equal to the sample mean", "A random variable"], 0,
          "Parameters are fixed unknowns in the classical setup."),
        q("Increasing $\\alpha$ makes rejecting $H_0$:",
          ["Easier (more Type I risk)", "Impossible", "Independent of data"], 0,
          "Larger reject region."),
        q("The phrase \"fail to reject $H_0$\" indicates:",
          ["Insufficient evidence against $H_0$ at the chosen $\\alpha$", "Proof that $H_0$ holds", "That $\\beta=0$"], 0,
          "Conservative language."),
    ]

    banks["PS_H_TESTS_QUIZ"] = [
        q("z-statistic $(\\bar x-\\mu_0)/(\\sigma/\\sqrt{n})$ with $\\bar x=52$, $\\mu_0=50$, $\\sigma=4$, $n=16$ equals:",
          ["$2$", "$0.5$", "$8$"], 0,
          "$(2)/(4/4)=2$."),
        q("For a one-sample $t$ with $n=20$, degrees of freedom equal:",
          ["$19$", "$20$", "$21$"], 0,
          "$n-1$."),
        q("Use $t$ instead of $z$ for a mean when:",
          ["$\\sigma$ is unknown and data are roughly normal / $n$ large", "$\\sigma$ is known exactly", "The parameter is a proportion with huge $n$ and known $p_0$ only"], 0,
          "Unknown SD leads to $t$."),
        q("One-proportion $z$: $\\hat p=0.6$, $p_0=0.5$, $n=100$. SE under $H_0$ is:",
          ["$0.05$", "$0.06$", "$0.5$"], 0,
          "$\\sqrt{p_0(1-p_0)/n}=\\sqrt{0.25/100}=0.05$."),
        q("That proportion $z$ statistic equals:",
          ["$2$", "$1$", "$0.1$"], 0,
          "$(0.6-0.5)/0.05=2$."),
        q("Critical value for two-sided $z$ at $\\alpha=0.05$ is about:",
          ["$1.96$", "$1.645$", "$2.576$"], 0,
          "Standard normal quantile."),
        q("Right-tailed $z$ at $\\alpha=0.05$ uses critical value about:",
          ["$1.645$", "$1.96$", "$0.05$"], 0,
          "Upper $5\\%$ point."),
        q("If a $95\\%$ CI for $\\mu$ is $(1.1, 2.3)$ and $H_0:\\mu=0$, then at $\\alpha=0.05$ two-sided we:",
          ["Reject $H_0$", "Fail to reject $H_0$", "Cannot decide from a CI"], 0,
          "Zero is outside the interval."),
        q("Test statistic for $H_0:\\mu=10$ with $\\bar x=10$ equals:",
          ["$0$", "$10$", "$1$"], 0,
          "No deviation from null."),
        q("Larger $n$ with the same $\\bar x-\\mu_0$ and $\\sigma$ makes $|z|$:",
          ["Larger", "Smaller", "Unchanged"], 0,
          "SE shrinks like $1/\\sqrt{n}$."),
        q("A one-sample $t$ formula replaces $\\sigma$ with:",
          ["$s$", "$\\bar x$", "$n$"], 0,
          "Sample SD."),
        q("For proportions, the null SE uses:",
          ["$p_0$, not $\\hat p$", "Only $\\hat p$", "Only $n$"], 0,
          "Standardize under $H_0$."),
        q("If $|z|=2.5$ in a two-sided $z$-test with critical $1.96$, decision is:",
          ["Reject $H_0$", "Fail to reject", "Increase $n$ mandatorily"], 0,
          "Beyond the critical value."),
        q("Matched pairs mean difference uses essentially a:",
          ["One-sample $t$ on differences", "Two-proportion $z$ only", "Chi-square with $0$ df"], 0,
          "Reduce to one sample."),
        q("Given $\\bar x=25$, $s=5$, $n=9$, $\\mu_0=20$, the $t$ statistic equals:",
          ["$3$", "$1$", "$5$"], 0,
          "$(5)/(5/3)=3$."),
    ]

    banks["PS_H_PVAL_QUIZ"] = [
        q("A p-value is the probability, under $H_0$, of:",
          ["A test statistic at least as extreme as observed", "$H_0$ being true", "Making a Type II error"], 0,
          "Tail probability under the null sampling distribution."),
        q("For a right-tailed $z$-test with $z=1.96$, the p-value is about:",
          ["$0.025$", "$0.05$", "$0.975$"], 0,
          "Upper-tail standard normal probability."),
        q("Two-sided p-value from $z=1.96$ is about:",
          ["$0.05$", "$0.025$", "$0.10$"], 0,
          "Double the one-sided tail."),
        q("If $p=0.03$ and $\\alpha=0.05$, we:",
          ["Reject $H_0$", "Fail to reject $H_0$", "Accept $H_0$ as proven"], 0,
          "$p\\le\\alpha$."),
        q("If $p=0.20$ and $\\alpha=0.05$, we:",
          ["Fail to reject $H_0$", "Reject $H_0$", "Set $\\alpha=0.20$"], 0,
          "Evidence not strong enough."),
        q("A p-value is NOT:",
          ["The probability that $H_0$ is true", "A tail probability under $H_0$", "Dependent on the alternative's direction"], 0,
          "Common misinterpretation."),
        q("Larger samples tend to produce smaller p-values for the same nonzero effect because:",
          ["The statistic's SE shrinks, enlarging $|z|$ or $|t|$", "Alpha automatically grows", "Data become discrete"], 0,
          "Precision increases."),
        q("Borderline $p=0.049$ vs $0.051$ shows that:",
          ["The $0.05$ cutoff is sharp but evidence is similar", "One proves truth and the other falsehood", "p-values must be integers"], 0,
          "Do not over-read tiny differences."),
        q("Left-tailed test with $z=-2.33$ has p-value about:",
          ["$0.01$", "$0.05$", "$0.99$"], 0,
          "Lower-tail probability near $0.01$."),
        q("Reporting only \"significant\" without the p-value hides:",
          ["The strength of evidence against $H_0$", "The sample size forever", "The definition of mean"], 0,
          "p-values quantify extremity."),
        q("If the alternative is two-sided and the one-sided tail is $0.02$, the two-sided p is:",
          ["$0.04$", "$0.02$", "$0.01$"], 0,
          "Double a symmetric one-sided tail."),
        q("A very large p-value means:",
          ["Data are compatible with $H_0$ (not proof of $H_0$)", "$H_a$ is true", "$\\alpha$ was too small"], 0,
          "Compatibility, not confirmation."),
        q("Computing a p-value requires the distribution of the test statistic under:",
          ["$H_0$", "$H_a$ only", "The posterior of $\\mu$"], 0,
          "Classical p-values are null-based."),
        q("If two-sided $p=0.06$ and $\\alpha=0.05$, the formal decision is:",
          ["Fail to reject $H_0$", "Reject $H_0$", "Accept $H_a$"], 0,
          "Just above the threshold."),
        q("Halving the SE while keeping the effect estimate fixed will generally:",
          ["Decrease the p-value", "Increase the p-value", "Leave $z$ unchanged"], 0,
          "Larger $|z|$."),
    ]

    banks["PS_H_ERRORS_QUIZ"] = [
        q("Type I error is:",
          ["Rejecting $H_0$ when $H_0$ is true", "Failing to reject when $H_a$ is true", "Any computer bug"], 0,
          "False positive decision."),
        q("Type II error is:",
          ["Failing to reject $H_0$ when $H_a$ is true", "Rejecting a true $H_0$", "Setting $\\alpha=0$"], 0,
          "False negative decision."),
        q("$\\alpha$ denotes:",
          ["$P(\\text{Type I error})$ under the chosen test", "Power", "$P(\\text{Type II error})$"], 0,
          "Significance level."),
        q("$\\beta$ denotes:",
          ["$P(\\text{Type II error})$ for a specific alternative", "Always $1-\\alpha$", "The mean"], 0,
          "Depends on the effect size."),
        q("Power equals:",
          ["$1-\\beta$", "$\\alpha$", "$\\beta$"], 0,
          "Probability of correctly rejecting."),
        q("Increasing sample size typically:",
          ["Increases power", "Increases $\\beta$ only", "Forces $\\alpha=1$"], 0,
          "SE shrinks; easier to detect effects."),
        q("Larger true effect size typically:",
          ["Increases power", "Decreases power", "Leaves $\\beta$ fixed by law"], 0,
          "Easier separation from $H_0$."),
        q("Decreasing $\\alpha$ (harder to reject) typically:",
          ["Increases $\\beta$ (trade-off)", "Increases power always", "Eliminates Type II errors"], 0,
          "Stricter tests miss more alternatives."),
        q("In a courtroom analogy, convicting an innocent defendant is like:",
          ["Type I error", "Type II error", "Power"], 0,
          "False rejection of innocence null."),
        q("Letting a guilty defendant go free is like:",
          ["Type II error", "Type I error", "Setting $\\alpha$"], 0,
          "Failure to reject a false null."),
        q("Power depends on:",
          ["$n$, effect size, $\\alpha$, and variability", "Only the letter $H$", "Only whether data are integers"], 0,
          "Multiple design factors."),
        q("If power is $0.8$, then $\\beta$ equals:",
          ["$0.2$", "$0.8$", "$0.05$"], 0,
          "$1-0.8=0.2$."),
        q("For fixed $n$ and $\\alpha$, reducing noise $\\sigma$ generally:",
          ["Raises power", "Raises $\\beta$", "Changes $\\alpha$ automatically"], 0,
          "Clearer signal."),
        q("You cannot make both $\\alpha$ and $\\beta$ arbitrarily small without:",
          ["More data (or larger effects / less noise)", "Renaming errors", "Using $p=1$"], 0,
          "Information limits."),
        q("A test with $\\alpha=0.01$ versus $\\alpha=0.10$, all else equal, has:",
          ["Lower Type I risk and typically lower power", "Higher Type I risk", "Identical rejection regions"], 0,
          "Stricter threshold."),
    ]

    banks["PS_R_CORR_QUIZ"] = [
        q("The correlation $r$ always satisfies:",
          ["$-1\\le r\\le 1$", "$r\\ge 0$", "$r>1$ possible"], 0,
          "Cauchy–Schwarz bound."),
        q("If $r=0.9$, the linear association is:",
          ["Strong and positive", "Strong and negative", "None"], 0,
          "Near $+1$."),
        q("If $y$ is replaced by $10y$, then $r$:",
          ["Stays the same", "Multiplies by $10$", "Becomes $0$"], 0,
          "Correlation is scale-free."),
        q("$r^2=0.64$ means about $64\\%$ of the variance of $y$ is:",
          ["Explained by the linear relation with $x$", "Unexplained noise only", "Equal to $r$"], 0,
          "Coefficient of determination."),
        q("A scatterplot with a clear U-shape can have $r$ near:",
          ["$0$ despite strong nonlinear association", "$1$ always", "$-2$"], 0,
          "Correlation captures linear trend only."),
        q("An outlier far from the cloud can:",
          ["Move $r$ substantially", "Never affect $r$", "Only change the median"], 0,
          "Correlation is not robust."),
        q("The sign of $r$ matches:",
          ["The sign of the least-squares slope", "Always positive", "The sample size"], 0,
          "Same direction."),
        q("If $r=-1$, points lie on:",
          ["A perfect decreasing line", "A perfect horizontal line", "A circle"], 0,
          "Perfect negative linear relation."),
        q("Swapping $x$ and $y$ leaves $r$:",
          ["Unchanged", "Negated", "Squared"], 0,
          "Symmetry of correlation."),
        q("Units of $r$ are:",
          ["None (unitless)", "The units of $y$", "Squared units of $x$"], 0,
          "Standardized."),
        q("If $r=0.2$, linear association is:",
          ["Weak positive", "Strong positive", "Perfect"], 0,
          "Near zero."),
        q("Adding a constant to $x$ changes $r$ by:",
          ["$0$", "That constant", "$-1$"], 0,
          "Location invariance."),
        q("When all points are identical, $r$ is:",
          ["Undefined (no variability)", "$1$", "$0$"], 0,
          "Need variation in both variables."),
        q("If $r^2=1$, residuals from the least-squares line are:",
          ["All zero", "All equal to $1$", "Maximally large"], 0,
          "Perfect fit."),
        q("Correlation near zero with a tight upward line after removing one wild point suggests:",
          ["That point was highly influential on $r$", "Correlation ignores outliers", "$r$ must be $1$ with the point"], 0,
          "Sensitivity demonstration."),
    ]

    banks["PS_R_ASSOC_QUIZ"] = [
        q("High correlation between ice cream sales and drowning does not prove:",
          ["That ice cream causes drowning", "Any association exists", "Seasonality exists"], 0,
          "Correlation is not causation."),
        q("A lurking variable is:",
          ["An unmeasured factor that may drive an observed association", "Always the response", "The intercept"], 0,
          "Confounding threat."),
        q("A randomized experiment is better than an observational study for:",
          ["Supporting causal claims", "Computing $r$ only", "Avoiding all ethics boards"], 0,
          "Random assignment balances confounders."),
        q("Simpson's paradox occurs when:",
          ["A trend reverses after aggregating or disaggregating groups", "$r$ exceeds $1$", "Means equal medians"], 0,
          "Group structure matters."),
        q("Extrapolation means:",
          ["Predicting far outside the observed $x$-range", "Using the median", "Setting $r=0$"], 0,
          "Risky beyond the data."),
        q("Ecological correlation refers to:",
          ["Association computed on aggregated group averages", "Animal studies only", "Residuals"], 0,
          "Group-level $r$ can mislead about individuals."),
        q("Describing a scatterplot uses direction, form, and:",
          ["Strength", "Only the mean of $x$", "p-values alone"], 0,
          "Standard vocabulary."),
        q("Confounding means:",
          ["Effects of variables are mixed so association is hard to attribute", "Variance is zero", "$H_0$ is true"], 0,
          "Entangled influences."),
        q("Observational studies can show association but struggle with:",
          ["Causal identification without strong assumptions", "Computing means", "Plotting points"], 0,
          "No random assignment."),
        q("A strong curved pattern should be described as nonlinear even if:",
          ["$r$ is near zero", "$r$ must be $1$", "Means differ"], 0,
          "Form matters beyond $r$."),
        q("Saying \"$x$ is associated with $y$\" claims:",
          ["A statistical relationship, not automatically a mechanism", "A proven law of nature", "Independence"], 0,
          "Association language."),
        q("Random assignment helps make treatment groups:",
          ["Comparable on average for confounders", "Identical in every outcome", "Larger than controls always"], 0,
          "Balance in expectation."),
        q("A news claim \"linked to\" usually signals:",
          ["Association, possibly not causation", "A randomized proof", "$r=1$"], 0,
          "Media wording."),
        q("If a third variable $z$ drives both $x$ and $y$, the $x$–$y$ correlation may be:",
          ["Spurious as a direct effect", "Impossible", "Always negative"], 0,
          "Common-cause confounding."),
        q("Form in a scatterplot might be linear, curved, or:",
          ["Clustered / no pattern", "Always normal", "A hypothesis test"], 0,
          "Shape vocabulary."),
    ]

    banks["PS_R_FIT_QUIZ"] = [
        q("Least-squares slope $b=r s_y/s_x$ with $r=0.8$, $s_y=10$, $s_x=4$ equals:",
          ["$2$", "$0.32$", "$8$"], 0,
          "$0.8\\cdot 10/4=2$."),
        q("Intercept $a=\\bar y-b\\bar x$ with $\\bar y=5$, $b=2$, $\\bar x=1$ equals:",
          ["$3$", "$5$", "$2$"], 0,
          "$5-2\\cdot 1=3$."),
        q("The least-squares line always passes through:",
          ["$(\\bar x,\\bar y)$", "$(0,0)$", "$(1,r)$"], 0,
          "Normal equations."),
        q("Predicted $\\hat y$ at $x=4$ for $\\hat y=3+2x$ equals:",
          ["$11$", "$8$", "$3$"], 0,
          "$3+8=11$."),
        q("Slope $b=2$ means that when $x$ increases by $1$, $\\hat y$ changes by:",
          ["$2$", "$1/2$", "$0$"], 0,
          "Slope interpretation."),
        q("Least squares minimizes:",
          ["Sum of squared residuals", "Sum of absolute residuals only", "The correlation"], 0,
          "OLS criterion."),
        q("An influential point is one that:",
          ["Markedly changes the fitted line if removed", "Always has residual $0$", "Has $x=\\bar x$"], 0,
          "High influence on fit."),
        q("If $r>0$, the least-squares slope is:",
          ["Positive", "Negative", "Zero"], 0,
          "Same sign as $r$."),
        q("For $\\hat y=10-0.5x$, when $x$ increases by $4$, $\\hat y$ changes by:",
          ["$-2$", "$2$", "$-0.5$"], 0,
          "$-0.5\\cdot 4=-2$."),
        q("If $s_x=s_y$ and $r=1$, then $b$ equals:",
          ["$1$", "$0$", "$-1$"], 0,
          "$b=r$ when scales match."),
        q("Extrapolation risk appears when predicting at $x$:",
          ["Far from the observed $x$-values", "Equal to $\\bar x$", "Between two nearby sample $x$'s"], 0,
          "Outside the data range."),
        q("If $\\bar x=0$ and $a=4$, the line's value at the origin is:",
          ["$4$", "$0$", "Undefined"], 0,
          "Intercept is $\\hat y(0)$."),
        q("Doubling all $y$-values doubles:",
          ["The slope and intercept of the OLS line", "Only $r$", "Only $s_x$"], 0,
          "Linear response scaling."),
        q("The residual at a point is small when:",
          ["The point lies near the fitted line", "$r=0$", "$n=2$ always"], 0,
          "Vertical distance tiny."),
        q("Given $b=-3$ and $r=-0.6$, $s_y/s_x$ equals:",
          ["$5$", "$0.2$", "$-5$"], 0,
          "$b=r(s_y/s_x)$ so $s_y/s_x=b/r=5$."),
    ]

    banks["PS_R_RESID_QUIZ"] = [
        q("Residual equals:",
          ["$y-\\hat y$", "$\\hat y-y$ always negative", "$x-\\bar x$"], 0,
          "Observed minus predicted."),
        q("If $y=10$ and $\\hat y=7$, the residual is:",
          ["$3$", "$-3$", "$17$"], 0,
          "$10-7=3$."),
        q("For a least-squares line with intercept, residuals sum to:",
          ["$0$", "$1$", "$n$"], 0,
          "Normal equation consequence."),
        q("A residual plot with clear curvature suggests:",
          ["A linear model is inadequate", "Perfect fit", "$r=1$"], 0,
          "Systematic nonlinear pattern."),
        q("Fan-shaped residual plot (spread growing with $\\hat y$) suggests:",
          ["Non-constant variance", "Perfect homoscedasticity", "Zero correlation always"], 0,
          "Heteroscedasticity."),
        q("A high-leverage point has unusual:",
          ["$x$-value (far from $\\bar x$)", "$y$-residual only by definition", "p-value"], 0,
          "Leverage from predictor space."),
        q("Influential points often combine:",
          ["High leverage with a large residual", "Residual exactly $0$", "Being the median"], 0,
          "Pull the line."),
        q("Standard error of the estimate measures:",
          ["Typical size of residuals about the line", "Only $\\bar y$", "Correlation units"], 0,
          "Residual SD analogue."),
        q("If residuals show a random horizontal band, that supports:",
          ["An adequate linear fit (no obvious misspecification)", "That $r=0$", "Causation"], 0,
          "No leftover pattern."),
        q("A point with residual $0$ lies:",
          ["On the fitted line", "On the $y$-axis", "At $(\\bar x,\\bar y)$ always"], 0,
          "Prediction matches observation."),
        q("Plotting residuals versus $x$ is useful to detect:",
          ["Curvature or non-constant spread", "The population mean alone", "Type I error rates"], 0,
          "Diagnostic scatter."),
        q("If a linear model is inappropriate, one remedy is:",
          ["Transform variables or fit a nonlinear model", "Always delete half the data", "Set all residuals to $1$"], 0,
          "Address the form."),
        q("Leverage focuses on unusual predictors; an outlier in $y$ with ordinary $x$ is mainly a:",
          ["Large-residual point", "High-leverage point by $x$", "Zero-residual point"], 0,
          "Vertical discrepancy."),
        q("The least-squares fit makes the residual vector orthogonal to:",
          ["The column space of the design (including the constant column)", "Every nonlinear curve", "The p-value vector"], 0,
          "Normal equations."),
        q("If $\\hat y=5+x$ and the point $(2,10)$ is observed, residual equals:",
          ["$3$", "$-3$", "$7$"], 0,
          "$\\hat y=7$, residual $10-7=3$."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "psStatsQuizzes.js",
        "/** Study-guide quiz banks for the Descriptive Statistics, Hypothesis Testing and Regression guides — 15 MCQs per section. */",
        build(),
    )
