# -*- coding: utf-8 -*-
"""Emit mvTaylorQuizzes.js — Taylor Series guide banks."""
from _quiz_emit import q, emit_file, OUT


def build():
    banks = {}

    banks["TAYLOR_CONCEPT_QUIZ"] = [
        q("The degree-1 Taylor polynomial of $f(x)=\\sqrt{x}$ at $a=4$ equals:",
          ["$2+\\dfrac{x-4}{4}$", "$2+(x-4)$", "$\\dfrac{x}{2}$"], 0,
          "$f(4)=2$ and $f'(4)=1/4$."),
        q("For $f(x)=\\cos x$ at $a=0$, the polynomial $T_2(x)$ is:",
          ["$1-\\dfrac{x^2}{2}$", "$1+x-\\dfrac{x^2}{2}$", "$1-x^2$"], 0,
          "$f(0)=1$, $f'(0)=0$, $f''(0)=-1$."),
        q("Compared with $T_1$, the quadratic $T_2$ of $e^x$ at $0$ typically:",
          ["Stays closer to $e^x$ near $0$", "Is exact for all $x$", "Ignores the second derivative"], 0,
          "Matching one extra derivative improves local accuracy."),
        q("Approximation by $T_n$ centered at $a$ generally worsens when:",
          ["$|x-a|$ becomes large", "$x=a$", "$n$ increases with $x$ fixed near $a$"], 0,
          "Error terms grow with distance from the center."),
        q("If $T_2(x)=3+2(x-1)-(x-1)^2$ at $a=1$, then $f(1)$ equals:",
          ["$3$", "$2$", "$-1$"], 0,
          "The constant term is $f(a)$."),
        q("Linearization of $f(x)=\\ln x$ at $a=e$ is:",
          ["$1+\\dfrac{x-e}{e}$", "$\\ln(x-e)$", "$x/e$"], 0,
          "$f(e)=1$ and $f'(e)=1/e$."),
        q("For $f(x)=x^3$ at $a=1$, $T_1(x)$ equals:",
          ["$1+3(x-1)$", "$3x$", "$(x-1)^3$"], 0,
          "$f(1)=1$ and $f'(1)=3$."),
        q("A graph of $f$ and $T_2$ near the center typically shows:",
          ["Contact of order 2 at $a$", "Only matching values, never slopes", "Identical curves everywhere"], 0,
          "Value, slope, and concavity match at the center."),
        q("For $f(x)=\\sin x$ at $a=\\pi$, $T_1(x)$ equals:",
          ["$-(x-\\pi)$", "$x-\\pi$", "$1-(x-\\pi)$"], 0,
          "$\\sin\\pi=0$ and $\\cos\\pi=-1$."),
        q("Using only $T_0(x)=f(a)$ means the approximation is:",
          ["The constant line through $(a,f(a))$", "The tangent line at $a$", "A secant through two points"], 0,
          "Degree $0$ ignores all derivatives."),
        q("For $f(x)=1/x$ at $a=2$, $T_2(x)$ equals:",
          ["$\\dfrac{1}{2}-\\dfrac{x-2}{4}+\\dfrac{(x-2)^2}{8}$", "$\\dfrac{1}{2}-\\dfrac{x-2}{2}+(x-2)^2$", "$1-(x-2)+(x-2)^2$"], 0,
          "$f(2)=1/2$, $f'(2)=-1/4$, $f''(2)=1/4$, so $c_2=(1/4)/2=1/8$."),
        q("Why can $T_3$ be worse than $T_1$ far from the center?",
          ["Higher powers of $(x-a)$ can dominate away from $a$", "Taylor polynomials never use factorials", "$T_n$ is always exact"], 0,
          "Polynomial growth in $|x-a|$ can overshoot."),
        q("Matching value and first derivative at $a$ means $T_1$ is the:",
          ["Tangent-line approximation", "Secant through two distant points", "Horizontal asymptote"], 0,
          "Standard linearization."),
        q("For $f(x)=e^{2x}$ at $a=0$, $T_2(x)$ equals:",
          ["$1+2x+2x^2$", "$1+2x+4x^2$", "$1+x+x^2$"], 0,
          "$f''(0)=4$, so $c_2=4/2=2$."),
        q("If $f$ and $T_n$ agree through the $n$th derivative at $a$, then $f(a)-T_n(a)$ equals:",
          ["$0$", "$f^{(n)}(a)$", "$n!$"], 0,
          "By construction $T_n(a)=f(a)$."),
    ]

    banks["TAYLOR_FORMULA_QUIZ"] = [
        q("In $\\sum_{n=0}^{\\infty}\\dfrac{f^{(n)}(a)}{n!}(x-a)^n$, the center is:",
          ["$a$", "$0$ always", "$x$"], 0,
          "Powers of $(x-a)$."),
        q("For $f(x)=e^x$ at $a=1$, the coefficient $c_2=f''(1)/2!$ equals:",
          ["$e/2$", "$e$", "$1/2$"], 0,
          "$f''=e^x$, so $e/2$."),
        q("Build $T_2$ for $f(x)=\\ln x$ about $a=1$:",
          ["$(x-1)-\\dfrac{(x-1)^2}{2}$", "$(x-1)+\\dfrac{(x-1)^2}{2}$", "$x-\\dfrac{x^2}{2}$"], 0,
          "$f(1)=0$, $c_1=1$, $c_2=-1/2$."),
        q("For $f(x)=\\sin x$ at $a=\\pi/2$, $c_1=f'(\\pi/2)$ equals:",
          ["$0$", "$1$", "$-1$"], 0,
          "$\\cos(\\pi/2)=0$."),
        q("If a Taylor series about $a=3$ has $c_3=5$, then $f'''(3)$ equals:",
          ["$30$", "$5$", "$5/6$"], 0,
          "$c_3=f'''(3)/3!$ so $f'''(3)=30$."),
        q("For $f(x)=\\sqrt{1+x}$ at $a=0$, $c_1$ equals:",
          ["$1/2$", "$1$", "$-1/2$"], 0,
          "$f'(0)=1/2$."),
        q("$T_3$ of $f(x)=\\cos x$ about $a=0$ equals:",
          ["$1-\\dfrac{x^2}{2}$", "$1-\\dfrac{x^2}{2}+\\dfrac{x^3}{6}$", "$1-x+\\dfrac{x^2}{2}$"], 0,
          "Odd derivatives of $\\cos$ vanish at $0$."),
        q("For $f(x)=1/(1+x)$ at $a=0$, $c_2=f''(0)/2!$ equals:",
          ["$1$", "$-1$", "$1/2$"], 0,
          "$f''(0)=2$, so $c_2=1$."),
        q("Coefficient $c_n$ in the Taylor expansion about $a$ is:",
          ["$f^{(n)}(a)/n!$", "$f^{(n)}(a)$", "$n!\\,f^{(n)}(a)$"], 0,
          "Standard formula."),
        q("For $f(x)=x^4$ at $a=1$, $c_2=f''(1)/2!$ equals:",
          ["$6$", "$12$", "$24$"], 0,
          "$f''(1)=12$, divide by $2$."),
        q("$T_2$ of $f(x)=e^{x}$ about $a=2$ equals:",
          ["$e^2\\bigl(1+(x-2)+\\dfrac{(x-2)^2}{2}\\bigr)$", "$1+(x-2)+\\dfrac{(x-2)^2}{2}$", "$e^2+(x-2)$"], 0,
          "All derivatives equal $e^2$ at $a=2$."),
        q("If $c_1=7$ in a Taylor series about $a$, then $f'(a)$ equals:",
          ["$7$", "$7/2$", "$1/7$"], 0,
          "$c_1=f'(a)/1!=f'(a)$."),
        q("For $f(x)=\\tan x$ at $a=0$, $c_1$ equals:",
          ["$1$", "$0$", "$\\sqrt{2}$"], 0,
          "$\\sec^2 0=1$."),
        q("$T_3$ of $\\sin x$ about $a=0$ is:",
          ["$x-\\dfrac{x^3}{6}$", "$x-\\dfrac{x^3}{3}$", "$x+\\dfrac{x^3}{6}$"], 0,
          "$f'''(0)=-1$, so $c_3=-1/6$."),
        q("If $T_2(x)=4-3(x+1)+\\dfrac{1}{2}(x+1)^2$ about $a=-1$, then $f''(-1)$ equals:",
          ["$1$", "$1/2$", "$-3$"], 0,
          "$c_2=f''(a)/2=1/2$, so $f''(a)=1$."),
    ]

    banks["MACLAURIN_CORE_QUIZ"] = [
        q("A Maclaurin series is a Taylor series centered at:",
          ["$a=0$", "$a=1$", "$a=\\infty$"], 0, "Definition."),
        q("The Maclaurin series for $e^x$ begins:",
          ["$1+x+\\dfrac{x^2}{2!}+\\dfrac{x^3}{3!}+\\cdots$", "$1+x+x^2+x^3$", "$x+\\dfrac{x^2}{2}$"], 0,
          "All derivatives equal $e^x$; evaluate at $0$."),
        q("Maclaurin series for $\\sin x$ begins:",
          ["$x-\\dfrac{x^3}{3!}+\\dfrac{x^5}{5!}-\\cdots$", "$1-\\dfrac{x^2}{2!}+\\cdots$", "$x+\\dfrac{x^3}{3!}$"], 0,
          "Odd function with alternating factorial denominators."),
        q("Maclaurin series for $\\cos x$ begins:",
          ["$1-\\dfrac{x^2}{2!}+\\dfrac{x^4}{4!}-\\cdots$", "$x-\\dfrac{x^3}{3!}$", "$1+x+\\dfrac{x^2}{2}$"], 0,
          "Even function."),
        q("Maclaurin series for $\\ln(1+x)$ (for $|x|<1$) begins:",
          ["$x-\\dfrac{x^2}{2}+\\dfrac{x^3}{3}-\\cdots$", "$1+x+\\dfrac{x^2}{2}$", "$x+\\dfrac{x^2}{2}+\\dfrac{x^3}{3}$"], 0,
          "Integrate the geometric series for $1/(1+x)$."),
        q("Geometric Maclaurin series $1/(1-x)$ equals:",
          ["$\\sum_{n=0}^{\\infty}x^n$ for $|x|<1$", "$\\sum n x^n$", "$\\sum x^n/n!$"], 0,
          "Classic geometric sum."),
        q("Because $\\sin x$ is odd, its Maclaurin series contains:",
          ["Only odd powers of $x$", "Only even powers", "A nonzero constant term"], 0,
          "Odd symmetry."),
        q("Because $\\cos x$ is even, its Maclaurin series contains:",
          ["Only even powers of $x$", "Only odd powers", "Log terms"], 0,
          "Even symmetry."),
        q("General term of $e^x$ is:",
          ["$x^n/n!$", "$x^n$", "$n!\\,x^n$"], 0, "Exponential series."),
        q("Coefficient of $x^4$ in the Maclaurin series for $\\cos x$ is:",
          ["$1/24$", "$-1/24$", "$1/4$"], 0,
          "$(-1)^2/(4!)=1/24$."),
        q("Coefficient of $x^3$ in $\\sin x$ is:",
          ["$-1/6$", "$1/6$", "$0$"], 0, "$-1/3!$."),
        q("Maclaurin polynomial $T_2$ for $1/(1-x)$ is:",
          ["$1+x+x^2$", "$1+x$", "$1-x+x^2$"], 0,
          "Partial sum of the geometric series."),
        q("Fifth derivative of $e^x$ at $0$ equals:",
          ["$1$", "$120$", "$5$"], 0,
          "$f^{(5)}(0)=e^0=1$."),
        q("For $\\ln(1+x)$, the coefficient of $x^4$ is:",
          ["$-1/4$", "$1/4$", "$-1/24$"], 0,
          "General term $(-1)^{n+1}x^n/n$ for $n=4$."),
        q("The constant term in every Maclaurin series is:",
          ["$f(0)$", "$f'(0)$", "$1$ always"], 0, "$c_0=f(0)$."),
    ]

    banks["TAYLOR_CATALOG_QUIZ"] = [
        q("Substitute into $e^u$: the Maclaurin series of $e^{-x^2}$ begins:",
          ["$1-x^2+\\dfrac{x^4}{2}-\\dfrac{x^6}{6}+\\cdots$", "$1-x+\\dfrac{x^2}{2}-\\cdots$", "$1+x^2+\\dfrac{x^4}{2}+\\cdots$"], 0,
          "Replace $u=-x^2$ in $1+u+u^2/2!+\\cdots$."),
        q("From $\\sin u$, the series for $\\sin(2x)$ begins:",
          ["$2x-\\dfrac{(2x)^3}{6}+\\cdots$", "$x-\\dfrac{x^3}{6}+\\cdots$", "$2x-\\dfrac{x^3}{6}+\\cdots$"], 0,
          "Replace $u$ by $2x$."),
        q("Maclaurin series of $\\cos(x^2)$ begins:",
          ["$1-\\dfrac{x^4}{2}+\\dfrac{x^8}{24}-\\cdots$", "$1-\\dfrac{x^2}{2}+\\dfrac{x^4}{24}-\\cdots$", "$1-x^2+\\dfrac{x^4}{2}-\\cdots$"], 0,
          "Replace $u$ by $x^2$ in the cosine series."),
        q("Multiplying $\\sum x^n$ by $x^2$ yields the series for:",
          ["$x^2/(1-x)$", "$1/(1-x^2)$", "$x/(1-x)$"], 0,
          "$x^2\\sum x^n=\\sum x^{n+2}$."),
        q("Termwise differentiation of $\\sum_{n=0}^{\\infty}x^n$ gives:",
          ["$\\sum_{n=1}^{\\infty}nx^{n-1}=1/(1-x)^2$", "$\\sum x^n$", "$\\sum n!\\,x^n$"], 0,
          "Differentiate the geometric series."),
        q("Integrating $\\sum_{n=0}^{\\infty}(-1)^n x^n$ termwise from $0$ to $x$ relates to:",
          ["$\\ln(1+x)$", "$e^{-x}$", "$\\sin x$"], 0,
          "Integral of $1/(1+x)$."),
        q("Coefficient of $x^3$ in $(1+x+x^2/2)(1-x+x^2/2)$ equals:",
          ["$0$", "$1$", "$-1/2$"], 0,
          "$a_1 b_2+a_2 b_1=1\\cdot(1/2)+(1/2)\\cdot(-1)=0$."),
        q("Series for $x\\sin x$ begins:",
          ["$x^2-\\dfrac{x^4}{6}+\\cdots$", "$x-\\dfrac{x^3}{6}+\\cdots$", "$1-\\dfrac{x^2}{6}+\\cdots$"], 0,
          "Multiply the sine series by $x$."),
        q("From $1/(1-x)=\\sum x^n$, replace $x$ by $-x^2$ to get:",
          ["$1/(1+x^2)=\\sum(-1)^n x^{2n}$", "$1/(1-x^2)=\\sum x^{2n}$", "$e^{-x^2}$"], 0,
          "Geometric substitution."),
        q("Coefficient of $x^4$ in $e^{x}\\cos x$ equals:",
          ["$-1/6$", "$1/6$", "$0$"], 0,
          "Product pairs give $1/24-1/4+1/24=-1/6$."),
        q("Differentiating the Maclaurin series of $\\ln(1+x)$ termwise recovers:",
          ["$1/(1+x)$", "$\\ln(1+x)$", "$1/(1-x)$"], 0,
          "Derivative of $\\ln(1+x)$."),
        q("Series for $\\sin x\\cos x$ can be obtained from:",
          ["$\\dfrac{1}{2}\\sin(2x)$ series", "$e^{x}\\sin x$ only", "Geometric series alone"], 0,
          "Double-angle identity."),
        q("The coefficient of $x^2$ in $\\cos(3x)$ is:",
          ["$-9/2$", "$-1/2$", "$-3/2$"], 0,
          "$1-(3x)^2/2+\\cdots$ contributes $-9x^2/2$."),
        q("Integrating $\\sum_{n=0}^{\\infty}\\dfrac{(-1)^n x^{2n}}{n!}$ from $0$ to $1$ approximates:",
          ["$\\int_0^1 e^{-x^2}\\,dx$", "$\\int_0^1 e^{x}\\,dx$", "$\\int_0^1\\sin x\\,dx$"], 0,
          "That sum is $e^{-x^2}$."),
        q("From $\\arctan x=\\int_0^x\\dfrac{1}{1+t^2}\\,dt$, the Maclaurin series begins:",
          ["$x-\\dfrac{x^3}{3}+\\dfrac{x^5}{5}-\\cdots$", "$x-\\dfrac{x^2}{2}+\\dfrac{x^3}{3}-\\cdots$", "$1-x^2+x^4-\\cdots$"], 0,
          "Integrate $\\sum(-1)^n t^{2n}$."),
    ]

    banks["TAYLOR_CONVERGENCE_QUIZ"] = [
        q("For the Taylor series of $e^x$ about $0$, the radius of convergence is:",
          ["$\\infty$", "$1$", "$0$"], 0,
          "Ratio test: $|x|/(n+1)\\to 0$ for all $x$."),
        q("Ratio test on $\\sum\\dfrac{(x-1)^n}{n\\,2^n}$: radius $R$ equals:",
          ["$2$", "$1$", "$1/2$"], 0,
          "$|x-1|/2<1$."),
        q("Geometric series $\\sum(x/3)^n$ converges when:",
          ["$|x|<3$", "$|x|\\le 3$", "$|x|>3$"], 0,
          "$|x/3|<1$."),
        q("Interval of convergence for $\\ln(1+x)=\\sum_{n=1}^{\\infty}(-1)^{n+1}x^n/n$ is:",
          ["$-1<x\\le 1$", "$-1\\le x\\le 1$", "$-1<x<1$"], 0,
          "Open at $-1$, closed at $1$."),
        q("Series $\\sum n!\\,x^n$ has radius:",
          ["$R=0$", "$R=1$", "$R=\\infty$"], 0,
          "Ratio grows like $n|x|$."),
        q("Taylor series of $1/(1-x)$ about $0$ has interval:",
          ["$-1<x<1$", "$-1\\le x\\le 1$", "All real $x$"], 0,
          "Geometric; endpoints diverge."),
        q("Shifting the center of a Taylor series:",
          ["Translates the interval with the new center", "Always forces $R=0$", "Deletes all odd terms"], 0,
          "Powers of $(x-a)$ recenter the disk."),
        q("For $\\sum\\dfrac{(x+2)^n}{5^n}$, convergence requires:",
          ["$|x+2|<5$", "$|x|<5$", "$|x+2|>5$"], 0,
          "Ratio with factor $1/5$."),
        q("At an endpoint of a power-series interval one must:",
          ["Test that single $x$-value separately", "Always include it", "Always exclude it"], 0,
          "Endpoint behavior is independent."),
        q("For $\\sum\\dfrac{x^{2n}}{n!}$, the series converges for:",
          ["All real $x$", "Only $|x|<1$", "Only $x=0$"], 0,
          "Same factorial growth as $e^{x^2}$."),
        q("If $\\lim|c_n/c_{n+1}|=4$, then $R$ for $\\sum c_n(x-a)^n$ equals:",
          ["$4$", "$1/4$", "$0$"], 0,
          "Standard consecutive-coefficient radius formula."),
        q("The series $\\sum\\dfrac{(2x)^n}{n}$ has radius:",
          ["$R=1/2$", "$R=2$", "$R=1$"], 0,
          "Needs $|2x|<1$."),
        q("Geometric series $\\sum x^n$ at $x=1$:",
          ["Diverges", "Converges to $1$", "Converges to $0$"], 0,
          "Terms equal $1$, not to $0$."),
        q("For $\\sum\\dfrac{x^n}{n}$, at $x=-1$ one obtains:",
          ["The alternating harmonic series (converges)", "The harmonic series (diverges)", "A geometric series with ratio $2$"], 0,
          "$\\sum(-1)^n/n$."),
        q("Inside the open interval of convergence, a power series may be:",
          ["Differentiated and integrated term by term", "Only added, never differentiated", "Evaluated only at integers"], 0,
          "Standard calculus of power series."),
    ]

    banks["TAYLOR_ERROR_QUIZ"] = [
        q("Taylor's inequality bounds $|R_n(x)|$ by:",
          ["$\\dfrac{M|x-a|^{n+1}}{(n+1)!}$ when $|f^{(n+1)}|\\le M$", "$M|x-a|$ only", "$n!$"], 0,
          "Standard remainder estimate."),
        q("For $f(x)=e^x$ on $[0,1]$ with $|f^{(n+1)}|\\le e$, one has $|R_n(1)|\\le$:",
          ["$e/(n+1)!$", "$e$", "$1/(n+1)$"], 0,
          "Plug distance $1$ into Taylor's inequality."),
        q("Alternating series error after $N$ terms is at most:",
          ["The next term's absolute value", "The first term", "$N!$"], 0,
          "Alternating series estimation theorem."),
        q("Approximate $\\sin(0.1)$ by $0.1$; the next sine term has size about:",
          ["$(0.1)^3/6\\approx 1.7\\times 10^{-4}$", "$0.1$", "$1$"], 0,
          "Next term $x^3/3!$."),
        q("To guarantee $|R_n(0.5)|\\le 10^{-4}$ for $e^x$ with $M=e$, a sufficient choice among these is:",
          ["$n=6$", "$n=1$", "$n=2$"], 0,
          "Factorials shrink the bound; $n=6$ works."),
        q("Lagrange form of the remainder uses some $c$ between:",
          ["$x$ and $a$", "$0$ and $1$ always", "$n$ and $n+1$"], 0,
          "Mean-value form of $R_n$."),
        q("If $|f^{(4)}|\\le 2$ and $|x-a|=0.1$, then $|R_3(x)|\\le$:",
          ["$2(0.1)^4/24$", "$2(0.1)/24$", "$2$"], 0,
          "Taylor inequality with $n=3$."),
        q("For alternating $\\ln(1+x)$ at $x=1$, error after terms through $x^5/5$ is at most:",
          ["$1/6$", "$1$", "$5$"], 0,
          "Next term absolute value $1/6$."),
        q("Choosing larger $n$ near $a$ typically:",
          ["Shrinks the remainder bound", "Forces divergence", "Removes the need for $M$"], 0,
          "Factorial growth in the denominator."),
        q("Bound $|R_1(x)|$ for $f=\\cos$ on $|x|\\le 0.2$ using $|f''|\\le 1$:",
          ["$|R_1(x)|\\le (0.2)^2/2=0.02$", "$|R_1|\\le 0.2$", "$|R_1|\\le 1$"], 0,
          "$n=1$, $M=1$."),
        q("If a remainder bound is $0.003$, a safe display precision is about:",
          ["Three decimal places", "Exactly ten decimals", "No decimals"], 0,
          "Match reported digits to the error bound."),
        q("For $f=\\sin$, $a=0$, $n=0$, Taylor's inequality with $M=1$ gives:",
          ["$|\\sin x|\\le|x|$", "$|\\sin x|\\le x^2$", "$|\\sin x|\\le 1/|x|$"], 0,
          "$|R_0(x)|\\le|x|$."),
        q("Increasing $|x-a|$ with fixed $n$ and $M$:",
          ["Worsens the a priori remainder bound", "Always improves it", "Has no effect"], 0,
          "Power $|x-a|^{n+1}$ grows."),
        q("For an alternating Taylor series, if the first omitted term has size $10^{-5}$, the truncation error is at most:",
          ["$10^{-5}$", "$10^{-10}$", "$1$"], 0,
          "Alternating estimate."),
        q("For $e^{0.1}$ with $T_3$ and $M=1.2$, $|R_3|\\le 1.2(0.1)^4/24$ which is:",
          ["$5\\times 10^{-6}$", "$0.1$", "$1$"], 0,
          "$1.2\\times 10^{-4}/24=5\\times 10^{-6}$."),
    ]

    banks["TAYLOR_ENGINEERING_QUIZ"] = [
        q("Small-angle $\\sin\\theta\\approx\\theta$ comes from $T_1$ of sine at:",
          ["$0$", "$\\pi/2$", "$1$"], 0, "Maclaurin linearization."),
        q("Pendulum linearization replaces $\\sin\\theta$ by $\\theta$ for small $\\theta$ to get a:",
          ["Simple harmonic ODE", "Pure exponential ODE", "Cubic oscillator only"], 0,
          "Standard small-angle model."),
        q("Limit $\\lim_{x\\to 0}\\dfrac{\\sin x}{x}$ via series equals:",
          ["$1$", "$0$", "$\\infty$"], 0,
          "$(x-x^3/6+\\cdots)/x\\to 1$."),
        q("Approximate $\\int_0^1 e^{-x^2}\\,dx$ using $1-x^2+x^4/2$:",
          ["$1-1/3+1/10$", "$1$", "$1/2$"], 0,
          "$\\int_0^1(1-x^2+x^4/2)\\,dx=1-1/3+1/10$."),
        q("Relativistic kinetic energy for small $v/c$ expands like $\\tfrac12 mv^2$ plus higher powers of:",
          ["$(v/c)^2$", "$v$", "$c$ alone"], 0,
          "Binomial expansion of $(1-v^2/c^2)^{-1/2}$."),
        q("Numerical: $T_3(0.2)$ for $e^{x}$ equals:",
          ["$1.2213\\ldots$", "$1.2$", "$2$"], 0,
          "$1+0.2+0.02+(0.008)/6$."),
        q("Approximate $\\cos(0.1)$ by $1-(0.1)^2/2$:",
          ["$0.995$", "$1.005$", "$0.9$"], 0, "$1-0.005=0.995$."),
        q("Hard limit $\\lim_{x\\to 0}\\dfrac{1-\\cos x}{x^2}$ via series equals:",
          ["$1/2$", "$1$", "$0$"], 0,
          "$(x^2/2-\\cdots)/x^2\\to 1/2$."),
        q("Integral $\\int_0^{0.1}\\sin x\\,dx$ approximated by $\\int_0^{0.1}x\\,dx$ equals:",
          ["$0.005$", "$0.01$", "$0.1$"], 0, "$[x^2/2]_0^{0.1}=0.005$."),
        q("If remainder bound is $10^{-3}$, report the approximation to about:",
          ["Three decimal places", "Ten decimals", "No decimals"], 0,
          "Match displayed precision to error."),
        q("Series for $\\sqrt{1+\\varepsilon}$ with tiny $\\varepsilon$ begins $1+\\varepsilon/2$, used for:",
          ["First-order binomial approximations", "Exact radical evaluation only", "Divergence tests"], 0,
          "Linear response in $\\varepsilon$."),
        q("Approximate $\\ln(1.1)$ by $0.1-(0.1)^2/2=0.095$ using:",
          ["The first two Maclaurin terms of $\\ln(1+x)$", "The exponential series", "The sine series"], 0,
          "$x=0.1$ in $\\ln(1+x)$."),
        q("In optics, $\\cos\\theta\\approx 1-\\theta^2/2$ for small $\\theta$ is the:",
          ["Maclaurin $T_2$ of $\\cos$", "Exact identity at $\\theta=\\pi/2$", "Geometric sum"], 0,
          "Standard quadratic cosine approximation."),
        q("Limit $\\lim_{x\\to 0}\\dfrac{\\tan x-x}{x^3}$ equals $1/3$ because the $x^3$ coefficient of $\\tan x-x$ is:",
          ["$1/3$", "$1$", "$0$"], 0,
          "$\\tan x=x+x^3/3+\\cdots$."),
        q("Approximate $e^{-0.01}$ by $1-0.01+0.00005$ using $T_2$; the value is about:",
          ["$0.99005$", "$0.99$", "$1.01$"], 0,
          "$1+u+u^2/2$ with $u=-0.01$."),
    ]

    banks["TAYLOR_CHALLENGE_QUIZ"] = [
        q("Maclaurin series of $e^{\\sin x}$ through order $x^2$ is:",
          ["$1+x+\\dfrac{x^2}{2}+\\cdots$", "$1+x+x^2+\\cdots$", "$1+\\dfrac{x^2}{2}+\\cdots$"], 0,
          "$\\sin x=x+O(x^3)$ and $e^u=1+u+u^2/2+\\cdots$."),
        q("First terms of $\\sec x=1/\\cos x$ about $0$ begin:",
          ["$1+\\dfrac{x^2}{2}+\\dfrac{5x^4}{24}+\\cdots$", "$1-\\dfrac{x^2}{2}+\\cdots$", "$1+x+\\dfrac{x^2}{2}+\\cdots$"], 0,
          "Invert the cosine series."),
        q("Limit $\\lim_{x\\to 0}\\dfrac{x-\\sin x}{x^3}$ via series equals:",
          ["$1/6$", "$1/2$", "$1$"], 0,
          "$\\sin x=x-x^3/6+\\cdots$."),
        q("Binomial coefficient $\\binom{1/2}{2}$ equals:",
          ["$-1/8$", "$1/8$", "$1/2$"], 0,
          "$(1/2)(1/2-1)/2=-1/8$."),
        q("Euler: imaginary part of $e^{i\\pi/2}$ equals:",
          ["$1$", "$0$", "$-1$"], 0,
          "$e^{i\\pi/2}=i$."),
        q("Coefficient of $x^3$ in the Maclaurin series of $(\\sin x)/x$ is:",
          ["$0$", "$-1/6$", "$1$"], 0,
          "$1-x^2/6+x^4/120-\\cdots$ has only even powers."),
        q("Series for $x/\\sin x$ about $0$ begins $1+x^2/6+\\cdots$. Coefficient of $x^2$ is:",
          ["$1/6$", "$1/2$", "$-1/6$"], 0,
          "Invert $1-x^2/6+\\cdots$."),
        q("Binomial $(1-4x)^{-1/2}$: coefficient of $x$ equals:",
          ["$2$", "$-2$", "$1/2$"], 0,
          "Linear term $\\alpha u$ with $\\alpha=-1/2$, $u=-4x$."),
        q("Limit $\\lim_{x\\to 0}\\dfrac{1-\\cos(2x)}{x^2}$ equals:",
          ["$2$", "$1$", "$4$"], 0,
          "$1-\\cos(2x)\\sim 2x^2$."),
        q("Coefficient of $x^4$ in $e^x\\sin x$ equals:",
          ["$0$", "$1/6$", "$-1/6$"], 0,
          "Pairs $x^3/6\\cdot x$ and $x\\cdot(-x^3/6)$ cancel."),
        q("Composition $\\sin(e^x-1)$ has linear term:",
          ["$x$", "$1$", "$0$"], 0,
          "$\\sin(e^x-1)\\sim e^x-1\\sim x$."),
        q("For $f=\\ln(1+x)$, Lagrange $|R_2(0.5)|$ with $|f'''|\\le 2$ on $[0,0.5]$ is at most:",
          ["$1/24$", "$(0.5)^3$", "$2$"], 0,
          "$2\\cdot(0.5)^3/3!=1/24$."),
        q("Coefficient of $x^2$ in $(1+x)^{1/3}$ is:",
          ["$-1/9$", "$1/9$", "$1/3$"], 0,
          "$\\binom{1/3}{2}=-1/9$."),
        q("Using $e^{ix}=\\sum(ix)^n/n!$, the coefficient of $x^3$ in $\\cos x$ is:",
          ["$0$", "$-1/6$", "$1/6$"], 0,
          "$\\cos$ has only even powers."),
        q("Limit $\\lim_{x\\to 0}\\dfrac{\\arcsin x-x}{x^3}$ equals:",
          ["$1/6$", "$-1/6$", "$1$"], 0,
          "$\\arcsin x=x+x^3/6+\\cdots$."),
    ]

    return banks


if __name__ == "__main__":
    emit_file(
        OUT / "mvTaylorQuizzes.js",
        "/** Study-guide quiz banks for the Taylor Series guide — 15 MCQs per section. */",
        build(),
    )
